triton-inference-server/server

- Dockerfile
- Dockerfile.QA
- qa/L0_simple_custom_example/models/simple/config.pbtxt
- qa/L0_simple_custom_example/test.sh
- src/clients/c++/request.cc
- src/core/BUILD
- src/core/constants.h
- src/core/model_config.cc
- src/core/server.cc
- src/core/utils.cc
- src/custom/addsub/BUILD
- src/custom/addsub/addsub.cc
- src/servables/custom/BUILD
- src/servables/custom/custom.h
- src/servables/custom/custom_bundle.cc
- src/servables/custom/custom_bundle.h
- src/servables/custom/custom_bundle.proto
- src/servables/custom/custom_bundle_source_adapter.cc
- src/servables/custom/custom_bundle_source_adapter.h
- src/servables/custom/custom_bundle_test.cc
- src/servables/custom/loader.cc
- src/servables/custom/loader.h
- src/servables/tensorrt/plan_bundle.cc
- src/servables/tensorrt/plan_utils.cc
- src/servables/tensorrt/plan_utils.h
The implementation is provided by a shared library.
> Add a custom backend

- src/core/grpc_service.proto
- src/core/server.cc
- src/nvrpc/BUILD
- src/nvrpc/BidirectionalStreamingLifeCycle.h
- src/nvrpc/Context.h
- src/nvrpc/Interfaces.h
> Adding TRTIS streaming API

- docs/client.rst
- docs/http_grpc_api.rst
- src/clients/python/__init__.py
- src/clients/python/crequest.cc
in "Client Libraries and Examples" and "Inference Server API"
> Updated stream inference documentation

- docs/model_configuration.rst
> Warning about http-thread-count and dynamic batching.

- Dockerfile
- Dockerfile.QA
- qa/L0_custom_param/models/param/config.pbtxt
- qa/L0_custom_param/param_test.py
- qa/L0_custom_param/test.sh
- src/core/backend.cc
- src/core/model_config.proto
- src/core/server.cc
- src/custom/param/BUILD
- src/custom/param/param.cc
- src/servables/custom/custom.h
- src/servables/custom/custom_bundle.cc
- src/servables/custom/custom_bundle.h
- src/servables/custom/custom_bundle.proto
- src/servables/custom/custom_bundle_source_adapter.cc
Custom backends recieve parameters during initialization. The
parameters are those specifically listed in the model configuration as
well as some delivered from the server. See custom.h.
> Fix #65. Model and server parameters.

- nvidia_entrypoint.sh
> DRIVER VERSIONS can be xxx.yy.zz if coming from side branches

- Dockerfile.QA
- qa/L0_sequence_batcher/sequence_batcher_test.py
- qa/L0_sequence_batcher/test.sh
- qa/common/gen_ensemble_model_utils.py
- qa/common/gen_qa_model_repository
- qa/common/gen_qa_sequence_models.py
- src/core/ensemble_scheduler.cc
Ensemble context wasn't passing the flags field to internal request header.
>  Add ensemble tests in L0_sequence_batcher.  Fix ensemble bug with sequence model

- Dockerfile
Fixing permission for all shared objects to be only read and executable.
> Hemantj cleanup

- src/core/model_config.proto
- src/servables/tensorrt/plan_bundle.cc
- src/servables/tensorrt/plan_bundle.h
Add model configuration optimization control to enable CUDA graphs.
> Fix CUDA graph generation

- qa/L0_output_name/output_name_test.py
> removing unused packages

- src/backends/onnx/onnx_backend.cc
- src/backends/onnx/onnx_utils.cc
- src/backends/onnx/onnx_utils.h
Change util function names for clarity
> Add input extraction from payloads to OrtTensor

- qa/L0_infer/infer_test.py
- qa/L0_infer/test.sh
- qa/L0_infer_reshape/infer_reshape_test.py
- qa/L0_infer_variable/infer_variable_test.py
- qa/L0_infer_variable/test.sh
- qa/L0_infer_zero/infer_zero_test.py
- qa/common/gen_qa_model_repository
- qa/common/gen_qa_models.py
- qa/common/gen_qa_reshape_models.py
- qa/common/gen_qa_sequence_models.py
- qa/common/gen_qa_zero_models.py
- qa/common/infer_util.py
- qa/common/test_util.py
- src/backends/pytorch/libtorch_backend.cc
PS: LibTorch **does not support zero sized input tensors**. Also supports **--variable**. **L0_infer_zero** tests not required.
> Generate models and test for L0_infer regular(+variable) + reshape

- src/clients/c++/perf_client.cc
Example outputs
`perf_client -m resnet50 -d -p 5000 -l 10 -f res.csv` (without specifying `--percentile`)
<details><summary>log</summary><p>
```
Batch size: 1
Latency limit: 10 msec
Reporting average latency
Client: 
Request count: 772
Throughput: 154 infer/sec
Avg latency: 6459 usec (standard deviation 93 usec)
50-th percentile latency: 6465 usec
90-th percentile latency: 6546 usec
95-th percentile latency: 6561 usec
99-th percentile latency: 6587 usec
Avg HTTP time: 6382 usec (send/recv 305 usec + response wait 6077 usec)
Server: 
Request count: 928
Avg request latency: 4933 usec (overhead 59 usec + queue 38 usec + compute 4836 usec)
...
```
</p></details>
<details><summary>csv</summary><p>
``` …
```
> Always report common percentile

- Dockerfile.QA
- qa/L0_output_validation/lt_op_val_client.py
- qa/L0_output_validation/test.sh
Add tests for LibTorch Output Validation
> Add L0_output_validation tests

- src/backends/caffe2/autofill.cc
- src/backends/onnx/onnx_backend.cc
- src/backends/onnx/onnx_utils.cc
- src/backends/tensorflow/autofill.cc
- src/backends/tensorflow/tf_utils.cc
- src/backends/tensorrt/autofill.cc
- src/backends/tensorrt/plan_backend.cc
Mention Config output shape and Model output shape when mismatch for **Caffe2**.
For **Caffe2, TensorRT, TensorFlow** - Autofill check for no versions directory
> Clear Autofill and verification messages

- Dockerfile
- build/CMakeLists.txt
- build/trtis/CMakeLists.txt
- src/core/CMakeLists.txt
- src/core/filesystem.cc
- src/servers/CMakeLists.txt
Cmake build and FileSystem interface for google cloud storage using C++ client API.
> Implement GCS Filesystem support

- qa/common/gen_qa_models.py
- qa/common/gen_qa_reshape_models.py
- qa/common/gen_qa_sequence_models.py
- qa/common/gen_qa_zero_models.py
Updated QA model generation + models in dbcluster
> Set external_inputs and external_outputs in QA Caffe2 models

- Dockerfile
- docs/build.rst
- qa/L0_custom_ops/test.sh
- qa/L0_custom_ops/zero_out_test.py
- qa/common/gen_qa_custom_ops
- qa/common/gen_qa_custom_ops_models.py
- tools/patch/tensorflow/tf_version_script.lds
Export TF symbols from library to enable custom ops
Make libtensorflow_framework.so available since that is what custom
ops are expecting to link against.
> Enable tensorflow custom operator support

- Dockerfile
- qa/L0_batcher/batcher_test.py
- qa/L0_batcher/test.sh
- qa/L0_sequence_batcher/sequence_batcher_test.py
- src/backends/pytorch/libtorch_backend.cc
- src/servers/CMakeLists.txt
> Add PyTorch tests for L0_batcher and L0_sequence_batcher

- qa/L0_infer_zero/test.sh
- qa/L0_output_name/test.sh
- qa/common/gen_qa_identity_models.py
- qa/common/gen_qa_model_repository
> Rename repository from zero to identity, Add PyTorch Identity models

- src/backends/onnx/autofill.cc
- If no inputs are specified in model config, all inputs of the model will be filled. The same for outputs.
- If some inputs / outputs are specified in model config, only the missing fields of those inputs will be filled. This is for the case where the model is sequence model, whose "control inputs" are specified in sequence batching section instead of input section.
- If some inputs / outputs have specified 'dims' field, it will be used as hint for determine if model truly should be batch model. For instance, if the model is non-batch model with variable size tensors and 'max_batch_size' is set to 0 explicitly, the previous implementation will mistake it as unspecified and infer that the model supports batching as all inputs have variable size first dimension.
> Enhance ONNX autofill to fill missing fields in input / output

- src/backends/onnx/autofill.cc
- src/backends/tensorrt/autofill.cc
Same idea as in #412, except that TensorRT plan has well defined max_batch_size and thus we don't need to look up provided input / output config for hint.
> Enhance TensorRT autofill to fill missing fields in input / output

- src/backends/tensorflow/autofill.cc
> Enhance savedmodel autofill to fill missing fields in input / output

- src/nvrpc/LifeCycleUnary.h
From [protobuf's documentation](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.message#Message.Clear.details), `Clear()` will not release the allocated memory as it assumes that the message will be reused for next request soon, which is not the case in our application.
> Delete finished message to release allocated memory for gRPC requests

- qa/L0_lifecycle/lifecycle_test.py
- qa/L0_lifecycle/test.sh
The file deletion has been handled due to another earlier change, this PR is adding test regarding to this.
> Add file deletion test in L0_lifecycle

- qa/L0_model_config/autofill_noplatform/ensemble/tensor_to_input_overmapped/expected
- src/backends/onnx/autofill.cc
- src/backends/tensorflow/autofill.cc
Follow up to earlier autofill fix - model config test failure resolved
> Fix Autofill errors 

- src/core/filesystem.cc
> Fix GCS to allow root directory to be model repository

- docs/client.rst
- docs/models_and_schedulers.rst
Added clarifications in Model Ensemble Example page and explanation on how dynamica batching works on main Ensemble Model page.
> Updated Ensemble Models docs

- src/clients/c++/request.h
- src/clients/c++/request_common.cc
- src/clients/c++/request_common.h
- src/clients/c++/request_grpc.cc
- src/clients/c++/request_http.cc
Fix for #544. Batch size is now taken into account for Inputs in shared memory
> Fix for batch size != 1

- docs/client.rst
Document the shared memory features as a Beta release
> Update Client docs for Shared Memory

- src/backends/pytorch/libtorch_backend.cc
libtorch_image test occasionally fails due to mis-classification, the cause may be that the input buffers are copied asynchronously since #607. So for now we always synchronize the copy before creating input tensor as a workaround, the better solution will be delaying tensor creation until all copies are initiated, and then synchronize and create tensors.
> Fix libtorch input tensor creation

- src/backends/tensorrt/plan_backend.cc
- src/backends/tensorrt/plan_utils.cc
- src/backends/tensorrt/plan_utils.h
Changes to flag non-linear formats as unsupported
> TensorRT: Check for non-linear tensor formats

- Dockerfile.QA
- qa/L0_batcher/batcher_test.py
- qa/L0_batcher/test.sh
- qa/L0_infer/infer_test.py
- qa/L0_sequence_batcher/sequence_batcher_test.py
- qa/L0_sequence_batcher/test.sh
- qa/L0_shared_memory/shared_memory_test.py
- qa/L0_shared_memory/test.sh
- qa/common/infer_util.py
- src/clients/python/__init__.py
- src/clients/python/simple_shm_client.py
- src/servers/grpc_server.cc
- src/servers/http_server.cc
> Shared Memory tests using Python Client API

- src/clients/c++/request_grpc.cc
- src/core/grpc_service.proto
- src/core/server.cc
- src/core/server.h
- src/core/server_status.proto
- src/core/shared_memory_manager.cc
- src/core/shared_memory_manager.h
- src/core/trtserver.cc
- src/core/trtserver.h
- src/servers/grpc_server.cc
- src/servers/http_server.cc
- src/servers/shared_memory_block_manager.cc
- src/servers/shared_memory_block_manager.h
> SharedMemory Status server API support

- qa/L0_model_config/autofill_noplatform/tensorrt/bad_dynamic_shapes_max/config.pbtxt
- qa/L0_model_config/autofill_noplatform/tensorrt/bad_dynamic_shapes_max/expected
- qa/L0_model_config/autofill_noplatform/tensorrt/bad_dynamic_shapes_min/config.pbtxt
- qa/L0_model_config/autofill_noplatform/tensorrt/bad_dynamic_shapes_min/expected
- qa/L0_model_config/test.sh
- qa/L0_trt_dynamic_shape/test.sh
- qa/common/gen_qa_models.py
- src/backends/tensorrt/plan_backend.cc
- src/backends/tensorrt/plan_backend.h
- src/backends/tensorrt/plan_utils.cc
- src/backends/tensorrt/plan_utils.h
TRT engine->setBindingDimensions() doesn't validate the shape it is trying to set. This shape should be in the range of selected optimization profile. Hence, adding the validation in TRTIS to ensure the sanity.
> Add the shape validation for dynamic shapes

- qa/L0_large_payload/large_payload_test.py
- qa/L0_large_payload/test.sh
- qa/common/gen_qa_identity_models.py
- qa/common/gen_qa_model_repository
Note that the PR is merging into 19.09 as TRT dynamic shape related change is only in 19.09 for now...
> Add TRT Plan in L0_large_payload

- src/clients/c++/library/request_grpc.cc
- src/core/grpc_service.proto
- src/servers/grpc_server.cc
- Should SharedMemoryStatus return KIND?
> Updated API for CUDA Shared Memory support

- build/libevhtp/evhtp.patch
> Be more efficient in reserving contiguous buffer for input

- qa/common/infer_util.py
- src/clients/c++/library/request_common.cc
- src/clients/c++/library/request_common.h
- src/clients/c++/library/request_grpc.cc
- src/clients/c++/library/request_http.cc
- src/clients/c++/perf_client/perf_client.cc
Use server-style timestamp collection. Adjust timestamp collection to
be more accurate.
> Update client timestamp collection

- qa/L0_batcher/batcher_test.py
- qa/L0_batcher/test.sh
- qa/common/infer_util.py
Improve runtime of tests by reused old shared memory regions. 
**PS**: Depends on sharedMemoryVariable changes. Before merging.
> Optmizie Batcher and L0 infer shared memory tests

- qa/L0_onnx_execution_provider/test.sh
@dzier this is the follow up test to ensure the ONNX EPs can process inference requests properly
> Fix ONNX EP test. Also validate EPs by sending inference request

- Dockerfile.QA
- qa/L0_pinned_memory/libtorch_ensemble.pbtxt
- qa/L0_pinned_memory/test.sh
This PR is waiting on #700 to be able to run in CI, the following is the log generated from local run. The log only shows end-to-end latency, but still, it suggests that the performance gain from using pinned memory is not significant.
Each element is 4 bytes
```
libtorch ensemble 16384 elements
non-pinned
Sync Serial Run (grpc)
Total time: 466.906 ms
Mean time: 4.669 ms
Stddev: 0.229 ms
Async Serial Run (grpc)
Total time: 459.508 ms
Mean time: 4.595 ms
Stddev: 0.139 ms
pinned
Sync Serial Run (grpc)
Total time: 461.882 ms
Mean time: 4.618 ms
Stddev: 0.102 ms
Async Serial Run (grpc)
Total time: 461.178 ms
Mean time: 4.611 ms
Stddev: 0.113 ms
libtorch ensemble 1048576 elements
non-pinned
Sync Serial Run (grpc)
Total time: 1262.29 ms
Mean time: 12.622 ms
Stddev: 0.84 ms
Async Serial Run …
```
> Add test to measure end-to-end performance on pinned / non-pinned memory

- src/core/pinned_memory_manager.cc
- src/core/pinned_memory_manager.h
Will make follow up change on the test after #716 is merged
> Add hard threshold on minimum size of pinned memory allocation

- docs/model_configuration.rst
> [DOC] Handle `label_filename` for generated config

- Dockerfile.QA
- qa/L0_simple_perf/test.sh
- qa/common/reporter.py
- src/clients/c++/examples/simple_perf_client.cc
Update to track nightly performance.
> L0_perf -> L0_simple_perf

- Dockerfile
- src/backends/onnx/autofill.cc
- src/backends/onnx/loader.cc
- src/backends/onnx/onnx_backend.cc
- src/backends/onnx/onnx_utils.cc
- src/backends/onnx/onnx_utils.h
Some changes in addition to removing limit on TRT EP:
* Specify OS version and Python version when building ORT library instead of patching build script.
* Update ORT API usage. ORT introduces an opaque API object to allow versioning.
> Advance ONNX Runtime commit to include fix on TensorRT Execution Provider

- qa/L0_tf_gpu_io/test.sh
`-b` option is no longer valid
> Fix L0_tf_gpu_io

- qa/L0_nullchar_string/nullchar_string_client.py
- qa/L0_nullchar_string/test.sh
- src/backends/tensorflow/base_backend.cc
- src/backends/tensorflow/tensorflow_backend_tf.cc
- src/backends/tensorflow/tensorflow_backend_tf.h
- src/clients/python/ensemble_image_client.py
- src/clients/python/grpc_image_client.py
- src/clients/python/image_client.py
- src/clients/python/simple_callback_client.py
- src/clients/python/simple_client.py
- src/clients/python/simple_sequence_client.py
- src/clients/python/simple_shm_client.py
- src/clients/python/simple_string_client.py
> Add test for String tensor with middle null character

- qa/L0_sequence_batcher/sequence_batcher_test.py
- qa/L0_sequence_stress/sequence_stress.py
- qa/L0_tf_multi_stream/multi_stream_client.py
- src/clients/c++/examples/image_client.cc
- src/clients/c++/examples/simple_callback_client.cc
- src/clients/c++/examples/simple_perf_client.cc
- src/clients/c++/examples/simple_sequence_client.cc
- src/clients/c++/library/request.h.in
- src/clients/c++/library/request_common.cc
- src/clients/c++/library/request_common.h
- src/clients/c++/library/request_grpc.cc
- src/clients/c++/library/request_http.cc
- src/clients/c++/perf_client/concurrency_manager.cc
- src/clients/c++/perf_client/inference_profiler.cc
- src/clients/python/__init__.py
- src/clients/python/crequest.cc
- src/clients/python/crequest.h
- src/clients/python/image_client.py
- src/clients/python/simple_callback_client.py
- src/clients/python/simple_sequence_client.py
Removing the support of older API.
> Client Lib clean-up

- qa/L0_simple_perf/test.sh
With the values of n in the orders of 100, the standard deviation in the throughput for plan and custom backend was 1000 and 600 respectively. With these new values, the std_dev is reduced to 500 and 300 respectively. These changes should smooth out some noise in our performance curves. However, they don't have that significant impact on the other backends as the absolute value of throughput is not that high for others.
> Change the config values of L0_simple_perf and break it into two

- src/clients/c++/library/request_http.cc
For small payloads the data transfer might complete before CURL call. This causes SEND_END to be updated before SEND_START. This fix ensures the correct ordering in the timer updates.
> Fixing send timer in http client library

- src/servers/memory_alloc.cc
Follow up on the last part of DLIS-838
> Add validation on output type and id in memory_alloc.cc

- qa/L0_perf_client/test.sh
- src/clients/c++/perf_client/concurrency_manager.cc
- src/clients/c++/perf_client/concurrency_manager.h
- src/clients/c++/perf_client/perf_client.cc
Besides adding support for synchronous API, added the timestamp reporting in the callback of AsyncRun() call for more precise latency values.
> Synchronous API support in perf_client

- Dockerfile.QA
- qa/L0_batcher/batcher_test.py
- qa/L0_infer/infer_test.py
- qa/L0_infer/test.sh
- qa/L0_sequence_batcher/sequence_batcher_test.py
- qa/common/infer_util.py
- qa/common/shm_util.py
- src/backends/onnx/onnx_backend.cc
Add test coverage for cuda shared memory - L0_infer and L0_batcher variants
Currently seeing test failures for String tensors in L0_infer for cuda shared memory
> Add L0_batcher and L0_infer cuda shared memory tests

- qa/L0_infer/infer_test.py
- qa/L0_io/test.sh
- qa/L0_sequence_batcher/sequence_batcher_test.py
- qa/L0_sequence_batcher/test.sh
- qa/common/gen_ensemble_model_utils.py
- qa/common/gen_qa_models.py
- qa/common/gen_qa_sequence_models.py
> Generate qa ensemble models for libtorch and ONNX

- docs/client.rst
- docs/client_example.rst
- docs/quickstart.rst
Signed-off-by: Aleksa Pavlovic <pavlovicaleksa@yahoo.com>
> Fix bad NGC client image links

- qa/L0_io/test.sh
- src/servers/memory_alloc.cc
> Add string tensor support to memory_alloc

- qa/L0_simple_cuda_shared_memory_example/test.sh
- qa/L0_simple_shared_memory_example/test.sh
- src/clients/c++/examples/CMakeLists.txt
- src/clients/c++/examples/simple_cudashm_string_client.cc
- src/clients/c++/examples/simple_shm_client.cc
- src/clients/c++/examples/simple_shm_string_client.cc
> Add C++ shared memory string client examples

- src/backends/caffe2/autofill.cc
- src/backends/caffe2/netdef_backend_factory.cc
- src/backends/custom/custom_backend_factory.cc
- src/backends/onnx/autofill.cc
- src/backends/onnx/onnx_backend_factory.cc
- src/backends/pytorch/autofill.cc
- src/backends/pytorch/libtorch_backend_factory.cc
- src/backends/tensorflow/autofill.cc
- src/backends/tensorflow/graphdef_backend_factory.cc
- src/backends/tensorrt/autofill.cc
- src/backends/tensorrt/plan_backend_factory.cc
- src/core/autofill.cc
- src/core/backend.cc
- src/core/filesystem.cc
- src/core/filesystem.h
- src/servers/main.cc
UPDATE : Actually we can load all files one be one and select the first passing. Visit all the files until we find the compatible files.
> Supporting multiple model files in version directory

- qa/L0_lifecycle/test.sh
- src/core/backend.cc
- src/core/grpc_service.proto
- src/core/model_repository_manager.cc
- src/core/model_repository_manager.h
- src/core/server.cc
- src/core/server.h
- src/core/server_status.cc
- src/core/server_status.h
- src/core/server_status.proto
- src/core/trtserver.cc
- src/core/trtserver.h
- src/servers/grpc_server.cc
- src/servers/grpc_server.h
- src/servers/http_server.cc
- src/servers/main.cc
HTTP response body will look like:
```Protobuf
models {
name: "graphdef_float32_float32_float32"
}
models {
name: "savedmodel_float32_float32_float32"
}
models {
name: "simple_graphdef_float32_float32_float32"
}
models {
name: "simple_savedmodel_float32_float32_float32"
}
```
> Add TRTServer API to retrieve all unique models in model repositories

- qa/L0_sequence_batcher/sequence_batcher_test.py
- qa/L0_sequence_batcher/test.sh
- qa/common/sequence_util.py
> Add libtorch back to L0_sequence_batcher

- src/clients/c++/library/request.h.in
- src/clients/c++/library/request_grpc.cc
- src/clients/c++/library/request_http.cc
- src/clients/c++/perf_client/load_manager.cc
- src/clients/c++/perf_client/perf_client.cc
- src/clients/python/crequest.cc
- src/clients/python/shared_memory/shared_memory_handle.h
- src/core/trtserver.h
- src/servers/grpc_server.cc
- src/servers/http_server.cc
- src/servers/http_v2_server.cc
- src/servers/shared_memory_block_manager.cc
- src/servers/shared_memory_block_manager.h
if to ifdef and fix http client status returned
> Fix HTTP V2 build

- qa/L0_perf_deeprecommender/test.sh
Fix issue - merging graphdef_trt + graphdef result
> Fix L0_perf_deeprecommender

- qa/L0_string_io/string_client_test.py
- qa/L0_string_io/test.sh
- qa/common/infer_util.py
- qa/common/shm_util.py
- src/clients/python/__init__.py
- src/clients/python/cuda_shared_memory/__init__.py
- src/clients/python/shared_memory/__init__.py
- src/clients/python/simple_cuda_shm_string_client.py
- src/clients/python/simple_shm_string_client.py
- src/clients/python/simple_string_client.py
> Add support to pass numpy array of bytes for string inputs

- qa/L0_batcher/batcher_test.py
- qa/L0_batcher/test.sh
- qa/L0_infer/infer_test.py
- qa/L0_infer_reshape/infer_reshape_test.py
- qa/L0_infer_variable/infer_variable_test.py
- qa/L0_infer_zero/infer_zero_test.py
- qa/common/infer_util.py
- qa/common/shm_util.py
Fix infer_zero function for variable shape tensors
> Cleanup infer_util

- Dockerfile.QA
- qa/L0_model_config/test.sh
- qa/L0_trt_shape_tensors/test.sh
- qa/L0_trt_shape_tensors/trt_shape_tensor_test.py
- qa/common/gen_qa_identity_models.py
- qa/common/infer_util.py
- src/backends/tensorrt/plan_backend.cc
- src/backends/tensorrt/plan_backend.h
- src/backends/tensorrt/plan_utils.cc
- src/backends/tensorrt/plan_utils.h
- src/clients/c++/library/request.h.in
- src/clients/c++/library/request_common.cc
- src/clients/c++/library/request_common.h
- src/clients/c++/library/request_grpc.cc
- src/core/backend_context.cc
- src/core/backend_context.h
- src/core/provider_utils.cc
Adds the batching support for the shape tensor I/O. 
Tests for dynamic batching will be added in a separate PR
> Adding batching support and static batch testing for trt shape tensors

- docs/model_configuration.rst
- qa/L0_model_config/autofill_noplatform/onnx/bad_input_dims/expected
- qa/L0_model_config/autofill_noplatform/onnx/bad_output_dims/expected
- qa/L0_model_config/autofill_noplatform/tensorflow_savedmodel/bad_input_dims/expected
- qa/L0_model_config/autofill_noplatform/tensorflow_savedmodel/bad_output_dims/expected
- qa/L0_model_config/autofill_noplatform/tensorrt/bad_input_dims/expected
- qa/L0_model_config/autofill_noplatform/tensorrt/bad_output_dims/expected
- src/backends/onnx/onnx_utils.cc
- src/backends/tensorflow/savedmodel_backend.cc
- src/backends/tensorflow/tf_utils.cc
- src/backends/tensorflow/tf_utils.h
- src/backends/tensorrt/plan_utils.cc
> Improve input/output tensor shape mismatch messages

- qa/L0_model_config/autofill_noplatform_success/tensorrt/no_config_shape_tensor/expected
- qa/L0_model_config/test.sh
- qa/L0_trt_shape_tensors/test.sh
- qa/L0_trt_shape_tensors/trt_shape_tensor_test.py
- qa/common/gen_qa_dyna_sequence_models.py
- qa/common/gen_qa_identity_models.py
- qa/common/gen_qa_model_repository
- qa/common/gen_qa_sequence_models.py
- qa/common/infer_util.py
- qa/common/sequence_util.py
- src/backends/tensorrt/plan_backend.cc
- src/core/backend.cc
- src/core/provider.cc
- src/core/provider.h
- src/core/sequence_batch_scheduler.cc
Includes the testing of SequenceBatcher and DynamicSequence batcher in L0_trt_shape_tensors
> Additional Shape Tensor tests

- docs/custom_operation.rst
- qa/L0_custom_ops/mod_op_test.py
- qa/L0_custom_ops/test.sh
- qa/L0_tf_multi_stream/test.sh
- qa/L0_trt_plugin/test.sh
- qa/common/gen_qa_custom_ops
- qa/common/gen_qa_custom_ops_models.py
- qa/common/util.sh
- Create a custom modulo operation (build shared library)
- Use this to create a model 
- Run the model with LD_PRELOAD and verify if it runs successfully
- Added new SERVER_LD_PRELOAD flag in common/util.sh
- Update custom_operation docs for PyTorch
> Add pytorch custom op model test

- README.rst
- deploy/single_server/values.yaml
- docs/build.rst
- docs/client.rst
- docs/install.rst
- docs/quickstart.rst
- docs/run.rst
OK to review and approve. Won't pull to master until release is complete.
> Update README and docs post-20.01 release

- qa/L0_perf_client/test.sh
The test should be added back with the fix to DLIS-1054.
> Skipping L0_perf_client's very high concurrency test

- Dockerfile.QA
- qa/L0_simple_sequence_example/models_dyna/simple_sequence/config.pbtxt
- qa/L0_simple_sequence_example/test.sh
- src/clients/c++/examples/simple_sequence_client.cc
- src/clients/python/api_v1/examples/simple_sequence_client.py
- src/core/dynamic_batch_scheduler.cc
- src/core/dynamic_batch_scheduler.h
* Fix dynamic sequence batcher and preserve_order option
* Allocate completion_queues to cover all completion IDs
> Fix dynamic sequence batcher and preserve_order option (#1111)

- Dockerfile
- Dockerfile.QA
- Dockerfile.centos_client
- Dockerfile.client
- docs/experimental_grpc_python_api.rst
- qa/L0_docs/test.sh
- qa/L0_grpc_v2/test.sh
- src/clients/python/experimental_api_v2/examples/grpc_v2_client.py
- src/clients/python/experimental_api_v2/examples/grpc_v2_explicit_byte_content_client.py
- src/clients/python/experimental_api_v2/examples/grpc_v2_explicit_int8_content_client.py
- src/clients/python/experimental_api_v2/examples/grpc_v2_explicit_int_content_client.py
- src/clients/python/experimental_api_v2/examples/grpc_v2_image_client.py
- src/clients/python/experimental_api_v2/examples/simple_grpc_v2_async_infer_client.py
- src/clients/python/experimental_api_v2/examples/simple_grpc_v2_class_client.py
- src/clients/python/experimental_api_v2/examples/simple_grpc_v2_health_metadata.py
- src/clients/python/experimental_api_v2/examples/simple_grpc_v2_infer_client.py
- src/clients/python/experimental_api_v2/examples/simple_grpc_v2_string_infer_client.py
- src/clients/python/experimental_api_v2/library/CMakeLists.txt
- src/clients/python/experimental_api_v2/library/grpc_build_wheel.sh
- src/clients/python/experimental_api_v2/library/grpc_setup.py
- src/clients/python/experimental_api_v2/library/grpcclient.py
- src/clients/python/experimental_api_v2/library/http_build_wheel.sh
- src/clients/python/experimental_api_v2/library/http_setup.py
- src/clients/python/experimental_api_v2/library/utils.py
* Reorganizing the python client library for triton
* Addressing review comments and fixing the documentation
* Fixing documentation errors
Co-authored-by: Tanmay Verma <tanmayv@nvidia.com>
> Reorganizing the python client library for triton (#1168)

- qa/L0_s3_local/test.sh
- src/core/filesystem.cc
Solve for #1173
Now supporting remote minio servers as well
> Fix regex for remote minio server

- qa/L0_grpc_v2/test.sh
- src/clients/python/experimental_api_v2/examples/CMakeLists.txt
- src/clients/python/experimental_api_v2/examples/simple_grpc_v2_model_control.py
- src/clients/python/experimental_api_v2/library/grpcclient.py
- src/core/grpc_service_v2.proto
- src/core/server.cc
- src/servers/grpc_server_v2.cc
- src/servers/grpc_server_v2.h
~~Don't merge yet. This PR is based on tanmayv-shmem branch, for collecting reviews.~~
Updated the base branch to master. PR can now be merged.
> Model control extension for gRPC V2

- Dockerfile.QA
- qa/L0_http_v2/test.sh
- src/clients/python/experimental_api_v2/examples/CMakeLists.txt
- src/clients/python/experimental_api_v2/examples/simple_grpc_v2_cudashm_client.py
- src/clients/python/experimental_api_v2/examples/simple_grpc_v2_shm_client.py
- src/clients/python/experimental_api_v2/examples/simple_http_v2_health_metadata.py
- src/clients/python/experimental_api_v2/examples/simple_http_v2_infer_client.py
- src/clients/python/experimental_api_v2/library/grpcclient.py
- src/clients/python/experimental_api_v2/library/httpclient.py
Note: Though a test template is included, this PR doesn't activate testing. There are some bugs on the server side which should be fixed before enabling the testing. 
The code changes can be used to reproduce the  failing cases.
> Python HTTP V2 client library

- src/core/trtserver.cc
- src/core/trtserver.h
- src/core/trtserver2.h
- src/servers/http_server_v2.cc
PS: Repository name is not yet supported. Also applies for GRPC V2.
> [HTTP V2] Add support for Model Repository/Control

- src/clients/python/experimental_api_v2/library/grpcclient.py
- src/clients/python/experimental_api_v2/library/httpclient.py
I will add the support for binary data for inference later.
> [HTTP V2] python client library update

- Dockerfile.QA
- qa/L0_grpc_v2/test.sh
- qa/L0_http_v2/test.sh
- qa/common/util.sh
- src/clients/python/experimental_api_v2/examples/simple_grpc_v2_health_metadata.py
- src/clients/python/experimental_api_v2/examples/simple_grpc_v2_infer_client.py
- src/clients/python/experimental_api_v2/examples/simple_grpc_v2_string_infer_client.py
- src/clients/python/experimental_api_v2/examples/simple_http_v2_async_infer_client.py
- src/clients/python/experimental_api_v2/examples/simple_http_v2_health_metadata.py
- src/clients/python/experimental_api_v2/examples/simple_http_v2_infer_client.py
- src/servers/http_server_v2.cc
Will add Shared Memory, Model Control, Infer Binary support once these features are added to the httpclient library
> [HTTP V2] Enable simple testing with Python client

- src/core/backend.cc
- src/core/ensemble_scheduler.cc
- src/core/infer_request.cc
- src/core/infer_request.h
- src/core/provider.cc
- src/core/trtserver.cc
Preparing to implement override inputs in InferenceRequest.
> Differentiate original inference inputs

- src/clients/python/experimental_api_v2/library/grpcclient.py
- src/clients/python/experimental_api_v2/library/httpclient.py
- src/core/server.cc
- src/servers/common.cc
This PR is just for collecting reviews. The base branch needs to changed to master when #1242 is merged to the master.
>  [GRPC V2] Scheduling Policy Extension

- Dockerfile
Update base image to `nvcr.io/nvidia/tritonserver`
Fixed user creation
> Update base image to tritonserver

- qa/L0_http_v2/test.sh
- src/clients/python/experimental_api_v2/examples/CMakeLists.txt
- src/clients/python/experimental_api_v2/examples/simple_grpc_v2_cudashm_client.py
- src/clients/python/experimental_api_v2/examples/simple_grpc_v2_shm_client.py
- src/clients/python/experimental_api_v2/examples/simple_http_v2_cudashm_client.py
- src/clients/python/experimental_api_v2/examples/simple_http_v2_shm_client.py
- src/clients/python/experimental_api_v2/library/CMakeLists.txt
- src/clients/python/experimental_api_v2/library/cuda_shared_memory/__init__.py
- src/clients/python/experimental_api_v2/library/grpc_build_wheel.sh
- src/clients/python/experimental_api_v2/library/grpcclient.py
- src/clients/python/experimental_api_v2/library/httpclient.py
- src/clients/python/experimental_api_v2/library/shared_memory/__init__.py
- src/clients/python/experimental_api_v2/library/shared_memory_build_wheel.sh
- src/clients/python/experimental_api_v2/library/shared_memory_setup.py
- src/servers/http_server_v2.cc
Separated shared memory and cuda shared memory from grpc into combined sharedmemoryutils library. 
Fixes to client side.
@tanmayv25 please have a look at the 'data' field. The follow should be missing for inputs and outputs in the case of shared memory.
> [HTTP V2] Add System + CUDA shared memory clients and testing 

- src/clients/python/experimental_api_v2/examples/simple_http_v2_infer_client.py
- src/clients/python/experimental_api_v2/library/grpcclient.py
- src/clients/python/experimental_api_v2/library/httpclient.py
- src/servers/http_server_v2.cc
- update HTTP client library with inference statistics support
- updated simple http v2 infer client to test for Model statistics
> [HTTP V2] Add Model Inference Statistics Support

- src/clients/c++/experimental_api_v2/library/utils.h
- src/core/CMakeLists.txt
- src/core/infer_request.h
- src/core/infer_response.cc
- src/core/infer_response.h
- src/core/status.h
- src/core/tritonserver.h
The InferenceResponse class represent the result of an inference
execution, including any output tensor produced by the execution.
> Add InferenceResponse class

- src/clients/python/experimental_api_v2/examples/simple_grpc_v2_infer_client.py
- src/clients/python/experimental_api_v2/examples/simple_http_v2_infer_client.py
- src/clients/python/experimental_api_v2/library/grpcclient.py
- src/core/infer_request.cc
- src/core/infer_request.h
- src/core/tritonserver.cc
- src/core/tritonserver.h
- src/servers/http_server_v2.cc
- Defaults to returning all outputs from model config. 
@tanmayv25 I believe I fixed the same for GRPC V2 as well
> [HTTP V2] Make Outputs specification optional in Inference Request

- src/backends/tensorrt/autofill.cc
Before:
failed to load if specify max_batch_size:
```
E0414 23:30:19.408713 142 model_repository_manager.cc:1584] unable to autofill for 'reshape_trt', configuration specified max-batch 4 but TensorRT engine only supports max-batch 0
```
If don't provide config:
```
config {
name: "reshape_trt"
platform: "tensorrt_plan"
version_policy {
latest {
num_versions: 1
}
}
input {
name: "input_tensor:0"
data_type: TYPE_FP32
dims: -1
dims: 224
dims: 224
dims: 3
}
output {
name: "resnet50_v1.5/output/softmax:0"
data_type: TYPE_FP32
dims: -1
dims: 1001
}
output {
name: "ArgMax:0"
data_type: TYPE_INT32
dims: -1
}
}
```
After:
```
config {
name: "reshape_trt"
platform: "tensorrt_plan"
version_policy {
latest {
num_versions: 1
}
}
max_batch_size: 16
input {
name: "input_tensor:0"
data_type: TYPE_FP32 …
```
> Relax check on first_dim_variable. Autofill if reshape is needed

- qa/L0_s3_local/test.sh
- src/core/filesystem.cc
Disable polling
- Use model control instead to workaround Minio timestamp issue.
- Fix build to work when only S3 is enabled and GCS is disabled
> Fix S3 local test

- qa/L0_grpc_v2/test.sh
- src/clients/c++/experimental_api_v2/examples/CMakeLists.txt
- src/clients/c++/experimental_api_v2/examples/simple_grpc_v2_async_infer_client.cc
- src/clients/c++/experimental_api_v2/library/common.h
- src/clients/c++/experimental_api_v2/library/grpc_client.cc
- src/clients/c++/experimental_api_v2/library/grpc_client.h
~~Base branch is set to "tanmayv-http-infer" to facilitate convenient code review.~~
Rebased to master
> Async Inference support for GRPC V2 C++ client lib

- qa/L0_http_v2/test.sh
- src/clients/c++/experimental_api_v2/examples/CMakeLists.txt
- src/clients/c++/experimental_api_v2/examples/simple_http_v2_async_infer_client.cc
- src/clients/c++/experimental_api_v2/library/common.h
- src/clients/c++/experimental_api_v2/library/grpc_client.cc
- src/clients/c++/experimental_api_v2/library/grpc_client.h
- src/clients/c++/experimental_api_v2/library/http_client.cc
- src/clients/c++/experimental_api_v2/library/http_client.h
The first commit belongs to PR #1319, which should go away when that PR is merged. Ignore the first commit for now.
> Async Infer support for HTTP V2 C++ client

- src/clients/python/experimental_api_v2/examples/simple_grpc_v2_sequence_stream_infer_client.py
- src/clients/python/experimental_api_v2/library/grpcclient.py
There is a 1:1 correspondence with stream and client. These changes avoid confusion.
> [GRPC V2 ]  Update gRPC Streaming API more intuitive 

- qa/L0_grpc_v2/test.sh
- qa/common/check_copyright.py
- src/clients/c++/experimental_api_v2/examples/CMakeLists.txt
- src/clients/c++/experimental_api_v2/examples/shm_utils.cc
- src/clients/c++/experimental_api_v2/examples/shm_utils.h
- src/clients/c++/experimental_api_v2/examples/simple_grpc_v2_async_infer_client.cc
- src/clients/c++/experimental_api_v2/examples/simple_grpc_v2_cudashm_client.cc
- src/clients/c++/experimental_api_v2/examples/simple_grpc_v2_health_metadata.cc
- src/clients/c++/experimental_api_v2/examples/simple_grpc_v2_infer_client.cc
- src/clients/c++/experimental_api_v2/examples/simple_grpc_v2_model_control.cc
- src/clients/c++/experimental_api_v2/examples/simple_grpc_v2_shm_client.cc
- src/clients/c++/experimental_api_v2/examples/simple_http_v2_async_infer_client.cc
- src/clients/c++/experimental_api_v2/examples/simple_http_v2_health_metadata.cc
- src/clients/c++/experimental_api_v2/examples/simple_http_v2_infer_client.cc
- src/clients/c++/experimental_api_v2/library/CMakeLists.txt
- src/clients/c++/experimental_api_v2/library/common.cc
- src/clients/c++/experimental_api_v2/library/common.h
- src/clients/c++/experimental_api_v2/library/grpc_client.cc
- src/clients/c++/experimental_api_v2/library/grpc_client.h
- src/clients/c++/experimental_api_v2/library/http_client.cc
- src/clients/c++/experimental_api_v2/library/http_client.h
Merge PR #1334 into this branch before merging to the master.
Grpc streaming and string results will be added with a separate PR.
> [GRPC V2] C++ client library: shared memory, statistics and model control

- src/clients/python/experimental_api_v2/examples/v2_image_client.py
> Fix typo during http model config parsing

- src/core/backend.cc
- src/core/backend.h
Can't run the corresponding L0_warmup test yet as the backends in the tests are not updated with the request / response changes.
> Fix warmup feature in general case

- qa/L0_grpc_v2/test.sh
- src/clients/c++/experimental_api_v2/examples/CMakeLists.txt
- src/clients/c++/experimental_api_v2/examples/simple_grpc_v2_string_infer_client.cc
- src/clients/c++/experimental_api_v2/examples/simple_http_v2_string_infer_client.cc
- src/clients/c++/experimental_api_v2/examples/v2_image_client.cc
- src/clients/c++/experimental_api_v2/library/common.cc
- src/clients/c++/experimental_api_v2/library/common.h
- src/clients/c++/experimental_api_v2/library/grpc_client.cc
- src/clients/c++/experimental_api_v2/library/http_client.cc
The http protocol can be supported after http_server_v2 is modified to provide classification result as binary_data.
> C++ image client using V2 API

- qa/L0_storage_S3/test.sh
- src/core/filesystem.cc
Priority: ENV Variables -> AWS_PROFILE -> default
> Allow passing S3 credentials via Environment Variables

- src/core/filesystem.cc
> Fix bugs in S3 model loading noticed in Tensorflow savedmodel

- src/clients/python/experimental_api_v2/examples/simple_http_v2_infer_client.py
- src/clients/python/experimental_api_v2/library/httpclient.py
- src/servers/http_server_v2.cc
@CoderHam Can you check if the `asyn_infer()` also needs to be fixed? The function declaration says exception will be raised but the error will be passed into the client callback, I think we just need to clarify on how the error will be reported.
> Fix server / client error checking

- src/servers/grpc_server_v2.cc
output.contents().raw_contents().size() == 0 doesn't guarantee the results to be classification. The fix in this PR is a hack to support both infer_zero tests and classification outputs in grpc in 20.05. I believe it will become cleaner in 20.06.
TRITONSERVER_InferenceRequestOutputData returns the byte_size of 0 even for classification results.
> Fixing zero sized output tensor for the grpc server

- src/servers/grpc_server_v2.cc
- src/servers/http_server_v2.cc
These fixes were made in v2test. Bringing them over to master
> fix bugs in api_regex, reading from and writing to json

- qa/L0_trt_shape_tensors/test.sh
- qa/L0_trt_shape_tensors/trt_shape_tensor_test.py
- qa/common/infer_util.py
- qa/common/sequence_util.py
@deadeyegoodwin @tanmayv25 This is for adding back the dropped commit in v2test, but please take a look at the last commit, which updated the `check_status()` function. It will only check request count and skip infer count and batch execution until we start reporting batch stats and inference count in 20.06
> Fix L0_trt_shape_tensors

- qa/L0_infer_zero/infer_zero_test.py
- qa/L0_infer_zero/test.sh
- qa/common/infer_util.py
- qa/common/shm_util.py
~~@tanmayv25 gRPC support for empty input/output tensors needs fixing. I have disabled them for now. (For non-empty tensors gRPC works as expected)~~
PS: Shared memory support will be added shortly.
> Port infer_zero util and L0_infer_zero

- qa/L0_cuda_shared_memory/cuda_shared_memory_test.py
- qa/L0_cuda_shared_memory/test.sh
- qa/L0_shared_memory/shared_memory_test.py
- qa/L0_shared_memory/test.sh
@tanmayv25 you can refer to the L0_cuda_shared_memory tests to reproduce the cuda handle serialization issues we spoke about.
> Port L0_shared_memory and L0_cuda_shared_memory to V2

- qa/L0_perf_client/test.sh
Verified this test to locally pass along with the changes from PR #1424.
Need to fix the json error reporting for complex messages before enabling graphdef_sequence_float32  test for http.
It depends upon the changes from PR #1424 to successfully pass. I believe the CI run is not necessary.
Note: The request rates has been reduced because the values didn't stabilize. Will look at it as a part of the tuning effort in 20.06.
> Enabling L0_perf_test for V2

- src/servers/http_server_v2.cc
Follow up change from PR #1419. I missed a case where the error was registered before the InferRequestClass was created. Basically Line 1955. 
With this fix:
>  curl -v -X POST -d '{"inputs":[{"name":"INPUT__0","shape":[1,1],"datatype":"FP32","data":[1.0]}],"outputs":[{"name":"OUTPUT__0"}]}' localhost:8000/v2/models/libtorch_name_1_float32/infer
> Note: Unnecessary use of -X or --request, POST is already inferred.
> *   Trying 127.0.0.1...
> * TCP_NODELAY set
> * Connected to localhost (127.0.0.1) port 8000 (#0)
> > POST /v2/models/libtorch_name_1_float32/infer HTTP/1.1
> > Host: localhost:8000
> > User-Agent: curl/7.58.0
> > Accept: */*
> > Content-Length: 110
> > Content-Type: application/x-www-form-urlencoded
> > 
> * upload completely sent off: 110 out of 110 bytes
> < HTTP/1.1 400 …
> HTTP V2: Resuming only when connection paused

- qa/L0_server_status/server_status_test.py
- src/clients/c++/experimental_api_v2/perf_client/model_parser.cc
- src/clients/python/experimental_api_v2/library/grpcclient.py
- src/core/tritonserver.cc
- src/servers/http_server.cc
Enable preserve_proto_field_names
> Ensure naming of protobuf message fields is preserved when converting to JSON

- qa/L0_grpc_v2/test.sh
- qa/L0_http_v2/test.sh
- src/clients/python/experimental_api_v2/examples/CMakeLists.txt
- src/clients/python/experimental_api_v2/examples/simple_grpc_v2_shm_string_client.py
- src/clients/python/experimental_api_v2/examples/simple_http_v2_string_infer_client.py
This fixes the L0_http_v2 test on v2test. It is mostly a carry over from PR #1445.
> Fix L0_http_v2 and adds shm string testing on CI

- src/clients/python/api_v1/library/build_wheel.sh
Fixed an incorrect path to request.dll for a windows client build
> Correct invalid library path for windows build

- qa/L0_batcher/verify_timestamps.py
- qa/common/infer_util.py
- qa/common/sequence_util.py
- qa/common/shm_util.py
This PR cherry-picked changes from #1449 to kick off a up-to-date CI, will remove the cherry-picked commit after CI passes build stage
> Fix test utils

- src/clients/python/experimental_api_v2/library/grpcclient.py
- src/clients/python/experimental_api_v2/library/httpclient.py
Raise error if model_version is not a string
> Check model version type is string in python clients

- qa/L0_grpc_v2/test.sh
- qa/L0_http_v2/test.sh
- src/clients/c++/experimental_api_v2/examples/CMakeLists.txt
- src/clients/c++/experimental_api_v2/examples/simple_grpc_v2_model_control.cc
- src/clients/c++/experimental_api_v2/examples/simple_http_v2_model_control.cc
- src/clients/c++/experimental_api_v2/examples/v2_ensemble_image_client.cc
- src/clients/c++/experimental_api_v2/examples/v2_image_client.cc
- src/clients/c++/experimental_api_v2/library/http_client.cc
- src/clients/python/experimental_api_v2/examples/CMakeLists.txt
- src/clients/python/experimental_api_v2/examples/simple_grpc_v2_model_control.py
- src/clients/python/experimental_api_v2/examples/simple_http_v2_model_control.py
- src/clients/python/experimental_api_v2/examples/v2_ensemble_image_client.py
Covers the test coverage offered by L0_ensemble_example.
> Ensemble Image Client using V2 APIs and testing

- src/clients/csharp/.devcontainer/devcontainer.json
- src/clients/csharp/.vscode/launch.json
- src/clients/csharp/.vscode/tasks.json
- src/clients/csharp/Program.cs
- src/clients/csharp/README.rst
- src/clients/csharp/csharp.csproj
Followed Go example functionality.
> add C# example for #1272

- qa/L0_lifecycle/lifecycle_test.py
- qa/L0_output_validation/lt_op_val_client.py
- qa/L0_server_status/server_status_test.py
Fix failures for L0_lifecycle, L0_server_status, L0_output_validation
> Fix error messages and server readiness check

- src/backends/onnx/onnx_backend.cc
- src/backends/onnx/onnx_backend.h
- src/backends/tensorflow/base_backend.cc
- src/core/backend.h
Manually tested with `simple_grpc_v2_string_infer_client.py` and `simple_grpc_v2_infer_client.py`
> Update ONNX backend to request / response flow

- src/clients/python/experimental_api_v2/examples/grpc_v2_image_client.py
Adds the async, streaming and image directory support to the grpc_v2_image_client.
Tested locally. Will add the test once #1464 gets merged.
> Fix grpc_v2_image_client to be like grpc_image_client

- src/clients/c++/api_v1/examples/image_client.cc
- src/clients/c++/experimental_api_v2/examples/v2_image_client.cc
Fixes the issue of image client getting stuck when the number of images in the specified image directory is not a multiple of specified batch size.
> Fix bug in image clients for async op

- src/backends/tensorrt/plan_backend.cc
- src/backends/tensorrt/plan_backend.h
Just tested with L0_infer.
There is some issue with shape tensor. Will address in a separate PR.
> Update TensorRT backend to new request / response flow

- src/servers/grpc_server.cc
@CoderHam  This should fix the server side failure you were seeing while running perf_client.
> Fix grpc server stat parsing to support large accumulated time

- src/clients/c++/perf_client/inference_profiler.cc
- src/clients/c++/perf_client/inference_profiler.h
- src/clients/c++/perf_client/perf_client.cc
- src/clients/c++/perf_client/triton_client_wrapper.cc
- src/clients/c++/perf_client/triton_client_wrapper.h
- src/core/infer_trace.h
- src/servers/grpc_server.cc
> Expose the newly added statistics to perf_client output

- qa/L0_grpc/test.sh
- src/clients/c++/examples/simple_grpc_model_control.cc
- src/clients/c++/examples/simple_http_model_control.cc
- src/clients/python/examples/grpc_image_client.py
- src/clients/python/examples/simple_grpc_model_control.py
- src/clients/python/examples/simple_http_model_control.py
- src/servers/http_server.cc
@CoderHam  This should fix the model control. It broke because we missed modifying the regex in http in PR #1509.
> Fixing L0_http and L0_grpc

- qa/L0_s3_local/test.sh
- src/core/filesystem.cc
> Fix S3 regex to include '-'

- src/clients/c++/perf_client/model_parser.cc
- src/clients/python/examples/grpc_image_client.py
- src/servers/grpc_server.cc
Tested locally and can be merged directly.
I will soon share the PR to fix L0_http.
> Fix grpc server and clients to pass L0_grpc successfully

- src/servers/http_server.cc
- src/servers/shared_memory_manager.cc
Tested locally and can be merged directly.
> Fix the http server to get L0_http pass

- qa/common/infer_util.py
- src/servers/http_server.cc
This should fix L0_infer_zero test.
> Fix http server to handle zero-shaped tensors

- qa/L0_model_config/noautofill_platform/invalid_gpu/expected
- qa/L0_model_config/noautofill_platform/negative_gpu/expected
- src/core/model_config_utils.cc
- src/core/server.cc
> Improve GPU available and compute capability error message

- src/backends/onnx/onnx_backend.cc
- src/core/backend_context.cc
- src/core/backend_context.h
- src/core/cuda_utils.h
- src/servers/grpc_server.cc
- Fix No GPU server build
- Fix build without stats collection
@GuanLuo can you have a look at the onnx change I made? I appears the string cuda copy check was always false.
> Fix L0_build_variants

- src/clients/c++/examples/image_client.cc
- src/clients/python/examples/image_client.py
Fixes image model tests for onnx.
> Fix image clients for non-batching models (like example onnx models)

- qa/L0_output_validation/lt_op_val_client.py
- We no longer validate shape of output tensors
> Fix L0_output_validation

- Dockerfile.QA
- qa/L0_perf_nomodel/run_test.sh
- qa/L0_perf_nomodel/test.sh
- for each type of shared memory
> Split L0_perf_nomodel into 3 parts

- qa/L0_trt_shape_tensors/trt_shape_tensor_test.py
- src/core/infer_request.cc
- src/core/infer_request.h
This should fix all the L0_trt_shape_tensor tests
> Fix shape tensor handling in sequence batcher

- qa/L0_perf_nomodel/run_test.sh
Fixes for libtorch and plan model special cases
> Fix L0_perf_nomodel* tests

- qa/L0_perf_client/test.sh
- src/clients/c++/library/grpc_client.cc
- src/servers/grpc_server.cc
This PR will improve the performance of C++ grpc client library when successive requests carry identical number of inputs(preferably content byte size).
UPDATE: Enabled the original request rates in  CI.
> Improving C++ gRPC client performance for successive requests

- Dockerfile
- qa/L0_custom_ops/onnx_op_test.py
- qa/L0_custom_ops/test.sh
- qa/common/check_copyright.py
- src/backends/onnx/autofill.cc
- src/backends/onnx/autofill.h
- src/backends/onnx/onnx_backend.cc
- src/core/autofill.cc
- src/core/model_config.proto
Grabbing the generated custom ops library from the onnxruntime unit-tests for now.
> Add support and test coverage for ONNX custom ops

- docs/run.rst
Signed-off-by: david yastremsky <dyastremsky@nvidia.com>
> Added command that needs to be run inside of image after the ENTRYPOINT

- src/backends/tensorrt/plan_backend.cc
- src/backends/tensorrt/plan_backend.h
- src/core/model_config.proto
> Add option on CUDA event synchronization

- src/servers/grpc_server.cc
Just moves the code specific to Infer RPC implementation towards the actual RPC implementation. 
Renames Handler ->InferHandler as it is used only as a base class for ModelInferHandler and ModelStreamInferHandler. Similar renaming.
These changes make the implementation more comprehensible and easier to maintain.
> Reorganize the grpc server to bring related code together

- src/backends/backend/examples/identity.cc
- src/backends/backend/triton_model.cc
- src/backends/backend/tritonbackend.h
- src/backends/caffe2/netdef_backend.cc
- src/backends/custom/custom_backend.cc
- src/backends/onnx/onnx_backend.cc
- src/backends/pytorch/libtorch_backend.cc
- src/backends/tensorflow/base_backend.cc
- src/backends/tensorrt/plan_backend.cc
- src/core/backend.cc
- src/core/backend.h
- src/core/ensemble_scheduler.cc
- src/core/infer_request.cc
- src/core/infer_request.h
- src/core/tritonserver.h
- src/servers/grpc_server.cc
- src/servers/http_server.cc
- src/servers/memory_alloc.cc
- src/servers/simple.cc
Add "flags" argument to allow additional semantics to be communicated
along these paths if that becomes necessary in the future.
> Add some future proofing to request release callback

- qa/common/gen_qa_models.py
- qa/common/gen_qa_noshape_models.py
No longer need to force CPU ops for add sub for int8, int16, int32. Will be updating the model repo as well shortly.
> Fix TF model generation for addsub models

- Dockerfile.centos_client
- Dockerfile.client
- docs/client_library.rst
- qa/L0_client/test.sh
- src/clients/c++/examples/CMakeLists.txt
- src/clients/c++/library/CMakeLists.txt
- src/clients/c++/library/common.h
- src/clients/c++/library/grpc_client.h
- src/clients/c++/library/http_client.h
- src/clients/c++/library/ipc.h
- src/clients/python/examples/CMakeLists.txt
> Fix client build for TRITON_ENABLE_GPU=OFF

- src/clients/python/api_v1/library/__init__.py
> Fix memory leak in get_async_run_results

- Dockerfile.QA
- qa/L0_http_fuzz/fuzztest.py
- qa/L0_http_fuzz/test.sh
Remaining: Fuzz testing JSON contents to ensure our parser and server is robust to erogenous JSONs.
> Add L0_http_fuzz test

- qa/L0_decoupled/decoupled_test.py
- src/clients/c++/examples/simple_grpc_custom_repeat.cc
- src/clients/python/examples/simple_grpc_custom_repeat.py
Fixes the timeout error on the CI
> Fix decoupled clients and test to produce tensors with correct shapes

- Dockerfile.QA
- qa/L0_decoupled/decoupled_test.py
- qa/L0_decoupled/models/identity_int32/config.pbtxt
- qa/L0_decoupled/models/sequence_repeat/config.pbtxt
- qa/L0_decoupled/models/simple_repeat/config.pbtxt
- src/backends/backend/examples/CMakeLists.txt
- src/backends/backend/examples/libtriton_square.ldscript
- src/backends/backend/examples/models/square_int32/config.pbtxt
- src/backends/backend/examples/square.cc
- src/backends/backend/triton_model.cc
- src/core/ensemble_scheduler.cc
- src/core/ensemble_utils.cc
- src/core/infer_response.cc
- src/core/infer_response.h
This is the first PR of adding decoupled ensemble test.
> Fix bugs. Add repeat-like ensembles in L0_decoupled

- qa/L0_storage_S3/test.sh
Expand test coverage for L0_storage_s3 to include polling model control mode.
> Include polling test for S3 model loading

- src/servers/grpc_server.cc
- src/servers/http_server.cc
The lifetime of the alarm object should be extended. The response must be marked ready only after the protobuf message is done preparing.
@GuanLuo  I have tested this fix with your script and it seems to be stable.
> Fix for intermittent segfaults in grpc server.

- src/core/ensemble_scheduler.cc
@deadeyegoodwin cherry-picked changes in PR https://github.com/NVIDIA/triton-inference-server/pull/1782, will rebase this PR after PR #1782 is merged
> Check response parameters and override accordingly in ensemble

- src/core/ensemble_scheduler.cc
Log error on conflict. Use inner model request parameters as default response parameters
> Improve response parameter handling in ensemble.

- qa/L0_perf_resnet/test.sh
@deadeyegoodwin @dzier merging into 20.07 branch as the change in TF is available since 20.07
> Track TF AMP performance in L0_perf_resnset

- qa/L0_s3_local/test.sh
- qa/L0_storage_S3/test.sh
- src/backends/custom/custom_backend_factory.cc
- src/backends/custom/loader.cc
- src/backends/onnx/autofill.cc
- src/backends/onnx/onnx_backend_factory.cc
- src/backends/tensorflow/autofill.cc
- src/backends/tensorflow/graphdef_backend_factory.cc
- src/backends/tensorflow/savedmodel_backend_factory.cc
- src/core/filesystem.cc
- src/core/filesystem.h
Custom backend did not support loading of model from S3. This PR fixes support for it and adds test coverage for custom backend models. 
Fix bug that causes incomplete deletion of models.
> Add Custom Backend coverage to S3

- src/core/filesystem.cc
Do we want to merge this in or wait for the GCS test to be added to the CI?
> GCS localize models similar to S3

- Dockerfile
- README.rst
- build/onnxruntime/compute30.patch
- deploy/single_server/values.yaml
- docs/build.rst
- docs/client.rst
- docs/install.rst
- docs/quickstart.rst
- docs/run.rst
- qa/common/gen_qa_custom_ops
- qa/common/gen_qa_model_repository
Also contains "Update README and docs post-20.07-v1 release".
Do not squash PR.
> Update NGC versions post-20.07-v1 release

- Dockerfile
- Dockerfile.QA
- README.rst
- build/onnxruntime/compute30.patch
- deploy/single_server/values.yaml
- docs/build.rst
- docs/client_library.rst
- docs/custom_operation.rst
- docs/install.rst
- docs/quickstart.rst
- docs/run.rst
- qa/L0_custom_ops/test.sh
- qa/L0_custom_ops/vision_op_test.py
- qa/L0_perf_resnet/test.sh
- qa/common/gen_qa_custom_ops
- qa/common/gen_qa_custom_ops_models.py
- qa/common/gen_qa_model_repository
- src/backends/pytorch/CMakeLists.txt
- src/backends/pytorch/libtorch_backend.h
- src/backends/pytorch/libtorch_backend_factory.cc
- src/servers/CMakeLists.txt
This also contains the update to the README and docs post-20.07 release.
Do Not Squash
> Update NGC versions post-20.07 release

- qa/L0_custom_ops/cuda_op_test.py
- qa/L0_custom_ops/mod_op_test.py
- qa/L0_custom_ops/onnx_op_test.py
- qa/L0_custom_ops/vision_op_test.py
- qa/L0_custom_ops/zero_out_test.py
- qa/common/gen_qa_custom_ops_models.py
Some cleanup after running the new python formatter on torchvision op changes from 20.07
> Fix formatting

- src/clients/c++/library/http_client.cc
Preallocating response buffer for large responses improves the client receive time considerably (**20683 usec** to **595 usec**). Experiments were performed on `resnet50_fp16_plan` :
```
Batch size: 128
Pass [1] throughput: 921.6 infer/sec. Avg latency: 137855 usec (std 5894 usec)
Pass [2] throughput: 896 infer/sec. Avg latency: 141616 usec (std 5400 usec)
Pass [3] throughput: 947.2 infer/sec. Avg latency: 136513 usec (std 4606 usec)
Client: 
Request count: 37
Throughput: 947.2 infer/sec
Avg latency: 136513 usec (standard deviation 4606 usec)
p50 latency: 138071 usec
p90 latency: 141941 usec
p95 latency: 142441 usec
p99 latency: 144178 …
```
> Preallocate response buffer in C++ HTTP client

- qa/L0_trt_plugin/test.sh
- qa/L0_trt_plugin/trt_plugin_test.py
- qa/common/gen_qa_model_repository
- qa/common/gen_qa_trt_plugin_models.py
- Both models will need to be regenerated
- The L0_trt_plugin test script has also been modified for the same. It verifies that the models runs + the output data is what is expected.
> Replace TRT plugins Clip and LRELU with Norm and GELU

- qa/L0_infer_reshape/infer_reshape_test.py
- qa/L0_infer_reshape/test.sh
- qa/common/gen_qa_reshape_models.py
- src/backends/onnx/onnx_backend.cc
- src/backends/tensorflow/base_backend.cc
This change will require the models to be regenerated for 20.08.
> Fix for reshaped zero-sized string tensors

- qa/L0_kibana_summary/perf_summary.py
As @dzier suggested we can have this sent to just me and @deadeyegoodwin for now.
> Don't send perf nightly summary to entire triton dl

- src/backends/tensorflow/tensorflow_backend_tf.cc
Just for updating the code in Github repo
> Fix tstring handling in Triton-TF library

- qa/L0_s3_local/test.sh
- qa/L0_storage_S3/test.sh
Fixed `awslocal-cli` to **0.7**
> S3 test cleanup and Fix version of awslocal-cli

- src/backends/backend/python/CMakeLists.txt
- src/backends/backend/python/python.cc
- src/backends/backend/python/python_host.proto
- src/backends/backend/python/resources/startup.py
- src/backends/backend/python/resources/triton_python_backend_utils.py
> Fix GRPC shutdown

- Dockerfile
- Dockerfile.QA
- Dockerfile.centos_client
- Dockerfile.client
- qa/L0_docs/test.sh
- qa/L0_perf_kaldi/test.sh
> Use setuptools<50.0.0 to avoid build failure

- src/backends/backend/python/CMakeLists.txt
I was not able to reproduce the flaky build problem locally but I changed the CMake build and I think this will fix that problem.
> Fix python backend flaky build

- Dockerfile
- Dockerfile.QA
- Dockerfile.centos_client
- Dockerfile.client
- qa/L0_docs/test.sh
- qa/L0_perf_kaldi/test.sh
This reverts commit d6562dbcfab39d8fb96e6a41950c4f6bf1ab0acb.
> Revert "Use setuptools<50.0.0 to avoid build failure (#1952)"

- README.rst
- deploy/single_server/values.yaml
- docs/build.rst
- docs/client_library.rst
- docs/install.rst
- docs/quickstart.rst
- docs/run.rst
Appears I missed the change after the release.
> Update README and docs post-20.08 release

- src/backends/tensorrt/plan_backend.cc
- src/backends/tensorrt/plan_backend.h
- src/backends/tensorrt/plan_utils.cc
- src/backends/tensorrt/plan_utils.h
@tanmayv25 This is just the same as the other PR (#1886), but from a different branch so that the TRT 7.2 specific changes are not included
> Initial work on supporting TensorRT reformat-free I/O

- src/servers/grpc_server.cc
- src/servers/http_server.cc
The request parameter named `classification_count` could exceed the class count of the model.
https://github.com/triton-inference-server/server/blob/7793fe74eb375307801770251abbc2110b2766cd/src/servers/classification.cc#L46-L64
> Fixed classification output shape

- src/backends/tensorrt/plan_backend.cc
- src/backends/tensorrt/plan_backend.h
- src/core/model_config.proto
- src/core/model_config_utils.cc
@deadeyegoodwin initial look and feel
> Formalize model config for inexact match CUDA graph

- build.py
This reverts commit b213b0231b17d4af7488d5f1d6e07772be8f5d73.
> Revert "Update ONNX Runtime version to 1.5.1 (#2078)"

- src/backends/pytorch/libtorch_backend.cc
Previous:
```
failed to run model 'resnet50_libtorch_0_0_gpu0'
```
Current:
```
failed to run model 'resnet50_libtorch_0_0_gpu0': The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
File "code/resnet50_libtorch.py", line 4, in forward
def forward(self,
input: Tensor) -> Tensor:
input0 = torch._convolution(input, self.conv1.weight, None, [2, 2], [3, 3], [1, 1], False, [0, 0], 1, False, False, True)
~~~~~~~~~~~~~~~~~~ <--- HERE
input1 = torch.batch_norm(input0, self.bn1.weight, self.bn1.bias, self.bn1.running_mean, self.bn1.running_var, False, 0., 1.0000000000000001e-05, True)
input2 = torch.threshold_(input1, 0., 0.)
RuntimeError: Input type (CUDAHalfType) and weight type (CUDAFloatType) should be the same
```
> Improve libtorch model run failure message

- qa/L0_backend_identity/identity_test.py
- qa/L0_backend_identity/test.sh
This additional testing can catch any issues like here:
https://github.com/triton-inference-server/server/issues/2148
> Testing the byte sizes reported by identity backend

- qa/L0_custom_ops/vision_op_test.py
- qa/common/gen_qa_custom_ops_models.py
@deadeyegoodwin this is ready to merge. I can replace the model and config file once this is merged in. Tested locally and it passed with the new changed. Confirmed that torchvision GPU ops are now supported.
> Fix custom torchvision op model to test for GPU support

- docs/model_management.md
- docs/model_repository.md
Enhancing a little bit DALI BE description & fixing some links in the docs
> Update DALI BE description

- Dockerfile.client
- Dockerfile.sdk
It should be merged after 20.11 code freeze.
> Add Model Analyzer to Triton SDK Container

- qa/L0_multi_server/test.sh
- src/core/cuda_memory_manager.cc
- src/core/cuda_memory_manager.h
- src/core/metrics.cc
- src/core/metrics.h
- src/servers/multi_server.cc
Use locks during creation of Cuda memory pool and enabling metrics
> Modify L0_multi_server to run multiple TRITONSERVER_Server instances in parallel

- src/backends/tensorrt/plan_backend.cc
- src/backends/tensorrt/plan_backend.h
- src/core/cuda_utils.cc
- src/core/cuda_utils.h
- I was a unable to test this since I do not have an integrated GPU in my workstation. I confirmed it does not impact dGPUs. 
PS: Do not merge till changes are verified internally.
> Leverage Zero Copy for integrated GPUs

- qa/L0_perf_deeprecommender/run_test.sh
- qa/L0_perf_kaldi/test.sh
- qa/L0_perf_nomodel/run_test.sh
- qa/L0_perf_resnet/run_test.sh
- qa/L0_perf_resnet/test.sh
- qa/L0_perf_tfs/test.sh
See kibana dashboard [here](https://gpuwa.nvidia.com/kibana/app/kibana#/dashboard/fb844ea0-2dfd-11eb-885e-f1087b061596?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-90d,to:now))&_a=(description:'Compares%20the%20Triton%20Server%20performance%20of%20Resnet50%20with%20TensorFlow%20Serving',filters:!(),fullScreenMode:!f,options:(darkTheme:!f,hidePanelTitles:!f,useMargins:!t),panels:!((embeddableConfig:(),gridData:(h:15,i:'6fb86ab1-ebf0-4c4e-a89e-5b5f2853c974',w:24,x:0,y:0),id:'9f02a340-2e00-11eb-885e-f1087b061596',panelIndex:'6fb86ab1-ebf0-4c4e-a89e-5b5f2853c974',type:visualization,version:'7.5.2'),(embeddableConfig:(),gridData:(h:15,i:e709d539-823c-46ea-a0b2-daa11cb1b768,w:24,x:24,y:0),id:'440279b0-2e01-11eb-885e-f1087b061596',panelIndex:e709d539-823c-46ea-a0b2-daa11cb1b7 …
> Adding the TFServing benchmark

- src/clients/c++/perf_analyzer/client_backend/tensorflow_serving/grpc_client.cc
Need to explicitly add the elements in RepeatedField, I wonder why TFS didn't complain and even generated an output tensor data.
> Fix the input tensor data creation for TFS perf_analyzer

- qa/L0_sequence_batcher/test.sh
- qa/common/sequence_util.py
- delay, threshold changes for jetson
- reduce cases due to slower execution.
> Fix L0_sequence_batcher failure on jetson

- docs/quickstart.md
It was not clear that the output needed to display the models loaded in the table. I added this to the expected output and provided some explanations for the errors I ran into, which I presume could be common errors.
> Description of correctly loaded models

- src/clients/go/README.rst
> Updating the Go client README

- qa/L0_perf_ts/test.sh
This just tests the basic support for TorchServe in perf_analyzer. The support is primitive and the test might have to be modified later to obtain results with more apple to apple comparisons with Triton.
> Adding the test for benchmarking TorchServe using perf_analyzer

- qa/L0_perf_tfs/test.sh
Fixes L0_perf_tfs failures
https://gitlab-master.nvidia.com/dl/dgx/tritonserver/-/jobs/18953162
Similar fix for L0_perf_ts will be filed as a separate PR.
> Building perf_analyzer from source in TFS benchmark

- qa/L0_backend_python/python_test.py
- qa/L0_backend_python/test.sh
- qa/python_models/add_sub/config.pbtxt
- qa/python_models/add_sub/model.py
- qa/python_models/ensemble_gpu/config.pbtxt
- qa/python_models/sub_add/model.py
Tests for triton-inference-server/python_backend#30
> Add test for Python backend when the input is in GPU

- build.py
- Needed by PyTorch for CPU model execution
> Add libmkl_vml_def.so

- qa/L0_storage_S3/test.sh
- src/core/filesystem.cc
Ignores both extra trailing and leading slashes in S3 path
Resolves https://github.com/triton-inference-server/server/issues/2403#issuecomment-764859864
> Ignore extra slashes in S3 path

- deploy/single_server/README.md
- docs/quickstart.md
Fix a couple of URLs found by Mahan
> Correct bad URLs in documentation

- src/core/persistent_backend_manager.cc
I was able to resolve the clean-up segmentation fault by loading openvino backend in persistent mode.
> Adding openvino in persistent backends list

- qa/L0_string_io/string_client_test.py
- qa/L0_string_io/test.sh
- qa/common/infer_util.py
- src/clients/python/library/tritonclient/utils/__init__.py
Reverts triton-inference-server/server#2524
> Revert "Fix np.object uninteded cast in Python client"

- src/clients/python/library/tritonclient/grpc/__init__.py
- src/clients/python/library/tritonclient/http/__init__.py
> Avoiding copy when reshaping the numpy array

- Dockerfile.QA
- qa/L0_backend_python/python_test.py
- qa/L0_large_payload/large_payload_test.py
- qa/L0_perf_nomodel/custom_models/custom_zero_1_float32/config.pbtxt
- qa/L0_perf_nomodel/run_test.sh
- qa/L0_perf_nomodel/test.sh
- qa/python_models/identity_fp32/config.pbtxt
- qa/python_models/identity_fp32/model.py
> Add python backend to nomodel perf benchmark

- qa/L0_perf_nomodel/run_test.sh
- qa/L0_perf_nomodel/test.sh
- Only batch size 1 tests for now
> Add openvino to nomodel perf benchmark

- src/core/backend_context.cc
- src/core/dynamic_batch_scheduler.cc
- src/core/infer_request.h
- src/core/kernel.cu
- src/core/kernel.h
- src/core/model_repository_manager.cc
- src/core/sequence_batch_scheduler.cc
- src/core/shared_library.cc
> Fix error message for OpenLibraryHandle to mention backend instead of custom library

- Dockerfile.QA
- qa/L0_perf_pyclients/custom_models/custom_zero_1_int32/config.pbtxt
- qa/L0_perf_pyclients/simple_perf_client.py
- qa/L0_perf_pyclients/test.sh
See the dashboard [here](https://gpuwa.nvidia.com/kibana/goto/fa9990c1e9a94d359d73a21c2c77f64f).
@CoderHam  I have added the ticket to include the pyclients perf in weekly reports.
https://jirasw.nvidia.com/browse/DLIS-2186
> Adding simple perf benchmark for python clients

- src/core/filesystem.cc
- Restructure S3 to report error regarding s3 path during initialization
> Improve Cloud Storage Filesystem error reporting

- qa/L0_client_memory_growth/client_memory_mail.py
- qa/L0_memory_growth/server_memory_mail.py
- qa/common/nightly_email_helper.py
> Add support for html in nightly summary emails, format to fix indentation

- docs/protocol/extension_model_repository.md
- qa/L0_lifecycle/lifecycle_test.py
- qa/L0_lifecycle/test.sh
- src/clients/python/library/tritonclient/grpc/__init__.py
- src/clients/python/library/tritonclient/http/__init__.py
- src/core/grpc_service.proto
- src/core/model_repository_manager.cc
- src/core/model_repository_manager.h
- src/core/server.cc
- src/core/server.h
- src/core/tritonserver.cc
- src/servers/grpc_server.cc
- src/servers/http_server.cc
@deadeyegoodwin This is the look and feel of the new protocol option
> Add end point to unload model and its dependents

- src/backends/tensorrt/logging.cc
- src/backends/tensorrt/logging.h
Need to match the specifier for future TRT release
> Fix TRT log declaration

- Dockerfile.sdk
- src/clients/python/examples/image_client.py
Merge two functions to `parse_model` using simple AttrDict.
Related to #2650
> `feature/merge_parse_model`

- deploy/gke-marketplace-app/README.md
- deploy/gke-marketplace-app/server-deployer/build_and_push.sh
- deploy/gke-marketplace-app/server-deployer/chart/triton/Chart.yaml
- deploy/gke-marketplace-app/server-deployer/chart/triton/values.yaml
- deploy/gke-marketplace-app/server-deployer/data-test/schema.yaml
- deploy/gke-marketplace-app/server-deployer/schema.yaml
further clarify on autoscaling metrics
> further clarify on autoscaling metrics

- qa/L0_cmdline_trace/test.sh
- src/backends/custom/custom_backend.cc
- src/backends/tensorrt/plan_backend.cc
- src/core/infer_request.cc
Depending on the merge order with #2724 , either PR will need to update the preserve ordering part of L0_batcher accordingly
> Fix trace reporting on using backend API

- Dockerfile.sdk
Needed to fix L0_perf_ts benchmark. 
https://gitlab-master.nvidia.com/dl/dgx/tritonserver/-/pipelines/2294525
> Add TRITON_ENABLE_GPU option to SDK container

- qa/L0_backend_python/python_test.py
- qa/L0_backend_python/test.sh
- qa/python_models/execute_error/model.py
> Improve python backend testing

- src/core/filesystem.cc
Fixes issues outlined in #2794
> Fix memory leak caused by repeated calling Aws::InitAPI

- src/test/sequence/src/sequence.cc
I missed this in the last legacy custom backend PR. It fixes the sequence batcher cudashm segfault
> Fix sequence batcher cudashm segfault

- qa/L0_large_payload/test.sh
The server stucks at loading model after restarting the server for a couple times. Not sure what the cause is but limiting the server to only load the model under test seems to work around the issue.
> Avoid loading models that are not under test in L0_large_payload

- deploy/gke-marketplace-app/README.md
- deploy/gke-marketplace-app/benchmark/README.md
- deploy/gke-marketplace-app/benchmark/model-store/bert_base_tf_cpu/config.pbtxt
- deploy/gke-marketplace-app/benchmark/model-store/bert_base_tf_gpu/config.pbtxt
- deploy/gke-marketplace-app/benchmark/model-store/bert_base_trt_gpu/config.pbtxt
- deploy/gke-marketplace-app/benchmark/model-store/bert_base_trt_gpu_seqlen128/config.pbtxt
- deploy/gke-marketplace-app/benchmark/model-store/bert_distill_tf_cpu/config.pbtxt
- deploy/gke-marketplace-app/benchmark/model-store/bert_distill_tf_gpu/config.pbtxt
- deploy/gke-marketplace-app/benchmark/perf-analyzer-script/perf_query.sh
- deploy/gke-marketplace-app/benchmark/perf-analyzer-script/triton_client.yaml
- deploy/gke-marketplace-app/client-sample/locustfile_bert_large.py
- deploy/gke-marketplace-app/client-sample/perf_analyzer_grpc.sh
- deploy/gke-marketplace-app/server-deployer/Dockerfile
- deploy/gke-marketplace-app/server-deployer/build_and_push.sh
- deploy/gke-marketplace-app/server-deployer/chart/triton/Chart.yaml
- deploy/gke-marketplace-app/server-deployer/chart/triton/templates/_helpers.tpl
- deploy/gke-marketplace-app/server-deployer/chart/triton/templates/application.yaml
- deploy/gke-marketplace-app/server-deployer/chart/triton/templates/deployment.yaml
- deploy/gke-marketplace-app/server-deployer/chart/triton/templates/hpa.yaml
- deploy/gke-marketplace-app/server-deployer/chart/triton/templates/istio-gateway.yaml
- deploy/gke-marketplace-app/server-deployer/chart/triton/templates/istio-vs.yaml
- deploy/gke-marketplace-app/server-deployer/chart/triton/templates/service.yaml
- deploy/gke-marketplace-app/server-deployer/chart/triton/values.yaml
- deploy/gke-marketplace-app/server-deployer/data-test/schema.yaml
- deploy/gke-marketplace-app/server-deployer/schema.yaml
@deadeyegoodwin  Add copyright
> Add copyright

- qa/L0_storage_S3/test.sh
- src/core/filesystem.cc
- src/core/filesystem.h
- src/core/model_repository_manager.cc
convert Millis to Nanoseconds for correct comparison
> Fix bug in GetModifiedTime that causes garbage modification time to be reported

- docs/perf_analyzer.md
Documentation for https://github.com/triton-inference-server/server/pull/2861/,  and https://github.com/triton-inference-server/client/pull/8
> Perf Analyzer C API documentation

- Dockerfile.QA
- qa/L0_backend_python/lifecycle/test.sh
- qa/L0_backend_python/restart/restart_test.py
- qa/L0_backend_python/restart/test.sh
- qa/L0_backend_python/test.sh
This should be merged after #2945
> Add tests for automatic restart of Python backend stubs

- deploy/gke-marketplace-app/README.md
- deploy/gke-marketplace-app/benchmark/README.md
- deploy/gke-marketplace-app/benchmark/model-store/bert_base_tf_cpu/config.pbtxt
- deploy/gke-marketplace-app/benchmark/model-store/bert_base_tf_gpu/config.pbtxt
- deploy/gke-marketplace-app/benchmark/model-store/bert_base_trt_gpu/config.pbtxt
- deploy/gke-marketplace-app/benchmark/model-store/bert_base_trt_gpu_seqlen128/config.pbtxt
- deploy/gke-marketplace-app/benchmark/model-store/bert_distill_tf_cpu/config.pbtxt
- deploy/gke-marketplace-app/benchmark/model-store/bert_distill_tf_gpu/config.pbtxt
- deploy/gke-marketplace-app/benchmark/perf-analyzer-script/perf_query.sh
- deploy/gke-marketplace-app/benchmark/perf-analyzer-script/triton_client.yaml
- deploy/gke-marketplace-app/client-sample/locustfile_bert_large.py
- deploy/gke-marketplace-app/client-sample/perf_analyzer_grpc.sh
- deploy/gke-marketplace-app/server-deployer/Dockerfile
- deploy/gke-marketplace-app/server-deployer/build_and_push.sh
- deploy/gke-marketplace-app/server-deployer/chart/triton/Chart.yaml
- deploy/gke-marketplace-app/server-deployer/chart/triton/templates/_helpers.tpl
- deploy/gke-marketplace-app/server-deployer/chart/triton/templates/application.yaml
- deploy/gke-marketplace-app/server-deployer/chart/triton/templates/deployment.yaml
- deploy/gke-marketplace-app/server-deployer/chart/triton/templates/hpa.yaml
- deploy/gke-marketplace-app/server-deployer/chart/triton/templates/istio-gateway.yaml
- deploy/gke-marketplace-app/server-deployer/chart/triton/templates/istio-vs.yaml
- deploy/gke-marketplace-app/server-deployer/chart/triton/templates/service.yaml
- deploy/gke-marketplace-app/server-deployer/chart/triton/values.yaml
- deploy/gke-marketplace-app/server-deployer/data-test/schema.yaml
- deploy/gke-marketplace-app/server-deployer/schema.yaml
Please don't modify the body of copyright text. Please contact @dzier (or comment below) if there are any concerns.
> Remove AFFILIATES from body of copyright text

- deploy/gke-marketplace-app/README.md
- deploy/gke-marketplace-app/benchmark/README.md
this pull request remove all version in markdown files. @dzier
> Remove version in README to help release management

- qa/common/check_copyright.py
This is `git cherry-pick` from https://github.com/triton-inference-server/model_analyzer/pull/158, plus some manual modification.
> Copyright script update

- build.py
- docs/optimization.md
- qa/L0_onnxtrt_optimization/test.sh
- qa/L0_perf_resnet/test.sh
Updating onnxruntime version to 1.8.0
Adding tests for ONNX Runtime backend optimizations for TRT
> update onnxruntime to 1.8 and add some tests

- qa/L0_storage_azure/test.sh
- src/core/filesystem.cc
* Add explicit model control test for Azure storage
* Update copyright
* Fix incorrectly detected failure when getting blob property
- for cases where errno is set to 0 but blob_property.valid() = false
* Improve verbose error logging for azure storage FS
> Cherry pick azure file system fix

- qa/L0_backend_python/env/test.sh
- qa/L0_backend_python/python_test.py
- qa/L0_backend_python/test.sh
- qa/python_models/non_contiguous/config.pbtxt
- qa/python_models/non_contiguous/model.py
Tests for triton-inference-server/python_backend#61.
> Add tests for non-contiguous tensors for Python backend

- qa/common/check_copyright.py
Fix the failing copyright CI test
> Add libdcgm to ignore path in copyright checker

- src/backends/backend/triton_model_instance.cc
- src/backends/backend/triton_model_instance.h
- src/core/rate_limiter.cc
- src/core/rate_limiter.h
- src/servers/main.cc
The rebase fixes are not showing up. 
For all the changes so far wrt current main.. refer to this umbrella PR. https://github.com/triton-inference-server/server/pull/2847
> Support for device blocking case for TRT backend

- qa/L0_large_payload/large_payload_test.py
The test script is modified and passed the CI test.
> Modify L0_large_payload test for GRPC errors

- src/test/caffe2plan.cc
- breaks support for TRT 7 and older versions
> Update caffe2plan to work with TRT 8 APIs

- qa/L0_trt_reformat_free/trt_reformat_free_test.py
- qa/common/gen_qa_trt_format_models.py
@dzier follow up fix for L0_trt_reformat_free
> Fix test script for reformat-free I/O

- docs/build.md
- docs/faq.md
- Note for debugging segmentation faults
> Add docs for building with debug symbols

- build.py
> Disable ORT-TRT on jetson

- src/backends/backend/triton_model_instance.cc
- src/backends/backend/triton_model_instance.h
needed for dla support in TRT backend.
> Implement backend API for accessing secondary devices

- build.py
- src/backends/backend/triton_model_instance.cc
- src/core/CMakeLists.txt
- src/core/backend_context.cc
- src/core/cuda_utils.cc
- src/core/dynamic_batch_scheduler.cc
- src/core/tritonserver.cc
Needed to collect nvtx markers in tensorrt-backend.
> Move nvtx header to common repo

- src/core/dynamic_batch_scheduler.cc
Fixes some possible segmentation faults.
> Move to next payload once backend thread has picked the payload

- Dockerfile.sdk
- README.md
- build.py
- deploy/aws/values.yaml
- deploy/gcp/values.yaml
- deploy/gke-marketplace-app/benchmark/perf-analyzer-script/triton_client.yaml
- deploy/gke-marketplace-app/server-deployer/build_and_push.sh
- deploy/gke-marketplace-app/server-deployer/chart/triton/values.yaml
- deploy/gke-marketplace-app/server-deployer/data-test/schema.yaml
- deploy/gke-marketplace-app/server-deployer/schema.yaml
- docs/build.md
- docs/compose.md
- docs/test.md
David, go and and merge when you approve.
> Update README and docs post-21.08 release

- qa/L0_server_status/server_status_test.py
- since new openvino models have been added
> Fix model stats count for L0_server_status

- Dockerfile.sdk
- build.py
- src/core/metrics.cc
- src/core/metrics.h
Update DCGM to 2.2.9 and add better error logging functionalities. 
Also adjusted installation method to be same as [build.py](https://github.com/triton-inference-server/server/blob/main/build.py)
Related PR: https://github.com/triton-inference-server/model_analyzer/pull/206
> Update DCGM version and add better error logging

- qa/common/gen_qa_dyna_sequence_models.py
- qa/common/gen_qa_identity_models.py
- qa/common/gen_qa_models.py
- qa/common/gen_qa_reshape_models.py
- qa/common/gen_qa_sequence_models.py
- check for valid openvino model should include batch dims
> Fix model gen for openvino

- qa/L0_memory_growth/server_memory_mail.py
- qa/L0_memory_growth/test.sh
> Re-enable L0_memory_growth busy op test

- deploy/alibaba-cloud/README.md
- qa/L0_infer/install_and_test.sh
Modified the engineering doc to stage wheels to test.pypi.org instead of sqrl for QA.
> Remove reference to nvidia-pyindex

- qa/L0_backend_python/lifecycle/test.sh
The test has been improved to catch an intermittent segfault.
> Improve lifecycle test for PB

- README.md
- docs/model_configuration.md
- docs/rate_limiter.md
- qa/L0_rate_limiter/test.sh
Also fix documentation in test script.
> Document rate limiter feature

- build.py
- qa/L0_onnx_optimization/test.sh
Update ORT version to 1.9 and add tests for newly added optimization configs for CUDA and CPU provider
> update ort version and add tests

- qa/common/gen_qa_model_repository
I have tested the L0_dyna_implicit_state on generated models locally and it works fine.
> Fix generation of dyna sequence implicit state models

- compose.py
- deploy/mlflow-triton-plugin/mlflow_triton/deployments.py
- deploy/mlflow-triton-plugin/scripts/triton_flavor.py
- qa/L0_backend_python/io/io_test.py
- qa/L0_backend_python/python_test.py
- qa/L0_backend_python/python_unittest.py
- qa/L0_batcher/verify_timestamps.py
- qa/L0_dyna_sequence_batcher/dyna_sequence_batcher_test.py
- qa/L0_long_running_stress/crashing_client.py
- qa/L0_long_running_stress/scenarios.py
- qa/L0_long_running_stress/stress.py
- qa/L0_long_running_stress/stress_mail.py
- qa/L0_rate_limiter/rate_limiter_test.py
- qa/L0_sequence_batcher/sequence_batcher_test.py
- qa/L0_server_status/server_status_test.py
- qa/common/gen_qa_dyna_sequence_implicit_models.py
- qa/common/gen_qa_dyna_sequence_models.py
- qa/common/gen_qa_identity_models.py
- qa/common/gen_qa_implicit_models.py
- qa/common/gen_qa_models.py
- qa/common/gen_qa_reshape_models.py
- qa/common/gen_qa_sequence_models.py
- qa/common/nightly_email_helper.py
- qa/common/reporter.py
- qa/python_models/init_args/model.py
- qa/python_models/non_contiguous/model.py
A small refactor of some of the testing and models to get rid of unused variables, imprecise asserts, unnecessary imports, and non-recommended syntax.
> Refactor Testing: Unused Variables, Imprecise Asserts

- build.py
Signed-off-by: Boris Fomitchev <bfomitchev@nvidia.com>
> Passing TorchTRT flag

- compose.py
- docs/compose.md
Remove support of cpu-only containers for compose.py
> Use compose.py --gpu-enable=false for cpu-only build and test

- qa/L0_backend_identity/test.sh
Cherry-picks the fix from main branch. PR #3660
> Fix L0_backend_identity test 21.12 branch

- docs/model_repository.md
> Fix typo in model_repository.md

- qa/L0_memory_growth/server_memory_mail.py
- qa/L0_memory_growth/test.sh
- qa/common/nightly_email_helper.py
WAR for case of PTX failure in L0_memory_growth. Report error in email and skip memory growth busyop graph
> Fix L0_memory_growth, L0_client_memory_growth and L0_long_running_stress failures

- docs/protocol/extension_statistics.md
- Add cache hit info to HTTP JSON stats response description
- Add cache hit info to GRPC Protobuf message
> Update extension_statistics.md doc for new cache stats

- qa/L0_s3_local/test.sh
The polling test passes i.e. adding a new version directory to a model triggers the polling and the new version is loaded as expected.
> Cleanup s3 local test and add polling coverage for model version updates from S3

- qa/L0_s3_local/test.sh
- qa/L0_storage_azure/test.sh
- src/core/filesystem.cc
- src/core/model_config_utils.cc
Fixes https://github.com/triton-inference-server/server/issues/3135
> Fix model load failure when using cloud storage without model config file and disabled strict model config

- qa/L0_sequence_batcher/sequence_batcher_test.py
- qa/L0_sequence_batcher/test.sh
- qa/common/gen_qa_implicit_models.py
- src/core/sequence_state.cc
- src/core/sequence_state.h
Cherry-picking the changes for r22.01.
> Fix type bytes for implicit state management (#3793)

- qa/L0_batcher/batcher_test.py
- qa/L0_batcher/test.sh
- src/core/dynamic_batch_scheduler.cc
- src/core/instance_queue.cc
- src/core/payload.cc
- src/core/payload.h
When running "test_max_queue_delay_only_non_default"
```
AssertionError: False is not true : unexpected error 4 not found in (1, 2) : expected model-exec-count (1, 2), got 4
```
```
***
*** Test Passed
***
```
Fixes #3624
> Grow batches till the payload is under execution

- qa/L0_batcher/batcher_test.py
- qa/L0_batcher/test.sh
- src/core/dynamic_batch_scheduler.cc
- src/core/instance_queue.cc
- src/core/payload.cc
- src/core/payload.h
Cherry-picks the changes from main
* Grow batches till the payload is under execution
* Add tests for max_queue_delay
* Fix
* Add the test description
* Fix rate_limiter
* Mark payloads to be saturated at accurate points
> Grow batches till the payload is under execution (#3789)

- src/servers/grpc_server.cc
- src/servers/grpc_server.h
cherry-pick PR
* Register more infer requests to improve concurrency
* Use multi GRPC handler to provide better stability
> Register more infer requests to improve concurrency (#3803)

- qa/L0_cmdline_trace/test.sh
- src/servers/grpc_server.cc
- src/servers/grpc_server.h
Should fix L0_decoupled and L0_cmdline_trace
> Fix bugs in GRPC handler changes

- README.md
- docs/inference_protocols.md
merge after https://github.com/bytedeco/javacpp-presets/pull/1124
> Java cpp readme

- qa/common/gen_qa_implicit_models.py
- src/core/sequence_state.cc
Address @CoderHam review comments for https://github.com/triton-inference-server/server/pull/3806
> Improve the error message when setting sequence state to zero

- qa/L0_sequence_batcher/sequence_batcher_test.py
- qa/common/gen_qa_implicit_models.py
Enable the variable dimension tests both for the L0_sequence_batcher and L0_implicit_state.
> Enable variable dimension tests for TRT backend in sequence batcher

- qa/L0_backend_python/ensemble/test.sh
- qa/L0_backend_python/examples/test.sh
- qa/L0_backend_python/test.sh
- qa/python_models/bls/model.py
The output tesnor list of the inference response is empty when there is an error. I added tests for it.
> Improve the tests for BLS when there is error

- src/core/dynamic_batch_scheduler.cc
Let me know if I should fire a CI for it. The change has already been tested in main branch
> Protect completion queue from consecutive access (#3949)

- qa/L0_java_simple_example/test.sh
This PR adds CPU-only tests to L0_java_simple.
> Add Java Simple Tests - CPU-Only

- build.py
More verbose error for user when building on jetpack. Helps with cases like https://github.com/triton-inference-server/server/issues/3262
> Improve error reporting while building for jetpack

- qa/L0_java_sequence_batcher/SequenceTest.java
- qa/L0_java_sequence_batcher/Simple.java
- qa/L0_java_sequence_batcher/test.sh
The tests cover using the sequence batcher with the Java Bindings. The test covers the ONNX, TensorFlow, and PyTorch backends.
> Add Java Sequence Batcher Tests

- docs/trace.md
This PR is following the previous PR: #3598 
The PR updates the trace document with the new feature of tracing tensors.
> Updating trace document

- Dockerfile.QA
- Dockerfile.sdk
This reverts commit f83f0e2333bb48163061ae13e74b42512ffd99a3.
> Revert "Build Java jar in sdk and QA containers (#3957)"

- src/servers/http_server.cc
Follow-up PR for https://github.com/triton-inference-server/third_party/pull/14
> Revert WAR on HTTP recv end timestamp

- Dockerfile.QA
- Dockerfile.sdk
Multistage build to add Java bindings jar to SDK and QA container
Actual build in client repo: https://github.com/triton-inference-server/client/pull/77
> build jar in sdk container

- qa/L0_perf_analyzer/test.sh
Add tests for fixed PA bug. Client side PR: https://github.com/triton-inference-server/client/pull/72
> Async PA with binary search test

- qa/L0_trt_dynamic_shape/test.sh
- qa/common/gen_qa_models.py
Tests for the case fixed by https://github.com/triton-inference-server/tensorrt_backend/pull/26
> Add testing for multiple trt profiles with dynamic batching

- docs/model_configuration.md
- qa/L0_decoupled/models/fan_repeat/config.pbtxt
- qa/L0_infer/test.sh
- qa/L0_io/test.sh
- qa/common/gen_ensemble_model_utils.py
- qa/common/gen_qa_models.py
- qa/common/infer_util.py
- qa/common/libtorch_infer_client.py
- qa/python_models/ensemble_gpu/config.pbtxt
- src/servers/memory_alloc.cc
- src/servers/simple.cc
Refer to https://github.com/triton-inference-server/pytorch_backend/pull/51
> [PyTorch] Add docs and testing for new allowed input naming convention

- qa/L0_libtorch_nvfuser/test.sh
- NvFuser is disabled for now due to a bug in PyTorch
Follow up for https://github.com/triton-inference-server/pytorch_backend/pull/52
> Fix for L0_libtorch_nvfuser

- qa/L0_onnx_optimization/test.sh
Tests corresponding to this PR https://github.com/triton-inference-server/onnxruntime_backend/pull/106
> Add tests for exposing memory and arena configs.

- Dockerfile.sdk
- qa/L0_sdk/test.sh
Client side change: https://github.com/triton-inference-server/client/pull/82
> using openjdk instead of deafult jdk, manual installation of maven

- build.py
- Fix CPU only build for pytorch backend on SBSA
Resolves https://github.com/triton-inference-server/server/issues/4134
> Use PyTorch WAR for unblocking TF1 CPU-only build

- src/main.cc
- src/shared_memory_manager.cc
- src/tracer.cc
Only format changes were made.
> Formatting

- Dockerfile.QA
- Dockerfile.sdk
- build.py
- docs/jetson.md
- qa/L0_infer/test.sh
- qa/L0_libtorch_nvfuser/test.sh
- qa/L0_sdk/test.sh
- qa/common/gen_qa_custom_ops
- qa/common/gen_qa_model_repository
Update NGC versions post-22.03
> Update NGC versions post-22.03

- qa/L0_lifecycle/test.sh
- src/grpc_server.cc
Should update the error message in L0_lifecycle test for the corresponding changes.
> Update error message in L0_lifecycle

- qa/L0_backend_python/bls/test.sh
- qa/L0_backend_python/python_unittest.py
- qa/python_models/bls/model.py
- qa/python_models/dlpack_identity/config.pbtxt
- qa/python_models/dlpack_identity/model.py
https://github.com/triton-inference-server/python_backend/pull/131
> Add testing for the lifetime of BLS tensors

- Dockerfile.QA
- qa/L0_register/config.pbtxt
- qa/L0_register/test.sh
> Add Register/Unregister Model Repository API Tests

- build.py
- CPU only builds need deps from GPU enabled container
> Fix build.py to accept gpu-base image for CPU only

- docs/test.md
Small fix to render test documentation correctly.
> Test Documentation Rendering

- docs/model_management.md
- qa/L0_lifecycle/lifecycle_test.py
- qa/L0_lifecycle/test.sh
- src/main.cc
Core PR: https://github.com/triton-inference-server/core/pull/62
> Add `load-model=*` tests and documentation

- qa/python_models/decoupled_execute_error/config.pbtxt
- qa/python_models/decoupled_execute_error/model.py
- qa/python_models/decoupled_return_response_error/config.pbtxt
- qa/python_models/decoupled_return_response_error/model.py
- qa/python_models/decoupled_send_after_close_error/config.pbtxt
- qa/python_models/decoupled_send_after_close_error/model.py
- qa/python_models/response_sender_error/config.pbtxt
- qa/python_models/response_sender_error/model.py
These are few basic tests I could think of. 
These tests don't include any validating GPU tensors. I need to add those next.
> Add some models for testing the decoupled API

- qa/L0_tf_unknown_rank/test.sh
Updated test to check for new error message when loading scalar model
> Updated test to check for new error message

- qa/L0_backend_python/test.sh
- qa/L0_perf_resnet/test.sh
Fix L0_perf_resnet and L0_backend_python failures
> Fix test failures on Jetpack

- docs/model_repository.md
Fixes https://github.com/triton-inference-server/server/issues/4335
> Fix autocomplete link

- qa/L0_grpc/test.sh
Add tests to ensure new channel is created
Client side PR: https://github.com/triton-inference-server/client/pull/84
> Add option to force create new channel

- qa/L0_backend_python/decoupled/decoupled_test.py
- qa/L0_backend_python/decoupled/models/decoupled_bls/1/model.py
- qa/L0_backend_python/decoupled/models/decoupled_bls/config.pbtxt
- qa/L0_backend_python/decoupled/models/decoupled_execute_error/1/model.py
- qa/L0_backend_python/decoupled/models/decoupled_send_after_close_error/1/model.py
Only the last commit needs to be reviewed.
> Improve decoupled API test to cover flags argument

- qa/L0_backend_python/examples/test.sh
Needs the clients to be fixed as per this PR: https://github.com/triton-inference-server/python_backend/pull/145
> Add python decoupled example tests

- qa/L0_perf_resnet/test.sh
* Disable ORT-TRT test on Jetson due to support being disabled
> Fix test failures on Jetpack (#4316)

- docs/model_configuration.md
Addresses https://github.com/triton-inference-server/server/issues/4341
> Add note on instance_groups for ensemble models

- Dockerfile.sdk
- build.py
This PR is designed to start using recommended approach for NVIDIA repository.
> Moving to recommended approach with using cuda-keyring package

- docs/model_configuration.md
- qa/L0_model_config/autofill_noplatform_success/tensorrt/empty_config/expected
- qa/L0_model_config/autofill_noplatform_success/tensorrt/empty_config_variable/expected
- qa/L0_model_config/autofill_noplatform_success/tensorrt/incomplete_input/expected
- qa/L0_model_config/autofill_noplatform_success/tensorrt/incomplete_input/expected.1
- qa/L0_model_config/autofill_noplatform_success/tensorrt/incomplete_input/expected.2
- qa/L0_model_config/autofill_noplatform_success/tensorrt/incomplete_input/expected.3
- qa/L0_model_config/autofill_noplatform_success/tensorrt/incomplete_output/expected
- qa/L0_model_config/autofill_noplatform_success/tensorrt/incomplete_output/expected.1
- qa/L0_model_config/autofill_noplatform_success/tensorrt/incomplete_output/expected.2
- qa/L0_model_config/autofill_noplatform_success/tensorrt/incomplete_output/expected.3
- qa/L0_model_config/autofill_noplatform_success/tensorrt/multi_prof_max_bs/expected
- qa/L0_model_config/autofill_noplatform_success/tensorrt/no_config/expected
- qa/L0_model_config/autofill_noplatform_success/tensorrt/no_config_shape_tensor/expected
- qa/L0_model_config/autofill_noplatform_success/tensorrt/no_config_variable/expected
- qa/L0_model_config/autofill_noplatform_success/tensorrt/no_name_platform/expected
- qa/L0_model_config/autofill_noplatform_success/tensorrt/no_name_platform_variable/expected
- qa/L0_model_config/autofill_noplatform_success/tensorrt/reshape_config_provided/expected
- qa/L0_model_config/test.sh
Updated model config tests for tensorrt; tensorrt makes use of autocompleting the dynamic batcher but not the default-max-batch-size. Updated the docs explaining the change
> Updated L0_model_config for TensorRT autocomplete changes

- qa/L0_infer/test.sh
Fixes failure for L0_infer on jetson due to slight increase in overall time to load all models
> Increased timeout from 3600 to 4000

- qa/L0_http/python_http_aio_test.py
- qa/L0_http/test.sh
- qa/L0_https/test.sh
Add related test cases into qa.
https://github.com/triton-inference-server/client/pull/121
> Add http asyncio python client

- qa/L0_grpc/python_grpc_aio_test.py
- qa/L0_grpc/test.sh
- qa/L0_secure_grpc/test.sh
Add related test cases into qa.
https://github.com/triton-inference-server/client/pull/120
> Add grpc asyncio python client

- docs/inference_protocols.md
> Add documentation regarding GRPC streaming use case

- qa/L0_dyna_implicit_state/test.sh
- qa/L0_dyna_sequence_batcher/test.sh
The tests are sensitive to the number of instances created as they change the manner requests get batched.
> Fix L0_dyna_sequence_batcher and L0_dyna_implicit_state

- CONTRIBUTING.md
There has been more and more people asking how to complete CLA as an individual contributor. Adding a line to simplify the same.
> Clarify CLA process for individual contributors

- qa/L0_lifecycle/lifecycle_test.py
- qa/L0_lifecycle/test.sh
test update re: https://github.com/triton-inference-server/core/pull/100
> Check errors on startup models and condense lifecycle test

- qa/L0_perf_analyzer/test.sh
Related Client PR: https://github.com/triton-inference-server/client/pull/136
> Add Tracing to Perf Analyzer GRPC/HTTP Client

- qa/L0_backend_python/bls/test.sh
- qa/python_models/bls/model.py
python_backend: https://github.com/triton-inference-server/python_backend/pull/179
> Add test coverage to check if output tensor is on GPU

- README.md
- RELEASE.md
PREVIEW:
This is not a final commit some changes/fixes can be added/introduced.
> Update README for 22.07 release

- docs/response_cache.md
- Break doc into easier sections
- Add note about min/max cache size settings
- min size appears subjective, hard to find a specific number, see internal boost [memory management](https://github.com/boostorg/interprocess/blob/41018201d6b7a34f38a0303a1ad591d978989cb8/include/boost/interprocess/mem_algo/rbtree_best_fit.hpp#L607-L615) code
- depending on allocation algorithm used, `get_min_size` is checked against initial allocation size
> Enhance response cache doc

- qa/common/inferentia_perf_analyzer_input_data_json/simple_model.py
Related PR: https://github.com/triton-inference-server/python_backend/pull/182
> Fix inferentia gen_pytorch_model

- qa/L0_custom_ops/test.sh
@GuanLuo  We should relnote this work-around in our release docs.
> Fix L0_custom_ops failure

- qa/L0_backend_python/logging/test.sh
- qa/python_models/init_args/model.py
* Fix model path for Jetson
* Fix backend path for Jetson
> Fix L0_backend_python for Jetson (#4912)

- docs/conf.py
- docs/examples/README.md
- docs/examples/stable_diffusion/README.md
- docs/examples/stable_diffusion/client.py
- docs/examples/stable_diffusion/export.py
- docs/examples/stable_diffusion/gui/README.md
- docs/examples/stable_diffusion/gui/client.py
- docs/examples/stable_diffusion/model_repository/pipeline/1/model.py
- docs/examples/stable_diffusion/model_repository/pipeline/config.pbtxt
- docs/examples/stable_diffusion/model_repository/text_encoder/config.pbtxt
- docs/examples/stable_diffusion/model_repository/vae/config.pbtxt
- docs/index.md
Add copyrights to docs where they are needed. Also applied auto-formatting to docs.
> Add Copyrights

- qa/L0_backend_python/examples/test.sh
> Skip testing JAX example for Jetson (#5012)

- docs/examples/stable_diffusion/README.md
Updated the stable diffusion example as the optimizations got merged into diffusers.
Reference: https://github.com/huggingface/diffusers/pull/532
> updated stable diffusion example

- qa/L0_model_config/autofill_noplatform/tensorrt/bad_dynamic_shapes_max/expected
- qa/L0_model_config/autofill_noplatform/tensorrt/bad_dynamic_shapes_min/expected
TRT backend now performs check in respect to full shape, so dimension index reported should be increment
> Update expected error message based on TRT backend changes

- qa/L0_lifecycle/test.sh
Refer to the ticket DLIS-4310 for details.
Core PR: https://github.com/triton-inference-server/core/pull/139
> Add test for older OS modification time

- Dockerfile.sdk
- build.py
- qa/L0_batcher/test.sh
- qa/L0_client_build_variants/test.sh
- qa/L0_client_memory_growth/test.sh
- qa/L0_client_valgrind/test.sh
- qa/L0_infer/test.sh
- qa/L0_memory_growth/test.sh
- qa/L0_perf_tfs/test.sh
- qa/L0_perf_ts/test.sh
- qa/L0_sequence_batcher/test.sh
* Remove setting LD_PRELOAD inside container. Only setting TCMALLOC_RELEASE_RATE
* Revert tcmalloc changes in testing
> Revert tcmalloc changes in testing (#5135)

- qa/L0_libtorch_nvfuser/test.sh
Fixes https://github.com/triton-inference-server/server/issues/5128
> Re-enable nvfuser test

- docs/user_guide/model_management.md
* Update documentation for LD_PRELOAD and tcmalloc
* Fix up
> Update documentation for LD_PRELOAD and tcmalloc (#5161)

- docs/protocol/extension_schedule_policy.md
Server: https://github.com/triton-inference-server/client/pull/203
> add asterisk to extension policy documentation

- qa/L0_lifecycle/lifecycle_test.py
- qa/L0_lifecycle/test.sh
This reverts commit 8a1a015eff94594bcc2bc83278c2f860f1b08e49.
> Revert "Add concurrent loading speedup test (#5032)" (#5179)

- qa/L0_storage_S3/test.sh
Test IAM temporary credential that uses session token
> Add AWS session token test

- docs/user_guide/model_configuration.md
- qa/L0_batch_custom/batch_custom_test.py
- qa/L0_batch_custom/test.sh
* Draft test for custom batching
* Test all ways to load custom batch
* Simplify test to loop
* Clean up and organize code
* Clean up test
* Fix log names
* Document custom batching
* New line at end of file
* Break up lines, max width
* Document custom batching cache functions (#5204)
* Document cache functions
* Default test tag to main
* Function description as table
* Word clarity
* A word for clarity
* Grammar
* Grammar
* Copyright year
* Remove unnecessary permutations
> Allow User-Defined Batching Strategies (#5177)

- src/shared_memory_manager.cc
Closes https://github.com/triton-inference-server/server/issues/5248
> Add PROT_READ to shared memory maps

- qa/L0_perf_analyzer/test.sh
This adds basic protection for the -request-intervals option in PA
> Add PA request-intervals test

- build.py
ref: https://github.com/triton-inference-server/fastertransformer_backend/blob/main/docker/create_dockerfile_and_build.py#L117
and 
https://github.com/triton-inference-server/fastertransformer_backend/blob/main/docker/Dockerfile
> Improve fastertransformer build in build.py

- qa/L0_backend_python/bls/test.sh
- qa/L0_backend_python/decoupled/decoupled_test.py
- qa/L0_backend_python/decoupled/models/decoupled_bls/1/model.py
- qa/L0_backend_python/decoupled/models/decoupled_bls_stream/1/model.py
- qa/L0_backend_python/decoupled/models/decoupled_bls_stream/config.pbtxt
- qa/L0_backend_python/decoupled/test.sh
- qa/L0_backend_python/examples/test.sh
- qa/L0_backend_python/python_unittest.py
- qa/python_models/bls/model.py
- qa/python_models/bls_async/model.py
- qa/python_models/bls_memory/model.py
- qa/python_models/bls_memory_async/model.py
- qa/python_models/dlpack_square/config.pbtxt
- qa/python_models/dlpack_square/model.py
- qa/python_models/identity_fp32_timeout/config.pbtxt
- qa/python_models/identity_fp32_timeout/model.py
Python Backend: https://github.com/triton-inference-server/python_backend/pull/203
> Add testing for BLS decoupled support

- qa/L0_tf_tag_sigdef/test.sh
- qa/common/gen_tag_sigdef.py
Generate a new TensorFlow model with two tags: the default tag with two inputs, a custom tag with one input. Make sure that after autocompletion, the correct model (with the tag and inputs/outputs listed in the configuration) is loaded.
TensorFlow: https://github.com/triton-inference-server/tensorflow_backend/pull/86
**Before TensorFlow change**
_Default tag read during ModelInitialize_
_Requested tag read during ModelInstanceInitialize_
_Model fails due to number of inputs/outputs no longer matching_
_Test fails_
**After TensorFlow change**
Before TensorFlow change:
_Requested tag read during ModelInitialize_
_Requested tag read during ModelInstanceInitialize_
_Model loading succeeds_
_Test passes_
> Add testing for multi-tag, multi-IO TensorFlow models

- docs/user_guide/model_repository.md
Related PR: https://github.com/triton-inference-server/core/pull/164
> Clarify how GCS client obtain credentials

- build.py
This reverts commit 2ae64dedb91b69d41e83071278c2d3b21df5c7d8.
> Revert "Using cuda11.8 container for ORT build"

- docs/user_guide/trace.md
- qa/L0_cmdline_trace/test.sh
- qa/L0_cmdline_trace/trace_client.py
- src/tracer.cc
https://github.com/triton-inference-server/core/pull/169
> Include the request id in the trace

- src/http_server.cc
Finishing what was started in https://github.com/triton-inference-server/server/pull/5193 after lack of activity
> Fix invalid use of info after deletion

- docs/protocol/extension_parameters.md
- qa/L0_parameters/model_repository/parameter/1/model.py
- qa/L0_parameters/parameters_test.py
- qa/L0_parameters/test.sh
- src/grpc_server.cc
- src/http_server.cc
> Add parsing paremters to the HTTP/GRPC frontends

- qa/common/gen_qa_identity_models.py
Generate an identity model that uses linalg. This will test that is loaded and used successfully.
> Generate identity model to test linalg

- qa/L0_lifecycle/lifecycle_test.py
- qa/L0_lifecycle/test.sh
Related PR: https://github.com/triton-inference-server/core/pull/165
> Add parallel model loading speedup test

- docs/user_guide/ragged_batching.md
- qa/L0_batcher/batcher_test.py
- qa/L0_batcher/test.sh
PyTorch backend PR: https://github.com/triton-inference-server/pytorch_backend/pull/95
> Add libtorch ragged test in L0_batcher

- src/http_server.cc
Looks like I made a mistake in cherry-picking the changes and chose the wrong version during merge conflict.
> Fix memory leak

- CITATION.cff
- qa/common/check_copyright.py
Fixes #5518 
Followed [NeMo's example](https://github.com/NVIDIA/nemo/blob/main/CITATION.cff).
Used `NVIDIA Corporation` as generic author.
> Add CITATION.cff

- qa/L0_backend_python/test.sh
- qa/python_models/init_exit/config.pbtxt
- qa/python_models/init_exit/model.py
Python Backend: https://github.com/triton-inference-server/python_backend/pull/221
> Add testing for model getting killed during initialization

- Dockerfile.QA
- qa/L0_json/test.sh
- src/http_server.cc
Common PR change: https://github.com/triton-inference-server/common/pull/84
> Add json datatype checks

- docs/protocol/extension_schedule_policy.md
- qa/L0_sequence_batcher/request_timeout_models/identity_fp32_timeout/config.pbtxt
- qa/L0_sequence_batcher/sequence_batcher_test.py
- qa/L0_sequence_batcher/test.sh
core: https://github.com/triton-inference-server/core/pull/180
> Add documentation for sequence request timeout. Add test

- qa/L0_backend_python/bls/test.sh
- qa/python_models/bls/model.py
Python backend: https://github.com/triton-inference-server/python_backend/pull/227
> Add testing for Python BLS preferred memory configuration

- Dockerfile.QA
- build.py
- docs/user_guide/jetson.md
- qa/L0_batcher/test.sh
- qa/L0_custom_ops/test.sh
- qa/L0_perf_resnet/test.sh
- qa/L0_tf_parameters/test.sh
This PR removed TF1 from the build and our QA testing.
Related PRs:
Core - https://github.com/triton-inference-server/core/pull/182
TensorFlow backend- https://github.com/triton-inference-server/tensorflow_backend/pull/90
> Remove tf1 dependency

- qa/L0_backend_python/test.sh
Some dependency related failure was observed. Re-ordering the sub-test fixed the issue.
> Re-order L0_backend_python test order

- .gitignore
- docs/user_guide/metrics.md
- qa/L0_metrics/metrics_test.py
- qa/L0_metrics/test.sh
- qa/L0_metrics/unit_test_models/identity_cache_off/config.pbtxt
- qa/L0_metrics/unit_test_models/identity_cache_on/config.pbtxt
- src/command_line_parser.cc
- src/command_line_parser.h
* Add metrics config CLI (#5581)
* Add Summary metric testing and docs (#5615)
> Add --metrics-config, docs, and tests (#5619)

- docs/protocol/extension_parameters.md
* Add documentation for forwarding headers
* Add an example
This PR doesn't require a respin.
> Add documentation for forwarding headers (#5662)

- qa/L0_backend_python/examples/test.sh
Related PR: https://github.com/triton-inference-server/python_backend/pull/230
> Update JAX installation

- docs/Dockerfile.docs
To avoid incompatibilities with package updates have pinned all versions of explicitly installed python packages.
> Pin Python Package Versions for HTML Document Generation

- qa/L0_backend_python/custom_metrics/test.sh
- qa/L0_backend_python/examples/test.sh
- qa/L0_backend_python/test.sh
- qa/python_models/custom_metrics/config.pbtxt
- qa/python_models/custom_metrics/model.py
Python Backend: https://github.com/triton-inference-server/python_backend/pull/235
> Add testing for Python custom metrics API

- qa/L0_memory_growth/test.sh
(1) reduce MAX_ALLOWED_ALLOC to be more strict for bounded tests, and generous for unbounded tests.
(2) allow unstable measurement from PA.
(3) improve logging for future triage
> [cherry-pick] Fix L0_memory_growth (#5795)

- deploy/mlflow-triton-plugin/mlflow_triton/deployments.py
UnboundLocalError: local variable 'meta_dict' referenced before assignment
The above error shows in listing models in Triton model repository
> Minor fix for running "mlflow deployments create -t triton --flavor triton ..."

- docs/user_guide/metrics.md
* Add note on --metrics-address
* Copyright
> Add note on --metrics-address (#5800)

- qa/L0_libtorch_inference_mode/test.sh
The client script used in the test was not set properly.
> Fix client script for L0_libtorch_inference_mode

- qa/L0_model_update/instance_update_test.py
core: https://github.com/triton-inference-server/core/pull/209
> Add more test on instance signature

- qa/L0_backend_python/lifecycle/lifecycle_test.py
- qa/python_models/execute_error/model.py
Add testing for: Python backend: https://github.com/triton-inference-server/python_backend/pull/251
> Add testing for new error handling API

- qa/L0_storage_S3_local/mock_s3_service.py
- qa/L0_storage_S3_local/test.sh
* Add test for detecting S3 http2 upgrade request
* Enhance testing
* Copyright year update
> Add test for detecting S3 http2 upgrade request (#5911)

- build.py
* Add HPCX dependencies to search path
* Copy hpcx to CPU-only container
* Add ucc path to CPU-only image
* Fixed if statement
* Fix df variable
* Combine hpcx LD_LIBRARY_PATH
> Ensure HPCX dependencies found in container (#5922)

- qa/L0_io/test.sh
- qa/L0_libtorch_instance_group_kind_model/client.py
- qa/L0_libtorch_instance_group_kind_model/gen_models.py
- qa/L0_libtorch_instance_group_kind_model/models/libtorch_multi_device/config.pbtxt
- qa/L0_libtorch_instance_group_kind_model/test.sh
* Add testing for Pytorch instance group kind MODEL
* Remove unused item
* Update testing to verify the infer result
* Add copyright
* Remove unused import
* Update pip install
* Update the model to use the same add sub logic
* Add torch multi-gpu and multi-device models to L0_io
* Fix up model version
> Add testing for Pytorch instance group kind MODEL (#5810)

- build.py
- Split CPU-only Linux libs into own function to make if-else statement clearer
> Refactor build.py CPU-only Linux libs for readability

- docs/customization_guide/inference_protocols.md
Javacpp-presets PR: https://github.com/bytedeco/javacpp-presets/pull/1361
Developer tools test: https://github.com/triton-inference-server/developer_tools/pull/20
Client script PR:  https://github.com/triton-inference-server/client/pull/331
> Update README to include CAPI Wrapper Java Bindings

- qa/L0_backend_python/bls/test.sh
- qa/python_models/bls_model_loading/config.pbtxt
- qa/python_models/bls_model_loading/model.py
Python backend: https://github.com/triton-inference-server/python_backend/pull/262
> Add test for Python BLS model loading API

- qa/L0_perf_analyzer/test.sh
- qa/L0_perf_analyzer_capi/test.sh
Testing updates to match updated error messages in https://github.com/triton-inference-server/client/pull/350
> Update test failure messages

- docs/user_guide/performance_tuning.md
Starting the server/client container in the background would immediately exit.
Updated the guide to use interactive container and fixed some formatting issues.
> Improve performance tuning guide

- qa/L0_model_queue/model_queue_test.py
- qa/L0_model_queue/test.sh
Core PR: https://github.com/triton-inference-server/core/pull/237
> Fix queue test to expect exact number of failures

- docs/index.md
- docs/user_guide/faq.md
Update docs with NVAIE messaging
> Update docs with NVAIE messaging (#6162)

- README.md
- docs/index.md
- docs/user_guide/faq.md
Remove extra whitespace that was added in a previous documentation update.
> Remove extra whitespace

- docs/user_guide/metrics.md
Updating docs to mention power unit, matching help description:
```
```
> Add Watts unit to nv_gpu_power_usage description

- Dockerfile.QA
- qa/L0_request_cancellation/models/model/config.pbtxt
- qa/L0_request_cancellation/test.sh
- src/grpc/grpc_utils.cc
- src/test/CMakeLists.txt
core: https://github.com/triton-inference-server/core/pull/249
common: https://github.com/triton-inference-server/common/pull/99
> Add L0_request_cancellation

- qa/L0_parameters/model_repository/ensemble/config.pbtxt
- qa/L0_parameters/model_repository/identity/config.pbtxt
- qa/L0_parameters/parameters_test.py
- qa/L0_parameters/test.sh
Server: https://github.com/triton-inference-server/server/pull/6284
Core: https://github.com/triton-inference-server/core/pull/261
> Add ensemble parameter forwarding test

- src/simple.cc
https://github.com/triton-inference-server/core/pull/258
> Update the request re-use example

- src/simple.cc
* Update the request re-use example
* Review edit
* Review comment
> Update the request re-use example (#6283)

- docs/README.md
- docs/user_guide/request_cancellation.md
> Add documentation on request cancellation (#6403)

- docs/user_guide/request_cancellation.md
> Fixes in request cancellation doc (#6409)

- qa/L0_data_compression/test.sh
Cherry pick https://github.com/triton-inference-server/server/pull/6424
> Fix missing library in L0_data_compression

- qa/common/gen_common.py
Cherry pick https://github.com/triton-inference-server/server/pull/6427
> Fix L0_implicit_state (#6427)

- qa/L0_java_memory_growth/test.sh
- qa/L0_java_resnet/test.sh
- qa/L0_java_sequence_batcher/test.sh
- qa/L0_java_simple_example/test.sh
Simplify testing when upstream (javacpp-presets) build changes. 
Cherry-pick https://github.com/triton-inference-server/server/pull/6385
> Add Javacpp-presets repo location as env variable in Java tests(#6385)

- build.py
vLLM's latest `emergency` release
> Adding emergency vllm latest release

- src/grpc/infer_handler.cc
- src/grpc/infer_handler.h
- src/grpc/stream_infer_handler.cc
> Fix notify state destruction and inflight states tracking (#6451)

- build.py
* TRTLLM backend post release
* TRTLLM backend post release
* Update submodule url for permission issue
* Update submodule url
* Fix up
* Not using postbuild function to workaround submodule url permission issue
> Update TRT-LLM backend url (#6455)

- build.py
This reverts commit 3d9cd82a4d9247d9fc1332829647ceec0243f152.
> Revert "Update ORT to 1.16.1 (#6439)"

- qa/L0_backend_python/bls/test.sh
- qa/python_models/bls/model.py
Python backend: https://github.com/triton-inference-server/python_backend/pull/293
> Test Python BLS with different sizes of CUDA memory pool

- docs/protocol/extension_generate.md
* Document generate HTTP endpoint
* Fix up
* format
> Document generate HTTP endpoint (#6412)

- build.py
Update build.py to use the post-build function for TRT-LLM backend.
> Use post build function for TRT-LLM backend

- qa/L0_model_config/autofill_noplatform/python/input_wrong_property/expected
> Follow up to autocomplete pr #317

- qa/L0_metrics/metrics_queue_size_test.py
- qa/L0_metrics/test.sh
* Enhance testing for pending request count
* Improve the documentation
* Add more documentation
> Enhance testing for pending request count (#6532)

- README.md
- docs/contents.md
- docs/customization_guide/deploy.md
* draft document
* updates
* updates
* updated
* updates
* updates
* updates
* updates
* updates
* updates
* updates
* updates
* updates
* updates
* updates
* updates
* updates
* updates
* updates
* updates
* updates
* updates
* updates
* updates
* update
* updates
* updates
* Update docs/customization_guide/deploy.md
* Update docs/customization_guide/deploy.md
* fixing typos
* updated with clearer warnings
* updates to readme and toc
---------
> secure deployment considerations guide (#6533)

- docs/user_guide/request_cancellation.md
Add TRT LLM backend into the list of backends that support request cancellation.
> Mention TRT LLM backend supports request cancellation

- docs/user_guide/request_cancellation.md
Pick https://github.com/triton-inference-server/server/pull/6585 into r23.11
> Mention TRT LLM backend supports request cancellation (#6585)

- docs/contents.md
Update generated docs with recent markdown pages.
Generate endpoint and secure deployment docs were already added in other PRs.
> Add request cancellation and debugging guide to generated docs

- qa/L0_backend_python/setup_python_enviroment.sh
This fixes the issue where python client has 
`AttributeError: 'NoneType' object has no attribute 'enum_types_by_name'
errors after python version is updated.
> Update protobuf after python update for testing

- build.py
Need to run the CI once the release branch has pushed to TRT-LLM backend GH repo.
> Revert tekit changes

- src/tracer.cc
This PR resolves the following issue: https://github.com/triton-inference-server/server/issues/6512
> Added request id to span attributes

- qa/L0_optional_input/models/optional_connecting_tensor/config.pbtxt
- qa/L0_optional_input/models/optional_identity/1/model.py
- qa/L0_optional_input/models/optional_identity/config.pbtxt
- qa/L0_optional_input/optional_input_test.py
- qa/L0_optional_input/test.sh
* Add test for optional internal tensor within an ensemble
* Fix up
> Add test for optional internal tensor within an ensemble

- Dockerfile.QA
- build.py
- qa/L0_backend_python/examples/test.sh
- qa/L0_backend_python/test.sh
- qa/L0_infer/test.sh
Bring iGPU build refactor into main
> iGPU build refactor (#6684)

- deploy/mlflow-triton-plugin/mlflow_triton/deployments.py
> Mlflow Plugin Fix (#6685)

- CMakeLists.txt
Adding default for the `TRITON_IGPU_BUILD` variable
> adding default value for TRITON_IGPU_BUILD=OFF

- qa/L0_backend_python/decoupled/decoupled_test.py
- qa/L0_backend_python/decoupled/models/decoupled_raise_exception/1/model.py
- qa/L0_backend_python/decoupled/models/decoupled_raise_exception/config.pbtxt
- qa/L0_backend_python/decoupled/test.sh
* Add test case for decoupled model raising exception
* Remove unused import
> Add test case for decoupled model raising exception (#6686)

- docs/protocol/extension_generate.md
> Escape special characters in generate docs

- qa/L0_infer_zero/infer_zero_test.py
Testing for https://github.com/triton-inference-server/pytorch_backend/pull/120
> Add testing for zero tensors in PyTorch backend

- qa/L0_trace/opentelemetry_unittest.py
- qa/L0_trace/test.sh
- qa/L0_trace/trace-config.yaml
- src/CMakeLists.txt
- src/grpc/infer_handler.cc
- src/grpc/infer_handler.h
- src/grpc/stream_infer_handler.cc
- src/http_server.cc
- src/http_server.h
- src/sagemaker_server.cc
- src/tracer.cc
- src/tracer.h
Added support for OTel context propagation
---------
> Support for Context Propagation for OTel trace mode (#6785)

- docs/user_guide/trace.md
> Fix typos in trace.md

- qa/L0_python_api/test.sh
Generate pytest reports to try parsing of unit test reports on gitlab CI side
> Generate unittest xml reports from L0_python_api

- docs/user_guide/metrics.md
Improve discoverability of TRTLLM backend metrics
> Add link to TRTLLM docs

- qa/L0_backend_python/test.sh
Fixes L0_backend_python variant tests with different Python versions.
> Install required pip pkgs

- docs/user_guide/model_configuration.md
- docs/user_guide/response_cache.md
- docs/user_guide/trace.md
> Add note on spacing

- Dockerfile.sdk
Cherry pick genai-perf into the sdk container for 24.03 release.
> Install `genai-pa` into SDK container (#6942)

- qa/L0_trace/trace_context.py
This PR adds the licensing header for NVIDIA.
> Fix Copyright in trace_context.py

- README.md
Add banner for onsite meetup event for visibility.
> Add meetup invite banner

- qa/L0_iterative_sequence/iterative_sequence_e2e.py
- qa/L0_iterative_sequence/models/iterative_sequence/config.pbtxt
- qa/L0_iterative_sequence/test.sh
https://github.com/triton-inference-server/core/pull/337
> Add testing for iterative scheduler backlogged requests

- qa/L0_logging/logging_endpoint_test.py
- qa/L0_logging/test.sh
- src/grpc/grpc_server.cc
- src/http_server.cc
Disable dynamic log file location, aka `--log_file` API.
> Disable Dynamic Log File

- qa/L0_trace/test.sh
- qa/L0_trace/trace_endpoint_test.py
- src/command_line_parser.cc
- src/grpc/grpc_server.cc
- src/http_server.cc
- src/tracer.cc
- src/tracer.h
Add trace_mode and trace_config to getTraceSettingsAPI
---------
> Add trace mode and trace config entries in trace settings API (#7050)

- qa/L0_shared_memory/shared_memory_test.py
- qa/L0_shared_memory/test.sh
- src/shared_memory_manager.cc
🍒 Cherry pick #7093 for r24.04
> Validate system shared memory region size when registering a region (#7093)

- qa/L0_logging/logging_endpoint_test.py
Commit on main https://github.com/triton-inference-server/server/commit/6b9da4e7d66dfca4e0b769c43a74caaca6fc784a
> Update L0_logging to reflect error when trying to update log_file (#7112)

- qa/L0_grpc_state_cleanup/cleanup_test.py
- qa/L0_grpc_state_cleanup/test.sh
- src/grpc/infer_handler.h
- src/grpc/stream_infer_handler.cc
* Fix state complete_ race condition
* Add delay and error checking to StreamInferResponseComplete
* Add test for gRPC decoupled infer complete flag
> Fix gRPC frontend race condition (#7110)

- src/shared_memory_manager.cc
Cherry pick of: https://github.com/triton-inference-server/server/pull/7137
Fixes windows issues caused by: https://github.com/triton-inference-server/server/pull/7083
> fix windows build for shared memory fix #7137

- docs/_reference/tritonclient_api.rst
- qa/L0_shared_memory/shared_memory_test.py
- qa/L0_shared_memory/test.sh
**Goal:** The python client was not properly deallocating dynamic memory when destroying shared memory regions. This PR bundle fixes the leak and adds an additional test case.
**Sub-Goal:** Fix the formatting in the .rst document to fix an unrelated CI failure.
Client PR: https://github.com/triton-inference-server/client/pull/614
> Fix Python Shm Client Leak

- Dockerfile.QA
* Upgrade the golang version to 1.22.3
* Move to recommended go install method
> Upgrade the golang version to 1.22.3 (#7208)

- build.py
* Update 'Dockerfile' Python path to include DALI
* Update 'Dockerfile' Python path to include DALI
* Switch to Dockerfile syntax
* Add indentation line
> Update 'Dockerfile' Python path to include DALI (#7216)

- src/CMakeLists.txt
- src/shared_memory_manager.cc
* Remove cuda dependency
* Remove unused include
* Add comments
> Remove the dependency on CUDA driver (#7224)

- qa/L0_backend_python/examples/test.sh
- qa/L0_backend_python/test.sh
* Fix TEST_JETSON double square bracket issue
* Use and instead of or
> Fix L0_backend_python iGPU PyTorch installation (#7231)

- qa/L0_simple_go_client/test.sh
* Fix the L0_simple_go_clien
* Remove unused variable
> Fix the L0_simple_go_client (#7239)

- qa/L0_backend_config/test.sh
Updated with functions to retrieve backend configuration map from server log after log formatting changes.
> updating log parsing in test

- docs/protocol/extension_logging.md
- qa/L0_backend_config/test.sh
- qa/L0_logging/log_format_test.py
- qa/L0_logging/test.sh
- qa/L0_model_update/instance_update_test.py
- qa/L0_pinned_memory/test.sh
- src/grpc/grpc_server.cc
Collects:
(#7219)
(#7248) 
(#7251)
---------
> Logging format cherry-picks (#7219) (#7248) (#7251)

- build.py
Resolved merge conflicts for https://github.com/triton-inference-server/server/pull/7089
> Update openvino to 2024.0.0

- build.py
vllm currently published v0.4.3 as a pre-release. Thus starting this PR to verify our ci.
None
Line 79
- CI Pipeline ID: 15471189 
None
vLLM releases: https://github.com/vllm-project/vllm/releases
None
> build: Update vllm version to v0.4.3 (latest)

- qa/L0_libtorch_disable_cudnn/test.sh
Add testing for https://github.com/triton-inference-server/pytorch_backend/pull/123/
> Add testing for libtorch cudnn

- qa/L0_onnx_optimization/test.sh
Add testing for https://github.com/triton-inference-server/onnxruntime_backend/pull/256 to verify CUDA EP options can now be set using the new format in config file.
L0_onnx_* tests should be passing, especially for L0_onnx_optimization
- CI Pipeline ID: 15608517
> test: Add testing for CUDA EP options

- Dockerfile.QA
- Dockerfile.sdk
- build.py
- docs/user_guide/jetson.md
- qa/L0_backend_fastertransformer/test.sh
- qa/L0_http_fuzz/test.sh
- qa/common/util.sh
Going to run tritonserver GitLab pipeline on nightly mode for comprehensive coverage.
- CI Pipeline ID: 15604366
Breaking changes introduced by numpy v2.0.0: [docs](https://numpy.org/devdocs/release/2.0.0-notes.html)
> ci: Restrict numpy to version 1.x

- qa/L0_simple_ensemble/ensemble_test.py
- qa/L0_simple_ensemble/test.sh
Cherrypick for Ensemble sequence flag preserve fix from server main.
CC @rmccorm4 @nv-kmcgill53
> test: Add test for sequence flags in ensemble streaming inference (#7344)

- README.md
> Update REAMDE.md for 24.06

- qa/L0_grpc_state_cleanup/cleanup_test.py
This PR fixes intermittence of L0_grpc_state_cleanup.
2 sources of intermittence:
1) *_error_status: Was failing periodically because it was seeing `The stream is no longer in valid state, the error detail is reported through provided callback. A new stream should be started after stopping the current stream.`, but expecting `This protocol is restricted, expecting header 'triton-grpc-protocol-infer-key'`
Due to request count > 1, there is a time interval between when the request1 gets picked by gRPC server infer handler and it detect that the protocol was restricted. The requests sent in between this time period from client side will not see  "The stream is no longer in valid state" error.
It was decided to relax the condition and checking for both errors.
2) *_shutdownserver:
Was failing …
> [fix]: grpc state cleanup fix

- build.py
Upgrading vllm version to the current latest 
vllm_backend: https://github.com/triton-inference-server/vllm_backend/pull/45
- CI Pipeline ID: 16271096
> [build]: vllm version update

- qa/L0_trt_compat/test.sh
Cherry-picking https://github.com/triton-inference-server/server/pull/7432 into the release branch.
> fix: Fix error message for L0_trt_compat (#7432)

- README.md
Update README for 24.07 release.
* [Internal contribution template](https://raw.githubusercontent.com/triton-inference-server/server/main/.github/PULL_REQUEST_TEMPLATE/pull_request_templ …
> Update README for 24.07

- build.py
> Pvijayakrish update packages trtllm

- README.md
Updating the version info in README for branch r24.07. 
* [Internal contribution template](https://raw.githubusercontent.com/triton-inference-server/server/main/.github/PULL_REQUEST_TEMP …
> Updating the version info in README

- build.py
> Including 'tritonserver.lib' into final package

- README.md
> Add vLLM x Triton user meetup announcement

- build.py
Upgrading the vLLM version to reference the current latest [v0.5.4](https://github.com/vllm-project/vllm/releases/tag/v0.5.4) for 24.08 release.
> Build: Upgrading vLLM version for 24.08 release

- build.py
Updating the vLLM version to reference [0.5.3.post1](https://github.com/vllm-project/vllm/releases/tag/v0.5.3.post1) for 24.08 release.
> Build: Update Vllm version for 24.08

- qa/python_models/custom_metrics/model.py
> test: Add python backend tests for the new histogram metric (#7540)

- src/grpc/infer_handler.h
> Intermittent `L0_decoupled_grpc_error` crash fixed. (#7552)

- README.md
Updates the README file for the 24.08 Triton release. 
>  Release: Update README for r24.08

- docs/customization_guide/build.md
Add python backend to windows build `build.py` command.
https://github.com/triton-inference-server/server/issues/7551
> docs: Add python backend to windows build command

- docs/customization_guide/tritonfrontend.md
- qa/L0_python_api/test_kserve.py
- src/python/tritonfrontend/__init__.pyi
Adding copyright information that are missing in current files that were merged as a part of this [PR](https://github.com/triton-inference-server/server/pull/7501). 
> fix: Adding copyright info

- build.py
Updates the Triton version in map to reflect the 24.09 Release version. 
> Build: Update triton version in Map

- qa/L0_cuda_shared_memory/cuda_shared_memory_test.py
- qa/L0_cuda_shared_memory/test.sh
- qa/L0_shared_memory/shared_memory_test.py
- qa/L0_shared_memory/test.sh
- qa/L0_trt_shape_tensors/test.sh
- qa/python_models/execute_delayed_model/config.pbtxt
- qa/python_models/execute_delayed_model/model.py
- src/grpc/infer_handler.cc
- src/grpc/infer_handler.h
- src/grpc/stream_infer_handler.cc
- src/http_server.cc
- src/http_server.h
- src/shared_memory_manager.cc
- src/shared_memory_manager.h
> Cherry-pick: fix: Add reference count tracking for shared memory regions (#7567)

- src/grpc/stream_infer_handler.cc
> Cherry-pick: Fix: Add mutex lock for state completion check in gRPC streaming to prevent race condition

- Dockerfile.win10.min
Dockerfile.win10.min - Update dependency versions
> Dockerfile.win10.min - Update dependency versions 

- README.md
Updates the README file for the 24.08 Triton release.
> Release: Update README for r24.09

- README.md
Removed vLLM meetup announcement
- CI Pipeline ID: N/A
> [docs] Removed vLLM meetup announcement

- README.md
Currently warning is not clearly visible/renderred:
After this PR:
> [doc]Adjusted formatting of the warning

- docs/user_guide/architecture.md
Clarify the meanings of key and value in an ensemble step in relation to the input/output tensors on the ensemble and composing models.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
> docs: Clarify meanings of ensemble key and value

- CMakeLists.txt
- qa/L0_java_memory_growth/MemoryGrowthTest.java
- qa/L0_java_resnet/ResnetTest.java
> Change compute capablity min value

- build.py
Update Openvino and vLLM versionsfor Release 24.10
> Build: Update Openvino and vLLM versionsfor Release 24.10

- qa/L0_trt_dla/dla_test.py
- qa/L0_trt_dla/test.sh
> Fix array size for jetson tests

- README.md
Updates the README file for the 24.10 Triton release.
> Release: Update README for r24.10 

- qa/L0_shared_memory/shared_memory_test.py
- qa/common/infer_util.py
> chore: ensure proper clean up in shared memory related tests

- qa/common/reporter.py
Include job id and nightly tag together with the results uploaded.
N/A
N/A
N/A
- CI Pipeline ID: 19882967
N/A
N/A
N/A
> refactor: Include job id and nightly tag to results uploaded

- CMakeLists.txt
- qa/L0_java_memory_growth/MemoryGrowthTest.java
- qa/L0_java_resnet/ResnetTest.java
This reverts commit 69e85e2893dbaf5d144a13ea43a53426a7558a4c.
* [Internal contribution template](https://raw.githubusercontent.com/triton-inference-server/server/main/.github/PULL_REQUES …
> Reapply "Change compute capability min value (#7708)"

- qa/common/gen_qa_model_repository
> Fix model generation

- qa/L0_storage_S3/test.sh
- qa/L0_storage_azure/test.sh
Modify the tests so that they only execute on requested backends.
CI Pipeline ID:
20331330
Core changes: https://github.com/triton-inference-server/core/pull/411
> test: RHEL Filesystem Tests

- qa/common/gen_jetson_trt_models
- qa/common/gen_qa_custom_ops
- qa/common/gen_qa_model_repository
> Update model generation scenario (#7793)

- qa/L0_dyna_implicit_state/test.sh
The test erros out:
```
cp: cannot stat '/data/inferenceserver/24.11_a100_a100/qa_dyna_sequence_implicit_model_repository/*': No such file or directory 
```
Since `L0_dyna_implicit_state` test will `cd` into `L0_dyna_sequence_batcher` test directory, need to remove the `${REPO_VERSION}_${TEST_REPO_ARCH}` to fix the name of the test repo.
- CI Pipeline ID: 20448566
> test: Fix L0_dyna_implicit_state--base

- qa/L0_dyna_implicit_state/test.sh
- qa/L0_dyna_sequence_batcher/test.sh
- qa/L0_response_cache/test.sh
Update the error message to be compared in the test for L0_response_cache.
Follow up PR for L0_dyna_implicit_state: https://github.com/triton-inference-server/server/pull/7801
> test: Follow up PR for L0_dyna_implicit_state. Fix error message for L0_response_cache test

- qa/L0_backend_python/decoupled/test.sh
- qa/L0_backend_python/test.sh
> Change torch versions

- qa/L0_input_validation/input_validation_test.py
- Updated ` shm.set_shared_memory_region()` call to write data matching the size of the created shm region
- CI Pipeline ID: 20432028
> fix: Fix L0_input_validation

- qa/L0_input_validation/input_validation_test.py
> fix: Fix L0_input_validation (#7800)

- qa/L0_memory_growth/test.sh
> test: Increase measurement-interval

- README.md
> Update REAMDE.md 

- qa/L0_backend_python/io/io_test.py
- qa/L0_backend_python/io/requested_output_model/config.pbtxt
- qa/L0_backend_python/io/requested_output_model/model.py
- qa/L0_backend_python/io/test.sh
Pick https://github.com/triton-inference-server/server/pull/7866 into r24.12
> test: Fix requested output deleting extra outputs (#7866)

- python/openai/requirements.txt
Addresses https://github.com/advisories/GHSA-f96h-pmfr-66vw
> fix: Upgrade starlette>=0.40.0 to address pulse scan

- build.py
Upgrade vLLM version to 0.6.3.post1
https://github.com/triton-inference-server/vllm_backend/pull/76
N/A
N/A
- CI Pipeline ID: See the related PR.
N/A
N/A
N/A
> perf: Upgrade vLLM version to 0.6.3.post1

- compose.py
> Add environment variable to `compose.py`

- qa/common/gen_qa_custom_ops
> Fixing typo in script

- docs/backend_guide/vllm.rst
- docs/client_guide/api_reference.rst
- docs/client_guide/in_process.rst
- docs/client_guide/kserve.rst
- docs/client_guide/kserve_extension.rst
- docs/client_guide/python.rst
- docs/client_guide/python_readme.rst
- docs/contents.rst
- docs/exclusions.txt
- docs/getting_started/llm.md
- docs/getting_started/quick_deployment_by_backend.rst
- docs/getting_started/quick_start.rst
- docs/perf_benchmark/genai-perf-README.rst
- docs/perf_benchmark/genai_perf.rst
- docs/perf_benchmark/model-analyzer-README.rst
- docs/perf_benchmark/model_analyzer.rst
- docs/perf_benchmark/perf-analyzer-README.rst
- docs/perf_benchmark/perf_analyzer.rst
- docs/repositories.txt
- docs/scaling_guide/scaling_guide.rst
- docs/server_guide/features.rst
- docs/server_guide/model_pipelines.rst
- docs/server_guide/state_management.rst
- qa/common/check_copyright.py
- tools/add_copyright.py
The PR adds copyrights to new files included in the docs folder.
> fix: Fix copyrights for new files added to documentation

- build.py
> Install python build package inside Winbase build container

- build.py
> fix: Correct triton_container_version

- qa/L0_openai/test.sh
Cherry-pick the fix for L0_openai_trtllm test.
> ci: Fix/Improve L0_openai_trtllm test (#7948)

- build.py
This fix reverts some pip installations where the packages are held by debian instead of python, thus causing a build error and failing. 
N/A
N/A
Re-run the CI with these changes and see that the builds pass
22888274
N/A
This is in relation to the patchelf downgrade: https://github.com/triton-inference-server/server/commit/fe3fcf7c42c81ee15cbee1768de9105c6b11743e
- N/A
> build: Fix bad pip installations in container build

- docs/introduction/compatibility.md
Update the release compatibility matrix for 25.01 release to show information about Triton vLLM Image, Triton TRT-LLM image, and Onnx runtime version supported. I added the Triton TRT-LLM image, even though this image will not be published today, to avoid requiring a change in documentation later on and since we don't expect the container software versions to change. 
- [ x ] PR title reflects the change and is of format `<commit_type>: <Title>`
- [ x ] Changes are described in the pull request.
- [ x ] docs
Updating the release compatibility matrix for customers to see the latest container image data for 25.01 release: …
> docs: Update compatibility matrix for r25.01 release

- CONTRIBUTING.md
This PR fixes the broken link for pre-commit-config.yaml file in contributing.md file.
NA
NA
NA
NA
- closes https://jirasw.nvidia.com/browse/DLIS-7955
> Docs: Fix the broken link for pre-commit-config.yaml file

- Dockerfile.win10.min
> Updated Dockerfile.win10.min with the versions needed for the windows build

- docs/customization_guide/sagemaker.md
Title says all.
N/A
N/A
N/A
SageMaker user guide is missing.
> doc: add a user guide of important pointers on how to run sagemaker_server

- build.py
> Enable remote cache if applicable 

- qa/common/gen_jetson_trt_models
- qa/common/gen_qa_custom_ops
- qa/common/gen_qa_model_repository
This change help us to see what is compute capability is exactly used and which device driver
> Extend gpu query on models generation

- qa/L0_batch_custom/test.sh
- qa/L0_client_build_variants/test.sh
Set default variables for repo tags to pass into tests which call cmake via:
````
cmake -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install \
-DTRITON_REPO_ORGANIZATION:STRING=${TRITON_REPO_ORGANIZATION} \
-DTRITON_BACKEND_REPO_TAG=${TRITON_BACKEND_REPO_TAG} \
-DTRITON_CORE_REPO_TAG=${TRITON_CORE_REPO_TAG} \
-DTRITON_COMMON_REPO_TAG=${TRITON_COMMON_REPO_TAG} .. &&
````
- qa/L0_batch_custom/test.sh
- qa/L0_client_build_variants/test.sh
25414242
New variables were added to tests in the following commit: https://github.com/triton-inference-server/server/commit/b534c7c898298c64d70afb86f2e03069d2f5c268
> [test]: L0_batch_custom & L0_client_build_variants: Set default values for triton repos to pass in to cmake

- qa/L0_io/test.sh
- qa/L0_string_io/string_client_test.py
- qa/L0_string_io/test.sh
> rm:TensorFlow - fix to 'L0_io' and 'L0_string_io'

- qa/L0_server_status/server_status_test.py
- qa/L0_server_status/test.sh
> rm:TensorFlow - fix to 'L0_server_status' 

- qa/L0_output_name/output_name_test.py
> rm:TensorFlow - fix to 'L0_output_name'(TPRD-1278)

- qa/L0_orca/orca_http_test.py
- qa/L0_orca/test.sh
> test: Add test for ORCA (#8009)

- qa/L0_nullchar_string/nullchar_string_client.py
- qa/L0_nullchar_string/test.sh
Fix the L0_nullchar_string test by replacing the tf and onnx models with python and libtorch models. Fix the input and output names for libtorch models.
- CI Pipeline ID: 26348600
> fix: Fix L0_nullchar_string test

- qa/L0_input_validation/test.sh
PR for
https://gitlab-master.nvidia.com/dl/dgx/tritonserver/-/jobs/153017913
L0_input_validation
> Update savemode to onnx

- src/python/tritonfrontend/_api/_kservegrpc.py
- src/python/tritonfrontend/_api/_kservegrpc.pyi
Fix the openai frontend's arguments missing error by adding the missing arguments in the python bindings.
26360276
https://nvidia.slack.com/archives/C075Z5D75V3/p1743551907903899?thread_ts=1743526595.070189&cid=C075Z5D75V3
> fix: fix the openai frontend's arguments missing error

- qa/L0_infer/test.sh
> TPRD-1327: Update number of tests

- qa/L0_infer/test.sh
- qa/ensemble_models/mix_platform_float32_float32_float32/config.pbtxt
> ci: Fix L0_infer--cpu* tests

- qa/L0_storage_S3_local/test.sh
- qa/L0_storage_azure/test.sh
onnx backend autocomplete works via substituting the whole input field and not only parts of it (dims and data_type)
26403847
> Adjusting storage tests for onnx models

- docs/introduction/compatibility.md
> Added 25.03 to the compatibility matrix.

- build.py
> vLLM backend SBSA build

- qa/L0_trace/test.sh
- qa/L0_trace/trace_stress_grpc_client.py
- src/tracer.cc
Server crashes after processing tens of thousands of requests with various segmentation faults. This PR fixs the root cause, which is deleting a mutex inside the lock and caused undefined behavior.
After the change, server runs normally tested overnight.
L0_trace
26879251
- closes GitHub issue: #7795
> fix: Fix segfaults in tracing mode after long run 

- build.py
- qa/L0_trace/test.sh
- qa/L0_trace/trace_stress_grpc_client.py
- src/tracer.cc
> Merge main onto release to bring 3 missing commits

- README.md
> fix: Update REAMDE.md

- src/python/tritonfrontend/_api/_kservegrpc.py
- src/python/tritonfrontend/_api/_kservegrpc.pyi
Quick fix for a bug that will cause the openai api frontend not able to start due to the missing arguments. 
27283832
> fix: fix the bug that openai api frontend not able to start 

- Dockerfile.QA
- qa/L0_grpc/test.sh
- qa/L0_http/test.sh
Related PRs:
client: https://github.com/triton-inference-server/client/pull/833
> Fixes for 25.04 release L0_grpc_* and L0_http_* tests

- Dockerfile.QA
- qa/L0_grpc/test.sh
- qa/L0_http/test.sh
> Fixes for 25.04 release L0_grpc_* and L0_http_* tests (#8152)

- qa/L0_input_validation/test.sh
Copy required model with minimal input size (TYPE_BOOL).
[27387023](https://github.com/triton-inference-server/core/pull/434)
L0_input_validation--base
27387023
> test: Input batch size overflow vulnerability

- build.py
> Upgrade vllm version to 0.8.1

- build.py
Motivation to have ability to trace the changes for build.
> Adding additional output to build process

- qa/L0_shared_memory/shared_memory_test.py
- qa/L0_shared_memory/test.sh
- src/shared_memory_manager.cc
Added an additional check to prevent the value of byte_size and offset from overflowing and passing the following memory bounds check. 
Confirm the reasoning behind L490 is valid to avoid an integer overflow 
27820787
> Fix: Update handling of shared mem integer values

- build.py
> boost vLLM to 0.8.5

- build.py
> proper 25.05 version

- README.md
> Update README.md for r25.05 release

- docs/introduction/compatibility.md
> R25.04 compatibility

- docs/introduction/compatibility.md
> R25.04 compatibility (#8201)

- qa/L0_backend_python/common.sh
- qa/L0_backend_python/env/test.sh
- qa/L0_backend_python/examples/test.sh
- qa/L0_backend_python/setup_python_enviroment.sh
> fix: Fix L0_backend_python test (#8178)

- README.md
- docs/introduction/compatibility.md
- docs/introduction/release_notes.md
> 25.05 release notes

- qa/L0_logging/test.sh
- qa/common/util.sh
Verify INFO logs are written to `stdout` and WARNING/ERROR logs to `stderr`.
https://github.com/triton-inference-server/common/pull/138
L0_logging
29629895
> test: Set correct log output stream

- qa/L0_client_nobatch/test.sh
> ci: Fix L0_client_nobatch--base

- README.md
Updating `README.md` for 25.06 release
> Update README.md for 2.59.0 / 25.06 release

- Dockerfile.sdk
- build.py
Recently DCGM released 4.3.0 and broke triton build. Install an old version (4.2.3) of datacenter-gpu-manager-4-dev will attempt to install the latest version (4.3.0) of datacenter-gpu-manager-4-core. Anchor the version of datacenter-gpu-manager-4-core to the old version to unblock the build.
```
#14 5.857 The following packages have unmet dependencies:
#14 5.920  datacenter-gpu-manager-4-dev : Depends: datacenter-gpu-manager-4-core (= 1:4.2.3-2) but 1:4.3.0-1 is to be installed
#14 5.926 E: Unable to correct problems, you have held broken packages.
```
32322048
> ci: Anchor datacenter-gpu-manager-4-core version

- qa/L0_backend_python/test.sh
> ci: Improve error handling for Python backend model initialization failures (#8303)

- qa/L0_shared_memory/shared_memory_test.py
- src/shared_memory_manager.cc
> fix: System shared memory boundary check (#8335)

- qa/L0_backend_python/model_control/model_control_test.py
- qa/L0_backend_python/model_control/test.sh
Add tests to confirm python_backend model load parameters are correctly validated
Cherry-pick for #8276 
#8276 
https://github.com/triton-inference-server/python_backend/pull/404
https://github.com/triton-inference-server/python_backend/pull/414
> fix: Add testing for explicit model load (#8276)

- qa/L0_lifecycle/test.sh
Locking cuda-python version to <13 to avoid cuda import issues for L0_lifecycle.
- CI Pipeline ID: 33298639
> fix: Locking cuda-python version to <13 for L0_lifecycle

- qa/L0_grpc/python_grpc_aio_test.py
Cherry-pick #8347
- CI Pipeline ID: 33317140
> ci: Resolve CI failures (#8347)

- python/openai/README.md
- python/openai/openai_frontend/frontend/fastapi/middleware/__init__.py
- python/openai/openai_frontend/frontend/fastapi/middleware/api_restriction.py
- python/openai/openai_frontend/frontend/fastapi_frontend.py
- python/openai/openai_frontend/main.py
- python/openai/tests/test_openai_restricted_apis.py
- python/openai/tests/utils.py
- src/command_line_parser.cc
> feat: Static key authentication for OpenAI frontend (#8374)

- docs/user_guide/performance_tuning.md
> fix: Replace dead link for Densenet (#8394)

- python/openai/requirements.txt
- python/openai/tests/vllm_mistral_models/mistral-nemo-instruct-2407/1/model.json
- python/openai/tests/vllm_models/llama-3.1-8b-instruct/1/model.json
- qa/L0_perf_vllm/test.sh
VLLM sets new config enable_log_requests: false by default.
See https://github.com/vllm-project/vllm/pull/21739
https://github.com/triton-inference-server/vllm_backend/pull/96
https://github.com/triton-inference-server/tutorials/pull/142
> ci: Remove deprecated vLLM config "disable_log_requests"

- src/simple.cc
> test: Fix L0_simple_lib--base (#8431)
