- README.rst
Also fix some line-length issues.
> Add README reference to release notes for #3

- src/test/caffe2plan.cc
When the targeted GPU does not support a requested int8 or fp16 option, issue a warning and continue by generating an fp16 plan. This allows CI tests to proceed even on GPUs that don't support all options.
> caffe2plan should proceed gracefully if int8 or fp16 not supported

- qa/L0_lifecycle/test.sh
- qa/common/util.sh
After server is live, wait until all models load/fail to load or until timeout (30 seconds)
> Improved "model fail" test in L0_lifecycle

- src/clients/c++/perf_client.cc
- src/core/dynamic_batch_scheduler.cc
- src/core/infer.cc
- src/core/scheduler.h
- src/core/sequence_batch_scheduler.cc
- src/core/sequence_batch_scheduler.h
- src/core/server.cc
- src/core/server_status.cc
- src/core/server_status.h
- src/servables/caffe2/netdef_bundle.cc
- src/servables/custom/custom_bundle.cc
- src/servables/tensorflow/base_bundle.cc
- src/servables/tensorrt/plan_bundle.cc
After this change, the scope of run timer is more aligned with the one in Run(), which is stopping the timer after `OnCompleteHandleInfer()`.
> Cleaned up timers on server side

- src/core/server.cc
- src/core/server_status.cc
- src/core/server_status.h
Addressed issue #36 , now the model config shown in status API is always up to date.
The error mentioned in the issue seems to be spurious (in my experiment, always show version 1 of the model). And the error message only happens on modified model. It may due to the fact that on modified model, the inference server first triggers its unload and then reload the model, which makes the model "unavailable" for a short period of time.
> Ensured ServerStatus to update stored model config on model modification

- src/servables/caffe2/netdef_bundle.cc
- src/servables/custom/custom_bundle.cc
- src/servables/tensorflow/base_bundle.cc
Suspect that it also fixes #14. Before the fix, the code only create runner threads based on number of instances and disregard the number of GPUs, which matches the description in #14.
> Fix #55 Corrected runner threads to spawn according to GPU counts.

- nvidia_entrypoint.sh
- qa/L0_infer/infer_test.py
- qa/L0_infer/test.sh
- src/core/metrics.cc
Note that the libcuda used is from `/usr/local/cuda-10.0/compat/lib.real/`, which is not a stub library. Because `cudaGetDeviceCount()` is called multiple times to initialize servables on proper devices (CPU if return cudaErrorNoDevice), avoid adding new condition if a usable library is already in the image.
> Use stub library if running on CPU-only device

- nvidia_entrypoint.sh
If the docker is run with option to change working directory, the entrypoint script will fail on CPU-only device.
**Don't delete this branch on merge, still using the branch for tuning CI tests**
> Use absolute path in case of changing work dir

- src/core/server.cc
- src/nvrpc/BidirectionalStreamingLifeCycle.h
- src/nvrpc/Interfaces.h
- src/nvrpc/LifeCycleUnary.h
With this commit, the TRTIS streaming API will:
1. handle (enqueue) the requests in the stream as they arrive (always run `ExecuteRPC()` on successful `Read()`)
2. queue up the responses in write-back queue as soon as they are ready (so they may be out of "order"), the lifecycle is no longer responsible for sending back responses in the same order as their requests arrived
In short, it will behave the same as what is in the non-streaming case, except that the requests and responses are transferred in the same connection, instead of one connection for one request/response pair.
> Modified server-side streaming behavior 

- src/clients/python/grpc_image_client.py
- src/clients/python/image_client.py
Currently image client examples works correcly only with square inputs. Width and height must be swapped in resize functions, see https://pillow.readthedocs.io/en/3.1.x/reference/Image.html#PIL.Image.Image.resize
> Fixed resize in client examples

- Dockerfile.QA
- qa/L0_batcher/batcher_test.py
- qa/L0_infer/test.sh
- qa/L0_infer_variable/test.sh
- qa/L0_sequence_batcher/sequence_batcher_test.py
- qa/L0_sequence_batcher/test.sh
- qa/common/infer_util.py
- qa/common/test_util.py
- qa/custom_models/custom_sequence_int32/config.pbtxt
- src/clients/c++/simple_sequence_client.cc
- src/clients/python/simple_sequence_client.py
- src/core/api.proto
- src/core/sequence_batch_scheduler.cc
- src/core/sequence_batch_scheduler.h
- src/core/server.cc
When all available slots are busy, sequences are kept in backlog
queues and then swapped into batch slots as they come available.
Add end-to-end testing for sequence batcher
> Fix sequence scheduler to efficiently handle backlogs

- src/core/BUILD
- src/core/metrics.cc
- src/core/metrics.h
- src/core/request_inprocess.cc
- src/servers/main.cc
Also move prometheus HTTP reporting out of libtrtserver and into main
executable.
> Add --allow-gpu-metrics to control when GPU metrics are reported

- src/clients/c++/perf_client.cc
sample output:
```
./perf_client -v -d -i grpc -u localhost:8001 -m resnet_v1_50_graphdef -p20000 -b1 -t4 --percentile 99
Batch size: 1
Measurement window: 20000 msec
Latency limit: 0 msec
Request concurrency: 4
Pass [1] throughput: 195 infer/sec. 99-th percentile latency: 32811 usec
Pass [2] throughput: 237 infer/sec. 99-th percentile latency: 24978 usec
Pass [3] throughput: 237 infer/sec. 99-th percentile latency: 24965 usec
Pass [4] throughput: 235 infer/sec. 99-th percentile latency: 25492 usec
Client: 
Request count: 4712
Throughput: 235 infer/sec
99-th percentile latency: 25492 usec
Avg gRPC time: 0 usec (marshal 0 usec + response wait 0 usec + unmarshal 0 usec)
Server: 
Request count: 5652
Avg request latency: 16355 usec (overhead 20 usec + queue 5209 …
```
> perf_client report percentile latency and use it as stable criteria

- src/core/model_repository_manager.cc
- src/core/model_repository_manager.h
- src/core/server.cc
- src/core/server.h
- src/core/server_status.cc
- src/core/server_status.h
First step of removing TFS. The public functions in ModelRepositoryManager should be compatible with future steps, except for the part that relies on singleton.
>  Encapsulate TFS components in ModelRepositoryManager

- src/servers/grpc_server.cc
- src/servers/grpc_server.h
- src/servers/http_server.cc
- src/servers/http_server.h
- src/servers/main.cc
Adding port options for API endpoints to be able to serve status, health, profile and infer at different (unique) ports. 
E.g.: --http-status-port, --grpc--status-port ... (status, health, profile, infer)
PS: retained naming convention for HTTP requests for consistency.
> Add port options for Status, Health, profile, and Infer APIs

- src/backends/pytorch/libtorch_backend.cc
- src/backends/pytorch/libtorch_backend.h
> Fix output validation for LibTorch backend

- src/backends/tensorflow/autofill.cc
Before this change, server that starts with `--strict-model-config=false` will fail to load a non-batch model that contains full config.pbtxt. Its `max_batch_size` will be overwritten to 1. Can reproduce with one of the QA non-batch saved model
> Always check input/output signature to verify batching support

- src/backends/onnx/onnx_backend.cc
- src/backends/tensorrt/plan_backend.cc
Fix output datatpe mismatch error messages for consistency across all backends.
Verified all backends rely on model output for datatype (either during Init or Runtime)
> Verify all backends get o/p datatype from model output

- docs/examples/model_repository/densenet_onnx/config.pbtxt
The ONNX model downloaded from ONNX model zoo has batch dimension 1 while TRTIS only allows batch dimension to be -1. So use reshape and set max_batch_size to be 0.
> Update model config in example model store

- src/clients/c++/perf_client.cc
Report percentiles in increment order, including user specified percentile.
<details><summary>p90 (duplicate percentile)</summary><p>
csv
```
Concurrency,Inferences/Second,Client Send,Network+Server Send/Recv,Server Queue,Server Compute,Client Recv,p50 latency,p90 latency,p95 latency,p99 latency
1,101,296,1102,48,8369,10,9889,10743,10796,10976
```
output
```
root@d3c067c510bb:/opt/tensorrtserver# qa/clients/perf_client -m resnet50_netdef -p 5000 -v --percentile 90 -d -f p90.csv
Batch size: 1
Latency limit: 0 msec
Stabilizing using p90 latency
Pass [1] throughput: 92 infer/sec. p90 latency: 11091 usec
Pass [2] throughput: 99 infer/sec. p90 latency: 10884 usec
Pass [3] throughput: 117 infer/sec. p90 latency: …
```
> Remove duplicate percentile report. Fix underflow in "network misc" repot.

- Dockerfile
TRTIS failed to run directly in base image (need to install libcurl)
`error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory`.
The issue is not obvious as build / devel images installed libcurl in advance for server / client build
> Add libcurl to base image

- src/backends/caffe2/autofill.cc
- src/backends/onnx/autofill.cc
- src/backends/pytorch/autofill.cc
- src/backends/tensorflow/autofill.cc
- src/backends/tensorrt/autofill.cc
Relax Autofill check to allow for multiple model versions. 
PS: Need to add aggressive checks across versions to make it more robust. Currently uses only the first version of the model.
> Allow autofill for multiple model versions

- src/clients/c++/image_client.cc
With this change image_client can run off from openCV 4 library. The execution was verified on client container with openCV 4 installed.
> opencv4 compatibility fix in image_client

- qa/L0_infer_reshape/infer_reshape_test.py
- qa/common/gen_qa_reshape_models.py
- src/core/server.cc
Based on doc [here](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/docs/http_grpc_api.rst#health), "live" should not return 200 when server is initializing.
Removing the "ensemble reshape error" test as it is a form of tensor shape mismatch, and this will be checked in ensemble config validation, which will be tested in L0_model_config (after another PR for enabling ensemble validation).
> Update api/health/live conditional to be aligned with the doc. Update ensemble reshape test

- Dockerfile
The base image such as `nvcr.io/nvidia/tensorrtserver:19.06-py3` already contains the onnxruntime library and the symlink (`libonnxruntime.so.0.4.0` and `libonnxruntime.so`). These need to be overwritten by the new ones created in the build process.
> Fix libonnxruntime linking in Docker build

- src/clients/c++/perf_client.cc
With these changes the user can get the summary of the run even if they interrupts the execution. If printing/writing of the information is time consuming or the user wants to immediately stop the execution, they can again interrupt the execution, in which case the perf_client will exit without completing the summary dump.
> Ctrl+C prints complete concurrency

- src/clients/c++/request.cc
- src/clients/c++/request.h
- src/clients/c++/request_grpc.cc
- src/clients/c++/request_grpc.h
- src/clients/c++/request_http.cc
- src/clients/c++/request_http.h
- src/clients/python/__init__.py
- src/clients/python/crequest.cc
- src/clients/python/crequest.h
- src/core/constants.h
- src/core/model_repository_manager.cc
- src/core/trtserver.h
This change depends on #468 (implemented based on `grpc_service.proto` in that change)
> Add control context in client library

- src/backends/custom/custom_backend.cc
Should return true and set `content` to `nullptr` if the output is not required, to be consistent with the [description](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/backends/custom/custom.h#L177)
> Fix CustomGetOutputFn_t for non-required output

- src/core/api.proto
- src/core/grpc_service.proto
Allow option to:
- Read (selected) Inputs from Shared Memory
- Write (selected) Outputs to Shared Memory
Support batching using offsets for each element with the same shm_key
Support for registering / unregistering SHM regions
> Support for using system Shared Memory for I/O 

- src/clients/c++/perf_client.cc
If the model is ensemble model, the printed log will be the following:
<details><summary>log with additional "Composing models" printed</summary><p>
```
root@2a495b81e2af:/opt/tensorrtserver# qa/clients/perf_client -m ensemble -p5000 -l5 -d -f res.csv
Batch size: 1
Latency limit: 5 msec
Client: 
Request count: 10193
Throughput: 2038 infer/sec
Avg latency: 481 usec (standard deviation 148 usec)
p50 latency: 468 usec
p90 latency: 523 usec
p95 latency: 544 usec
p99 latency: 626 usec
Avg HTTP time: 432 usec (send/recv 31 usec + response wait 401 usec)
Server: 
Request count: 12210
Avg request latency: 232 usec (overhead 232 usec + queue 0 usec + compute 0 usec)
Composing models: …
```
> Enhance perf_client to report composing model stats if running ensemble model

- src/backends/pytorch/libtorch_backend.cc
PyTorch image for 19.08 uses 1.20 where the load api no longer returns a shared pointer
@deadeyegoodwin should I modify this PR for r19.08 instead of master?
> Fix PyTorch Backend for 19.08

- src/backends/tensorflow/base_backend.cc
- src/backends/tensorflow/base_backend.h
- src/backends/tensorflow/tensorflow_backend_tf.cc
- src/backends/tensorflow/tensorflow_backend_tf.h
- src/core/model_config.proto
- src/core/model_config_utils.cc
- tools/patch/tensorflow/cc/saved_model/loader.cc
The tensorflow model configuration can now specify kind KIND_MODEL, in which case TRTIS relinquishes control of model placements on devices, letting the model instances being placed as specified in graphdef.
> Adding an option to let Graphdef dictate the model placement on devices

- qa/L0_output_validation/test.sh
Rename from `libtorch_validation_store` -> `libtorch_model_store2`
> Fix libtorch model repository name

- src/clients/c++/simple_shm_client.cc
Default to using shared memory only for inputs.
> Fix L0_simple_shared_memory_example

- src/clients/c++/inference_profiler.cc
- src/clients/c++/inference_profiler.h
- src/clients/c++/perf_client.cc
- src/core/ensemble_scheduler.cc
- src/core/server_status.cc
- src/core/server_status.h
Instead of just printing 0 for compute and queue times for ubrella ensemble, server will set them to the total sum of the compute and queue times of the composing models.
> server will populate the compute and queue times for ensemble models

- src/core/backend_context.cc
* fix #ifdef TRTIS_ENABLE_GPU logic in backend_context.cc
Discovered this while working on build automation. Very simple fix for the build.
> Fix TRTIS_ENABLE_GPU=OFF builds

- build/trtis/CMakeLists.txt
- src/backends/tensorrt/plan_backend.cc
(note: this pull request is a clean-up version of #414 )
1. Jetson Xavier with Jetpack 4.2.1
2. CUDA 10.0
3. TensorRT 5.1.6
1. Add CUDA version check in CMake.
2. Disable CUDA graph if CUDA version < 10.1.
1. Please follow the official [instructions](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/build.html#building-the-server-with-cmake) for building server with CMake.
2. CUDA 10.0 and TensorRT 5.1.6 are installed by Jetpack sdkmanager during flashing.
3. Install all other packages listed in [Dockerfile](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/Dockerfile#L159).
4. Native compile on Jetson.
```
mkdir builddir
cd builddir
cmake -DCMAKE_BUILD_TYPE=Release \
-DTRTIS_ENABLE_METRICS=ON \
-DTRTIS_ENABLE_CUSTOM=ON \
-DTRTIS_ENABLE_GPU=ON \ …
```
> [Jetson] Native compile on Jetson Xavier

- src/clients/python/__init__.py
- src/clients/python/simple_callback_client.py
Request ID can only be retrieve via callback function.
> Fix Python aysnc_run_with_cb() documentation and example

- src/clients/go/gen_go_stubs.sh
- src/clients/go/grpc_simple_client.go
Add baseline reference for a Go client as requested in #175 
This sample script assumes that the protobuf stubs will be compiled local to the client, under the `nvidia_inferenceserver` directory. This can be easily tweaked by uncommenting `gen_go_stubs.sh` to generate the stubs in `${GOPATH}/src/nvidia_inferenceserver` to have something more global instead.
Usage:
```bash
git clone https://github.com/NVIDIA/tensorrt-inference-server.git
cd tensorrt-inference-server/docs/examples
./fetch_models.sh
docker run -d -p8000:8000 -p8001:8001 -p8002:8002 \
-it -v $(pwd)/model_repository:/models \
nvcr.io/nvidia/tensorrtserver:19.07-py3 \
trtserver --model-store=/models
cd ../../src/clients/go
./gen_go_stubs.sh
go run grpc_simple_client.go
```
<details>
<summary>Sample Output</summary>
<p>
```bash …
```
> Add simple gRPC Go client

- Dockerfile
- src/backends/onnx/autofill.cc
- src/backends/onnx/loader.h
- src/backends/onnx/onnx_backend.cc
- src/backends/onnx/onnx_backend.h
- src/backends/onnx/onnx_utils.cc
- src/backends/onnx/onnx_utils.h
The commit includes fixes to:
* [deploying model across multiple GPUs](https://github.com/microsoft/onnxruntime/issues/1592)
* [building ONNX Runtime C libraray with TensorRT Execution Provider](https://github.com/microsoft/onnxruntime/issues/1803)
* [ONNX Runtime slowdown due to tensor copies between CPU and GPU](https://github.com/microsoft/onnxruntime/issues/1675)
> Advance ONNX Runtime version to a fixed commit after rel-0.5.0

- src/clients/c++/request.h.in
- src/clients/c++/request_common.cc
- src/clients/c++/request_common.h
- src/clients/c++/simple_shm_client.cc
Solves #562
Returns size in bytes given a shape and datatype.
See simple_shm_client.cc for example.
> Helper function ByteSize that returns size in bytes

- src/core/model_config.proto
Fixes `cc_model_names` typo at https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/protobuf_api/model_config.proto.html#_CPPv4N6nvidia15inferenceserver11ModelConfig22default_model_filenameE
> cc_model_names -> cc_model_filenames typo in docs

- qa/L0_perf/test.sh
- qa/L0_perf_nomodel/perf_analysis.py
- src/clients/c++/examples/simple_perf_client.cc
- src/clients/c++/library/request_http.cc
curl_easy has significant delay in handling responses when a
curl_easy_handle is reused. curl_easy_reset does not fix the
problem. So create a new curl_easy_handle for each sync request.
> Fix sync HTTP client performance

- src/clients/c++/library/request_http.cc
- src/servers/http_server.cc
This change replaces 97edcd5e4659851661d9e2dbd2af7b0ae7928816.  Use
curl_easy_reset with the aync run. Fix the server so that it disables
Nagle's so that long delays are not introduced in the response.
> Proper fix for HTTP client performance

- src/clients/c++/examples/CMakeLists.example
- src/clients/c++/library/CMakeLists.txt
It seems like CURL should be a private dep(?).
Even though that means nothing for a static library, at least
it makes it clearer that the interface used by librequest(_static)
is not tied to CURL in any way and its consumers don't need 
to see CURL headers.
Seems to me that CURL is not used in the public C++ API and is
hidden in code. It should be the same for CMake, since
it's the same for gRPC (although that seems to be linked
statically).
Signed-off-by: Andrei-Florin BENCSIK <andrei.bencsik@gmail.com>
> Make CURL dependency PRIVATE in CMake

- qa/L0_batcher/batcher_test.py
Fix time thresholds for batcher to avoid shared memory failures
> Fix time thresholds for L0_batcher_shm test

- qa/L0_perf_client/test.sh
- src/clients/c++/perf_client/inference_profiler.cc
- src/clients/c++/perf_client/inference_profiler.h
- src/clients/c++/perf_client/perf_client.cc
- src/clients/c++/perf_client/perf_utils.cc
- src/clients/c++/perf_client/perf_utils.h
The usage message will look like:
[Note: pasting here removed some indentation in the message]
> 
> Usage: ../install/bin/perf_client [options]
> ==== SYNOPSIS ====
>  
> 	-m <model name>
> 	-x <model version>
> 	-v
> 
> I. MEASUREMENT PARAMETERS: 
> 	--measurement-interval (-p) <measurement window (in msec)>
> 	--concurrency-range <start:end:step>
> 	--latency-threshold (-l) <latency threshold (in msec)>
> 	--max-threads <thread counts>
> 	--stability-percentage (-s) <deviation threshold for stable measurement (in percentage)>
> 	--max-trials (-r)  <maximum number of measurements for each profiling>
> 	--percentile <percentile>
> 	DEPRECATED OPTIONS
> 	-t <number of concurrent requests>
> 	-c <maximum concurrency>
> 	-d
> 	-a
> 
> II. INPUT DATA OPTIONS: 
> 	-b <batch size>
> …
> cleaning the perclient cli arguments

- src/backends/tensorflow/base_backend.cc
- src/backends/tensorflow/tensorflow_backend_tf.cc
- src/backends/tensorflow/tensorflow_backend_tf.h
Fixes the TRTISTF_TensorSetString function to also use string length to include intermediate null characters.
PS: This does not have any test coverage Should I add the same.
> Fix string serialization to tensor to allow null characters

- Dockerfile.QA
One of the nested dependencies "cffi" has a newer version 1.13 and now `pip install` will pick up this version. It requires "Python.h" file which can be obtained from `python-dev`
> Use python-dev to satisfy Python package dependency

- src/backends/pytorch/libtorch_backend.cc
It is possible that the model output can be non-contiguous. Flattening this may cause unexpected behavior as mentioned [here](https://pytorch.org/docs/stable/torch.html#torch.flatten). Thus we make the tensor contiguous before calling `flatten()`.
> Fix libtorch output flattening for non-contiguous tensors

- src/backends/caffe2/netdef_backend.cc
- src/backends/custom/custom.h
- src/backends/custom/custom_backend.cc
- src/backends/custom/custom_backend.h
- src/backends/onnx/onnx_backend.cc
- src/backends/pytorch/libtorch_backend.cc
- src/backends/tensorflow/base_backend.cc
- src/backends/tensorrt/plan_backend.cc
- src/core/backend_context.cc
- src/core/backend_context.h
- src/core/ensemble_scheduler.cc
- src/core/provider.cc
- src/core/provider.h
- src/core/trtserver.cc
- src/core/trtserver.h
- src/custom/identity/identity.cc
- src/servers/grpc_server.cc
- src/servers/http_server.cc
- src/servers/simple.cc
Major change is let TRTIS internal be aware of 'memory_type_id', this is done by tying it with all occurrences of 'memory_type'.
Fix custom backend implementation to match description (return acutal memory type and type id)
> Support 'memory_type_id' along with 'memory_type'

- qa/L0_simple_perf/test.sh
- src/clients/c++/examples/simple_perf_client.cc
The vector request_duration_ns was dynamically grown and the stale pointers forwarded to the callback functions of the request were causing the segmentation faults.
The problem is not present in the sync case because we already pre-allocate the vector memory.
> Fixing the simple perf client to work on async concurrency 8

- qa/L0_nullchar_string/test.sh
Not going to run CI as it is just documentation change.
> Clarify why ONNX is not in L0_nullchar_string

- qa/L0_trt_plugin/trt_plugin_test.py
- src/backends/custom/custom_backend.cc
- src/backends/onnx/onnx_backend.cc
- src/backends/onnx/onnx_backend.h
- src/backends/pytorch/libtorch_backend.cc
- src/backends/tensorflow/base_backend.cc
- src/core/backend_context.cc
- src/core/backend_context.h
- src/core/ensemble_scheduler.cc
- src/core/provider.cc
- src/core/provider.h
- src/core/trtserver.cc
- src/core/trtserver.h
- src/custom/identity/identity.cc
- src/servers/grpc_server.cc
- src/servers/http_server.cc
- src/servers/memory_alloc.cc
- src/servers/simple.cc
> Fix Response Allocation

- src/core/CMakeLists.txt
- src/core/cuda_utils.cc
- src/core/cuda_utils.h
- src/core/server.cc
It turns out that peer access needs to be enabled so that peer-to-peer copy will behave as expected. If not enabled, the copy will be staged through the host (i.e. device 0 -> host -> device 1, see [programming guide](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#peer-to-peer-memory-copy)).
> Enable peer access for all device pairs at server initialization

- src/backends/caffe2/netdef_backend.cc
- src/backends/caffe2/netdef_backend.h
- src/backends/caffe2/netdef_backend_factory.cc
- src/backends/custom/custom_backend.cc
- src/backends/custom/custom_backend.h
- src/backends/ensemble/ensemble_backend.cc
- src/backends/ensemble/ensemble_backend.h
- src/backends/onnx/onnx_backend.cc
- src/backends/onnx/onnx_backend.h
- src/backends/onnx/onnx_backend_factory.cc
- src/backends/pytorch/libtorch_backend.cc
- src/backends/pytorch/libtorch_backend.h
- src/backends/pytorch/libtorch_backend_factory.cc
- src/backends/tensorflow/base_backend.cc
- src/backends/tensorflow/base_backend.h
- src/backends/tensorflow/graphdef_backend.cc
- src/backends/tensorflow/graphdef_backend.h
- src/backends/tensorflow/graphdef_backend_factory.cc
- src/backends/tensorflow/savedmodel_backend.cc
- src/backends/tensorflow/savedmodel_backend.h
- src/backends/tensorflow/savedmodel_backend_factory.cc
- src/backends/tensorrt/plan_backend.cc
- src/backends/tensorrt/plan_backend.h
- src/backends/tensorrt/plan_backend_factory.cc
- src/core/backend.cc
- src/core/backend.h
- src/core/backend_context.h
This is part of adding warmup functionality, the main purpose is to expose `Run()` in base class so that warmup functionality can utilize it without knowing underlying backends, and to remove redundant code.
> Clean up InferenceBackend

- src/clients/c++/library/request.h.in
- src/clients/c++/library/request_grpc.cc
- src/clients/c++/library/request_http.cc
- src/core/trtserver.cc
- src/core/trtserver.h
Impacted functions: RegisterCudaSharedMemory and TRTSERVER_SharedMemoryBlockGpuNew
They return error when called with TRTIS_ENABLE_GPU=OFF
> Fix client/server builds by keeping functions in header files for non-GPU build

- Dockerfile.centos_client
- build/CMakeLists.txt
- src/clients/c++/examples/CMakeLists.example
Add a Dockerfile which builds the client libraries and examples for a CentOS 7 system.
Also includes a few minor changes to CMake files in order to make them more portable.
> Add CentOS client Dockerfile

- Dockerfile.QA
- qa/L0_backend_release/simple_seq_models/simple_sequence/config.pbtxt
- qa/L0_backend_release/test.sh
- src/core/dynamic_batch_scheduler.cc
- src/core/dynamic_batch_scheduler.h
- src/core/sequence_batch_scheduler.cc
- src/servers/http_server.cc
- src/servers/shared_memory_block_manager.cc
- src/servers/shared_memory_block_manager.h
If the server is exiting or a backend is unloaded, it could be that a
scheduler thread for that backend is holding the last reference to the
backend. In this case the scheduler thread itself will destroy the
backend and thus destroy the DynamicBatchScheduler which owns the thread. So
the thread needs to handle this case where it is destroying itself correctly.
> Fix dynamic and sequence batcher to handle unloaded backend case

- src/servers/grpc_server.cc
- src/servers/http_server.cc
Without this cleanup the provider is leaked which also keeps a backend
reference so that it can't be unloaded.
> Correctly cleanup request provider if early infer error

- src/clients/python/build_wheel.sh
In the python client build_wheel.sh script, make the CUDA shared memory feature condition check if the needed files exist instead of looking for the CUDA_VERSION environment variable.  
The current check breaks builds that have the TRTIS_ENABLE_GPU flag disabled on systems that have CUDA installed.
> Improve CUDA feature check in build_wheel.sh

- Dockerfile.QA
- qa/L0_cmdline_trace/test.sh
- src/core/ensemble_scheduler.cc
- src/core/server_status.cc
- src/core/server_status.h
- src/core/tracing.cc
- src/core/tracing.h
- src/core/trtserver.cc
- src/core/trtserver.h
- src/servers/grpc_server.cc
- src/servers/http_server.cc
- src/servers/http_v2_server.cc
- src/servers/memory_alloc.cc
- src/servers/simple.cc
- src/servers/tracer.cc
- src/servers/tracer.h
For ensemble case, the tracer generates the below trace (formatted). In short, additional fields "id" and "parent_id" will be shown for model execution within ensemble. "id" shows the order that the model is executed in the request. "parent_id" will be set if the model is part of another nested ensemble, and it will be set to the "id" of the nested ensemble.
```JSON
[
{
"timestamps":[
{
"name":"request handler start",
"ns":2198577174107855
},
{
"name":"queue start",
"ns":2198577174110088
},
{
"name":"compute start",
"ns":2198577174191902
},
{
"name":"compute end",
"ns":2198577174274423
},
{
"name":"request handler end",
"ns":2198577174284459
},
{
"name":"compute input end",
"ns":2198577174200233
},
{
"name":"compute output start",
"ns":2198577174272504
}
], …
```
> Modify TRTServer tracing interface to better capture trace for ensemble

- Dockerfile.QA
- qa/L0_perf_custom/test.sh
Have a look at the following linked dashboard for generated [plots](https://gpuwa.nvidia.com/kibana/goto/db22719526e0fd516d678ce3c50ebead). 
Kindly note that this [commit](https://github.com/NVIDIA/tensorrt-inference-server/commit/bc53a89b888aff9da8b387b08b08f209f729f546) renames benchmark_kind from benchmark_perf_custom to perf_custom for better legends.
> Add perf_client tests that compare against existing simple_perf_client jester data

- qa/L0_perf_resnet/test.sh
- src/servers/main.cc
Large inference requests (like resnet50 with BS >= 128) benefit from
having some allocation pool reuse, so set the default appropriately.
> Set GRPC allocation pool default to better handle large inference

- qa/L0_cmdline_trace/test.sh
- qa/common/trace_summary.py
Should discuss more about what we want to show for ensemble traces, I think the trace_summary is focusing more on activities happened within the model, i.e. what is the time span for different stages of the execution. But for ensemble, we are interested more on how the models affect each other. For instance, if a ensemble is defined to execute a single model multiple times in parallel, we are interested in checking whether the executions are serialized (perhaps due to low amount of model instances). The summary log can still tell us that by looking at the queue time, but visualization will be more intuitive. Thus I think we want a tool to plot the timeline for ensemble.
The generated summary for ensemble looks like the following:
```
File: trace_ensemble.log
simple (-1):
id: 0
http recv …
```
> Update trace_summary to show nested results for ensemble

- build/trtis/CMakeLists.txt
- src/core/CMakeLists.txt
- src/core/provider.h
- src/core/provider_utils.h
- src/servers/CMakeLists.txt
- src/servers/main.cc
Fix build errors when HTTP and gRPC are both turned off
Split from #942
> Fix build errors when HTTP and gRPC are both turned off

- qa/L0_http_v2/test.sh
Fixes HTTP V2 failure introduced with: https://github.com/NVIDIA/tensorrt-inference-server/pull/945
> Fixes http v2 test failure

- docs/http_grpc_api.rst
- qa/L0_server_status/server_status_test.py
- src/servers/http_server.cc
Option to use `?format=json` in request url or Accept: `application/json` to get server status as JSON
> Add JSON Format Reporting for Server Status

- src/backends/tensorrt/loader.cc
- src/backends/tensorrt/plan_backend.cc
- src/backends/tensorrt/plan_utils.cc
- src/backends/tensorrt/plan_utils.h
**NOTE** : Merge to master when TRT 7  is released.
When using fixed shape models with explicit batch dimensions there were a bunch of warnings being generated by TRT.
**Before:**
```
Batch size: 1
W1213 00:17:06.015177 29518 logging.cc:46] Explicit batch network detected and batch size specified, use enqueue without batch size instead.
W1213 00:17:06.016012 29518 logging.cc:46] Explicit batch network detected and batch size specified, use enqueue without batch size instead.
W1213 00:17:06.016669 29518 logging.cc:46] Explicit batch network detected and batch size specified, use enqueue without batch size instead.
W1213 00:17:06.017329 …
```
> Use correct version of TRT enqueue API

- src/backends/tensorflow/tf_utils.cc
Fixing the bug in TensorFlow backend `ShapeToString` where the index in the for loop is incremented twice. This bug causes inaccurate error messages when the data shape is not matched for model.
> Fix duplicate index incrementation for TF ShapeToString

- qa/common/gen_qa_custom_ops
- qa/common/gen_qa_model_repository
The latest nvidia-docker no longer uses `nvidia-docker`. The standard way is to call `docker run --gpus=#` where `#` is the number of GPUs. This change updates the model generation scripts to use the correct nvidia docker command.
> Update to new Nvidia docker command

- qa/L0_trt_shape_tensors/test.sh
- qa/L0_trt_shape_tensors/trt_shape_tensor_test.py
- qa/common/infer_util.py
The payloads with identical values should be batched together. These tests are meant for the same.
> Adding dynamic batcher tests for shape tensor I/O

- qa/L0_sequence_batcher/sequence_batcher_test.py
- qa/L0_sequence_batcher/test.sh
- qa/common/sequence_util.py
- qa/custom_models/custom_sequence_int32/config.pbtxt
- src/backends/custom/custom_backend.cc
- src/backends/custom/custom_backend.h
- src/clients/python/shared_memory/__init__.py
- src/core/provider_utils.cc
- src/custom/sequence/sequence.cc
Required to support ragged batches in custom backends. Each payload's
input tensors can have a different shape.
> Fix custom backend to set input tensor shape correctly for each payload.

- src/backends/caffe2/netdef_backend.cc
- src/backends/caffe2/netdef_backend.h
- src/backends/custom/custom.h
- src/backends/custom/custom_backend.cc
- src/backends/onnx/onnx_backend.cc
- src/backends/onnx/onnx_backend.h
- src/backends/pytorch/libtorch_backend.cc
- src/backends/tensorflow/base_backend.cc
- src/core/backend.cc
- src/core/cuda_utils.cc
- src/core/pinned_memory_manager.cc
- src/core/pinned_memory_manager.h
- src/core/provider.cc
- src/core/provider.h
- src/core/trtserver.h
- src/custom/identity/identity.cc
- src/servers/common.cc
- src/servers/common.h
- src/servers/grpc_server.cc
- src/servers/http_server.cc
- src/servers/http_v2_server.cc
- src/servers/memory_alloc.cc
- src/servers/simple.cc
Currently we are being conservative on the output from the frameworks (if CPU buffer, then always assume to be non-pinned), and always prefer pinned CPU buffer when TRTIS need to allocate CPU buffer.
> Add memory type CPU_PINNED

- src/backends/onnx/autofill.cc
- src/backends/onnx/onnx_backend.cc
Not needed and caused build error when building on a system without
TensorRT installed.
> Remove unnecessary NvInfer.h

- qa/common/gen_qa_custom_ops
- qa/common/gen_qa_model_repository
Setting gpus=1 was selecting the first gpu irrespective of CUDA_DEVICE id. Verified the model generation on a system with multiple gpus.
> Fixing the model generation script to pick correct gpu id

- src/clients/c++/perf_client/concurrency_manager.cc
- src/clients/c++/perf_client/load_manager.cc
- src/clients/c++/perf_client/load_manager.h
- src/clients/c++/perf_client/request_rate_manager.cc
PerfClient was not catching the GetAsyncRunResult errors before which made client unaware of failed inferences. 
Before Changes
==========================
../clients/perf_client -m onnx_float32_float32_float32 -p 50000 -b 8 --input-data zero --concurrency-range 2  --shared-memory=cuda --output-shared-memory-size=8388608 --shape INPUT0:151658240 --shape INPUT1:151658240 --async
Batch size: 8
Measurement window: 50000 msec
Using asynchronous calls for inference
Request concurrency: 2
Failed to update context stat: [ 0] INTERNAL - Timer not set correctly.
Failed to update context stat: [ 0] INTERNAL - Timer not set correctly.
Failed to update context stat: [ 0] INTERNAL - Timer not set correctly.
Failed to update context stat: [ …
> Handling for GetAsyncRunResults failures in the callback

- qa/L0_perf_client/test.sh
- src/clients/c++/perf_client/concurrency_manager.cc
- src/clients/c++/perf_client/concurrency_manager.h
The seq_ids would redistribute when the concurrency is changed. It might lead to a race condition and breaking the order.
> Fixing the race condition while changing concurrency level

- src/core/autofill.cc
/opt/tensorrtserver/bin/trtserver --model-repository=/opt/tensorrtserver/qa/L0_perf_client/ensemble_model --strict-model-config=false	
2020-02-11 23:12:14.334942: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2	
I0211 23:12:14.366611 332 metrics.cc:164] found 2 GPUs supporting NVML metrics	
I0211 23:12:14.372117 332 metrics.cc:173]   GPU 0: GeForce GT 710	
I0211 23:12:14.378348 332 metrics.cc:173]   GPU 1: TITAN RTX	
I0211 23:12:14.378551 332 server.cc:115] Initializing TensorRT Inference Server	
**W0211 23:12:14.542686 332 autofill.cc:234] Autofiller failed to retrieve model. Error Details: OK: 	
W0211 23:12:14.542708 332 autofill.cc:238] Proceeding with simple config for now**	
2020-02-11 23:12:14.543681: I …
> Removing false warnings from autofiller

- qa/L0_perf_client/test.sh
- src/clients/c++/perf_client/load_manager.cc
1. ../clients/perf_client -m inception_graphdef -b 1 --shared-memory=system
[ 0] INVALID_ARG - unable to get shared memory descriptor for shared-memory key '/InceptionV3/Predictions/Softmax'
2. ../clients/perf_client -m inception_graphdef -b 1 --shared-memory=cuda        
[ 0] INTERNAL - sharedmemorycontrol request did not return status
1. ../clients/perf_client -m inception_graphdef -b 1 --shared-memory=system
Batch size: 1
Client: 
Request count: 412
Throughput: 82.4 infer/sec
Avg latency: 12121 usec (standard deviation 1161 usec)
p50 latency: 12476 usec
p90 latency: 13208 usec
p95 latency: 13465 usec
p99 latency: 14448 usec
Avg HTTP …
> Fixing perf_client to generate valid shared memory region names

- src/core/backend.cc
- src/core/ensemble_scheduler.cc
- src/core/trtserver.cc
- src/core/trtserver.h
- src/servers/common.cc
- src/servers/memory_alloc.cc
- src/servers/simple.cc
This PR is branch-off from `gluo-timeout` and targeted to `gluo-timeout` to show the change for adding TRTServer options on top of the changes in `gluo-timeout`
> Add TRTServer options for setting priority and request timeout

- src/core/backend_context.cc
#1148 can be reproduced using an older compiler gcc 5.4.0, which will raise error in such case. Changing to "creating object with direct-list-initialization and then copy assign" allows the build to continue
> Avoid copy-list-initialization as it is ill-formed if explicit constructor is chosen

- src/core/provider.cc
The data_type field should be populated only when the --api-version is set 2. The following tests were conducted on the 20.02 clients.
> Traceback (most recent call last):
>   File "infer_variable_test.py", line 151, in test_raw_ooo
>     self._full_exact(np_dtype_string, np_dtype_string, np_dtype_string, (16,), (16,), (16,))
>   File "infer_variable_test.py", line 91, in _full_exact
>     output0_raw=output0_raw, output1_raw=output1_raw, swap=swap)
>   File "infer_variable_test.py", line 65, in _infer_exact_helper
>     use_cuda_shared_memory=TEST_CUDA_SHARED_MEMORY)
>   File "../common/infer_util.py", line 215, in infer_exact
>     output_req, batch_size)
>   File "/usr/local/lib/python3.6/dist-packages/tensorrtserver/api/__init__.py", line 1582, in run
>     self._last_request_id = …
> Fixing backwards compatibility in ResponseHeader

- qa/L0_sequence_batcher/test.sh
- qa/common/gen_qa_model_repository
- qa/common/gen_xavier_trt_models
This must be done since TRT models must be generated again on Jetson and stored in the **\<version\>_jetson** directory.
> Add gen script for TensorRT models on JetPack 4.4

- qa/L0_grpc_v2/test.sh
- src/clients/python/experimental_api_v2/examples/CMakeLists.txt
- src/clients/python/experimental_api_v2/examples/simple_grpc_v2_async_infer_client.py
- src/clients/python/experimental_api_v2/examples/simple_grpc_v2_class_client.py
- src/clients/python/experimental_api_v2/examples/simple_grpc_v2_health_metadata.py
- src/clients/python/experimental_api_v2/examples/simple_grpc_v2_infer_client.py
- src/clients/python/experimental_api_v2/examples/simple_grpc_v2_shm_client.py
- src/clients/python/experimental_api_v2/examples/simple_grpc_v2_string_infer_client.py
- src/clients/python/experimental_api_v2/library/CMakeLists.txt
- src/clients/python/experimental_api_v2/library/cuda_shared_memory/__init__.py
- src/clients/python/experimental_api_v2/library/cuda_shared_memory/cuda_shared_memory.cc
- src/clients/python/experimental_api_v2/library/cuda_shared_memory/cuda_shared_memory.h
- src/clients/python/experimental_api_v2/library/grpc_build_wheel.sh
- src/clients/python/experimental_api_v2/library/grpc_setup.py
- src/clients/python/experimental_api_v2/library/grpcclient.py
- src/clients/python/experimental_api_v2/library/shared_memory/__init__.py
- src/clients/python/experimental_api_v2/library/shared_memory/shared_memory.cc
- src/clients/python/experimental_api_v2/library/shared_memory/shared_memory.h
- src/clients/python/experimental_api_v2/library/shared_memory/shared_memory_handle.h
- src/core/grpc_service_v2.proto
- src/core/server.cc
- src/servers/grpc_server.cc
- src/servers/grpc_server_v2.cc
- src/servers/grpc_server_v2.h
- src/servers/http_server.cc
- src/servers/http_v2_server.cc
- src/servers/shared_memory_manager.cc
- src/servers/shared_memory_manager.h
The following enhancements are included in this PR:
1. New handler for handling multiple RPCs in grpc_server_v2
2. System and CUDA shared memory support in server
3. Client side support for system shared memory
4. Simple example using system shared memory
I plan to make the following changes as future set of PRs:
1. Client side support for cuda shared memory
2. Simple example using cuda shared memory
3. L0_shared_memory_v2 and L0_cuda_shared_memory_v2 using the new clients.
4. Package the shared_memory and cuda_shared_memory modules in separate packages outside tritongrpcclient and tritonhttpclient.
> System Shared Memory support for GRPC V2

- build/CMakeLists.txt
- src/core/CMakeLists.txt
- src/core/cuda_memory_manager.cc
- src/core/cuda_memory_manager.h
- src/core/cuda_utils.cc
- src/core/cuda_utils.h
- src/core/memory.cc
- src/core/memory.h
- src/core/pinned_memory_manager.h
- src/core/server.cc
- src/core/server.h
- src/core/trtserver.cc
- src/core/trtserver.h
- src/servers/CMakeLists.txt
- src/servers/main.cc
@deadeyegoodwin Unfortunately the management library that I am using doesn't support growing the buffer until threshold, we can only preallocate enough CUDA memory on initialization. The other option is the [caching allocator](https://github.com/NVlabs/cub/blob/1.8.0/cub/util_allocator.cuh#L59) where it will allocate new memory if there is no appropriate cached bin, but we can't control the behavior when max_cached_size is reach (i.e. it `cudaFree()` the allocation if max_cached_size is reach). I will keep looking into other alternatives and replace the library if I find one that fits.
One concern about the growing approach is that we can not completely avoid `cudaMalloc` as it is needed for growing the pool, so some requests will be affected if they happen to trigger the growth.
> Add CUDA memory manger to avoid raw cudaMalloc / cudaFree

- src/servers/CMakeLists.txt
Should build METRICS support even when HTTP if off just as before
> Fix to build METRICS support when both HTTP is disabled

- src/servers/http_server.cc
- src/servers/http_server_v2.cc
Pointing out where the lifecycle of the HTTP infer request object is manged, which is not obvious.
> Improve inline comment

- src/servers/CMakeLists.txt
- src/servers/http_server_v2.cc
- src/servers/http_server_v2.h
- src/servers/main.cc
api_version decides which metrics server version to launch. 
PS: The duplication of the HTTP metrics server is intentional and will be remove once the old HTTP server is removed.
> [HTTP V2] Add metrics support

- src/core/trtserver.cc
- src/core/trtserver2.h
In the case of having pre-allocate buffer pool, we want to release the buffer back to the pool once it is done.
> Add API to release output buffer explicitly

- docs/install.rst
- docs/quickstart.rst
I believe the NGC login requirement for pulling Triton was removed quite some time ago.  This step is definitely not needed now.
Signed-off-by: Niek Sanders <niek.sanders@gmail.com>
> NGC Container Registry login not required.

- qa/L0_lifecycle/test.sh
- src/servers/http_server.cc
Error message: "The request header should contain 'NV-InferRequest'"
Error Code: 400
> Fix crash when NV-InferRequest not in InferRequestHeader

- src/clients/python/experimental_api_v2/examples/simple_http_v2_async_infer_client.py
- src/clients/python/experimental_api_v2/examples/simple_http_v2_infer_client.py
- src/clients/python/experimental_api_v2/library/httpclient.py
- src/core/server.cc
The examples explicitly disables the use of binary data because of some issues on the server side (DLIS-1204). Once the issue is fixed these "binary_data=False" settings can be removed.
> [HTTP V2] Bianry data extension support from client side

- Dockerfile
test-generator is newly dependency added when ONNX Runtime uses a newer version of OpenVINO (2019 R3.1) https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/linux/docker/scripts/install_openvino.sh#L33
> Update comment on ONNX Runtime OpenVINO

- src/clients/python/experimental_api_v2/library/grpcclient.py
- src/clients/python/experimental_api_v2/library/httpclient.py
This will be useful while dealing with dynamic shaped inputs. Users can use same InferInput object to send out requests with different shape and data.
> set_shape API for InferInput class

- src/core/infer_request.cc
- src/core/infer_request.h
More an ad-hoc solution for now, need to consider the necessity of BatchByteSize() and MutableOriginalInput() which is only used for manipulating input data.
> Relax normalization check for reusing inference request efficiently

- src/backends/custom/custom_backend.cc
- src/core/infer_request.cc
- src/core/infer_request.h
- src/core/sequence_batch_scheduler.cc
- src/core/sequence_batch_scheduler.h
Manually tested using `simple_grpc_v2_sequence_sync_infer_client.py` and `simple_grpc_v2_sequence_stream_infer_client.py`. Also use sequence_sync_client with different length sequences to test null request.
> Fix sequence batcher. Fix null request

- src/clients/python/experimental_api_v2/library/httpclient.py
These are the follow up changes with PR #1307. I missed fixing it for async_infer call.
> Fixing the binary data in async inference

- src/backends/custom/custom_backend.cc
- src/backends/tensorflow/base_backend.cc
- src/backends/tensorrt/plan_backend.cc
- src/backends/tensorrt/plan_backend.h
- src/core/backend.cc
- src/core/backend.h
- src/core/backend_context.cc
- src/core/backend_context.h
- src/core/dynamic_batch_scheduler.cc
- src/core/dynamic_batch_scheduler.h
- src/core/scheduler.h
- src/core/scheduler_utils.cc
- src/core/scheduler_utils.h
- src/core/sequence_batch_scheduler.cc
- src/core/sequence_batch_scheduler.h
Require input shape tensors to be in contiguous CPU memory. This
removes the need for peek functionality and simplifies request
handling. If we need more functionality in the future we can promote
shape tensors to CPU memory early in request handling instead of where
we were doing it.
> Simplify shape tensor handling

- src/core/infer_request.cc
@tanmayv25 I think we need modification like this on server side. The shape tensor value will not contain batch size.
In V2, for the config below, to send a request with batch size 4, the shapes of inputs will be:
`DUMMY_INPUT0 : [4, x, y]`; `INPUT0 : [2] (i.e. value: [32, 32])`. The output will be:
`DUMMY_OUTPUT0 : [4, 32, 32]`; `OUTPUT0 : [4, 2] (i.e. value: [[32, 32], [32, 32], [32, 32], [32, 32]])`. Then it is aligned with the V1 behavior.
```
...
max_batch_size: 8
input [
{
name: "DUMMY_INPUT0"
data_type: TYPE_FP32
dims: [ -1,-1 ]
},
{
name: "INPUT0"
data_type: TYPE_INT32
dims: [ 2 ]
is_shape_tensor: true
}
]
output [
{
name: "DUMMY_OUTPUT0"
data_type: TYPE_FP32
dims: [ -1,-1 ]
},
{
name: "OUTPUT0"
data_type: TYPE_INT32
dims: [ 2 ]
is_shape_tensor: true
}
]
```
> Skip shape manipulation for shape tensor

- src/servers/grpc_server_v2.cc
rapid JSON is being strict on the value type.. Later on we should make sure the value we set in rapid JSON is of desired type.
> Fix stats in GRPC server

- docs/client.rst
- qa/common/check_copyright.py
- src/clients/c++/experimental_api_v2/library/CMakeLists.txt
- src/clients/c++/experimental_api_v2/library/cencode.c
- src/clients/c++/experimental_api_v2/library/cencode.h
- src/clients/c++/experimental_api_v2/library/common.cc
- src/clients/c++/experimental_api_v2/library/common.h
- src/clients/c++/experimental_api_v2/library/http_client.cc
* Fixing Windows10 build for V2 client library
* Include algortihms.h unconditionally
* Removing unnecessary linker flags
* Format fixes
> Fixing Windows10 build for V2 client library (#1373)

- qa/L0_trt_shape_tensors/test.sh
- qa/L0_trt_shape_tensors/trt_shape_tensor_test.py
- qa/common/infer_util.py
- qa/common/sequence_util.py
Manually tested regular, system shared memory, and cuda shared memory (w/o HTTP).
Note that the `check_status` is changed as infer stats is collected differently in V2:
- batch infer is reported based on total batch size of the execution instead of batch size of the request
- ~~infer count is incremented by 1 for each request, instead of by the batch size of the request.~~
@CoderHam Note that I touched some sequence utilities, please check if those changes make sense to you.
> Fix L0_trt_shape_tensors

- src/clients/python/experimental_api_v2/library/utils.py
- src/servers/http_server_v2.cc
Needed to allow for client library to pass empty string tensors to the server. Follow up changes for #1396
> Relax check on tensor size to allow for empty string tensors

- src/servers/http_server_v2.cc
We pause the connection in InferRequestClass constructor, which is resumed in the callback. If TRITONSERVER_ServerInferAsync itself failed then we must explicitly resume the connection so that error message gets delivered. 
root@81251697a639:/opt/tritonserver/qa/L0_http_v2# /tmp/host/install/bin/perf_client_v2 -m simple -b 10
Batch size: 10
Failed to maintain requested inference load. Worker thread(s) failed to generate concurrent requests.
Thread [0] had error: inference request batch-size must be <= 8 for 'simple'
root@81251697a639:/opt/tritonserver/qa/L0_http_v2# /tmp/host/install/bin/perf_client_v2 -m simple -b 10
*** Measurement …
> Fix for error reporting in HTTP server

- src/clients/c++/experimental_api_v2/examples/CMakeLists.txt
- src/clients/c++/experimental_api_v2/library/cencode.c
- src/clients/c++/experimental_api_v2/library/http_client.cc
- src/clients/python/experimental_api_v2/library/CMakeLists.txt
- src/clients/python/experimental_api_v2/library/cuda_shared_memory/cuda_shared_memory.cc
The encoded base64 string was not getting null terminated. Fixed the termination to let the libraries detect the end.
I tested with the perf_client and it worked fine,
@CoderHam Can you try this fix with L0_* cuda shared memory tests?
> Fix base64 encoding to null terminate the string

- src/servers/http_server_v2.cc
The error messages can be complex sometimes. Relying on the rapidjson to do correct encoding, 
root@27ab6cfd09e0:/opt/tritonserver/qa/clients# ../clients/perf_client_v2 -v -i http -m graphdef_sequence_float32 --shape INPUT:2 --input-data=/opt/tritonserver/qa/L0_perf_client/json_input_data_files/float_data_with_shape.json --input-data=/opt/tritonserver/qa/L0_perf_client/json_input_data_files/float_data_with_shape.json -p2000 --shared-memory=none
Successfully read data for 6 stream/streams.
Batch size: 1
Measurement window: 2000 msec
Using asynchronous calls for inference
Pass [1] throughput: 0.5 infer/sec. Avg latency: 9353 usec (std 0 usec)
**Failed to retrieve results from inference request.
Thread [0] …
> Allow HTTP server to report complex error messages

- src/clients/c++/experimental_api_v2/perf_client/inference_profiler.cc
Relaxes the validation to let model version be 0. Will fix some of the tests in our CI,
> Allowing model version to be zero for perf_client_v2

- qa/L0_lifecycle/lifecycle_test.py
- src/core/model_repository_manager.cc
**Old Error Message:**
Missing/Incorrect model_name/model_version: `"Request for unknown model 'graphdef_float32_float32_float32'"`
**New Error Message:**
Missing/Incorrect model_name: `"Request for unknown model: 'graphdef_float32_float32_float32' is not found"`
Model name correct but version=-1 and no version is available anymore: `"Request for unknown model: 'graphdef_float32_float32_float32' has no available versions"`
Missing/Incorrect model_version: `"Request for unknown model: 'graphdef_float32_float32_float32' version 1 is not found"`
> Fix model repository error message for incorrect version

- src/clients/c++/experimental_api_v2/examples/v2_image_client.cc
- src/clients/c++/experimental_api_v2/library/common.h
- src/clients/c++/experimental_api_v2/library/grpc_client.cc
- src/clients/c++/experimental_api_v2/library/http_client.cc
The response from successive synchronous inference requests was getting over-written,
> Fixing the result overwrite bug in C++ client library

- src/clients/python/examples/v2_image_client.py
L0_async test use the preprocess function to prepare image data for the model. Hence, we can not use FLAGS inside this function but must pass the protocol explicitly. Once in, L0_async will again start passing.
> Update image client for L0_async

- Dockerfile.centos_client
There should be a trailing backslash.
> Fix syntax error in Dockerfile.centos_client

- src/backends/tensorrt/plan_backend.cc
- src/backends/tensorrt/plan_backend.h
TRT backend supports the pipelined execution of multiple requests. This PR will fix the issue arising when Backend::Run() returns but the ProcessResponse is not done finalizing the request.
> Extend the lifetime of InferenceRequest objects for TRT backend

- src/servers/grpc_server.cc
- src/servers/grpc_server.h
Will use a single thread and completion queue for handling all non-inference requests.
The changes have been tested locally with simple_grpc_health_metadata example.
> gRPC to handle all non-inference RPC with a common handler

- src/servers/grpc_server.cc
> {
>     "model_stats": [
>         {
>             "name": "simple",
>             "version": "1",
>             "last_inference": 1590094368740,
>             "inference_count": 4,
>             "execution_count": 4,
>             "inference_stats": {
>                 "success": {
>                     "count": 4,
>                     "ns": 41781417847706535
>                 },
>                 "fail": {
>                     "count": 0,
>                     "ns": 0
>                 },
>                 "queue": {
>                     "count": 4,
>                     "ns": 539764
>                 },
>                 "compute_input": {
>                     "count": 4,
>                     "ns": 579680
>                 },
>                 "compute_infer": {
> …
> Include inference and execution count in grpc stat response

- src/core/backend.h
The server segfaults when the status is not ok
../clients/perf_client -m plan_float32_float32_float32-4-32 --shape INPUT0:16 --shape INPUT1:16 -b 10*** Measurement Settings ***  Batch size: 10  Measurement window: 5000 msec  Using synchronous calls for inference
Failed to maintain requested inference load. Worker thread(s) failed to generate concurrent requests.
Thread [0] had error: inference request batch-size must be <= 8 for 'plan_float32_float32_float32-4-32'
> Fixing FAIL_ALL_AND_RETURN_IF_ERROR macro

- src/clients/c++/library/common.h
- src/clients/c++/library/http_client.cc
- src/clients/c++/perf_client/perf_client.cc
Add extra verbose mode to perf_client to show client verbose output.
Enable with "-v -v"
> Improve verbose output and infer response error handling in http client

- src/clients/c++/library/common.h
- src/clients/c++/library/http_client.cc
- src/clients/c++/library/http_client.h
Otherwise the connection is not shared which causes low performance
and can also exhaust all sockets under heavy load.
> Use the same libcurl easy_handle for all synchronous requests

- qa/L0_server_status/server_status_test.py
- qa/L0_server_status/test.sh
- src/clients/python/examples/grpc_explicit_byte_content_client.py
Note that now server returns only the infer_stats for models that are ready. This PR tunes the test to the new behavior.
> Fixing L0_server_status

- qa/L0_trt_shape_tensors/trt_shape_tensor_test.py
- qa/common/infer_util.py
- qa/common/sequence_util.py
- src/backends/tensorrt/plan_backend.cc
- src/backends/tensorrt/plan_backend.h
- src/core/backend_context.cc
This PR in itself doesn't fix the L0_trt_shape_tensor tests. There is only one failing test left:test_sequence_different_shape_values. 
We can not use the dummy value as content for shape tensors in null requests for sequence scheduler . The shape values must be in range of optimization profile. I am working out on a solution.
> Fix TRT backend to handle dynamically batched requests

- Dockerfile.centos_client
- Dockerfile.custombackend
- src/clients/c++/examples/CMakeLists.txt
- src/clients/c++/examples/ensemble_image_client.cc
- src/clients/c++/examples/image_client.cc
- src/clients/c++/examples/json_utils.cc
- src/clients/c++/examples/json_utils.h
- src/clients/c++/examples/simple_http_cudashm_client.cc
- src/clients/c++/examples/simple_http_health_metadata.cc
- src/clients/c++/examples/simple_http_infer_client.cc
- src/clients/c++/examples/simple_http_model_control.cc
- src/clients/c++/examples/simple_http_shm_client.cc
- src/clients/c++/library/CMakeLists.txt
- src/clients/c++/library/common.cc
- src/clients/c++/library/common.h
- src/clients/c++/library/grpc_client.cc
- src/clients/c++/library/grpc_client.h
- src/clients/c++/library/http_client.cc
- src/clients/c++/library/http_client.h
- src/clients/c++/perf_client/CMakeLists.txt
- src/clients/c++/perf_client/perf_utils.h
- src/clients/c++/perf_client/triton_client_wrapper.cc
- src/core/CMakeLists.txt
- src/core/json.h
- src/core/tritonserver.cc
- src/servers/CMakeLists.txt
- src/servers/grpc_server.cc
- src/servers/http_server.cc
- src/servers/shared_memory_manager.h
The C++ API is changes to return JSON as a string, not as a rapidjson object model.  The examples themselves continue to use radpijson to parse that json when necessary (but any json library could be used).
> Update C++ client libraries to use TritonJson

- src/clients/python/examples/simple_http_sequence_sync_infer_client.py
The issue was fixed earlier and the comment is no longer applicable.
> Fix the unneccessary comment from a client example

- src/backends/tensorrt/plan_backend.cc
- src/backends/tensorrt/plan_backend.h
timestamps should be recorded when event is completed instead of when event is recorded. Note that this is still not the exact timestamp as the event may be completed before the synchronize call (bottleneck on launching CUDA jobs).
Use trace summary as example:
Before:
```
File: trtis_trace.log.resnet_1
Summary for model (1): trace count = 42006
Infer request (avg): 9144us
Handler (avg): 9154us
Overhead (avg): 131us
Queue (avg): 121us
Compute (avg): 8901us
Input (avg): 397us
Infer (avg): 357us
Output (avg): 8146us
```
After:
```
File: triton_trace.log.resnet_1
Summary for model (1): trace count = 42012
Infer request (avg): 9146us
Handler (avg): 9155us
Overhead (avg): 131us
Queue (avg): 120us
Compute (avg): 8904us
Input (avg): 3556us
Infer (avg): 5324us
Output (avg): 23us
```
> Fix timestamp locations in Plan backend

- qa/L0_config_json/ensemble_config.pbtxt
- qa/L0_config_json/test.sh
- src/backends/backend/examples/identity.cc
- src/backends/backend/triton_model.cc
- src/clients/c++/perf_client/model_parser.cc
- src/core/json.h
- src/core/model_config_utils.cc
- src/core/model_config_utils.h
- src/core/tritonserver.cc
Protobuf json utilities represent 64-bit integers as strings in the generated json. There is no option to disable this unwanted behavior. So fix up the json generated for the config so integers are represented as json numbers.
> Fix json representation of model configuration

- Dockerfile.QA
- qa/L0_https/nginx.conf
- qa/L0_https/test.sh
- src/clients/python/examples/simple_http_infer_client.py
- src/clients/python/library/httpclient.py
ngrep logs showing the transaction at port 443 (default https port).
```
####
T 127.0.0.1:55364 -> 127.0.0.1:443 [AP] #4
.............{l.].hv.Hp#...y..J@.#e.U..~X.{ ....:.#"...u.O.....SN......y..;..........,.0.+./...................$.(.........k.j.9.8.....#.
'.........g.@.3.2.].a.\.`.s.w.r.v.W.S.V.R.............E.D.............=.<.5./.Q.P.......A...............localhost........................
.#.............0.................................................+............-.....3.&.$... ..ww...x.4.....z...'...m..2....p...r........
..........................................................................................................                               
##
T 127.0.0.1:443 -> 127.0.0.1:55364 [AP] #6
....A...=.....l:.8....Y....Tk....P$.._2..x...0.................#..........=...9.. …
```
> Enabling HTTPS in python HTTP client library

- qa/L0_custom_backend/param_test.py
- qa/L0_custom_image_preprocess/preprocess_test.py
- qa/L0_custom_ops/cuda_op_test.py
- qa/L0_custom_ops/mod_op_test.py
- qa/L0_custom_ops/onnx_op_test.py
- qa/L0_custom_ops/zero_out_test.py
- qa/L0_custom_param/param_test.py
- qa/L0_nullchar_string/nullchar_string_client.py
- qa/L0_sequence_stress/sequence_stress.py
- src/clients/python/library/httpclient.py
Optional parameters must be provided along with the keyword. 
```
root@48c7caea4b4a:/opt/tritonserver/qa/L0_custom_ops# python zero_out_test.py -m graphdef_zeroout
Traceback (most recent call last):
File "zero_out_test.py", line 72, in <module>
results = client.infer(model_name, inputs)
File "/usr/local/lib/python3.6/dist-packages/tritonhttpclient/__init__.py", line 1076, in infer
query_params=query_params)
File "/usr/local/lib/python3.6/dist-packages/tritonhttpclient/__init__.py", line 277, in _post
body=request_body)
File "/usr/local/lib/python3.6/dist-packages/geventhttpclient/client.py", line 272, in post
return self.request(METHOD_POST, request_uri, body=body, headers=headers)
File "/usr/local/lib/python3.6/dist-packages/geventhttpclient/client.py", line 226, in request
sock = …
```
> Fix QA tests to correctly specify client verbosity

- src/servers/common.h
- src/servers/http_server.cc
Message format prior to change: `{"error":"attempt to access JSON non-unsigned-integer as unsigned-integer"}`
Message format prior to change: `{"error":"Unable to parse 'shape': attempt to access JSON non-unsigned-integer as unsigned-integer"}`
> Improve HTTP Server JSON error messages

- src/backends/backend/examples/models/repeat_int32/config.pbtxt
- src/clients/python/examples/CMakeLists.txt
- src/clients/python/examples/simple_grpc_custom_repeat.py
- src/core/backend.cc
- src/core/backend.h
- src/core/grpc_service.proto
- src/core/infer_response.cc
- src/core/infer_response.h
- src/core/tritonserver.cc
- src/core/tritonserver.h
- src/servers/grpc_server.cc
~There is some bug with state machine which manifests when issuing multiple requests and large number of responses. I am working on fixing it.~
UPDATE: Fixed the state machine to conform with the contract of the GRPC. 
Important aspects of these contracts are:
1.  There should be at max a single outstanding write on both side of the stream.
2. The multiple writes of the decoupled response must be separated with notification on completion queue.
I have used the Alarm workaround to place the task on the completion queue as described [here](https://github.com/G-Research/grpc_async_examples/blob/1fe69d1d025916f15fa1dc4a48704b57b49e3cd9/async_streaming_server_alarm.cc#L138). The server seems to be pretty stable with these changes. I have tested with multiple simultaneous inflight requests and …
> Align grpc server with decoupled API

- src/clients/c++/library/http_client.cc
free instead of delete when using malloc
Fixes issue described in #1636
> Fix memory leak in Cuda Shared Memory registration using HTTP Client library 

- Dockerfile
- Dockerfile.QA
- build/server/CMakeLists.txt
- docs/build.rst
- docs/custom_operation.rst
- qa/L0_custom_ops/test.sh
- qa/L0_custom_ops/vision_op_test.py
- qa/common/gen_qa_custom_ops_models.py
- src/backends/pytorch/CMakeLists.txt
- src/backends/pytorch/libtorch_backend.h
- src/backends/pytorch/libtorch_backend_factory.cc
- src/servers/CMakeLists.txt
Partial resolution to #1415. Although Torchvision ops will be supported with the changes from this PR, not all models will work with the Triton.
We may need to expand the libtorch backend to support inputs as List of Tensors apart from regular Tensors. Outputs in some cases can be in different form than Tenors. For example fasterrcnn expects Inputs as [List of Tensors](https://github.com/pytorch/vision/blob/master/torchvision/models/detection/faster_rcnn.py#L28-L29) and Outputs as [Dict of Tensors](https://github.com/pytorch/vision/blob/master/torchvision/models/detection/faster_rcnn.py#L39-L40)
Included test in L0_custom_ops
> Add support for Torchvision ops

- Dockerfile.QA
- qa/L0_client_timeout/client_timeout_test.py
- qa/L0_client_timeout/models/custom_identity_int32/config.pbtxt
- qa/L0_client_timeout/models/simple_sequence/config.pbtxt
- qa/L0_client_timeout/test.sh
- src/clients/c++/examples/image_client.cc
- src/clients/c++/examples/simple_grpc_async_infer_client.cc
- src/clients/c++/examples/simple_grpc_custom_repeat.cc
- src/clients/c++/examples/simple_grpc_infer_client.cc
- src/clients/c++/examples/simple_grpc_sequence_stream_infer_client.cc
- src/clients/c++/examples/simple_http_async_infer_client.cc
- src/clients/c++/examples/simple_http_infer_client.cc
- src/clients/c++/library/common.h
- src/clients/c++/library/grpc_client.cc
- src/clients/c++/library/grpc_client.h
- src/clients/c++/library/http_client.cc
- src/clients/c++/perf_client/triton_client_wrapper.cc
- src/clients/python/examples/simple_grpc_async_infer_client.py
- src/clients/python/examples/simple_grpc_infer_client.py
- src/clients/python/examples/simple_grpc_sequence_stream_infer_client.py
- src/clients/python/library/grpcclient.py
- src/servers/grpc_server.cc
Timeout specification has been added for the inference request. Have intentionally left streaming timeout from the python grpc because of a bug in grpc. For streaming RPC, most likely it treats the timeout in milliseconds instead of seconds(even though it is documented as seconds).  Will explore the issue and add it later.
> Adding the end-to-end timeout on the client side

- src/core/dynamic_batch_scheduler.cc
- src/core/dynamic_batch_scheduler.h
- src/core/infer_request.h
- src/core/infer_response.cc
- src/core/infer_response.h
With this fix, calling `InferenceResponseFactory::SendFlags` will invoke the dynamic batcher's preserve ordering so that all "responses" will be checked. Previously the "null response" carrying the FINISH flag will be lost and cause dynamic batcher not sending responses from sequential requests.
> Fix delegator to be invoked on sending "null" response. Fix preserve ordering

- qa/L0_perf_deeprecommender/run_test.sh
- qa/L0_perf_deeprecommender/test.sh
@deadeyegoodwin I removed the Dynamic Batch case and include coverage for HTTP perf as well. I'll update the dashboard as well shortly. 
Limit to batch size 256 to prevent OOM for libtorch. Remove onnx_trt for now due to segfault in server with batch size 256.
> Include ONNX and Libtorch backends in DeepRecommender perf test

- src/backends/backend/examples/backend_utils.h
- src/backends/backend/examples/identity.cc
- src/backends/backend/examples/repeat.cc
- src/backends/backend/examples/square.cc
- src/core/json.h
- src/core/model_config_utils.cc
- src/core/model_repository_manager.cc
- src/core/tritonserver.cc
- src/core/tritonserver.h
- src/servers/common.h
- src/servers/grpc_server.cc
- src/servers/http_server.cc
- src/servers/main.cc
Fixes most of the 'definitely lost' memory leaks reported by valgrind. This effort covers only custom models and does not fixes leaks in other backends. There is a 32 bytes leak within cnmem library and in dlopen calls. I read that valgrind sometimes report false positive leaks in dlopen. 
See the attached file for detail report after the fixes : [mem_custom.txt](https://github.com/NVIDIA/triton-inference-server/files/4929019/mem_custom.txt)
> Fixes some of the memory leaks

- src/backends/backend/examples/backend_utils.cc
- src/backends/backend/examples/identity.cc
- src/backends/backend/examples/repeat.cc
- src/backends/backend/examples/square.cc
- src/backends/backend/triton_model.cc
- src/backends/backend/tritonbackend.h
Inputs must be looked up by name. Using index would likely lead to
errors since it implies that every request in a batch would have the
same input->index mapping, which is not true.
> Remove backend API to get input by index

- docs/protocol/grpc_core_service.proto
- qa/L0_output_name/output_name_test.py
- src/clients/c++/library/grpc_client.cc
- src/clients/go/grpc_simple_client.go
- src/clients/python/examples/grpc_client.py
- src/clients/python/examples/grpc_explicit_byte_content_client.py
- src/clients/python/examples/grpc_explicit_int8_content_client.py
- src/clients/python/examples/grpc_explicit_int_content_client.py
- src/clients/python/examples/grpc_image_client.py
- src/clients/python/library/grpcclient.py
- src/core/grpc_service.proto
- src/servers/grpc_server.cc
Perf client arguments: `-m resnet50_fp16_plan -b 128 --concurrency-range=4 -i grpc`
> Inferences/Second vs. Client Average Batch Latency
> Concurrency: 4, throughput: 3814.4 infer/sec, latency 134257 usec
> Inferences/Second vs. Client Average Batch Latency
> Concurrency: 4, throughput: 2816 infer/sec, latency 183080 usec
> Inferences/Second vs. Client Average Batch Latency
> Concurrency: 4, throughput: 3865.6 infer/sec, latency 132671 usec
> Improving gRPC server performance with new message hierarchy

- Dockerfile.QA
Revert this commit https://github.com/NVIDIA/triton-inference-server/commit/6bc91497baad952f84ef348923cfe3c84eeea376
> Revert the disabling of golang gRPC install now that upstream is fixed

- src/core/autofill.cc
This change will let autofill behave the same as before: load and autofill once if platform / backend is specified. If both platform and backend is not specified, the backend that uses backend API will simply look for default filename (see TF autofill), and all backends should adopt this behavior as they gradually port to use backend API. Once all backends are ported, the autofill and its derived classes can be simplified.
> Modify autofill logic on trying different backends

- src/backends/tensorflow/tensorflow_backend_tf.cc
Not running CI as the changes to this file will not show impact right away...
I am not authenticated to push to the tensorflow repository. Filing here to collect reviews.
~However, there is still the matter of some ops not getting recognized as TF-TRT Candidates for optimization purposes, but are included when the network is converted outside triton. I am waiting for TFTRT team response to understand the same.~
These changes fix the problem. I was missing one of the libraries in container. These changes improve the performance of optimized TRTEngine by **25%** as seen on `resent_v1_50_savedmodel`.
> 2020-08-05 00:21:41.520011: I tensorflow/compiler/tf2tensorrt/segment/segment.cc:486] There are 16 ops of 9 different types in the graph that are not converted to TensorRT: Softmax, Squeeze, …
> Improve the TFTRT optimization path

- build/CMakeLists.txt
- src/clients/c++/library/CMakeLists.txt
- src/clients/c++/library/cmake/TRITONConfig.cmake.in
This PR addresses #1428.
The originally proposed solution, essentially `s/find_package(CURL CONFIG REQUIRED)/find_package(CURL REQUIRED)/`, did not retain the expected default behavior. When running the build according to https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/build.html, CMake found the system curl, even though a newer curl was installed in the build directory.
Instead, the approach of #1846 is followed to introduce a configuration option `TRITON_CURL_WITHOUT_CONFIG`. This option is disabled by default, so the expected build behavior is preserved. This is safer, as the option should only be selected by users who know that they also need to point to the correct files/directories with `-DCURL_LIBRARY` and `-DCURL_INCLUDE_DIR`.
This change was …
> flag to find curl package without using cmake config

- build/CMakeLists.txt
Need to advance the grpc version to 1.25.0 as [`rules_proto_grpc`](https://github.com/rules-proto-grpc/rules_proto_grpc), used for generating `*.pb.cc` and `*pb.h` files inside bazel build system doesn't have a release supporting GRPC 1.24.0.
> Advance GRPC to 1.25.0

- src/backends/backend/python/python.cc
Fix build warning complaining about dangerous use of `mktemp`.
> Replace mktemp with mkdtemp

- qa/L0_client/grpc_test.cc
- src/clients/c++/library/libgrpcclient.ldscript
Fix the ldscript to make symbols starting with `inference::` global.
> Fix undefined protobuf symbols in the client shared library

- src/custom/image_preprocess/image_preprocess.cc
In the upper code in `Contex::Preprocess`, the input image was converted to RGB.
So, VGG normalization value should be reversed.
> Fixed VGG_MEAN order

- src/custom/image_preprocess/image_preprocess.cc
`127.5` is the correct  value for INCEPTION scaling.
In short, `(0~255)` should be `(-1 ~ 1)`.
> Fixed INCEPTION scale

- src/backends/tensorrt/plan_backend.cc
- src/backends/tensorrt/plan_backend.h
- src/core/model_config.proto
- src/core/model_config_utils.cc
@deadeyegoodwin Given the limitation of CUDA graph, this is the new config option to increase the usefulness of CUDA graph in the case of dynamic shape. User needs to specify the combinations explicitly so that the users can control what the graphs to be captured for different models and Triton doesn't need to populate the combinations.
> Add CUDA graph specification in model config

- src/core/ensemble_scheduler.cc
- src/core/infer_request.cc
This bug seems to affects`ensemble_scheduler` to report underflow-ish(?) value.
> Fixed InferenceRequest::ReportStatisticsWithDuration

- src/servers/http_server.cc
In HandleInfer, when TRITONSERVER_ServerInferAsync returns an error, the infer_req unique pointer goes out of scope without being released. However, since no release callback is called, the InferRequestClass still has an AllocPayload::OutputInfo object in the output_map_.
> Fixes HTTPAPIServer leak

- qa/L0_perf_client/test.sh
Ensembles can now show 0 usec queue time so need to allow that in the test.
> Ensemble stats reporting is now fixed, requires test update

- qa/common/util.sh
- src/backends/tensorrt/loader.cc
There seemed to be duplicated calling of createInferRuntime using the same pointer, resulting in the leak of the first runtime.
> Fixed leak in TensorRT PlanBackend

- Dockerfile.QA
Side note: A few tests install awslocal-cli elasticsearch and some other packages in the test scripts (gitlab) 
I will have a follow up PR to move those installs into the Dockerfile.QA
> Install dependencies for generating nightly summary pdf

- qa/L0_s3_local/test.sh
The endpoint url used to be cached in awslocal v0.7 but it is unstable. This workaround will ensure the CI does not fail due to the endpoint url.
> Fix occasional failure due to incorrect endpoint

- src/backends/tensorrt/plan_backend.cc
- src/backends/tensorrt/plan_backend.h
- src/backends/tensorrt/plan_utils.cc
- src/backends/tensorrt/plan_utils.h
- src/core/backend_context.cc
In server-client communication, the input shape will still be in linear format so that plan backend can set binding dimension properly, but it will expect the client to prepare the input data in the corresponding non-linear form.
Cleaned up the use of `binding_index` and `io_index`. `binding_index` is the index that takes profile index into account, and it is used to prepare the executing profile properly, `io_index` is used to refer to io information that is consistent across profiles.
> Formalize reformat-free input. Minor plan_backend clean up

- Dockerfile
This was left from #2034. Should be merged after merging triton-inference-server/python_backend#7.
> Fix python backend repo tag

- Dockerfile
- src/backends/backend/triton_backend_manager.cc
- src/backends/backend/triton_backend_manager.h
- src/core/CMakeLists.txt
- src/core/model_repository_manager.cc
- src/core/server.cc
- src/core/server.h
- src/core/tritonserver.cc
- src/servers/CMakeLists.txt
A screenshot of how the logs will look like:
> Add backend state summary to Triton logs

- qa/L0_http/test.sh
- src/clients/c++/library/http_client.h.in
- src/clients/python/library/tritonclient/http/__init__.py
Picks major implementation from PR #2047
Adds simple test cases for HTTP clients and documents the optional feature.
> Allow optional base path in http url

- build.py
Change build steps to use https://github.com/microsoft/onnxruntime/tree/v1.5.1/dockerfiles as reference instead of https://github.com/microsoft/onnxruntime/tree/master/tools/ci_build/github/linux/docker because the latter is configured for ORT's CI environment
> Update ONNX Runtime version to 1.5.1

- qa/L0_sequence_batcher/test.sh
This test seems to take way too long on 20.10. Shortening it to 12 tests should allow it pass at the cost of some coverage.
> Shortened number of L0_sequence_batcher_valgrind tests to 12 tests

- src/backends/backend/triton_backend_manager.cc
- src/backends/backend/triton_backend_manager.h
- src/backends/backend/triton_memory_manager.cc
- src/backends/backend/triton_model.cc
- src/clients/python/library/setup.py
- src/core/infer_parameter.h
- src/core/infer_request.h
- src/core/infer_response.h
- src/core/infer_stats.h
- src/core/infer_trace.h
- src/core/model_config.h
- src/core/status.h
- src/core/tritonserver.cc
- src/core/tritonserver_apis.h
Compile core to export server and backend API symbols
Use LOCAL for dlopen to avoid exposing symbols.
> Fixes for backend loading via dlopen

- qa/L0_backend_dali/test.sh
- qa/L0_backend_dali/test_identity.sh
- qa/L0_backend_dali/test_rn50_ensemble.sh
Test scripts, that add 2 tests for dali_backend:
1. `identity`
2. `rn50_ensemble`
Please refer to https://github.com/triton-inference-server/dali_backend/pull/3 for more details
I'm not sure, that my convention (running `.sh` scripts in a `test.sh` script) is going to work. Please advise
Signed-off-by: szalpal <mszolucha@nvidia.com>
> DALI Backend tests for CI: identity and rn50_ensemble

- Dockerfile.QA
- qa/L0_rate_limiter/test.sh
- src/core/model_config.proto
- src/core/rate_limiter.cc
- src/core/rate_limiter.h
- src/test/CMakeLists.txt
- src/test/rate_limiter_test.cc
Note: This is just a rate limiter unit implementation and it is not connected to the server yet.
I will add the extensive testing with other PR.
The logs of the rate_limter_test covering very basic functionalities from my machine
```
[==========] Running 7 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 7 tests from RateLimiterTest
[ RUN      ] RateLimiterTest.SingleInstanceSingleInfer
[       OK ] RateLimiterTest.SingleInstanceSingleInfer (0 ms)
[ RUN      ] RateLimiterTest.SingleInstanceMultiInfer
[       OK ] RateLimiterTest.SingleInstanceMultiInfer (0 ms)
[ RUN      ] RateLimiterTest.MultiInstanceMultiInfer
[       OK ] RateLimiterTest.MultiInstanceMultiInfer (0 ms)
[ RUN      ] RateLimiterTest.SpecificInstanceMultiInfer
[       OK ] …
```
> Rate Limiter for cross-model prioritization and resource constraining

- Dockerfile.QA
- qa/L0_custom_legacy/custom_legacy_test.py
- qa/L0_custom_legacy/models/custom_identity_int32/config.pbtxt
- qa/L0_custom_legacy/test.sh
- src/backends/custom/custom_backend.cc
- src/core/backend.h
- src/test/custom/identity/identity.cc
Fixes #2104 
`tritonclient.utils.InferenceServerException: Deadline Exceeded`
```
POST /v2/models/custom_identity_int32/infer, headers {'Inference-Header-Content-Length': 164}
b'{"inputs":[{"name":"INPUT0","shape":[1,1],"datatype":"INT32","parameters":{"binary_data_size":4}}],"outputs":[{"name":"OUTPUT0","parameters":{"binary_data":true}}]}\n\x00\x00\x00'
<HTTPSocketPoolResponse status=200 headers={'content-type': 'application/json', 'content-length': '71'}>
bytearray(b'{"model_name":"custom_identity_int32","model_version":"1","outputs":[]}')
```
> Fix non-decoupled custom backend to return empty responses

- qa/L0_model_config/test.sh
- src/backends/tensorrt/autofill.cc
Upon calling runtime->destroy(), the object is destroyed but not set to nullptr. In the next attempt, autofiller tries to load the model 
with the pointer to a destroyed object causing the segfault. Fix is to reset the runtime to nullptr with each iteration.
```
root@0e283331531f:/opt/tritonserver/qa/L0_trt_dynamic_shape# /opt/tritonserver/bin/tritonserver --model-repository=./models --strict-model-config=false
I1021 00:02:48.688651 219 metrics.cc:184] found 2 GPUs supporting NVML metrics
I1021 00:02:48.694152 219 metrics.cc:193]   GPU 0: GeForce GT 710
I1021 00:02:48.700276 219 metrics.cc:193]   GPU 1: TITAN RTX
I1021 00:02:48.925943 219 pinned_memory_manager.cc:195] Pinned memory pool is created at '0x200c00000' with size 268435456
I1021 00:02:48.926747 219 cuda_memory_manager.cc:98] …
```
> Fix TensorRT autofiller to handle non-plan files in version directory

- qa/L0_backend_dali/test.sh
- qa/L0_backend_dali/test_inception_ensemble.sh
Since Triton removes Caffe2 support, remove this dependency from DALI backend testing. Put Inception model instead of RN50.
Signed-off-by: szalpal <mszolucha@nvidia.com>
> Remove Caffe2 dependency from DALI backend tests

- qa/L0_lifecycle/lifecycle_test.py
- qa/L0_lifecycle/test.sh
- src/servers/grpc_server.cc
Only RepositoryModelUnload and RepositoryModelLoad specify the async flag true. Other RPCs are quite direct and overhead of spawning an extra thread and an extra state transition can become more pronounced.
Note that this implementation frees up the handler to serve the new incoming requests. Whenever the execution is completed the **async_thread_** will add the CallData back to the completion queue to later write response to client.
> Async Model Load/Unload for GRPC endpoint

- src/clients/c++/perf_analyzer/inference_profiler.cc
- src/clients/c++/perf_analyzer/inference_profiler.h
- src/clients/c++/perf_analyzer/main.cc
- src/clients/c++/perf_analyzer/triton_client_wrapper.cc
- src/clients/c++/perf_analyzer/triton_client_wrapper.h
- src/core/ensemble_scheduler.cc
- src/core/server.cc
The cases fixed are:
1. TRITON_ENABLE_STATS = OFF, TRITON_ENABLE_TRACING = OFF
1. TRITON_ENABLE_STATS = ON, TRITON_ENABLE_TRACING = OFF
Fixes #2137 
```
root@285c0698ad37:/opt/tritonserver/qa/L0_grpc# /tmp/host/perf_analyzer -m simple -f test.csv
Batch size: 1
Client: 
Request count: 8308
Throughput: 1661.6 infer/sec
Avg latency: 600 usec (standard deviation 91 usec)
p50 latency: 581 usec
p90 latency: 681 usec
p95 latency: 727 usec
p99 latency: 944 usec
Avg HTTP time: 597 usec (send/recv 66 usec + response wait 531 usec)
Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 1661.6 infer/sec, latency 600 usec
``` …
> Fix the statistics collection and reporting in perf_client/triton server

- src/core/cuda_memory_manager.cc
- src/core/pinned_memory_manager.cc
- src/core/pinned_memory_manager.h
When creating multiple instances of `TRITONSERVER_Server` using `TRITONSERVER_ServerNew()` use the pinned and cuda memory pool defined by the first server and log the same.
- Earlier error reported that PinnedMemoryManager and CudaMemoryManager were already created 
Now just log the follow message and return success.
```
cuda_memory_manager.cc:80] New CUDA memory pools could not be created since they already exists
pinned_memory_manager.cc:182] New pinned memory pool of size 268435456 could not be created since one already exists of size 268435456
```
Note: The user must use the Pinned and CUDA memory pools as specified by the first instance of Tritonserver.
> Fix crash when creating multiple instance of Tritonserver (in the same process)

- Dockerfile.QA
- qa/L0_client_timeout/test.sh
- src/clients/c++/tests/CMakeLists.txt
- src/clients/c++/tests/client_timeout_test.cc
Added a test binary for C++ client library testing with timeouts.
Need to use the custom_identitiy_int32 models with custom delay for testing with L0_client_timeout
> Fixing L0_client_timeout test

- Dockerfile.QA
- qa/L0_multi_server/test.sh
- src/servers/CMakeLists.txt
- src/servers/multi.cc
- src/servers/multi_server.cc
- Allow 3 repos and create 2 instances of Tritonserver that use:
- Repo 1 and Repo 2
- Repo 1 and Repo 3
- Use Model Repository APIs to load models
- Use Inference APIs to run models
- Use Model Repository APIs to unload models
Repo 1 has model: simple1
Repo 2 has model: simple2
Repo 3 has model: simple3
All 3 models do the same thing but have different names to avoid conflict.
Created an L0_multiserver test. Since it is technically a server I have kept it in src/servers and not src/test
Test passes successfully!
> Create multi-server example

- src/clients/c++/examples/simple_grpc_sequence_stream_infer_client.cc
- src/clients/c++/examples/simple_grpc_sequence_sync_infer_client.cc
- src/clients/c++/examples/simple_http_sequence_sync_infer_client.cc
- src/clients/c++/perf_analyzer/client_backend/CMakeLists.txt
- src/clients/c++/perf_analyzer/client_backend/client_backend.cc
- src/clients/c++/perf_analyzer/client_backend/client_backend.h
- src/clients/c++/perf_analyzer/client_backend/tensorflow_serving/CompileProto.cmake
- src/clients/c++/perf_analyzer/client_backend/tensorflow_serving/grpc_client.cc
- src/clients/c++/perf_analyzer/client_backend/tensorflow_serving/grpc_client.h
- src/clients/c++/perf_analyzer/client_backend/tensorflow_serving/tfserve_client_backend.cc
- src/clients/c++/perf_analyzer/client_backend/tensorflow_serving/tfserve_client_backend.h
- src/clients/c++/perf_analyzer/client_backend/tensorflow_serving/tfserve_infer_input.cc
- src/clients/c++/perf_analyzer/client_backend/tensorflow_serving/tfserve_infer_input.h
- src/clients/c++/perf_analyzer/concurrency_manager.cc
- src/clients/c++/perf_analyzer/inference_profiler.cc
- src/clients/c++/perf_analyzer/main.cc
- src/clients/c++/perf_analyzer/model_parser.cc
- src/clients/c++/perf_analyzer/model_parser.h
- src/clients/c++/perf_analyzer/perf_utils.cc
- src/clients/c++/perf_analyzer/perf_utils.h
- src/clients/c++/perf_analyzer/request_rate_manager.cc
There are two important things to note:
By default, perf_analyzer will use the "serving_default" signature. The model might name the predict engine differently. In this case, use "--model-signature-name" option with perf_client.
The model metadata didn't carry any information regarding whether the first variable dimension is batching or not. I have hence, simplified the logic. The batch dimension, if present, should be provided explicitly to the perf_analyzer using --shape option. For instance, above --shape x:3,1 is generating request of batch size 3 to the model.  One can generate, batch size 10 requests by specifying --shape x:10,1.
**Also, I understand the build is not very clean but it does what it supposed to do. I will address improving the build through another ticket after we are …
> TF Serving Client Backend for perf_analyzer

- src/clients/c++/perf_analyzer/client_backend/CMakeLists.txt
- src/clients/c++/perf_analyzer/client_backend/client_backend.cc
- src/clients/c++/perf_analyzer/client_backend/torchserve/http_client.cc
- src/clients/c++/perf_analyzer/client_backend/torchserve/http_client.h
- src/clients/c++/perf_analyzer/client_backend/torchserve/torchserve_client_backend.cc
- src/clients/c++/perf_analyzer/client_backend/torchserve/torchserve_client_backend.h
- src/clients/c++/perf_analyzer/client_backend/torchserve/torchserve_infer_input.cc
- src/clients/c++/perf_analyzer/client_backend/torchserve/torchserve_infer_input.h
- src/clients/c++/perf_analyzer/main.cc
- src/clients/c++/perf_analyzer/model_parser.cc
- src/clients/c++/perf_analyzer/model_parser.h
```
root@71e48591fdfc:/# /tmp/host/perf_analyzer -m densenet161 -u localhost:8080 --service-kind torchserve --input-data input_data.json -b 8
Successfully read data for 1 stream/streams with 1 step/steps.
Batch size: 8
Client: 
Request count: 42
Throughput: 67.2 infer/sec
Avg latency: 118069 usec (standard deviation 11192 usec)
p50 latency: 117551 usec
p90 latency: 133335 usec
p95 latency: 138522 usec
p99 latency: 143168 usec
Avg HTTP time: 118595 usec (send/recv 0 usec + response wait 118595 usec)
Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 67.2 infer/sec, latency 118069 usec
```
I need to run some …
> TorchServe Client Backend for perf_analyzer

- build.py
- docs/custom_operations.md
- qa/L0_custom_ops/test.sh
User must add Pytorch libs to LD_LIBRARY_PATH to load models with custom ops. Not needed for torchvision default ops.
> Remove PyTorch from LD_LIBRARY_PATH; Fix PyTorch custom op docs

- src/clients/c++/perf_analyzer/inference_profiler.cc
- src/clients/c++/perf_analyzer/main.cc
```
root@e0b4737f4a08:/work# /tmp/host/perf_analyzer  -m resnet50v1.5_fp16_savedmodel --service-kind tfserving -i grpc --shape input:4,224,224,3
Client: 
Request count: 526
Throughput: 105.2 infer/sec
Avg latency: 9506 usec (standard deviation 303 usec)
p50 latency: 9440 usec
p90 latency: 9915 usec
p95 latency: 10133 usec
p99 latency: 10571 usec
Avg gRPC time: 9477 usec ((un)marshal request/response 828 usec + response wait 8649 usec)
Inferences/Second vs. Client Average Batch Latency
Concurrency: 1, throughput: 105.2 infer/sec, latency 9506 usec
```
> Fix the perf_analyzer for non-batching TFServing models

- qa/L0_perf_analyzer/test.sh
- src/clients/c++/perf_analyzer/concurrency_manager.cc
- src/clients/c++/perf_analyzer/load_manager.cc
- src/clients/c++/perf_analyzer/load_manager.h
- src/clients/c++/perf_analyzer/request_rate_manager.cc
This was a glaring bug with the sequence flags in the options not being reset to false in the perf_analyzer. Fixed the bug. This might change some of the performance measurements on sequence models.
> Fixing the sequence flag setup in perf_analyzer

- src/clients/python/library/tritonclient/utils/shared_memory/__init__.py
- src/clients/python/library/tritonclient/utils/shared_memory/shared_memory.cc
- must munmap before shm_unlink
> Fix memory leak in python client shared memory

- src/backends/backend/CMakeLists.txt
- src/backends/backend/triton_backend_config.cc
- src/backends/backend/triton_backend_config.h
- src/backends/backend/triton_model.cc
- src/core/CMakeLists.txt
- src/core/persistent_backend_manager.cc
- src/core/persistent_backend_manager.h
- src/core/server.cc
- src/core/server.h
Needed to avoid handing that occurs in the initialization of some
framework shared libary initialization on dlopen in some cases.
> Persistently load some backends even if no corresponding model is loaded

- src/clients/c++/perf_analyzer/client_backend/CMakeLists.txt
- src/clients/c++/perf_analyzer/client_backend/tensorflow_serving/CMakeLists.txt
- src/clients/c++/perf_analyzer/client_backend/torchserve/CMakeLists.txt
- src/clients/c++/perf_analyzer/client_backend/triton/CMakeLists.txt
Separates proto compilation needed for TFServing into a separate CMake files.
> Clean perf_analyzer cmake files

- src/clients/python/examples/simple_grpc_cudashm_client.py
- src/clients/python/examples/simple_grpc_shm_client.py
- src/clients/python/examples/simple_grpc_shm_string_client.py
- src/clients/python/examples/simple_http_cudashm_client.py
- src/clients/python/examples/simple_http_shm_client.py
- src/clients/python/examples/simple_http_shm_string_client.py
- src/clients/python/library/tritonclient/utils/cuda_shared_memory/__init__.py
- src/clients/python/library/tritonclient/utils/shared_memory/__init__.py
On the python shared memory library side: 
User should confirm `shm.mapped_shared_memory_regions()` to be empty before the python client exits. This will ensure that the user does not cause any shared memory leaks by leaving a process mapped / un-destroyed before exiting.
To destroy these regions the user must call `shm.destroy_shared_memory_region(<shm_handle>)`
Similarly on the cuda shared memory side the user must use: `cudashm.allocated_shared_memory_regions()`
> Add check for (remaining) mapped system / allocated cuda shared memory regions

- Dockerfile.sdk
- qa/L0_perf_tfs/test.sh
- qa/L0_perf_ts/test.sh
Uses the same dockerfile to build sdk on ubuntu and then copy perf_analyzer binary from there. Look at the gitlab side changes for more context.
This fixes L0_perf_tfs(https://gitlab-master.nvidia.com/dl/dgx/tritonserver/-/jobs/19072257) and L0_perf_ts(https://gitlab-master.nvidia.com/dl/dgx/tritonserver/-/jobs/19095253)
> Using perf_analyzer built on 18.04 ubuntu and cmake in non-triton benchmarks

- docs/client_libraries.md
- docs/compose.md
- docs/model_configuration.md
- docs/optimization.md
- docs/perf_analyzer.md
- docs/protocol/extension_classification.md
- docs/quickstart.md
- docs/v1_to_v2.md
In the Web version of the current documentation, there existed many cases when \<pseudovariables\> were used, but < and > symbols weren't properly escaped. In these cases, they were interpreted by the Markdown engines as inline HTML, and were completely invisible on the page. In this PR I escaped most of the < and > symbols in the documentation. Note, that such symbols inside the code blocks are not interpreted as inline HTML and thus there is no need to escape them.
See example:
in the comment source:  `<var1> vs \<var2\>`
rendered: <var1> vs \<var2\>
> Wrap <> pseudovariables in markdown, to avoid their interpretation as HTML

- src/clients/c++/perf_analyzer/client_backend/torchserve/http_client.cc
- src/clients/c++/perf_analyzer/client_backend/torchserve/http_client.h
Using the callback based approach allows perf analyzer to capture and report the http send/receive times for TorchServe service.
```
root@58d21eb46ebc:/home/model-server# /tmp/host/perf_analyzer -m resnet50 -u localhost:8080 -i http --service-kind torchserve --input-data data.json
Successfully read data for 1 stream/streams with 1 step/steps.
Client: 
Request count: 849
Throughput: 169.8 infer/sec
Avg latency: 5876 usec (standard deviation 528 usec)
p50 latency: 5809 usec
p90 latency: 5920 usec
p95 latency: 6004 usec
p99 latency: 7310 usec
Avg HTTP time: 5852 usec (send/recv 0 usec + response wait 5852 usec)
Inferences/Second vs. Client …
```
> Using curl_mime_data_cb to capture HTTP send/recv times for TorchServe

- src/clients/c++/perf_analyzer/data_loader.cc
The check for shape availability was missing in our pipeline when reading data from json.
See here: https://github.com/triton-inference-server/server/issues/2431#issuecomment-763228814
> Validate whether shapes are provided when providing data through json

- src/clients/c++/perf_analyzer/inference_profiler.cc
- src/clients/c++/perf_analyzer/inference_profiler.h
Fixes #2429 .
Perf analyzer will report the queue and compute time as the sum of its composing models. This PR makes report more comprehensible and less confusing.
```
Server: 
Inference count: 677
Execution count: 677
Successful request count: 677
Avg request latency: 8348 usec
Total avg compute input time : 82 usec
Total avg compute infer time : 7875 usec
Total avg compute output time : 223 usec
Total avg queue time : 0 usec
Composing models: 
dali, version: 
Inference count: 677
Execution count: 677
Successful request count: 677
Avg request latency: 2307 usec (overhead 3 usec + queue 42 usec + compute input 5 usec + compute infer 2220 usec + compute output 37 usec)
resnet50_fp32_libtorch, version: 
Inference count: 677
Execution count: 677
Successful request count: 677
Avg request …
```
> Fix perf_analyzer report for ensemble models

- Dockerfile.sdk
Need to go back to 3.18.4 from 3.19 since c-ares build is broken in the 3.19
> Fix grpc (client) build for 18.04

- qa/common/util.sh
Symbols on the whitelist were lost for very deep stack traces, this increases the size of the leaks records retrieved by grep from 8 lines to 12 lines.
> Increased leak depth in check_valgrind_log

- build.py
- Similar to TF, PyTorch build now copies out files from the Pytorch docker directly.
> Remove pytorch custom build and move to pytorch repository

- src/backends/tensorrt/plan_backend.cc
- src/backends/tensorrt/plan_backend.h
- src/core/model_config.proto
To avoid overwrites we ping-pong between two different sets of device buffers
> Add an option to use separate cuda stream for output copy

- src/backends/backend/triton_model_instance.cc
```
I0223 11:27:31.560848 2639 openvino.cc:1131] TRITONBACKEND_ModelInstanceInitialize: group_name_here (CPU device 0)
I0223 11:27:32.382028 2639 openvino.cc:1131] TRITONBACKEND_ModelInstanceInitialize: group_name_here (CPU device 0)
I0223 11:27:32.382209 2639 openvino.cc:1131] TRITONBACKEND_ModelInstanceInitialize: group_name_here (CPU device 0)
I0223 11:27:32.382404 2639 openvino.cc:1131] TRITONBACKEND_ModelInstanceInitialize: group_name_here (CPU device 0)
I0223 11:27:32.382567 2639 openvino.cc:1131] TRITONBACKEND_ModelInstanceInitialize: group_name_here (CPU device 0)
I0223 11:27:32.382826 2639 openvino.cc:1131] TRITONBACKEND_ModelInstanceInitialize: group_name_here (CPU device 0)
I0223 11:27:32.383053 2639 openvino.cc:1131] TRITONBACKEND_ModelInstanceInitialize: group_name_here (CPU …
```
> Fixing the naming of triton model instance

- qa/L0_perf_nomodel/run_test.sh
- qa/L0_perf_nomodel/test.sh
- Model failure when moving to version 2021.1
> Disable openvino from nomodel test

- qa/L0_backend_python/python_test.py
- qa/L0_infer_zero/infer_zero_test.py
- qa/common/gen_ensemble_model_utils.py
- qa/common/gen_qa_dyna_sequence_models.py
- qa/common/gen_qa_identity_models.py
- qa/common/gen_qa_models.py
- qa/common/gen_qa_noshape_models.py
- qa/common/gen_qa_ragged_models.py
- qa/common/gen_qa_reshape_models.py
- qa/common/gen_qa_sequence_models.py
- qa/common/gen_qa_trt_format_models.py
- qa/common/gen_qa_trt_plugin_models.py
- qa/common/infer_util.py
- qa/common/test_util.py
- src/clients/python/examples/grpc_image_client.py
- src/clients/python/library/tritonclient/utils/__init__.py
This PR removes the [deprecated numpy usages](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations) from the codebase. 
Specifically `numpy.bool` usages and fixes one mis-use of `numpy.object`.
> Remove deprecated numpy usages from client

- src/backends/tensorrt/plan_backend.cc
- src/backends/tensorrt/plan_backend.h
The timestamp captured for each phase is more realistic:
resnet before:
`Avg request latency: 4254 usec (overhead 2 usec + queue 72 usec + compute input 920 usec + compute infer 3244 usec + compute output 16 usec)`
resnet after:
`Avg request latency: 4348 usec (overhead 2 usec + queue 73 usec + compute input 312 usec + compute infer 3930 usec + compute output 31 usec)`
But there is additional overhead introduced by the fix, which is obvious for small model (end-to-end < 1ms):
plan_zero_1_float32 before:
`Avg request latency: 101 usec (overhead 1 usec + queue 13 usec + compute input 76 usec + compute infer 7 usec + compute output 4 usec)`
after:
`Avg request latency: 130 usec (overhead 3 usec + queue 13 usec + compute input 58 usec + compute infer 23 usec + compute output 33 usec)`
> Fix TRT backend to capture timestamp as soon as possible

- qa/L0_simple_go_client/test.sh
Fix test failure due to latest goloand/protoc
- Work around 'go_package' requirement in .proto source files
> Fix L0_simple_go_client test failure

- qa/L0_grpc/test.sh
- src/clients/c++/examples/simple_grpc_infer_client.cc
- src/clients/c++/library/grpc_client.cc
- src/clients/c++/library/grpc_client.h.in
- src/clients/c++/perf_analyzer/client_backend/client_backend.cc
- src/clients/c++/perf_analyzer/client_backend/client_backend.h
- src/clients/c++/perf_analyzer/client_backend/tensorflow_serving/grpc_client.cc
- src/clients/c++/perf_analyzer/client_backend/tensorflow_serving/grpc_client.h
- src/clients/c++/perf_analyzer/client_backend/tensorflow_serving/tfserve_client_backend.cc
- src/clients/c++/perf_analyzer/client_backend/tensorflow_serving/tfserve_client_backend.h
- src/clients/c++/perf_analyzer/client_backend/triton/triton_client_backend.cc
- src/clients/c++/perf_analyzer/client_backend/triton/triton_client_backend.h
- src/clients/c++/perf_analyzer/main.cc
- src/clients/python/examples/simple_grpc_infer_client.py
- src/clients/python/library/tritonclient/grpc/__init__.py
- src/servers/grpc_server.cc
- src/servers/grpc_server.h
- src/servers/main.cc
Uses per call compression only for inference requests. Using compression for non-infer related requests is not a good idea.
client-side compression:
`I0316 12:05:30.316294326    7617 message_compress_filter.cc:265] Compressed[deflate] 204 bytes vs. 102 bytes (50.00% savings)`
server-side compression:
`I0316 12:50:35.188782589   10734 message_compress_filter.cc:265] Compressed[deflate] 187 bytes vs. 99 bytes (47.06% savings)`
performance for sure seems to suffer. The numbers are collected on RN50 saved model:
```
No Compression: Concurrency: 1, throughput: 69 infer/sec, latency 14488 usec
Deflate: Concurrency: 1, throughput: 27.8 infer/sec, latency 35990 usec
Gzip: Concurrency: 1, throughput: 27.8 infer/sec, latency 35957 usec
```
> Support compression in gRPC transactions

- Dockerfile.sdk
Model Analyzer's report generation depends on `pdfkit` which depends on `wkhtmltopdf`
> Added dependency for Model Analyzer Reports

- src/clients/python/library/tritonclient/utils/__init__.py
This pr improves byte tensor serialization by order of magnitude. (`6.5s` -> `10.4 ms`), thus making `set_data_from_numpy` for byte tensors much faster. 
```python
import tritonclient.grpc as grpcclient
import numpy as np
log_ls = ['test log '*100]*10000
log_ls = [l.encode('utf-8') for l in log_ls]
log_ar = np.array(log_ls).reshape(1,len(log_ls))
input_grpc = grpcclient.InferInput("raw_log",log_ar.shape,"BYTES")
```
```python
input_grpc.set_data_from_numpy(log_ar)
```
```
Wall time:  6.55 s
```
```python
input_grpc.set_data_from_numpy(log_ar)
```
```
CPU times: user 9.24 ms, sys: 1.26 ms, total: 10.5 ms
Wall time: 10.4 ms
```
CC: @BartleyR, @bsuryadevara
> Make byte tensor serialization faster for python client

- qa/L0_output_validation/lt_op_val_client.py
L0_output_validation failed due to the earlier error msg fix in tf, onnx and pytorch backends
> Fix check for new err msg

- qa/L0_cmdline_trace/test.sh
- src/core/ensemble_scheduler.cc
- src/core/infer_request.cc
- src/core/infer_trace.cc
- src/core/infer_trace.h
- src/servers/tracer.cc
The summary after fix:
```
File: trace_ensemble.log
simple (1):
id: 3
HTTP_RECV_START
103.794us
HTTP_RECV_END
245.399us
REQUEST_START
20.291us
QUEUE_START
3957.801us
HTTP_SEND_START
18.882us
HTTP_SEND_END
41.437us
REQUEST_END
nop_TYPE_INT32_-1 (1):
id: 4
parent id: 3
REQUEST_START
11.938us
QUEUE_START
75.141us
COMPUTE_START
39.37us
COMPUTE_INPUT_END
158.294us
COMPUTE_OUTPUT_START
0.206us
COMPUTE_END
342.193us
REQUEST_END
fan_plan_int32_int32_int32 (1):
id: 5
parent id: 3
REQUEST_START
20.166us
QUEUE_START
2832.751us
REQUEST_END
nop_TYPE_INT32_-1 (1):
id: 6
parent id: 5
REQUEST_START
9.831us
QUEUE_START
42.432us
COMPUTE_START
15.753us
COMPUTE_INPUT_END
51.833us
COMPUTE_OUTPUT_START
0.184us
COMPUTE_END
120.681us
REQUEST_END
plan_int32_int32_int32 (1):
id: 7
parent id: 5
REQUEST_START …
```
> Fix nested trace in ensemble

- qa/common/reporter.py
It looks like 'Server Compute' field was renamed at some point and the perf results were not calculating the correct sum for average latency. This should solve the problem we were seeing with large payload perf results.
> Include infer output/input time in the average latency

- src/core/model_config.proto
- src/core/model_config_utils.cc
As mentioned in other PR, I think we should remove backend specific check from Triton core. This particular check prevents other backends from reflecting the model placement in the appropriate way, i.e. the model config of the backend will specify `KIND_CPU` as WAR for now while that is not true.
> Remove TF check for KIND_MODEL from Triton

- src/core/nvtx.h
For performance reasons, some tools will return a fixed value when
implementing the callback for `nvtxRangePushA`. Keeping track of the
nesting level for each thread requires accessing thread local data which
does not come for free.
For instance, Nsight Systems always returns `-1`. Following the previous
code logic, all ranges would be pushed but never popped.
Applications should not to detect failures in the tool via return codes
of NVTX API functions. It is intentionally something NVTX was designed to
prevent. We want the application to always take the same branches,
whether a tool is profiling the application or not.
This PR:
* Modifies the `NvtxRange` class to ignore the return value of
`nvtxRangePushA`.
* Overload the constructor of `NvtxRange` to prevent potential
unnecessary string …
> Fix nvtx annotations

- deploy/gke-marketplace-app/server-deployer/chart/triton/templates/hpa.yaml
HPA target value shouldn't be hardcoded and should set to :https://github.com/triton-inference-server/server/blob/master/deploy/gke-marketplace-app/server-deployer/chart/triton/values.yaml#L33
> fix GKE marketplace app HPA. target average value

- qa/L0_batcher/batcher_test.py
- qa/L0_batcher/test.sh
- qa/L0_dyna_sequence_batcher/dyna_sequence_batcher_test.py
L0_sequence_batcher already has ragged test enabled, so no change is needed.
Only the ragged test in L0_batcher added additional TRT and ONNX because we can use existing models to construct the "ragged models" expected by the test, but extra amount of effort will be needed for the test in (dyna) sequence. However, this should be fine since the batcher tests are mainly focusing on testing whether the requests will be batched appropriately, testing with one backend (sequence / dyna_sequence test model) will be sufficient.
> Enable ragged test in L0_batcher, L0_dyna_sequence_batcher

- qa/L0_backend_identity/test.sh
~~@tanmayv25 I fixed a smaller perf issue like earlier i.e. .find() in set is much faster than vector using the stl std::find~~
I also ran through most of the code base but no other places existed where indices were being compared as string instead of integers
> Fix L0_backend_identity failure

- qa/L0_batcher/test.sh
Can enable now that it is fixed by https://github.com/triton-inference-server/identity_backend/pull/12
> Enable cudashm L0_batcher preserve ordering test

- src/servers/grpc_server.cc
- src/servers/tracer.cc
- src/servers/tracer.h
@tanmayv25 The idea is that a trace object will be created whenever GRPC frontend is ready for next request, so there will always be trace objects that the GRPC frontend is responsible to delete, this change is addressing that.
> Fix trace lifecycle in GRPC

- qa/L0_batcher/test.sh
For the timestamp for batcher_cudashm to be reported corrected we need to use GPU instance and not CPU. The cudaSetDevice is only triggered for GPU instances
> Fix minor typo

- build/server/CMakeLists.txt
User might be using an untagged older commit for the dependency repos. In those cases, user might see a fetch content failure as the older commit is not pulled.
> Don't use GIT_SHALLOW to pull common,core and backend 

- build.py
The builld.py argument parser reads --enable-nvtx but did not pass the option to cmake
which created a false impression this option works.
It is fixed in this commit
> Propagate build.py --enable-nvtx flag to CMake options

- qa/L0_sequence_batcher/sequence_batcher_test.py
- qa/L0_sequence_batcher/test.sh
- Fix L0_sequence_batcher_valgrind failure caused by sequence timeout due to cuda init delay
> sequence batcher Load nop_* identity model on GPU instead of CPU

- src/backends/backend/triton_model_instance.cc
- src/backends/backend/triton_model_instance.h
I have separated this change in a separate PR from tanmay-dev as it can go for now. I have tested it for TRT backend repo and it passes L0_infer_variable.
This will prevent frequent rebases.
Linked PR on core: https://github.com/triton-inference-server/core/pull/20
> Add the Optimization Profile APIs for TRT backend

- qa/L0_sdk/grpc_test.cc
- qa/L0_sdk/http_test.cc
Change unit test to reflect changes in the client
Changed code:
https://github.com/triton-inference-server/client/pull/14
> Remove nvidia from client namespace

- Dockerfile.win10.min
This solves the docker build issue in Windows 10
Error `The request was aborted: Could not create SSL/TLS secure channel.` is eliminated with this changes.
> Solve windows docker build issues

- src/backends/backend/triton_model.cc
- src/backends/backend/triton_model_instance.cc
- src/backends/backend/triton_model_instance.h
This ensures the backend threads are created and shared among TritonModelInstance correctly. Note this PR extends an earlier [PR](https://github.com/triton-inference-server/server/pull/2891).
With this the threading model is fairly complete. Remaining work on server core:
1. WarmUp and related reorganization.
2. Sequence scheduler update.
Also left in TensorRT repo: 
1. Integration with new threading model for truly asynchronous operation.
2. Autofiller
3. WarmUp.
4. Bugs causing failures in CI.
We would have to run a round of perf tuning for these changes. I am noticing a perf drop on our add-sub model because of RateLimiter in single instance case.
For this PR:
System: Single GPU and Four Instances
```
I0520 14:09:21.366773 24727 triton_model_instance.cc:371] Starting backend thread for …
```
> Add support for device blocking backend execution policy

- qa/L0_trt_dla/test.sh
- src/backends/tensorrt/autofill.cc
- src/backends/tensorrt/loader.cc
- src/backends/tensorrt/loader.h
- src/backends/tensorrt/plan_backend.cc
- src/backends/tensorrt/plan_backend.h
- src/backends/tensorrt/plan_backend_factory.cc
- src/core/model_config_utils.cc
TODO: When moving to separate repo and new Backend API the parallel changes need also to be made
Must add secondary devices to model config to specify that the model should use DLA as shown below:
```
instance_group [
{
kind: KIND_GPU
secondary_devices [
{
kind: KIND_NVDLA 
device_id: 1
}
]
}
]
```
When launched on a machine with no DLA cores, Triton reports the following error
```
+----------------+---------+--------------------------------------------------------------------------------------+
| Model          | Version | Status                                                                               |
+----------------+---------+--------------------------------------------------------------------------------------+
| resnet50_plan  | 1       | UNAVAILABLE: Internal: unable to …
```
> Add support for DLA in TensorRT backend

- src/core/cuda_memory_manager.cc
- cnmem is not initialized when memory pool sizes are 0
> Fix cuda memory manager destructor when not initialized

- nvidia_entrypoint.sh
Remove NVM linking. Since we have moved off of NVML to DCGM, we do not need 
special linking in entry script. 
This PR should merge after https://github.com/triton-inference-server/server/pull/2924
Solves https://github.com/triton-inference-server/server/issues/2600
> Remove NVML linking from entrypoint script

- src/core/infer_request.cc
Fix the first 4 bytes to correctly represent the total number of bytes available in a null request. Closes #2855.
> Fix null requests for TYPE_STRING

- qa/L0_storage_azure/test.sh
- src/core/filesystem.cc
Fix case errno is 0 but the blob_property.valid() returns false. It appears errno is the correct way to check for errors based on the azure sdk [sample](https://github.com/Azure/azure-storage-cpplite/blob/master/sample/sample2.cpp).
> Add explicit model control test for Azure storage

- qa/L0_sdk/test.sh
Check for cases like: https://github.com/triton-inference-server/client/pull/18.
> Test for PA binary within tritonclient pip wheel

- src/backends/backend/triton_model_instance.cc
- src/core/dynamic_batch_scheduler.cc
- src/core/dynamic_batch_scheduler.h
- src/core/rate_limiter.cc
- src/core/rate_limiter.h
This enables the dynamic batches to the models. I have fixed the perf difference for most of the cases. There are few cases performance of this DB still lags. The reason is now the batcher thread acquires the lock to the priority queue more frequently. I have to do some more tuning and believe after which the performance might actually improve.
UPDATE: I have done some of the tune ups to batcher. Take a look at the performance analysis and further scope with DLIS-2534.
> Build dynamic batches using BatcherThread

- deploy/gcp/README.md
This has been fixed upstream by the prometheus team and tested on GKE k8s 1.19 and 1.20 for triton 21.05 and 21.06
Signed-off-by: Ryan McCormick <rmccormick@nvidia.com>
> Remove note about prometheus incompatibility on GKE

- deploy/aws/README.md
- deploy/aws/templates/deployment.yaml
- deploy/gcp/README.md
- deploy/gcp/templates/deployment.yaml
- Move `securityContext` from container scope to pod scope to support Helm3 in addition to Helm2. 
- Update `gcp/README.md` and `aws/README.md` with instructions on Helm3 and Helm2 installation.
Helm3 fails with this error described here: https://github.com/zammad/zammad-helm/issues/40
Fix is to move `securityContext` up one level from container scope to pod scope.
```bash
$ helm3 install local-helm3 . 
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext
```
```
$ helm2 install --name local-helm2 .
NAME:   local-helm2
LAST DEPLOYED: Fri Jun 25 15:40:34 2021
NAMESPACE: default
STATUS: DEPLOYED …
```
> Add support for Helm3 (helm2 still supported) 

- src/core/backend.cc
- src/core/dynamic_batch_scheduler.cc
- src/core/dynamic_batch_scheduler.h
- src/core/sequence_batch_scheduler.cc
- src/core/sequence_batch_scheduler.h
There is a big performance slump.
**Config:**
model: simple_savedmodel_sequence_object
instance count: 1
max_batch_size: 8
sequence_batching {
max_sequence_idle_microseconds: 5000000
}
concurrent sequences: 4
request concurrencies: 5
**New SequenceBatcher:**
Concurrency: 5, throughput: 1830 infer/sec, latency 2701 usec
Avg request latency: 2543 usec (overhead 91 usec + **queue 2008 usec** + compute input 32 usec + compute infer 403 usec + compute output 9 usec)
**Current SequenceBatcher**
Concurrency: 5, throughput: 3619 infer/sec, latency 1348 usec
Avg request latency: 1171 usec (overhead 178 usec + **queue 512 usec** + compute input 37 usec + compute infer 431 usec + compute output 13 usec)
The nsight traces  show some serious missed notification. I will address the perf slump as a part …
> Integrate SequenceBatcher with new threading abstraction

- docs/model_repository.md
Clarify requirements to deploy triton with an azure storage model repository
> Update azure storage docs

- src/core/model_config_utils.cc
Removing the platform checks when backend is present. This will allow people to put custom backends onto the server after building it, rather than building with the backend flags enabled.
> Remove platform checks when the backend is present.

- Dockerfile.QA
> Fixing the boofuzz version to 0.3.0

- deploy/gke-marketplace-app/README.md
- deploy/gke-marketplace-app/client-sample/locustfile_bert_large.py
2 fixes in README to resolve startup error user might run into
> Update based on Feedback from TME

- qa/L0_http/test.sh
- src/servers/http_server.cc
> Add check for input shape

- src/backends/backend/triton_model_instance.cc
- src/backends/backend/triton_model_instance.h
This should be able to fix L0_decoupled.
> Explicitly wait for the backend thread when destructing instance

- qa/L0_infer/infer_test.py
- qa/L0_infer/test.sh
- qa/common/gen_qa_dyna_sequence_models.py
- qa/common/gen_qa_identity_models.py
- qa/common/gen_qa_model_repository
- qa/common/gen_qa_models.py
- qa/common/gen_qa_reshape_models.py
- qa/common/gen_qa_sequence_models.py
- qa/common/test_util.py
~https://github.com/openvinotoolkit/openvino/issues/4798 prevents this from working till the next release i.e. 2021.3~
Moving forward to Openvino 2021.4 
Openvino does not support variable shape tensors 
- This impacts batch as well as variable shape [-1] models such as identity models.
- Hence for now while we generate all non-variable models but enable just L0_infer
PS: Bug filed against Openvino for multi dims models with different I/O dtypes such as addsub with inputs of FP32 dtype and outputs of INT32 dtype
https://github.com/openvinotoolkit/openvino/issues/7173
> Add generation scripts for OpenVino models (No variable shapes)

- src/servers/CMakeLists.txt
Because the dl library is needed by boost::stacktrace, the dl library should be linked after the Boost stacktrace libraries are linked.
> Fix build_variants

- Dockerfile.QA
- qa/L0_storage_azure/test.sh
Fixes L0_storage_azure failure:
```
File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/_session.py", line 46, in load
if st.st_mtime + max_age < time.clock():
AttributeError: module 'time' has no attribute 'clock'
```
> Fix setuptools version to WAR azure cli error

- src/core/tritonserver.cc
- MinComputeCapability
- BackendDir
- StrictModelConfig
> Fix default values for backend configs when not set

- src/core/response_cache.cc
- src/core/response_cache.h
- src/test/CMakeLists.txt
- src/test/response_cache_test.cc
Threading
Unit Tests
Memory
Clean Up
> Response Cache v1

- build.py
- compose.py
- docs/compose.md
Enable compose script to compose cpu-only containers. Fixed upstream-version confusion to ensure compose script works for all branches
> Add CPU only to compose script

- src/backends/backend/triton_model.cc
- src/backends/backend/triton_model.h
- src/backends/backend/triton_model_instance.cc
- src/core/instance_queue.cc
- src/core/instance_queue.h
- src/core/payload.cc
- src/core/payload.h
- src/core/rate_limiter.cc
- src/core/rate_limiter.h
- src/core/server.cc
**Model:** resnet50v1.5_savedmodel;  **Instance Count**: 2
Avg request latency: 16645 usec (overhead 47 usec + **queue 7450 usec** + compute input 136 usec + compute infer 8994 usec + compute output 18 usec)
Avg request latency: 15629 usec (overhead 47 usec + **queue 6979 usec** + compute input 137 usec + compute infer 8448 usec + compute output 18 usec)
Avg request latency: 25244 usec (overhead 50 usec + **queue 18561 usec** + compute input 163 usec + compute infer 6452 usec + compute output 18 usec)
Rate limiter seems to be working. 
There is some overhead in the rate limiting logic. For an efficient rate limiting implementation, I would assume the following: 
`queue time for case 3 = queue time of Case 2 + compute time of Case 2.`
which comes out to be 15582us. However. we see the …
> Connects the rate limiter to the scheduling pipeline

- build.py
When building the armnn_tflite_backend independently of the server with `build.py`, if mali gpu support is to be included in the triton components, then the cmake arg should be added. It's better if this is not conditional the inclusion of the armnn_tflite_backend in the build.
For reference a server build with no armnn_tflite_backend and mali gpu support would be done with:
```bash
./build.py --cmake-dir=/workspace/build --build-dir=/tmp/citritonbuild --image=base,arm64v8/ubuntu:20.04 --enable-logging --enable-stats --enable-tracing --enable-metrics --endpoint=http --endpoint=grpc --enable-mali-gpu
```
> Make mali gpu flag non-dependent on armnn tflite backend

- docs/architecture.md
This PR updates the documentation to clarify that, by default, [one instance is created per GPU](https://github.com/triton-inference-server/server/blob/main/docs/architecture.md#concurrent-model-execution).
> Clarify default model instance behavior

- qa/L0_model_config/autofill_noplatform/pytorch/too_few_inputs/config.pbtxt
- qa/L0_model_config/autofill_noplatform/pytorch/too_few_inputs/expected
- qa/L0_model_config/autofill_noplatform/pytorch/too_few_outputs/config.pbtxt
- qa/L0_model_config/autofill_noplatform/pytorch/too_few_outputs/expected
- qa/L0_model_config/test.sh
Autofill should return error if no inputs / outputs are provided in model config
> Add test coverage for pytorch too few inputs/outputs

- qa/L0_backend_identity/test.sh
The output log of the server is being returned as binary file. 
```
inference_server.log: data
```
> Fix L0_backend_identity test

- src/core/infer_request.cc
This must be enforce otherwise CopyAsNull() is operating on invalid shape information
> Check input shape is fixed on infer request normalization

- compose.py
openvino backend directory name is now tagged to reflect the version. In order to compose image with mulitple openvino backends user must explicitly specify `--backend openvino_<vers_str>`. To support --backend openvino, we tag the name with default ov version from the build.py.
> Fix compose script by tagging openvino backend dir name before trying to copy it out

- qa/L0_lifecycle/lifecycle_test.py
- qa/L0_lifecycle/test.sh
This updates the lifecycle tests to check specific errors are returned when a model load fails. The tests check for errors in the server logs for model control modes NONE and EXPLICIT.
I am not seeing errors returned for the tests in POLL mode (which load the models successfully, then modify the models to fail reloading). If we expect those to return errors too, the tests can be updated.
> Update Lifecycle Tests to Check Specific Errors

- qa/L0_memory_growth/server_memory_mail.py
- Reports PTX failure now when busyop log file is missing i.e. when Server fails to start due to PTX issue.
> Fix typo that causes incorrect content in memory growth email

- qa/common/gen_qa_custom_ops_models.py
Fix path for roi_align function
cc @dzier
> The torchvision ops were removed from torch. We must now use torchvision 

- qa/L0_sequence_batcher/sequence_batcher_test.py
- qa/common/gen_qa_dyna_sequence_implicit_models.py
- qa/common/gen_qa_implicit_models.py
- qa/common/gen_qa_sequence_models.py
- qa/python_models/dlpack_add_sub/model.py
- qa/python_models/dlpack_sub_add/model.py
Removes the following deprecation warning
```
DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
```
> Remove np.bool deprecation warnings

- src/core/infer_request.h
When enqueuing to the dynamic batcher, the function will be called again and results in recording incorrect queue start time
> Avoid overwriting queue timer in the case of oldest sequence batcher

- docs/model_configuration.md
There is 3 different version policy for model configuration.
Adding samples configuration to imporve the documentation.
> Add config sample for version_policy

- src/core/infer_request.h
This reverts commit b0f1b33bc550274f474996cba1e4ce5602c46f68.
@deadeyegoodwin we may need to think about how to collect timestamp properly for oldest sequence batcher. The issue is that dynamic batcher also uses "queue start" timestamp to determine if its max queue delay is exceeded, so "queue start" timestamp should be recorded when the request reaches the dynamic batcher, which then doesn't reflect the actual queue time (start from when the request arrives oldest sequence batcher).
> Revert "Avoid overwriting queue timer if it has been set (#3778)"

- deploy/k8s-onprem/Chart.yaml
- deploy/k8s-onprem/README.md
- deploy/k8s-onprem/dashboard.json
- deploy/k8s-onprem/templates/_helpers.tpl
- deploy/k8s-onprem/templates/deployment.yaml
- deploy/k8s-onprem/templates/hpa.yaml
- deploy/k8s-onprem/templates/ingressroute.yaml
- deploy/k8s-onprem/templates/service.yaml
- deploy/k8s-onprem/values.yaml
This PR provides a new helm chart and instructions for deploying Triton Inference Server in an on-premises Kubernetes environment. In particular, it includes a horizontal pod autoscaler and Traefik load balancer to replace CSP specific components.
> On-Prem Kubernetes Deploy Helm Chart

- src/servers/grpc_server.cc
- src/servers/grpc_server.h
This PR is in conjunction with https://github.com/triton-inference-server/client/pull/55 to improve single process GRPC throughput. After the change, the single perf analyzer performance is comparable with two perf analyzer sending requests to the same server (total of ~6300 infer / sec). Note that there is still abnormal grpc time compare to server-side latency which suggests long network overhead, networking analysis is needed to determine if it can be further improved
before:
```
install/bin/perf_analyzer -m batching --concurrency-range=1024 -i grpc -a -v -p 10000
Batch size: 1
Using "time_windows" mode for stabilization
Measurement window: 10000 msec
Using asynchronous calls for inference
Request concurrency: 1024
Pass [1] …
```
> Register more infer requests to improve concurrency

- build.py
Prior to change:
Using `--override-backend-cmake-arg=python:TRITON_ENABLE_GPU=OFF` resulted in incorrect parsing
```
backend "python" CMake override "-Dpython=TRITON_ENABLE_GPU=OFF"
```
After change:
```
backend "python" CMake override "-DTRITON_ENABLE_GPU=OFF"
```
> Fix parsing of --override-backend-cmake-arg

- src/core/dynamic_batch_scheduler.cc
- src/core/infer_request.cc
- src/core/infer_request.h
- src/core/instance_queue.cc
- src/core/payload.cc
- src/core/payload.h
- src/core/scheduler_utils.cc
- src/core/sequence_batch_scheduler.cc
Now in the case of oldest sequence batcher, the queue time is tracked (not counting towards overhead)
Before:
```
...
Avg request latency: 68538 usec (overhead 60622 usec + queue 2080 usec + compute input 172 usec + compute infer 5525 usec + compute output 139 usec)
...
```
After:
```
...
Avg request latency: 69777 usec (overhead 168 usec + queue 63749 usec + compute input 168 usec + compute infer 5554 usec + compute output 138 usec)
...
```
> Add batcher timestamp to report queue time properly and to maintain batcher functionality

- deploy/mlflow-triton-plugin/mlflow_triton/deployments.py
This is a trivial bugfix.
If `TRITON_URL` contains a full URL like `http://...`, `mlflow deployment ...` should be failed. Although [`deploy/mlflow-triton-plugin/mlflow_triton/deployments.py`](https://github.com/triton-inference-server/server/blob/main/deploy/mlflow-triton-plugin/mlflow_triton/deployments.py) is checking if a given URL has URL scheme or not and removing URL scheme, the check and removal don't work well. Therefore, creating a Triton client instance (at [`deploy/mlflow-triton-plugin/mlflow_triton/deployments.py#L67`](https://github.com/triton-inference-server/server/blob/043a95e911102571231fdfc8ed94ca1836e75c8e/deploy/mlflow-triton-plugin/mlflow_triton/deployments.py#L67)) causes an error, and overall command also fails.
> Bugfix: wrong URL scheme check in MLFlow plugin deployment.

- deploy/mlflow-triton-plugin/scripts/triton_flavor.py
This is a trivial bugfix. When users use [`deploy/mlflow-triton-plugin/scripts/publish_model_to_mlflow.py`](https://github.com/triton-inference-server/server/blob/main/deploy/mlflow-triton-plugin/scripts/publish_model_to_mlflow.py) with a model option, `--model_directory`, having slash (`/`) at the end of model path (e.g., `--model_directory <path-to-the-examples-directory>/onnx_float32_int32_int32/`), `FileExistsError` occurs like below.
(Note that this error never happens with a normalized path like `--model_directory <path-to-the-examples-directory>/onnx_float32_int32_int32`.)
```
Traceback (most recent call last):
File "publish_model_to_mlflow.py", line 71, in <module>
publish_to_mlflow()
File "/usr/local/lib/python3.8/dist-packages/click-8.0.3-py3.8.egg/click/core.py", line 1128, in …
```
> Bugfix: normalize a model path in MLFlow plugin script.

- src/core/payload.cc
- src/core/payload.h
- src/core/rate_limiter.cc
- src/core/sequence_batch_scheduler.cc
- src/core/sequence_batch_scheduler.h
This change improves performance of DirectSequenceBatcher and brings it at par with r21.08.
perf_analyzer -u localhost:8001 --streaming -i gRPC -m citrinet-1024-en-US-asr-streaming-throughput -b 1 --input-data ensemble_chunk800/ --shape=AUDIO_SIGNAL:12800 --shape=CUSTOM_CONFIGURATION:1,2 --sequence-length=4  --concurrency-range=128:128:1 -p 1000
`citrinet-1024-en-US-asr-streaming-throughput` is an ensemble model with 5 composing sequence models. Only 1 of these five  uses DirectSequenceBatcher, others use Oldest scheme.
```
Inferences/Second vs. Client Average Batch Latency
Concurrency: 128, throughput: 983 infer/sec, latency 136770 usec
```
```
Inferences/Second vs. Client Average Batch Latency
Concurrency: 128, throughput: 644 infer/sec, latency 199690 usec
```
```
*** Measurement …
```
> Block the DirectSequenceBatcher thread to form larger batches

- Dockerfile.QA
- qa/L0_simple_nodejs_client/test.sh
The NodeJS grpc generated client is being developed in this PR: https://github.com/triton-inference-server/client/pull/52
> Add NodeJs grpc generated client in CI test

- src/core/sequence_batch_scheduler.cc
- src/core/sequence_batch_scheduler.h
The root cause was that we were reusing the same override input for all the sequence slots. If the sequence ended but the request was not executed yet, the slot will belong to a new sequence and override the correlation id of the previous sequence which has not been executed which lead to mismatch between the request correlation ID and input override correlation ID.
> Fix mismatch between the override correlation ID and request correlation ID

- src/backends/backend/triton_model.cc
- src/core/rate_limiter.cc
- src/core/rate_limiter.h
```
==21418== Thread 32:
==21418== Invalid read of size 8
==21418== at 0x4CCA20F: nvidia::inferenceserver::RateLimiter::ModelInstanceContext::RequestRemoval() (in\
/opt/tritonserver/lib/libtritonserver.so)
==21418== by 0x4CCA285: nvidia::inferenceserver::RateLimiter::ModelInstanceContext::WaitForRemoval() (in\
/opt/tritonserver/lib/libtritonserver.so)
==21418== by 0x4CD1480: nvidia::inferenceserver::RateLimiter::UnregisterModel(nvidia::inferenceserver::T\
ritonModel const*) (in /opt/tritonserver/lib/libtritonserver.so)
==21418== by 0x4DC498A: nvidia::inferenceserver::TritonModel::~TritonModel() (in /opt/tritonserver/lib/l\
ibtritonserver.so)
==21418== by 0x4DC504C: nvidia::inferenceserver::TritonModel::~TritonModel() (in /opt/tritonserver/lib/l\
ibtritonserver.so)
==21418== by 0x4C61E46: …
```
> Fixes a memory leak during model unloading 

- build/sagemaker/serve
Adding logging options to sagemaker [serve](https://github.com/triton-inference-server/server/blob/043a95e911102571231fdfc8ed94ca1836e75c8e/build/sagemaker/serve#L75) script to make the log level configurable for Sagemaker inference endpoints
```
import time
from sagemaker.predictor import Predictor
from sagemaker.model import Model
model_path='<s3_model_path>'
image_uri='<image_uri>'
role='<sagemaker_execution_role>'
model_name='resnet'
model = Model(model_data=model_path,
image_uri=image_uri,
role=role,
env={'SAGEMAKER_TRITON_LOG_VERBOSE':'1'},
predictor_cls=Predictor,name=model_name+time.strftime("-%Y-%m-%d-%H-%M-%S", time.gmtime()))
endpoint_name=model_name+time.strftime("-%Y-%m-%d-%H-%M-%S", time.gmtime())
predictor=model.deploy(endpoint_name=endpoint_name,
initial_instance_count=1, …
```
> Adding logging options to sagemaker startup script

- docs/protocol/README.md
- docs/protocol/extension_trace.md
- docs/trace.md
- qa/L0_cmdline_trace/test.sh
- qa/L0_trace/test.sh
- qa/L0_trace/trace_endpoint_test.py
- qa/common/trace_summary.py
- src/core/server.cc
- src/servers/grpc_server.cc
- src/servers/http_server.cc
- src/servers/http_server.h
- src/servers/main.cc
- src/servers/tracer.cc
- src/servers/tracer.h
@deadeyegoodwin look-and-feel of the trace endpoints and the new trace configuration requested
> Add trace endpoints. Add trace log frequency

- docs/metrics.md
Documentation on new cache metrics/stats introduced in https://github.com/triton-inference-server/server/pull/3569
> Add cache metrics docs

- src/backends/backend/triton_model_instance.cc
- src/core/constants.h
- src/core/dynamic_batch_scheduler.cc
- src/core/ensemble_scheduler.cc
- src/core/metric_model_reporter.cc
Follow-up to https://github.com/triton-inference-server/server/pull/3569/files/752abbe7f07f3cc1ab787033d982a9d2aa8fde34#r802145062
> Replace magic numbers for MetricModelReporter device_id with constants

- docs/jetson.md
* Move docs from release notes to dedicated jetson doc section
* Must install the PyTorch wheel as well. Needed for build + runtime
* Fix for 2.19.0 release
* Move version specific information to release notes
> Move docs from release notes to dedicated Jetson docs section (#3958)

- docs/protocol/extension_model_repository.md
- qa/L0_lifecycle/lifecycle_test.py
- qa/L0_lifecycle/test.sh
- src/core/model_config_utils.cc
- src/core/model_config_utils.h
- src/core/model_repository_manager.cc
- src/core/model_repository_manager.h
- src/core/server.cc
- src/core/server.h
- src/core/tritonserver.cc
- src/servers/grpc_server.cc
- src/servers/http_server.cc
@deadeyegoodwin @tanmayv25 @CoderHam Look and feel of the extended API. In terms of GRPC API, I think we could `ModelRepositoryParameter` extend to have `ModelConfig` as one of the value option, but requiring JSON string for now to match the HTTP side.
> Extend model repository API for config override

- qa/python_models/identity_fp32/config.pbtxt
Looks like the `L0_perf_no_model` tests for Python backend were running with 3 instances instead of 2 instances because the model configuration looked like below:
```
instance_group [
{
count: 1
kind : KIND_CPU
}
]
instance_group [ { kind: KIND_CPU, count: 2 }]
```
> Remove instance group setting from identity model config

- Dockerfile.QA
- Dockerfile.sdk
Multistage build to add Java bindings jar to SDK and QA container
Actual build in client repo: https://github.com/triton-inference-server/client/pull/68
> Build Java jar in sdk and QA containers

- build.py
- Use Triton min container to copy out cuda libraries, cudnn, nccl for CPU only build when PyTorch backend is enabled.
> This is needed because the pytorch NGC container has a build that is not designed for a CPU only environment.
> Add work around to enable building PyTorch backend in CPU-only container

- qa/L0_lifecycle/lifecycle_test.py
- qa/L0_lifecycle/test.sh
- src/grpc_server.cc
- src/http_server.cc
- src/http_server.h
Detect whether the port assigned to GRPC, HTTP, or metrics is already in use when server is starting up. If so, return a error.
> Port Collision Detection

- docs/jetson.md
- qa/L0_infer/test.sh
Enhance L0_infer to allow smaller default shm size for python backend on jetson
> Update jetson docs for Jetpack 22.03

- Dockerfile.QA
- qa/L0_backend_python/ensemble/ensemble_test.py
- qa/L0_backend_python/io/io_test.py
- qa/L0_backend_python/lifecycle/lifecycle_test.py
- qa/L0_backend_python/model_control/model_control_test.py
- qa/L0_backend_python/python_test.py
- qa/L0_backend_python/python_unittest.py
- qa/L0_backend_python/restart/models/restart/1/model.py
- qa/common/shm_util.py
- qa/python_models/bls/model.py
Adds shared memory leak detection to Python backend tests. The tests that involved growing the shared memory region do not use this utility.
Corresponding Python backend PR: https://github.com/triton-inference-server/python_backend/pull/130
Usage is shown in the `shm_util.py`.
> Add shared memory leak detection to Python backend tests

- Dockerfile.QA
- qa/L0_metrics/test.sh
Appears that the unit test in https://github.com/triton-inference-server/core/pull/46 wasn't added to existing test
> Add metric API unit test to L0_metrics

- docs/jetson.md
Resolved https://github.com/triton-inference-server/server/issues/4172
> Update pytorch wheel url for new naming convention

- src/grpc_server.cc
For decoupled model the map with the timestamps was getting corrupted as the callbacks can be recorded along with timestamps for GRPC_SEND_START and GRPC_SEND_END. Recording the only the first callback into the timestamp when tracing.
```
first = "INFER_RESPONSE_COMPLETE", second = 2271529015212328}, {first = "INFER_RESPONSE_COMPLETE", second = 2271529015285980}, {first = "GRPC_SEND_START", second = 2271529015386244}, {first = "", 
second = 48}, {first = "", second = 435710686577}, {first = <error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>, second = 140587214766080}, {
first = "\260Z\000`\335\177\000\000P\213\000`\335\177\000\000\200\016\000\354\334\177\000\000\001\000\000\000\000\000\000\000\060", '\000' <repeats 23 times>, …
```
> Record INFER_RESPONSE_COMPLETE only at the first callback

- qa/L0_backend_python/python_unittest.py
Looks like in some cases there could be shared memory growth on the second call too.
> Fix L0_backend_python

- build.py
- Removes the following failure while loading models in the pytorch backend.
```
/opt/tritonserver/backends/pytorch/libtorch_cuda.so: undefined symbol: cublasLtMatmulDescCreate
```
> Fix CPU only failure for pytorch backend

- docs/optimization.md
Having this keyword included should benefit users searching for Triton support of TF-TRT models. Currently it's only mentioned explicitly in a few CI test comments.
> Add 'TF-TRT' and `ORT-TRT' keywords to docs for searchability

- qa/python_models/optional/config.pbtxt
- Fixed jetson failure since GPU instances are not supported
Fixes L0_backend_python failure
> Fix instance type to CPU for optional python model

- qa/L0_backend_tutorial/test.sh
Currently we cat the client log when failing to find something in server log output - this makes it hard to see what happened in CI test failure output.
> Cat SERVER_LOG when failing to grep it

- Dockerfile.win10.min
Dockerfile.win10.min
---
Moving away from checking out the specific commit and start using [vcpkg:tag:2022.04.12](https://github.com/microsoft/vcpkg/tree/2022.04.12) repository tag reference.
>  Moving away from commit hash reference and start using tag. 

- compose.py
> Fix compose.py to use updated container_versions() function from build.py

- build.py
Currently only identity backend uses this CMake option, but should expose it to all backends to be consistent with core
> Update build.py to expose TRITON_ENABLE_METRICS to backends

- qa/L0_java_memory_growth/Simple.java
- qa/L0_java_memory_growth/test.sh
- Ignore outliers when calculating memory growth
- Separate sanity check (checking accuracy) from longer-running memory growth test
- Add long-running stress test components to test script (will officially add to long-running stress test in future PR).
> Ignore Outliers in Java API Memory Test

- Dockerfile.sdk
- build.py
To best ensure the security and reliability of our RPM and Debian package repositories, NVIDIA is updating and rotating the signing keys used by apt, dnf/yum, and zypper package managers beginning April 27, 2022. Failure to update your repository signing keys will result in package management errors when attempting to access or install packages from CUDA repositories.
https://forums.developer.nvidia.com/t/notice-cuda-linux-repository-key-rotation/212771
> GPG CUDA Linux Repository Key Rotation

- qa/L0_http/http_test.py
- qa/L0_http/test.sh
Unit tests for https://github.com/triton-inference-server/client/pull/101
> Add unit tests for transfer-encoding HTTP headers

- build.py
- compose.py
- Avoid extra copy of nccl library
> Shift copying of NCCL for TF2 backend into build.py

- qa/L0_lifecycle/test.sh
--strict-model-config=false is going to be the new default. This PR fixes a test which relies on --strict-model-config=true being set.
> Fix L0_lifecycle test when autocompleteing models

- build.py
This PR is a cherry-picked commit https://github.com/triton-inference-server/server/commit/a144ccca023826ab4d75cf509abfab3892636f0d from the `main` branch. 
For correct build of `r21.08-nvaie1.2` branch, we need DALI version `1.4` (from the `21.08` container). Currently, always the latest DALI version is built. Therefore we need to add a possibility to specify extra arguments for the build script. Using these arguments, we can pass the following variables to DALI Backend build:
```bash
-D DALI_VERSION=1.4
-D DALI_EXTRA_INDEX_URL=...
-D DALI_DOWNLOAD_EXTRA_OPTIONS=...
./build.py 
--extra-backend-cmake-arg=dali:DALI_VERSION=1.4 
--extra-backend-cmake-arg=dali:DALI_EXTRA_INDEX_URL=... 
--extra-backend-cmake-arg=dali:DALI_DOWNLOAD_EXTRA_OPTIONS=
```
The cherry-picked commit …
> Add build.py option to set/override cmake args (#3606)

- qa/L0_perf_ts/test.sh
This is temporary fix. 
Required because we are using public image for `pytorch/torchserve` which is quiet outdated and doesn't have nightly builds or container with proper fix. 
https://hub.docker.com/r/pytorch/torchserve/tags
> Adding GPG fix

- docs/model_configuration.md
- qa/L0_libtorch_io_names/io_names_client.py
- qa/L0_libtorch_io_names/test.sh
- qa/L0_simple_go_client/test.sh
- Tests fall back to enforcing ordering for cases when index and model arguement naming convention for I/O is not met
- These models that would earlier fail to load, now load succesfully and the input/outputs assume the order they are specified in inside the model configuration file
> Add L0_libtorch_io_names test and update docs for new Naming Convention for PyTorch backend

- docs/model_configuration.md
We reference the model configuration doc for `cc_model_filenames` [here](https://github.com/triton-inference-server/server/blob/185253ce225a0b012e73cade5c9a948ef9e75abd/docs/model_repository.md#tensorrt-models), but there is no corresponding documentation on it, so I added a short section.
> Add section on cc_model_filenames to model config docs

- src/sagemaker_server.cc
- src/sagemaker_server.h
1. This change is an addition to the MME changes in this PR: https://github.com/triton-inference-server/server/pull/4181. 
2. This change adds the ability for the SM endpoint to throw a 507 to the SM platform as per  - https://docs.aws.amazon.com/sagemaker/latest/dg/mms-container-apis.html#multi-model-api-load-model. 
3. Can be updated to throw capture more specific errors for different backends.
4. It also adds the ability for Triton on SM to handle the model artifact within two locations i.e. both `/opt/ml/models/<hash>/model` as well as `/opt/ml/models/<hash>/model/<model_subdir>`. The second one is useful if the customer is re-using a model after trying it in SME mode.
> Re-throw certain specific OOM errors as 507 for SageMaker MME + repo path enhancement

- build.py
Added this as a part of work on a bug. Might do so for some other backends if required in future.
See linked PR here: https://github.com/triton-inference-server/pytorch_backend/pull/64
> Enable nvtx markers in pytorch backend

- qa/L0_perf_nomodel/run_test.sh
- qa/L0_perf_nomodel/test.sh
- qa/L0_perf_resnet/run_test.sh
- qa/L0_perf_resnet/test.sh
> Add triton_c_api to perf tests

- docs/model_configuration.md
- qa/L0_backend_config/test.sh
- Updated L0_backend_config test to include backends which make use of the default-max-batch-size parameter.
- Updated the documentation to declare which backends make use of this feature.
> Autocomplete is Used by Triton Supported Backends

- docs/rate_limiter.md
According to "The available number of resource copies are, by default, the max across all model instances that list that resource."
"R4: 7" should change to "R4: 5"
> Correct number of resource copies for R4

- qa/common/gen_qa_custom_ops
Fix the PTX error if the op is compiled with newer CUDA version and used with older CUDA version.
Before:
```
graphdef_busyop | 1       | UNAVAILABLE: Internal: unable to create stream: the provided PTX was compiled with an unsupported toolchain.
```
After:
```
graphdef_busyop | 1       | READY
```
> Build testing custom op with backward compatibility

- deploy/mlflow-triton-plugin/examples/onnx_float32_int32_int32/config.pbtxt
- qa/L0_mlflow/plugin_test.py
- qa/L0_mlflow/test.sh
Followup for https://github.com/triton-inference-server/server/pull/4413
> Add test for different variance of ONNX flavor

- deploy/mlflow-triton-plugin/mlflow_triton/deployments.py
Add `config_path` key to `copy_paths` to avoid `KeyError` when deploying from mlflow models in **onnx** flavor with `config.pbtxt`
> fix error when deploying a model from mlflow

- qa/L0_output_validation/lt_op_val_client.py
With the new PyTorch naming convention the model loads properly but the inference fails. Updated the error message check so that the test passes.
> Fix L0_output_validation test

- docs/protocol/extension_trace.md
GitHub's markdown renders the trace_file examples as math, so the text is difficult to read. I wasn't able to find a way to escape the dollar signs, so I wrapped them as an in-line code block for readability.
> Fix Trace Documentation Rendering

- src/shared_memory_manager.cc
Protect GetMemoryInfo and GetCUDAHandle with mutex to avoid race condition when the map information is being accessed.
> Protect shared_memory_map_ from concurrent access

- build.py
Currently, `build.py` script specifies `DALI_VERSION` variable to be set using environment variable. However, in https://github.com/triton-inference-server/dali_backend/pull/133, DALI Backend changed the way of setting the version of DALI which it builds against. Right now, DALI Backend includes a [DALI_VERSION file](https://github.com/triton-inference-server/dali_backend/blob/main/DALI_VERSION) and this file is going to specify the DALI version required for the build. We changed this, because of practical reasons: since DALI C/C++ APIs are yet experimental, there might happen a situation, when DALI last minute changes the API, which is result will break DALI Backend. We want to be able to manually control DALI version. In general, in DALI Backend we are going to keep the latest DALI, but …
> Remove `DALI_VERSION` from `build.py`

- qa/L0_perf_analyzer_report/test.sh
Looks like L0_perf_analyzer_report broke in this commit (https://github.com/triton-inference-server/server/commit/9460c753a82b76d80f0a91f1ebe265f94fd7cdb6) because of unescaped newlines. 
Used commas instead of newline for simplicity, and added `-e` to the echo's to avoid similar errors in the future.
> Fix unescaped newline in L0_perf_analyzer_report

- qa/L0_lifecycle/lifecycle_test.py
- src/grpc_server.cc
- src/http_server.cc
Prefix logs with the request ID, where possible.
Related changes:
Backend: https://github.com/triton-inference-server/backend/pull/60
Core: https://github.com/triton-inference-server/core/pull/85
> Prefix Logs with Request ID

- qa/L0_model_config/cli_messages/cli_deprecation/expected
- qa/L0_model_config/cli_messages/cli_override/expected
- qa/L0_model_config/test.sh
- src/main.cc
This PR adds a warning on startup for the user if they are using the now deprecated `--strict-model-config` flag. Additionally, we add a warning that the `--disable-auto-complete-config` flag will be used instead of the `--strict-model-config` if both are provided and they contradict. In the event the two options are in agreement, then the user only gets the deprecation warning.
> Resolve disable-auto-complete-config and strict-model-config conflict

- src/http_server.cc
When the data type is BYTE, `JsonBytesArrayByteSize` function is called to calculate the expected byte size. The calculation uses depth-first search (DFS) to finds each characters from the input, no matter how "deep" they are nested within the dimensions, and greedily sums the byte size along the search. The function calls itself iteratively to complete the DFS.
The original search function will initialize the byte size to 0 whenever it is called. This is incorrect as when the DFS switches branch, the byte size from the previous branch is discarded. The updated search function fixes the re-initialization bug.
For example, the original function calculates `['a', 'b']` correctly as there is no nested array, and also `[['a', 'b']]` correctly as there is no branch switch, but `[['a'], ['b']]` …
> Fix expected byte size calculation

- docs/perf_analyzer.md
Closes https://github.com/triton-inference-server/server/issues/4674
> Add a note about string data type when using base64

- qa/L0_lifecycle/lifecycle_test.py
- qa/L0_lifecycle/test.sh
- qa/L0_nan_inf/models/nan_inf_output/1/model.py
- add new test to assert failure on loading non-existing startup (`--load-model`) model
- update lifecycle test to expect existing models to still be ready in model control mode after a failed load of the same model
- unused var cleanup
> Lifecycle test fixes

- qa/L0_perf_analyzer/test.sh
- qa/L0_perf_analyzer_capi/test.sh
- qa/L0_perf_analyzer_ground_truth/test.sh
- qa/L0_perf_analyzer_report/test.sh
Some PA tests were failing to stabilize due to a past enhancement to the stability calculation ([#111](https://github.com/triton-inference-server/client/pull/111)), which caused the CI test to fail. This ensures that PA CI tests are less likely to need to be rerun. Eventually, we can implement a version of PA that doesn't check for stability (and instead runs normally to allow us to test whatever else is intending to be tested) to avoid this issue.
> Fix PA test stability

- src/tracer.cc
Fix issue [4636](https://github.com/triton-inference-server/server/issues/4636).
The JSON byte tensor data output **before fix**: 
```
[
{
"id":1,
"activity":"TENSOR_QUEUE_INPUT",
"tensor":{"name":"inputs","data":""a","b"","shape":"2,1","dtype":"BYTES"}
},
{
"id":1,
"activity":"TENSOR_BACKEND_OUTPUT",
"tensor":{"name":"input_ids","data":"97,98","shape":"2","dtype":"INT32"}
}
]
```
Notice the `TENSOR_QUEUE_INPUT` `tensor` `data`, `""a","b""`, is invalid.
**After fix**:
```
[
{
"id":1,
"activity":"TENSOR_QUEUE_INPUT",
"tensor":{"name":"inputs","data":"\"a\",\"b\"","shape":"2,1","dtype":"BYTES"}
},
{
"id":1,
"activity":"TENSOR_BACKEND_OUTPUT",
"tensor":{"name":"input_ids","data":"97,98","shape":"2","dtype":"INT32"}
}
]
```
```
$ cat trace.json | jq
[
{
"id": 1,
"activity": …
```
> Escape double quote for trace JSON byte tensor data output

- docs/README.md
- docs/performance_tuning.md
- docs/walkthrough.md
Context is to give users a clear path from taking their trained model to deploying it optimally/at-scale with Triton.
> Add end-to-end config tuning doc

- docs/model_repository.md
Adds documentation for using the cloud storage credential file. The [core PR](https://github.com/triton-inference-server/core/pull/103) does the change.
> Add cloud storage credential management

- README.md
The previous Url https://github.com/triton-inference-server/backend/docs/backend_platform_support_matrix.md
is a broken link.
> fix: update link to backend_platform_support_matrix.md

- build.py
This little fix allows to build `tritonserver` docker image on MacOS with M-series chip. 
Actually in MacOS with arm chip `arch` command will return `arm64`, while on linux its returns `aarch64`, it's broke *miniconda* installing, because they have no install script for `Linux-arm64`.
> Fix MacOS ARM docker building

- compose.py
After upgrading openvino to 2022.1, the `build.py` no longer requires tagged openvino backend. This PR removes the tagged openvino backend from `compose.py` as well.
> Remove tagged openvino backend

- qa/L0_infer/infer_test.py
- qa/L0_infer/test.sh
- qa/common/check_valgrind_log.py
- qa/common/infer_util.py
Related PRs:
common: https://github.com/triton-inference-server/common/pull/67
backend: https://github.com/triton-inference-server/backend/pull/67
tensorrt_backend: https://github.com/triton-inference-server/tensorrt_backend/pull/44
> Increase SERVER_TIMEOUT for L0_infer_valgrind

- docker/sagemaker/serve
SM customers cannot specify TF version since Triton only supports switching via cmdline, related issue: https://github.com/aws/deep-learning-containers/issues/2176
Adding this environment variable to allow specifying TF version as default when starting Triton via the serve script.
> Add environment variable in SM entrypoint to specify TF version

- qa/common/gen_qa_model_repository
TensorRT removed their custom clip plugin sample, so this ticket switches model generation to use their 8.4 Release code. I checked with an engineer on their team and they don't foresee issues. They should be providing a new custom plugin sample in an upcoming TensorRT release.
> [Temporary Fix] TensorRT Plugin Generation

- docs/README.md
- docs/customization_guide/build.md
- docs/customization_guide/inference_protocols.md
- docs/getting_started/quickstart.md
- docs/user_guide/architecture.md
- docs/user_guide/decoupled_models.md
- docs/user_guide/faq.md
- docs/user_guide/metrics.md
- docs/user_guide/model_configuration.md
- docs/user_guide/model_management.md
- docs/user_guide/model_repository.md
- docs/user_guide/optimization.md
- docs/user_guide/perf_analyzer.md
- docs/user_guide/performance_tuning.md
- docs/user_guide/response_cache.md
- docs/user_guide/trace.md
- docs/user_guide/v1_to_v2.md
Used [markdown-link-checker](https://github.com/tcort/markdown-link-check) to scrape through the docs for broken links.
example:
```bash
for f in $(ls); do 
docker run -v ${HOME}:/mnt:ro --rm -i ghcr.io/tcort/markdown-link-check:stable /mnt/triton/main/server/docs/user_guide/$f 
echo -e "\n===============\n===============\n"; 
done
```
I'm sure links in other repos will be broken as well and should be fixed.
> Fix broken links after refactor

- build.py
Use special ORT branch 'tensorrt-8.5ea' brought in by the ORT 1.12.1 release to make use of the built-in tensorrt parser. 
See corresponding PR in onnxruntime_backend for more details.
> Use special ORT branch 'tensorrt-8.5ea' brought in by the ORT 1.12.1 release to make use of the built-in tensorrt parser.

- build.py
Reverts triton-inference-server/server#4816
> Revert "Use special ORT branch 'tensorrt-8.5ea' brought in by the ORT 1.12.1 release to make use of the built-in tensorrt parser."

- docs/user_guide/response_cache.md
Looks like beta tag was re-added in the doc rework PR accidentally, so removing it again.
> Remove beta tag from cache doc

- src/grpc_server.cc
- src/http_server.cc
Initialize local request ID to empty string. This is to prevent null pointers from being accessed.
> Initialize Local Request ID to Empty String

- qa/L0_client_memory_growth/test.sh
- qa/L0_client_valgrind/test.sh
- qa/common/check_valgrind_log.py
After upgrading OpenVINO from 2021.x to 2022.1, `InferenceEngine` is no longer used by the openvino_backend, so the memory leak from 2021.x is no longer an issue.
> Remove OpenVINO from mem leak whitelist

- build.py
Most of the CLI options work fine as they are.
Some findings which are fixed in this PR:
1. The `pull/` prefix is not working only when using `--repo-tag` option. It seems to work with `--backend` and `--repoagent` option.
2. When running the script with `--no-core-build` option, the build fails when building the `tritonserver_cibase` image due to some missing directories.
> Update the comment for the limitations of build.py script

- src/http_server.cc
> Solve the problem of Chinese garbled characters when using custom metrics.

- build.py
**OBSERVATIONS:**
Triton server uses `build.py` to generate `Dockerfile` for CPU only builds.
One of the steps for it is the `COPY` library dependencies.
As of now those library dependencies are using version specific path instead of using CUDA defined symlinks with [alternatives](https://linux.die.net/man/8/alternatives) .
**HYPOTHESIS**
Change hardcoded version values to the defined alternatives.
**BENEFITS:**
Triton server build became less version agnostic
> Using alternative managed symbolic links  for library paths

- qa/common/trace_summary.py
Fixes: #4720 
Added support for splitting strings in `get_numpy_array` using python csv import, example 
```
>>> import csv
>>> next(csv.reader(['"3", "a, b", "C"'], skipinitialspace=True))
['3', 'a, b', 'C']
```
> fix: Update to support parsing string tensor data

- qa/L0_metrics/test.sh
The CPU utilization metric has occasionally been failing the L0_metrics test by having duplicate values. This can be expected to happen if the server is either not doing much work or doing some consistent work. I propose adding some tolerance for number of duplicate values for the utilization and memory metrics. They will still fail the test if consistently returning the same value for more than the defined tolerance (50%).
> Add tolerance to cpu metrics test

- qa/L0_lifecycle/lifecycle_test.py
- qa/L0_lifecycle/test.sh
Add a case to L0_lifecycle to ensure a speedup is observed when two models are loading in parallel.
Core PR: https://github.com/triton-inference-server/core/pull/137
> Add concurrent loading speedup test

- Dockerfile.win10.min
Cherry-picked Misha's commit since the updated windows base container should resolve the docker build issue: https://github.com/triton-inference-server/server/issues/4981
> Update Windows dockerfile

- qa/L0_simple_go_client/test.sh
Update Go test to generate Go stubs and packages from the client repository. This makes it so that we have one source of truth (the client script).
This PR updates the testing so that the changes in [this client PR](github.com/triton-inference-server/client/pull/138) do not break the L0_simple_go_client test.
> Update Go Test

- compose.py
Triton has backends that are not shipped with the official containers such as
[FasterTransformer Backend](https://github.com/triton-inference-server/fastertransformer_backend).
This PR allows `compose.py` to use local images so users can further decrease the size of the images
with these more customized backends.
Use case: 
`python3 compose.py --backend pytorch --backend fastertransformer --image full,triton_with_ft:22.11 --image gpu-min,nvcr.io/nvidia/tritonserver:22.11-py3-min --image min,nvcr.io/nvidia/tritonserver:22.11-py3-min --skip-pull`
> Add skip-pull flag to allow local build

- docs/protocol/extension_shared_memory.md
Document in the shared-memory extension documentation that there is currently no support in Windows and only system shared memory support on Jetson.
> Document systems where shared memory supported

- qa/L0_storage_S3_local/test.sh
There was a recent version update on the MinIO server (RELEASE.2023-01-02T09-40-09Z), which seems to have caused the server failed to start. Changing the server address from localhost:4572 to 127.0.0.1:4572 solved the issue.
> Use ip for minio server address

- docs/user_guide/model_configuration.md
- qa/L0_batch_custom/test.sh
This PR builds on #5177. For custom batching where the user defines additional constraints for the dynamic batcher, this PR allows the user to call two new optional functions that initialize and finalize once. This allows them to create a cached object that can be read for every batch without needing to be re-initialized.
An example use case is where the user needs to read a value from the model config for batching, so they would only want to read it from the config once and save it to use with their custom batch-handling logic. See volume_batching.cc in this PR as an example.
The server PR documents these two new functions.
Backend: https://github.com/triton-inference-server/backend/pull/76
Core: https://github.com/triton-inference-server/core/pull/149
> Document custom batching cache functions

- qa/L0_perf_analyzer/test.sh
We always get errors saying test failed to stabilize, but it's not necessary to stabilize to verify what the test wants to verify, so, if we increase stability threshold to 100, we skip the stabilization check, which was unnecessary anyway.
> Increase PA test stability threshold

- Dockerfile.sdk
Previously we were using  head of master on javacpp-presets to build tritonserver. This caused an error when Javaccp-presets repo transitioned to a full version (thus removing their *-snapshot from the maven repo). Now we can use the actual build
> Update Javacpp-presets build to use version tag instead of head of master

- qa/L0_client_memory_growth/test.sh
- qa/L0_memory_growth/test.sh
Currently we're checking the return code of `TEST_DURATION=${SECONDS}` in the example below:
```
valgrind --tool=massif memory_growth_test ...
TEST_DURATION=${SECONDS}
if [ $? -ne 0]; then
...
fi
```
which is just a variable assignment and will always succeed.
This change makes sure we check the return code of the actual valgrind test on the line above:
```
valgrind --tool=massif memory_growth_test ...
TEST_RETCODE=$?
TEST_DURATION=${SECONDS}
if [ ${TEST_RETCODE} -ne 0]; then
...
fi
```
Occasionally seeing the following error in the `client_memory_growth.http.c++` section of `L0_client_memory_growth` test
> Failed to update context stat: Timer not set correctly. Send time from 1672873758293288720 to 0.
> error: unable to run model: failed to parse the request JSON buffer: The document is …
> Fix checking of return code from memgrowth tests

- deploy/gke-marketplace-app/README.md
- deploy/gke-marketplace-app/server-deployer/chart/triton/values.yaml
- deploy/gke-marketplace-app/server-deployer/data-test/schema.yaml
- deploy/gke-marketplace-app/server-deployer/schema.yaml
Provide the fix since GKE depreciate the istio on GKE so we manually install. 
Also change the github repo to a static GCS public bucket with example models before we fix the bert pipeline which generate TRT engine for different version of Triton.
> new instruction for GKE marketplace app

- qa/L0_trt_reformat_free/test.sh
Perf_client is no longer used in L0_trt_reformat_free, so this PR removes its variable.
> Remove unused variable in L0_trt_reformat_free

- qa/L0_tf_gpu_io/test.sh
- qa/L0_tf_gpu_io/tf_gpu_io_test.py
- qa/common/infer_util.py
Perf_client was being used to generate requests in l0_tf_gpu_io. This PR decouples the test from perf_client. Instead one request is sent to Triton server then logs are examined, speeding up this test and removing for the dependency on perf_client.
> Refactor L0_tf_gpu_io to remove perf_client dependency

- Dockerfile.QA
- qa/common/util.sh
Help to better debug server hangs moving forward by capturing relevant backtrace rather than having to try to reproduce locally each time.
To demonstrate if it works or not, I added an intentional deadlock in `model_lifecycle.cc` on model load. Here's the output from the test. Note that even for a RELEASE build this helps point to an issue in core:
```
Thread 1 (Thread 0x7f80077f3000 (LWP 638148)):
#0  __lll_lock_wait (futex=futex@entry=0x5581ab4f1980, private=0) at lowlevellock.c:52
#1  0x00007f8008ec60a3 in __GI___pthread_mutex_lock (mutex=0x5581ab4f1980) at ../nptl/pthread_mutex_lock.c:80
#2  0x00007f80088892c6 in triton::core::ModelLifeCycle::AsyncLoad(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, …
```
> Add gdb backtrace to qa tests when server fails to start within timeout

- docker/sagemaker/serve
- qa/L0_sagemaker/test.sh
- src/sagemaker_server.cc
- src/sagemaker_server.h
1. Enable verbose logging by default, customers can still disable it by specifying `SAGEMAKER_TRITON_LOG_VERBOSE`:`false`.
2. Added more strings for OOM checker to detect, in order to return 507
3. Changed /ping health check to rely on 'live', instead of 'ready' to handle SageMaker corner cases where it expects model server to react with '200' for /ping even if model load has failed separately for some other models, whereas has succeeded for others and are ready to be served. (difference of 'live'/'ready' is found in kserve description - https://github.com/kserve/kserve/blob/master/docs/predict-api/v2/rest_predict_v2.yaml#L10-L26)
> Improvements to SM server and entrypoint

- qa/common/util.sh
If the process doesn't exist (example: a test that expects server startup to fail, but not hang), then the gdb commands will fail that the PID doesn't exist and that error will propogate to fail the test. 
Add `|| true` to the commands since its OK if these commands fail for whatever reason and shouldn't alter the test result.
> Allow gdb commands to fail if process doesn't exist

- qa/L0_libtorch_io_names/test.sh
- qa/L0_libtorch_io_types/test.sh
Add test that verify the server will not start with unsupported PyTorch data type (e.g. uint64) in the config.pbtxt.
Related PR: https://github.com/triton-inference-server/pytorch_backend/pull/93
> Add libtorch data type test

- build.py
This will use 22.12 container for ORT backend build by default so the user doesn't have to explicitly provide it as an option in build.py.
See the discussion in this issue here: https://github.com/triton-inference-server/server/issues/5309
> Adding default base container for ORT backend build

- qa/python_models/torchvision/resnet50/config.pbtxt
- qa/python_models/torchvision/resnet50/model.py
This PR adds 2 files, required by a python backend for the test.
To enhance model control stress test to check memory growth for Python models, `model.py` initializes a ResNet50 model with the best weights available in `torchvision.models` subpackage.
`config.pbtxt` describes the model's configuration.
> Updating model control stress test to add python backend

- build.py
FIL backend fails debug build as described in DLIS-4618, so override the build type flag for FIL.
> Add --build-type exception for FIL backend

- docs/user_guide/response_cache.md
Redis implementation likely won't be finished/tested for the 23.03 release, so remove it for now. I'll add it back once redis is properly finished and integrated.
> Remove redis mentions until finished

- docker/sagemaker/serve
- src/sagemaker_server.cc
- src/sagemaker_server.h
This PR updates the behavior of SageMaker UNLOAD function to use the repository index and verify that the model has been completely UNLOADED to the best of Triton's ability i.e. the model _state_ is `UNAVAILABLE` and the _reason_ is `unloaded`.
This (at least in case of python backend) ensures that the function returns only after the associated python workers for the models have been killed.
> Add timed wait during UNLOAD while the model becomes UNAVAILABLE in SageMaker

- qa/L0_backend_python/examples/test.sh
https://github.com/triton-inference-server/python_backend/pull/209 adds adds example, showing how to integrate KIND_GPU/KIND_CPU with the Python model.
This PR adjusts L0_backend_python/examples/test.sh to make sure added example is verified.
> Adding test for Model Instance Kind Example added to Python Backend

- qa/L0_infer/infer_test.py
- qa/L0_infer/test.sh
Python models: Doesn't cause server hanging, only has OOM issue when loading all models at once.
Onnx models: It takes about 12 hours to load all the models. At some point the server stuck for a while when this [line](https://github.com/microsoft/onnxruntime/blob/rel-1.13.1/include/onnxruntime/core/common/spin_pause.h#L22) is called, but it will resume eventually. Reduce the instance count and the number of models being loaded help with the case.
Hence, modify to test with python and onnx models in separate runs.
> Add onnx and python models back to L0_infer_valgrind test

- qa/L0_backend_config/test.sh
This PR adds tests to check edge cases for backend configuration resolution.
Current logic for backend config resolution sorts default configs and specific configs lexicographically. Then it iterates through them  and prioritizes backend specific config over the default one.
We would like to make sure that in the following situation (example)
```
specific_config = {"a":4}
default_config = {"b":5,"c":6,"d":7}
```
"c" and "d" are not lost.  
And in the following situation
(example)
```
specific_config = {"x":4, "y":5, "z":9}
default_config = {"b":5,"c":6,"d":7}
```
"y" and "z" are not lost.
> Fixing issue in ResolveBackendConfigs

- qa/L0_trt_reformat_free/trt_reformat_free_test.py
- qa/common/gen_qa_implicit_models.py
- Catch uninitialized variable in trt_reformat_free and use if/elif/else instead of separate if statements
- In gen_qa_implicit_models, combine if/else statements to minimize number of checks and improve flow for readability
> Small refactoring (if/else paths)

- .github/workflows/codeql.yml
Increase codeql static analysis run frequency. Run daily on Sunday-Friday, 6pm PST. (Interpreted in UTC: 1am Monday-Sunday).
> Update codeql run frequency

- qa/python_models/torchvision/resnet50/model.py
To make sure `ResNet50` model is loaded and compatible with `torchvision=0.14`, that we are using in tests, torch hub needs a proper tag.
> Adding repo tag to torch.hub.load to fix compatibility issues

- docker/sagemaker/serve
This issue was recently addressed: https://github.com/triton-inference-server/server/issues/5150, one of the associated PRs is - https://github.com/triton-inference-server/server/pull/5362/files.
This change requires that `--model-namespacing=true` option be added to the tritonserver start command. Adding it to the SageMaker entrypoint script that specifies the start command.
> Enable model namespacing in SageMaker entrypoint

- qa/common/gen_qa_dyna_sequence_implicit_models.py
- qa/common/gen_qa_dyna_sequence_models.py
- qa/common/gen_qa_identity_models.py
- qa/common/gen_qa_implicit_models.py
- qa/common/gen_qa_models.py
- qa/common/gen_qa_ragged_models.py
- qa/common/gen_qa_reshape_models.py
- qa/common/gen_qa_sequence_models.py
- qa/common/gen_qa_trt_data_dependent_shape.py
- qa/common/gen_qa_trt_format_models.py
- qa/common/gen_qa_trt_plugin_models.py
New usage requires:
[set_memory_pool_limit](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/BuilderConfig.html#tensorrt.IBuilderConfig.set_memory_pool_limit) (pool: tensorrt.tensorrt.MemoryPoolType, pool_size: int)
pool: [tensorrt.tensorrt.MemoryPoolType](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/BuilderConfig.html?highlight=tensorrt%20tensorrt%20memorypooltype#tensorrt.MemoryPoolType) was set to `trt.MemoryPoolType.WORKSPACE`, since according to api docs : 
> WORKSPACE is used by TensorRT to store intermediate buffers within an operation. This is equivalent to the deprecated IBuilderConfig.max_workspace_size and overrides that value.
> Removing deprecated usage of  config.max_workspace_size in favor of config.set_memory_pool_limit

- src/http_server.cc
- src/test/distributed_addsub/src/distributed_addsub.cc
I intend on using the Triton Inference server on 3 devices (amd64, arm64 and arm/v7). After trying to build the server for my arm/v7 device, I noticed that there where casting errors. I realized that I needed to make similar fixes in the backend and core repositories as well. Once all the casting issues have been solved in the 3 repos, I was able to correctly run inferences on all three of my devices.
> Adding the fixes for arm32

- qa/L0_implicit_state/implicit_state.py
Test `assertEquals` was broken by addition of status code to exception string output: https://github.com/triton-inference-server/client/pull/278/files
Use `str.lower()` and [assertIn](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertIn) over assertEquals to be more resilient to minor string format changes
> Make string checks more resilient to minor format changes in L0_implicit_state

- src/command_line_parser.cc
- src/command_line_parser.h
Preliminary changes to expose config settings. These will be used to opt-in and toggle future metrics features.
Below are just rough ideas of things that would be configured based on user feedback, not the exact set of args we will necessarily support. We can roll out functionality in stages based on feedback and priorities.
Example (settings/values TBD): 
```
tritonserver --metrics-config summaries=all 
tritonserver --metrics-config summaries=true
tritonserver --metrics-config summaries=*   (similar to --load-model support)
tritonserver \
--metrics-config summaries=all
--metrics-config summary_quantiles=0.5, 0.75, 0.9, 0.95, 0.99, 0.999
tritonserver --metrics-config summaries=compute
tritonserver \
--metrics-config histograms=all 
--metrics-config histogram_buckets=0.01, 0.1, 1, 10, 100, …
```
> Add metrics config CLI

- qa/L0_implicit_state/implicit_state.py
Follow-up to https://github.com/triton-inference-server/server/pull/5588, I missed one subtest in the last PR.
This branch is now passing locally:
```
***
*** Test Passed
***
+ exit 0
***
*** Implicit State Passed
***
```
> Fix L0_implicit_state 

- qa/L0_rate_limiter/test.sh
Would help understand these failures seen on the CI.
```
+ '[' 0 '!=' 0 ']'
+ grep 'Resource count for "resource1" is limited to 1 which will prevent scheduling of one or more model instances, the minimum required count is 4' ./inference_server_r1.log
++ RV=1
++ set +x
sha256:6f73d21c0193dbe9f3d82f924304824dcdaa5ad7d8597fcf8fcf9344c6492898
```
> Increase the test verbosity for better visibility into inconsistent failures

- qa/L0_backend_python/lifecycle/lifecycle_test.py
Fixed the check for the error message as the returned error message starts with some error code, `[400] Failed to process the request(s)...`, which failed the check `str(e.exception).startswith`
> Fix L0_backend_python lifecycle test

- qa/L0_logging/test.sh
Update the expected numbers to address the table printing of gRPC keepalive paramteres:
```
> I0410 23:12:55.866256 288 grpc_server.cc:4888] === GRPC KeepAlive Options ===
> I0410 23:12:55.866268 288 grpc_server.cc:4889] keepalive_time_ms: 7200000
> I0410 23:12:55.866272 288 grpc_server.cc:4891] keepalive_timeout_ms: 20000
> I0410 23:12:55.866275 288 grpc_server.cc:4893] keepalive_permit_without_calls: 0
> I0410 23:12:55.866279 288 grpc_server.cc:4895] http2_max_pings_without_data: 2
> I0410 23:12:55.866283 288 grpc_server.cc:4897] http2_min_recv_ping_interval_without_data_ms: 300000
> I0410 23:12:55.866286 288 grpc_server.cc:4900] http2_max_ping_strikes: 2
```
```
< I0410 22:56:34.139461 1317 grpc_server.cc:2344] 
< +----------------------------------------------+---------+
< | GRPC …
```
> Fix L0_logging with new number of logs

- qa/common/infer_util.py
Previously, both CUDA and system shared memory were imported if either was being tested. Fix the conditionals to only import each type of memory if it is being tested.
> Separate CUDA and system shared memory imports in infer utils

- qa/L0_perf_nomodel/run_test.sh
After shared memory validation was added to perf client [here](https://github.com/triton-inference-server/client/commit/1dab8821644c05c2f971be3108585b83e0d0c083), it made it clear that shared memory is not being correctly parsed in this test. An error is not returned, so it does not affect test results (we should look into checking for this later). However, this fix will allow perf_client to run.
> Remove extra quotes for shared memory in test

- docs/user_guide/model_management.md
- src/command_line_parser.cc
- src/command_line_parser.h
On systems with large core counts, this default is too large. In fact, it is causing issues on OCI nodes hitting resource limits.
4 should be a comfortable default for the average use case or simple ensemble cases (preprocess, infer, postprocess) - and users who knowingly need high load concurrency can increase via CLI flag. 
Corresponding core PR: https://github.com/triton-inference-server/core/pull/193
We should rel note this change in 23.05 as well. CC @nv-kmcgill53
> Reduce default --model-load-thread-count to 4

- qa/L0_sequence_batcher/test.sh
- qa/common/sequence_util.py
Since responses are sent before inference statistics are reported, there is the risk that statistics are checked before they are ready. This may be the cause of L0_sequence_batcher failing infrequently with statistics missing one request, with messages like:
```
Traceback (most recent call last):
File "sequence_batcher_test.py", line 577, in test_no_sequence_end
self.check_status(model_name, {1: 4 * (idx + 1)},
AssertionError: 7 != 8 : expected model-execution-count 8 for batch size 1, got 7
```
Only in the case that sequence batcher is going to fail due to not having enough requests ready, this change will provide up to 10 seconds in .5 second increments for the requests to be ready.
> Give sufficient time to get inference statistics for sequence tests

- src/command_line_parser.cc
- src/command_line_parser.h
**Note**, I'm going to wait for the Open Telemetry PRs to be merged before this, to avoid merge conflicts in those branches. However, ready for high level review.
This is another step in the direction of sectioning the CLI parser into groups. For now, I just want to make the `help/usage` output more legible without spending too much time on the refactor, so didn't go as far as creating separate Parser classes for each. However, something along those lines could be added on top of this in the future as the config groups have been separated out.
Example outputs below:
---
<details>
<summary>
Example minimal output with many features disabled:
```
cmake -D CMAKE_INSTALL_PREFIX=install -D TRITON_CORE_HEADERS_ONLY=ON -D TRITON_ENABLE_TRACING=OFF -D TRITON_ENABLE_LOGGING=OFF -D …
```
> Categorize tritonserver CLI options into groups

- qa/L0_perf_deeprecommender/run_test.sh
- qa/L0_perf_nomodel/run_test.sh
- qa/L0_perf_resnet/run_test.sh
- Add higher --max-trials default with configurable env var
- Print timestamps periodically to help debug timeouts
Per https://github.com/triton-inference-server/server/pull/5673#discussion_r1173179521
> Add higher --max-trials to L0_perf tests with configurable PA_MAX_TRIALS var

- qa/L0_batcher/batcher_test.py
L0_batcher occasionally fails with a similar error to that seen in L0_sequence_batcher seen [here](https://github.com/triton-inference-server/server/pull/5670). Proposing a similar fix to ensure the test does not check statistics before they are ready.
> Give sufficient time to get inference statistics for batcher tests

- qa/L0_model_config/autofill_noplatform/tensorflow_savedmodel/too_many_inputs/config.pbtxt
- qa/L0_model_config/autofill_noplatform/tensorflow_savedmodel/unknown_input/expected
TensorFlow backend changes: https://github.com/triton-inference-server/tensorflow_backend/pull/92
> Update the L0_model_config test to align with the auto-complete changes made to the TensorFlow backend

- qa/L0_client_memory_growth/test.sh
Corresponding client PR that implements test fixes: https://github.com/triton-inference-server/client/pull/303
> Add notes to L0_client_memory_growth test

- qa/L0_trt_error_propagation/trt_error_propagation_test.py
It is observed that TensorRT might update their internal error messages. This PR is to enable checking TensorRT error message only on its critical parts, rather than trying to match the entire TensorRT error message.
> Check TensorRT error message more granularly

- qa/L0_batch_custom/batch_custom_test.py
- qa/L0_batch_custom/test.sh
- qa/L0_optional_input/optional_input_test.py
- qa/L0_trt_shape_tensors/trt_shape_tensor_test.py
- Test that the full user-provided error (type, message) is returned when the custom batcher fails to initialize
- While working on this ticket, I saw the model-execution failure that's been fixed [previously](https://github.com/triton-inference-server/server/pull/5699) in other tests, so I copied the fix over to the utils used in this one as well as the remaining ones. Since they all have slightly different functions, I left them in their respective test files rather than trying to centralize the check_status functions.
Related core PR: https://github.com/triton-inference-server/core/pull/196
> Test full error returned when custom batcher init fails

- qa/L0_socket/test.sh
- src/command_line_parser.cc
- src/command_line_parser.h
1. Add `--metrics-address` to support configuring a unique metrics address, even with TRITON_ENABLE_HTTP=OFF in the build. 
Note I made a conscious choice here to add `--metrics-address` as a new CLI arg rather than adding it to `--metrics-config` such as `--metrics-config address=<address>`. 
This is because:
- (a) I think for now, `--metrics-config` will be for Core-side metrics configuration, whereas the `--metrics-address` are server-side configurations.
- (b) This more intuitively matches existing `--metrics-port`, `--http-address`, `--grpc-address` args for users.
Down the line I think we should deprecate and move any non-server-side metrics configs like `--metrics-interval-ms` to be part of `--metrics-config`.
---
2. This PR also reorganizes some of the other similar args to be in …
> Add --metrics-address and testing

- qa/L0_grpc/grpc_basic_auth_test.py
- qa/L0_grpc/nginx.conf
- qa/L0_grpc/test.sh
- qa/L0_http/http_basic_auth_test.py
- qa/L0_http/nginx.conf
- qa/L0_http/test.sh
Client: https://github.com/triton-inference-server/client/pull/310
> Add testing for basic auth plugin for HTTP/gRPC clients

- src/sagemaker_server.cc
Small note update in Sagemaker integration. Note explains that Ensemble model is not supported. However code does parse for ensemble correctly and seems to support it as far as the code goes.
Note caused some confusion which led to us having to parse more code to understand what was the behaviour of sagemaker MME when using triton for ensemble models. 
I wrote some update on note to clarify actual code behaviour.
> Update note on SageMaker MME support for ensemble

- Dockerfile.QA
- qa/L0_backend_python/decoupled/test.sh
- qa/L0_backend_python/io/test.sh
- qa/L0_backend_python/test.sh
This PR updated the subtests in L0_backend_python to be run using a virtual environment. This was done to prevent any dependencies from interfering with each other during the installation of dependencies in each test. Reverted the test order changes in this PR https://github.com/triton-inference-server/server/pull/5607 and the JAX example ran successfully.
> Run L0_backend_python subtests with virtual environment

- qa/L0_custom_ops/test.sh
Fix L0_custom_ops for ubuntu 22.04.
We have upgraded to python 3.10 from python 3.8. the .so file needed to be updated.
> Fix L0_custom_ops

- qa/L0_model_update/instance_update_test.py
- qa/L0_model_update/test.sh
Changes: 
- Add test(s) for model instance name update. [Add model instance name update test](https://github.com/triton-inference-server/server/pull/5724/commits/a14ad288a8b4b5d529e22c8f4c6c9ce4953c90fa)
- Any changes to a file on disk should be fully written to disk before the modification function returns. [Add gap for timestamp to update](https://github.com/triton-inference-server/server/pull/5724/commits/e336d037ab93b9db2a41d3f0052cac0a02f849d8) (Passed 100+ iterations)
- For supported test cases, the test should cover starting the server with rate limiter off. [Extend supported test on rate limit off](https://github.com/triton-inference-server/server/pull/5724/commits/2fc3a18ce0bbc1c3913e8a933b98aee2bf947966)
- Add some tests with dynamic batching on. [Add some tests with dynamic …
> Enhance tests in L0_model_update

- qa/L0_memory_growth/test.sh
1. reduce MAX_ALLOWED_ALLOC to 100MB to be more strict for bounded tests, and generous for unbounded tests. Many failures were due to the unbounded test only reaching 110-130MB of usage, not > 150MB. Also, the bounded tests are typically only using 20-70MB depending on framework, so I think it's valuable to make the bounds tighter to catch growths/regressions.
2. allow unstable measurement from PA: same old here
3. improve logging for future triage: try to add memory usage to job log for every test so it's easier to see at a glance what each framework is roughly using if this test has to be modified in the future.
> Fix L0_memory_growth

- qa/L0_perf_analyzer/test.sh
Adding new test to cover new sequence mode
> Adding test for new sequence mode

- qa/L0_mlflow/test.sh
This PR fixes mlflow failing when installing python test dependencies. The `python3-blinker` default installed version is `1.4` but the python dependencies need version `1.6` installed. Removing the default installed version of blinker which comes with Ubuntu 22.04 allows pip to install the necessary dependencies.
> Fix L0_mlflow

- qa/L0_http_fuzz/test.sh
Adding back in pip install of boofuzz library into the devel container. 
Git blame on the main branch says this was added 2 years ago. @mc-nv is there a reason why this was deleted before?
> Fix L0_http_fuzz

- qa/L0_storage_S3/test.sh
- qa/L0_storage_S3_local/test.sh
Related PR: https://github.com/triton-inference-server/core/pull/205
> Add error message test on S3 access decline

- qa/L0_storage_S3_local/test.sh
Restore AWS_SECRET_ACCESS_KEY on S3 local test, after it is being invalidated for access decline test.
> Restore AWS_SECRET_ACCESS_KEY on S3 local test

- src/grpc/stream_infer_handler.cc
In stream infer process function, request id was being retrieved even if the request object was not created due to earlier error. 
This was guarded in `infer_handler.cc`, applied same guard in `stream_infer_handler.cc`.
Fix for issue:
https://github.com/triton-inference-server/server/issues/5828
> nnshah1 stream infer segfault fix

- docs/customization_guide/build.md
The GPU base flag defaults to the Triton min container (for the current Triton version) for CPU-only builds. As a result, it is optional. Document this. The user can still change the flag value if they want to use a different container for getting the CUDA stubs and dependencies.
> Document that gpu-base flag is optional for cpu-only builds

- qa/L0_batch_input/batch_input_test.py
- qa/L0_batch_input/test.sh
- qa/common/gen_qa_model_repository
- qa/common/gen_qa_ragged_models.py
Add test model generation and testing for batch_input for libtorch.
Note that capitalization is used to match the input names in the model configs and output order is important for the PyTorch backend.
Pytorch_backend batch input implementation here: https://github.com/triton-inference-server/pytorch_backend/pull/98
> Test batch input for libtorch

- build.py
- docs/user_guide/response_cache.md
- qa/L0_response_cache/test.sh
- qa/common/util.sh
Add docs on Redis cache implementation, and update L0_response_cache tests to test Redis cache as well.
**NOTE:** The CI tests don't do anything comprehensive like starting or restarting multiple tritons or restarting Redis like I showed in my demo - they mostly test the same behaviors as existing `local` cache implementation. 
For these more comprehensive kinds of tests specific to Redis, I'd like to add some more end-to-end like testing with some Python clients/unittests in the style of our more recent CI tests in the future, **but not in time for this release**.
Core PR: https://github.com/triton-inference-server/core/pull/217
> Add Redis cache build, tests, and docs

- qa/L0_config_json/max_priority_level.pbtxt
- qa/L0_config_json/test.sh
- qa/L0_model_queue/model_queue_test.py
- qa/L0_model_queue/test.sh
- src/grpc/infer_handler.cc
- src/http_server.cc
Updating request priority apis to support uint64.
See discussion here https://github.com/triton-inference-server/common/pull/82#issuecomment-1547650136.
Major changes:
- Added test to L0_config_json to ensure large unsigned integers recovered correctly
- Added test to L0_model_queue to ensure large unsigned integer priority levels and default handled correctly
- changed grpc server to accept both U64 and int64 parameter for priority (error handling on negative priority)
- changed http server to use TRITONSERVER_InferenceRequestSetPriority64
> Updated handling for uint64 request priority

- build.py
Prepend HPCX dependencies to LD_LIBRARY_PATH search path so that the correct version is found by PyTorch.
These already exist in the install repo in CPU-only builds, so they are found there. For the GPU build, these need to be on the search paths so that libtorch.so finds them before the versions installed by apt for other packages.
PyTorch: https://github.com/triton-inference-server/pytorch_backend/pull/113
> Ensure HPCX dependencies found in container

- qa/python_models/custom_metrics/model.py
Python backend: https://github.com/triton-inference-server/python_backend/pull/254
> Add test case where MetricFamily is deleted before deleting Metric

- docs/user_guide/model_management.md
- qa/L0_model_update/instance_update_test.py
This PR adds a test to ensure the model instance can be updated by passing the new model configuration via the load API, without having to modify the 'config.pbtxt'. The PR also adds more documentation on the ability to pass new model configuration via the load API, and some text editor may interfere with Triton's determination on model modifications.
> Add test for sending instance update config via load API

- qa/L0_batcher/batcher_test.py
Unlike the sequence batcher's check_status function, L0_batcher's check_status expects the execution count to be provided as a set. This allows one of the tests to provide two execution values. As a result, it gets checked via AssertIn. To be consistent in the stability check and allow it to pass when the batch is ready, L0_batcher needs to check that the actual execution count is in the expected execution count.
- Use "in" check rather than equality check for consistency
- Correct error message when execution count fails
> Fix count check in L0_batcher

- qa/L0_http/test.sh
Adds an end-to-end case to L0_http to test out json tensor format
> Add testing for json tensor format

- qa/L0_model_update/instance_update_test.py
- qa/L0_model_update/test.sh
Add the test to decrease the rate limiter max resource limit, by updating instances to a lower resource count. If the rate limiter sees a instance is being removed that specifies a higher resource count than the max resource, then the "Should not print this" warning is printed, and the test script is also updated to capture the phrase "Should not print this" and report test failure if found.
Core PR: https://github.com/triton-inference-server/core/pull/208
> Add test on rate limiter max resource decrease update

- docs/protocol/extension_parameters.md
- docs/user_guide/decoupled_models.md
Cherry-picking docs for related decoupled final response feature in 23.06. Shouldn't require any respin.
> Add docs on decoupled final response feature (#5936)

- docker/sagemaker/serve
- qa/L0_sagemaker/test.sh
- src/sagemaker_server.cc
- src/sagemaker_server.h
* /ping relies on the ‘live’ ping check of the Triton model server i.e. return 200 if the model server is running irrespective of whether any model has been loaded, or whether any loaded model is ready to serve requests. 
* This change was made for the following reason:
* In MME mode, if one of the models fails to load for any reason, the /ping health-check will not return 200, thereby preventing other future models to be loaded. This breaks the MME feature where customers expect models to be available independent of each other.
However, /ping need not rely on 'live' for SageMaker's default single-model endpoint mode. Hence, changing the default behavior in SME to use 'ready', and for MME to continue to use 'live'. When required, users can provide env variable `SAGEMAKER_TRITON_PING_MODE` …
> Allow changing ping behavior based on env variable in SageMaker and entrypoint updates

- qa/L0_perf_analyzer/test.sh
The HPCX libraries are needed for the PyTorch backend. Since this test only needs to remove `libmpi.so` (and possibly `libmpi.so.40` and `libmpi.so.40.30.5`, CC: @matthewkotila and @tanmayv25 to confirm), only remove those libraries.
> Remove only MPI libraries in HPCX in L0_perf_analyzer

- qa/L0_batch_input/batch_input_test.py
L0_batch_input has been flaky in passing. It looks like the reason is that the responses rely on the requests being in order. Otherwise, for example, accumulation values will differ (since each request has a different volume and the tests assume that the request volumes will be received in the same order as requests sent).
This PR switches this test to use the GRPC client's streaming capability to ensure requests are received in order.
> Ensure L0_batch_input requests received in order

- qa/L0_io/test.sh
- qa/L0_libtorch_instance_group_kind_model/gen_models.py
- qa/L0_libtorch_instance_group_kind_model/test.sh
This PR adds a check and returns a clearer error message when the tests are run on a machine that has less than 4 GPUs.
> Improve the error message when the number of GPUs is insufficient for L0_io and L0_libtorch_instance_group_kind_model

- qa/L0_storage_S3/test.sh
Now that >1000 model files can be loaded, add a test to verify this can be done.
Results of test before changes (model.py is not loaded due to not being one of first 1000 files in ascending order):
Results of test after changes:
Core: https://github.com/triton-inference-server/core/pull/225
> Add test that >1000 model files can be loaded in S3

- qa/L0_backend_python/python_test.py
- qa/L0_backend_python/test.sh
Python backend: https://github.com/triton-inference-server/python_backend/pull/249
> Add testing for GPU tensor error handling

- qa/L0_backend_python/test.sh
- qa/L0_dlpack_multi_gpu/test.sh
It takes a lot of time to find a multi-GPU machine in CI. This should enable us to iterate faster.
> Move multi-GPU dlpack test to a separate L0 test

- qa/L0_backend_python/python_unittest.py
- qa/L0_warmup/test.sh
- qa/python_models/bls_onnx_warmup/config.pbtxt
- qa/python_models/bls_onnx_warmup/model.py
onnxruntime_backend: https://github.com/triton-inference-server/onnxruntime_backend/pull/202
> Add test to check the output memory type for onnx models

- docs/user_guide/architecture.md
- qa/L0_implicit_state/implicit_state.py
- qa/L0_implicit_state/test.sh
- qa/L0_sequence_batcher/sequence_batcher_test.py
- qa/L0_sequence_batcher/test.sh
- qa/common/gen_qa_implicit_models.py
- qa/common/gen_qa_model_repository
Add testing for https://github.com/triton-inference-server/pytorch_backend/pull/103
> Add testing for implicit state for PyTorch backend

- qa/L0_backend_python/common.sh
- qa/L0_backend_python/env/test.sh
Add test for https://github.com/triton-inference-server/python_backend/pull/266
> Allow uncompressed conda execution enviroments

- src/CMakeLists.txt
Specifying compile features for OpenTelemetry for jetson build
> Adding target_compile_features cxx_std_17 to tracing lib

- docs/customization_guide/inference_protocols.md
- docs/user_guide/decoupled_models.md
`grpc_server.cc` was recently moved to `grpc` folder, so I'm updating the docs links to point to the correct location
> Fix broken links pointing to the `grpc_server.cc` file

- qa/python_models/init_args/model.py
After merging https://github.com/triton-inference-server/core/pull/231 PR, the default instance name no longer varies based on the instance group count.
For example, in the past, if `count = 1`, the default instance name is `init_args_0`. If `count > 1`, the default instance names are `init_args_0_0`, `init_args_0_1`, ... After the change, the default instance names will always be `init_args_0_0`, `init_args_0_1`, ... regardless of `count`.
> Fix L0_backend_python expected instance name

- qa/L0_sdk/test.sh
After change in CI, the wheel file generated has suffix `xxx.dev${CI_PIPELINE}`, the `sed` here needs to be changed as otherwise it will add trailing 0 that results in incorrect name (`xxx.dev0${CI_PIPELINE}`)
> Fix L0_sdk: update the search name for the client wheel

- qa/L0_backend_python/decoupled/decoupled_test.py
- qa/L0_backend_python/test.sh
After merging https://github.com/triton-inference-server/core/pull/231 PR, the default instance name no longer varies based on the instance group count.
For example, in the past, if `count = 1`, the default instance name is `model_name_0`. If `count > 1`, the default instance names are `model_name_0_0, model_name_0_1, ...` After the change, the default instance names will always be `model_name_0_0, model_name_0_1, ...` regardless of count.
> Fix L0_backend_python default instance name when count = 1

- qa/L0_backend_python/lifecycle/lifecycle_test.py
After merging https://github.com/triton-inference-server/core/pull/231 PR, the default instance name no longer varies based on the instance group count.
For example, in the past, if `count = 1`, the default instance name is `model_name_0`. If `count > 1`, the default instance names are `model_name_0_0, model_name_0_1, ...` After the change, the default instance names will always be `model_name_0_0, model_name_0_1, ...` regardless of count.
> Fix L0_backend_python lifecycle default instance name

- qa/python_models/bls_model_loading/config.pbtxt
- qa/python_models/bls_model_loading/model.py
To avoid unsafely using the model loading API, reduce the model instance count to 1.
> Reduce instance count to 1 for python bls model loading test

- deploy/k8s-onprem/dashboard.json
The new panels are appended at last, please see the layout below.
| Column 0                 | Column 1        |
|--------------------------|-----------------|
| GPU Power Usage          | GPU Power Total |
| GPU Framebuffer Mem Used | GPU Utilization |
| Memory Used              | CPU Utilization |
I don't have a chance to test on aws/gcp/fleetcommand, so they are not touched.
> Add CPU & GPU metrics in Grafana dashboard.json for K8s on prem deployment (fix #6047)

- qa/L0_backend_python/argument_validation/test.sh
- qa/L0_backend_python/bls/test.sh
- qa/L0_backend_python/custom_metrics/test.sh
- qa/L0_backend_python/decoupled/test.sh
- qa/L0_backend_python/ensemble/test.sh
- qa/L0_backend_python/env/test.sh
- qa/L0_backend_python/examples/test.sh
- qa/L0_backend_python/io/test.sh
- qa/L0_backend_python/lifecycle/test.sh
- qa/L0_backend_python/logging/test.sh
- qa/L0_backend_python/model_control/test.sh
- qa/L0_backend_python/restart/test.sh
- qa/common/util.sh
> Improve L0_backend_python debugging

- qa/L0_perf_analyzer/test.sh
This PR fixes a failing CI due to rephrasing of the error messages in `CLIParser` in client repo ([#371](https://github.com/triton-inference-server/client/pull/371)). Removing this test case that checks if the `CLIParser` properly catches an invalid input for `--shape` flag, which is already being handled in the PA's unit tests.
> Remove a test case that sanity checks input value of --shape CLI flag

- docs/user_guide/debugging_guide.md
> Add deadlock gdb section to debug guide

- qa/python_models/bls/model.py
Manually tested on CI for couple of runs that after adding `gc.collect()` to the script, the GPU tensor lifecycle test has not been failing.
> Add gc collect to make sure gpu tensor is deallocated

- qa/L0_lifecycle/test.sh
Enhance test to check for explicit log message for user experience from: https://github.com/triton-inference-server/core/pull/244
> Check for log error on failing to find explicit load model

- qa/L0_infer/test.sh
Set the default shm-size for Python backend to 1MB
Related PR: https://github.com/triton-inference-server/python_backend/pull/291
> Set default shm size to 1MB for Python backend

- qa/L0_http/http_test.py
With [adding the input name to the log message](https://github.com/triton-inference-server/core/pull/243), need to update the error message in the test.
Error from L0_http:
```
AssertionError: 'For BYTE datatype raw input, the model must have input shape [1]' not found in '{"error":"[request id: <id_unknown>] For BYTE datatype raw input \'INPUT0\', the model must have input shape [1]"}'
```
> Fix the error message for L0_http

- qa/L0_trace/test.sh
- src/command_line_parser.cc
- src/command_line_parser.h
- src/grpc/grpc_server.cc
- src/http_server.cc
- src/tracer.h
Related issue: https://github.com/triton-inference-server/server/issues/6153
Issue fix is in files `http_server` and `grpc_server` - added catch for out of range exception .
I've also added a wrapper to `ParseOptions` in `command_line_parser` to handle `stoi`, `stoull`, `stoll` exceptions + report option, for which conversion didn't work.
> Adding safe string to number conversions

- qa/L0_backend_python/lifecycle/lifecycle_test.py
- qa/L0_backend_python/lifecycle/test.sh
- qa/python_models/error_code/config.pbtxt
- qa/python_models/error_code/model.py
Related PR: https://github.com/triton-inference-server/python_backend/pull/292
This new test ensures the optionally supplied Python `execute()` error code can be picked up on the calling gRPC client.
> Test Python execute() to return Triton error code

- docs/protocol/README.md
Based on request for docs from this issue: https://github.com/triton-inference-server/server/issues/5305#issuecomment-1432034997
> Add docs on IPv6

- qa/L0_trt_compat/test.sh
- qa/L0_trt_compat/trt_compatibility_test.py
- qa/common/gen_qa_identity_models.py
- qa/common/gen_qa_model_repository
- qa/common/infer_util.py
Add testing for TensorRT version-compatible model support.
The feature will be implemented in the TensorRT backend in this pull request: https://github.com/triton-inference-server/tensorrt_backend/pull/74.
> Add test for TensorRT version-compatible model support

- build.py
https://github.com/triton-inference-server/core/pull/250
> Apply UCX workaround

- src/CMakeLists.txt
Initial location is not stable. The new value also used by DLFW team.
> Update condition to bypass iGPU build

- qa/L0_infer_zero/test.sh
- qa/L0_nullchar_string/test.sh
Some QA tests do not need the version-compatible models. Including them will result in the tests failing if the server is started with version compatibility disabled. Remove these models from those tests.
> Exclude extra TRT version-compatible models from tests

- src/sagemaker_server.cc
1. So far, model_name is provided by SageMaker as a 'model_hash' (for other naming and abstraction reasons). We have been using this as model_name, but logging the actual model archive name (provided as a header) as a log-line when LOADING, UNLOADING, and INVOKING the model.
2. However, while this works alright, a better experience is to identify the model with the archive name specified by users when calling SageMaker.
3. This also helps identifying the metrics associated with the model archive when metrics publishing is enabled.
4. Model archive name and the model hash have a 1:1 mapping for a given instance in SageMaker, and hence maybe used interchangeably.
5. This PR enables changes the model 'id' to use the archive name from the header when available, otherwise default to the model …
> Use targetmodel from header as model name in SageMaker

- src/sagemaker_server.cc
* Use targetmodel from header as model name in SageMaker
* Update naming for model hash
> Use targetmodel from header as model name in SageMaker (#6147)

- qa/L0_lifecycle/test.sh
- src/http_server.cc
- src/http_server.h
1. Clean up common parsing components of request JSON into helper functions. 
- This will separate some logic between parsing inputs provided in current format `ParseJsonTritonIO --> {inputs: {name, datatype, shape}, ...}` and accepting json inputs in other formats in future such as `{prompt, parameters}`.
- Breaks up a ~400 line `EVBufferToInput` function into more manageable chunks
2. Return error messages in response body more consistently for most routes. Improved CLI/`curl` UX, similar to FastAPI and vLLM API server experience.
- Routes without any handler (not found) will now return **404 instead of 400** at top-level Handler
Query triton routes:
```bash
rmccormick@ced35d0-lcedt:~$ curl -w "\n" -X POST localhost:8000/v2
rmccormick@ced35d0-lcedt:~$ curl -w "\n" -X POST …
```
> Refactor HTTP server

- docs/customization_guide/inference_protocols.md
- qa/L0_java_memory_growth/test.sh
- qa/L0_java_resnet/test.sh
- qa/L0_java_sequence_batcher/test.sh
- qa/L0_java_simple_example/test.sh
closes: https://github.com/triton-inference-server/server/pull/6275
Fixes build for javaCPP-CAPI binding tests. 
Does not fix memory growth test issue.
Related PR: https://github.com/bytedeco/javacpp-presets/pull/1412
> Disable developer tools build for In-process API + JavaCPP tests

- docs/user_guide/model_repository.md
- qa/L0_storage_S3/test.sh
- qa/L0_storage_azure/test.sh
Tests and docs for this PR: https://github.com/triton-inference-server/core/pull/254
> Tests and docs for ability to specify subdirectory to download for LocalizePath

- src/http_server.cc
- src/http_server.h
1. Compartmentalize `HandleInfer` into logical helpers for better readability and re-usabilty for different inference handlers
2. Replace nested `if (err == nullptr)` logic with early return macro style for better readability. Added a callback helper to cleanup on error and resume the request if `connection_paused`. Currently it will always be paused when inference request is created, but left the variable in for clarity.
3. Set JSON content type before early returns so it's properly set on early errors, and add a helper to condense the code a bit.
4. Remove some unnecessary ifdefs around `trace` usage to remove some noise, as we already have [TraceManager](https://github.com/triton-inference-server/server/blob/5dd9398dd76a90a117ce6b3052e15561337fe88b/src/http_server.h#L340) in the code …
> Refactor HandleInfer into more readable chunks

- qa/L0_scalar_io/scalar_test.py
- qa/L0_scalar_io/test.sh
- qa/common/gen_qa_model_repository
- qa/common/gen_qa_ort_scalar_models.py
Please only review the last commit. The other commits will be rebased after https://github.com/triton-inference-server/server/pull/6336 is merged in.
https://github.com/triton-inference-server/onnxruntime_backend/pull/213
> Add testing for scalar I/O in ORT backend

- src/grpc/grpc_utils.cc
- src/grpc/grpc_utils.h
- src/grpc/infer_handler.cc
- src/grpc/infer_handler.h
- src/grpc/stream_infer_handler.cc
- src/grpc/stream_infer_handler.h
There are few items that have been identified and fixed:
1. It is unsafe to call ctx_->IsCancelled() if the tag from AsyncNotifyWhenDone(). I am using a dummy State object that points to the first state object of ongoing context tracking the bidi grpc streaming RPC.
2. Introduced a new state step called PARTIAL_COMPLETE. We would need to handle the lifetimes of the state objects ourselves so that State is released only when all the RPC is complete. This means that callbacks have been processed, all the standard loops from the state->steps_ are complete and Done notification has been processed. The sad thing is there is no order guarantee on the standard CQ delivery and Done notification delivery.
3. There is a possibility that server when shutting down might not receive the Done() event. …
> Fixes on the gRPC frontend to handle AsyncNotifyWhenDone() API

- build.py
Currently the build is using internal GitLab repo for both TRT-LLM backend and TRT-LLM repositories. Will switch the link to the GitHub repo once they're ready.
TRT-LLM backend: https://github.com/triton-inference-server/tensorrtllm_backend/pull/3
> Add TRT-LLM backend build to Triton

- Dockerfile.QA
- qa/L0_grpc_state_cleanup/cleanup_test.py
- qa/L0_grpc_state_cleanup/test.sh
Locally the server seems to be quite stable for these tests. Other tests in the CI are also looking stable.
To-Do:
~~1. Add tests for non-decoupled streaming.~~
~~2. Add tests for non-streaming inferences.~~
After these two are added. We can be quite confident on the new state transitions in the gRPC frontend. 
Additional follow-up is to move decoupled_infer to a common infer utilities where different tests can utilize these calls.
> Add L0_grpc_state_cleanup test

- qa/L0_backend_python/decoupled/decoupled_test.py
- qa/L0_backend_python/decoupled/test.sh
- qa/L0_backend_python/lifecycle/lifecycle_test.py
- qa/L0_backend_python/lifecycle/test.sh
- qa/python_models/error_code/model.py
- qa/python_models/execute_cancel/config.pbtxt
- qa/python_models/execute_cancel/model.py
Related PR: https://github.com/triton-inference-server/python_backend/pull/304
Add test on Python backend models checking for request cancellation and responding cancelled status.
> Add Python backend request cancellation test

- build.py
Addressed comment here: https://github.com/triton-inference-server/server/pull/6392#discussion_r1348925324
> Move import to the top

- build.py
* Add trtllm backend to build
* Temporarily adding version map for 23.07
* Fix build issue
* Update comment
* Comment out python binding changes
* Add post build
* Update trtllm backend naming
* Update TRTLLM base image
* Fix cmake arch
* Revert temp changes for python binding PR
> Add TRT-LLM backend build to Triton (#6365)

- build.py
The vLLM backend is a Python-based backend, so it relies on Python backend existing. Add it as a dependency in the build. If it does not exist, log that and use the vLLM's repo tag as the tag for the Python backend.
> Add Python backend when vLLM backend built

- qa/L0_http/generate_endpoint_test.py
- qa/L0_http/test.sh
- src/http_server.cc
- src/http_server.h
Adding a specific key word for generate endpoint to support passing parameters such as:
curl -s localhost:8000/v2/models/mock_llm/generate_stream -d '{"PROMPT":"hello","STREAM":true, "parameters"\
:{"REPETITION":5}}'
> support parameters object in generate route

- qa/L0_java_memory_growth/test.sh
- qa/L0_java_resnet/test.sh
- qa/L0_java_sequence_batcher/test.sh
- qa/L0_java_simple_example/test.sh
This is to simplify testing when upstream (javacpp-presets) build changes. Related to https://github.com/triton-inference-server/client/pull/409
> add extra enviroment variables for building

- build.py
For 23.10, we won't bring any changes to the structure of TRT-LLM backend. This PR fixes some path issues so that Triton can build using CMake. Also adding some temporary workaround to solve the repo permission issues. We will update those once the GitHub repo is ready.
> TRT-LLM backend build changes

- qa/L0_request_cancellation/grpc_cancellation_test.py
- qa/L0_request_cancellation/test.sh
Related PR: https://github.com/triton-inference-server/client/pull/417
This PR:
- Fix L0_request_cancellation failures on gRPC cancellation tests; and
- Refactor gRPC cancellation tests; and
- Add tests for gRPC AsyncIO request cancellation.
> Add gRPC AsyncIO request cancellation tests

- build.py
* Update url
* Debugging
* Debugging
* Update url
* Fix build for TRT-LLM backend
* Remove TRTLLM TRT and CUDA versions
* Fix up unused var
* Fix up dir name
* FIx cmake patch
* Remove previous TRT version
* Install required packages for example models
* Remove packages that are only needed for testing
> TRT-LLM backend build changes (#6406)

- build.py
* Fixing torch version for vllm
* cherry pick https://github.com/triton-inference-server/server/pull/6433
> Fixing vllm build (#6433)

- src/grpc/infer_handler.cc
- src/grpc/infer_handler.h
- src/grpc/stream_infer_handler.cc
For the cases where gRPC doesn't deliver notification, we have moved the notify_state_ ~delete to the context  destructor~ to the unique_ptr.
This should fix the valgrind failures on CI.
Fixing the tracking of inflight states to erase the states as and when they complete or run into an error. This should fix the L0_perf_analyzer under heavy streaming load case.
> Fix notify state destruction and inflight states tracking

- build.py
Will need to cherry-pick this PR to r23.10
> Update TRT-LLM backend url

- qa/L0_model_config/autofill_noplatform/custom/unknown_backend.unknown/expected
Minor fix to the L0_model_config test suite.
Core changes: https://github.com/triton-inference-server/core/pull/278
> L0_model_config Fix

- qa/L0_backend_python/bls/bls_parameters_test.py
- qa/L0_backend_python/bls/test.sh
- qa/python_models/bls_parameters/config.pbtxt
- qa/python_models/bls_parameters/model.py
Related PR: https://github.com/triton-inference-server/python_backend/pull/313
Add a new test on BLS parameters. The model call itself recursively via BLS to completes the requested number of parameters. Each recursive level only completes the parameters, on 3 different supported data type `str` `int` `bool`, of its level. For example, at the initial `num_params = 3`, the parameters is changed from `{}` to
```
"bool_3": True, "int_3": 3, "str_3": "3"
```
Then, the remaining as completed by calling itself recursively with `num_params - 1`.
At `num_params = 2`, the parameters become
```
"bool_3": True, "int_3": 3, "str_3": "3",
"bool_2": True, "int_2": 2, "str_2": "2"
```
At `num_params = 1`, the parameters become
```
"bool_3": True, "int_3": 3, "str_3": "3",
"bool_2": True, "int_2": 2, …
```
> Add test for Python BLS parameters

- deploy/k8s-onprem/README.md
- deploy/k8s-onprem/templates/deployment.yaml
In Kubernetes 1.19 `startupProbe` was introduced in Beta to solve the following issue:
> Slow starting containers are difficult to address with the current status of health probes: they are either killed before being up, or could be left deadlocked during a very long time before being killed.
>This proposal adds a new probe called `startupProbe` that holds off all the other probes until the pod has finished its startup. In the case of a slow-starting pod, it could poll on a relatively short period with a high `failureThreshold`. Once it is satisfied, the other probes can start.
Since a Triton container having multiple heavy models can be a good example of a slow-starting container, I've added the `startupProbe` to the helm deployment template with some reasonable values and documented the …
> StartupProbe for K8s-onprem added and documented

- Dockerfile.win10.min
Windows build with newer vcpkg results in HTTP server not properly parse URL with regex (provided by RE2), combining with the segfault from GRPC server suggests that a different version of the library is dynamically linked. GRPC itself brings an older version of RE2 and builds against that, while HTTP server links a newer RE2 shared library installed by vcpkg.
This PR is WAR to use a different but compatible library at runtime, the long-term fix is to isolate the dependency between HTTP and GRPC so they may use different version of the library.
> Downgrade vcpkg version to WAR RE2 library inconsistency

- qa/L0_backend_python/argument_validation/test.sh
- qa/L0_backend_python/bls/test.sh
- qa/L0_backend_python/custom_metrics/test.sh
- qa/L0_backend_python/decoupled/test.sh
- qa/L0_backend_python/ensemble/test.sh
- qa/L0_backend_python/env/test.sh
- qa/L0_backend_python/examples/test.sh
- qa/L0_backend_python/io/test.sh
- qa/L0_backend_python/lifecycle/test.sh
- qa/L0_backend_python/logging/test.sh
- qa/L0_backend_python/model_control/test.sh
- qa/L0_backend_python/restart/test.sh
- qa/common/util.sh
The test script will exit directly if segfault happens outside the `set +e` scope, hence the function for collecting artifacts will not be called. Move the artifacts collection in the sub directories to the GitLab yaml file so that when coredump happens during the test, the logs/coredumps will still be collected.
> Remove sub directory artifacts collection from test script

- qa/L0_socket/test.sh
- src/command_line_parser.cc
The reuse-grpc-port and reuse-http-port flags are documented in the options as booleans but parsed as integers. This PR makes it so they are parsed as booleans.
Addresses [6481](https://github.com/triton-inference-server/server/issues/6481).
> Parse reuse-grpc-port and reuse-http-port as booleans

- docs/user_guide/model_repository.md
Related PR: https://github.com/triton-inference-server/core/pull/280
Mention support for JSON authorized user credentials, and reformat the order of how the credentials are fetched and attempted.
> Enhance GCS credentials documentations

- qa/L0_backend_python/python_unittest.py
- qa/L0_backend_python/request_rescheduling/grpc_endpoint_test.py
- qa/L0_backend_python/request_rescheduling/test.sh
- qa/L0_backend_python/test.sh
- qa/python_models/bls/model.py
- qa/python_models/bls_request_rescheduling/config.pbtxt
- qa/python_models/bls_request_rescheduling/model.py
- qa/python_models/generative_sequence/config.pbtxt
- qa/python_models/generative_sequence/model.py
- qa/python_models/request_rescheduling_addsub/config.pbtxt
- qa/python_models/request_rescheduling_addsub/model.py
- qa/python_models/wrong_return_type/config.pbtxt
- qa/python_models/wrong_return_type/model.py
* Add testing
* Fix up
* Enhance testing
* Fix up
* Revert test changes
* Add grpc endpoint test
* Remove unused import
* Remove unused import
* Update qa/L0_backend_python/request_rescheduling/grpc_endpoint_test.py
* Update qa/python_models/bls_request_rescheduling/model.py
---------
> Add testing for Python backend request rescheduling (#6509)

- src/grpc/grpc_server.cc
- src/http_server.h
- src/sagemaker_server.h
- src/vertex_ai_server.cc
Underlying issue was the storage of a reference to the RestrictedFeatures object. In general this can be done as long as the lifetime of the object is known to be longer than the holder (similar to a pointer). However in this case for vertex and sagemaker a reference to a temporary was being stored. In http / grpc cases the reference was to an object with longer lifetime and so no issue was present.
Changed to copy the value and store it as this initialization only happens once.
> changing references to concrete instances

- qa/L0_sagemaker/test.sh
I removed the model name field from add_sub in a different PR so we wouldn't have to keep sed'ing it everywhere, and then some leftover tests having seds with too generic of a regex are matching input names instead of model names now, and editing the input name. This test was another one impacted, similar to this PR: https://github.com/triton-inference-server/server/pull/6510
Just removed the unnecessary sed and test passes now.
> Fix L0_sagemaker

- build.py
updated build.py to install current latest version of vLLM (v.0.2.2): https://github.com/vllm-project/vllm/releases
> Bumped vLLM version to v0.2.2

- build.py
r23.11 is already using this patch release of ORT-TRT with memory leak fix.
> Upgrade ORT version

- src/CMakeLists.txt
- src/grpc/CMakeLists.txt
With the latest updates on NVTX utitlity, we need this flag to let it compile for `__VA_ARGS__`
Find more details here: https://stackoverflow.com/questions/5134523/msvc-doesnt-expand-va-args-correctly
Other PRs:
core: https://github.com/triton-inference-server/core/pull/296
backend: https://github.com/triton-inference-server/backend/pull/91
common: https://github.com/triton-inference-server/common/pull/109
trt backend: https://github.com/triton-inference-server/tensorrt_backend/pull/78
ORT backend: https://github.com/triton-inference-server/onnxruntime_backend/pull/219
> Use compliant preprocessor on windows

- README.md
Trying to minimize the scope of changes when doing a release.
> Bring back the README

- qa/L0_batch_custom/test.sh
I made a typo and merged the changes to the `main` branch with following PR: 
https://github.com/triton-inference-server/server/pull/6675/files
> restore typo

- deploy/mlflow-triton-plugin/mlflow_triton/deployments.py
[This ](https://github.com/mlflow/mlflow/pull/9402/files) PR introduced a new YAML file to the artifact/triton directory called 'registered_model_meta'. Because our _get_copy_paths function in the mlflow_deploy folder overwrites the copy path per item in the folder, we end up copying this file to the model_repo instead of the model folder.
The contents of this new file were:
```
model_name: onnx_float32_int32_int32
model_version: '1'
```
Which is similar to the `mlflow-meta.json` already produced by our plugin which contains:
```
{
"name": "onnx_float32_int32_int32",
"triton_model_path": "models/onnx_float32_int32_int32",
"mlflow_model_uri": "models:/onnx_float32_int32_int32/1",
"flavor": "triton"
}
```
Due to the style of existing code, I simply appended the new file to not be copied. …
> Mlflow Plugin Fix

- docs/protocol/extension_generate.md
- qa/L0_http/generate_endpoint_test.py
- src/http_server.cc
**Overview**
evhtp_add_header was appending extra headers when already set, rather than overwriting existing value, ending with some cases of extra headers.
Rather than adding more logic and branching throughout the code, just updating the `AddContentType` header to first remove the header if found before adding new one.
---
Before:
```
{'Content-Type': 'application/json, text/event-stream; charset=utf-8', 'Transfer-Encoding': 'chunked'}
{'Content-Type': 'application/json, application/json'}
```
After:
```
{'Content-Type': 'text/event-stream; charset=utf-8', 'Transfer-Encoding': 'chunked'}
{'Content-Type': 'application/json'}
```
---
**Testing**
Added more strict equality checking to header values in generate endpoint tests
> Fix extra content-type headers in HTTP server

- CMakeLists.txt
* adding default value for TRITON_IGPU_BUILD=OFF
* fix newline
---------
Picking this into release for our users. Otherwise for the 23.12 release they would have to include TRITON_IGPU_BUILD in their `build.py` invocation.
> adding default value for TRITON_IGPU_BUILD=OFF (#6705)

- qa/L0_backend_python/python_unittest.py
The issue appears fixed by #302, so the double unit test before checking for memory leak can be reduced down to a single unit test.
> Remove Python backend double unit test

- qa/L0_lifecycle/lifecycle_test.py
There is a check on "L0_lifecycle" "test_concurrent_same_model_load_unload_stress" case which fails the entire test if the case was not able to reproduce a load while async unloading. This check can be problematic on machines with less concurrency, because they may not be able to reproduce a load while async unloading at all. This PR changes the check from failing the entire test to log a warning on the test printout.
For example, on a machine that reproduces a load while async unloading:
```
+ python lifecycle_test.py LifeCycleTest.test_concurrent_same_model_load_unload_stress
+ '[' 0 -ne 0 ']'
+ cat ./test_concurrent_same_model_load_unload_stress.statistics.log
{"failed to unload 'identity_zero_1_int32', versions that are still available: 1": 115}     <---- acceptable failure logged
``` …
> Fix L0_lifecycle on insufficient hardware concurrency

- qa/L0_storage_S3/test.sh
Our L0_storage_S3 test intermittently fails.
Examining the the job history of this test in our CI, it fails intermittently with successful tests completing in ~25-30 minutes and failed tests finishing in ~35-50 minutes.
In my mind, either we are experiencing a deadlock which triggers the server timeout or the server timeout value is simply too low for the number of files that need to be uploaded. I think the server timeout value being too low is the more likely culprit for three reasons:
1. AFAIK we do not violate the thread safety contract with [AWS](https://github.com/awslabs/aws-c-io/tree/main?tab=readme-ov-file#thread-safety).
2. We have tests that are passing that just barely finish before hitting the server timeout value (with < 10s left).
3. The failed jobs are taking longer to …
> Increase L0_storage_S3 Test Timeout

- build.py
Server: https://github.com/triton-inference-server/server/pull/6775
Python Backend: https://github.com/triton-inference-server/python_backend/pull/334
Gitlab: !1027
Based on issues with jfrog similar to this: https://github.com/boostorg/boost/issues/849#issue-2069720679
> Move from jfrog artifactory to archives.boost.io to fix boost download

- CMakeLists.txt
- src/CMakeLists.txt
- src/grpc/CMakeLists.txt
Setting a min required cxx standard for Triton to 17.
Note in our containers default cxx is 17, thus no `-std=..` flag is shown. However, if higher version is desired, the following command:
``` 
cmake -DTRITON_MIN_CXX_STANDARD=20 -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install .. && make -j1 VERBOSE=1 install
```
will add `-std=gnu++20` flag during build. 
This PR:
- adds `TRITON_MIN_CXX_STANDARD` cmake variable, which defaults to 17 
- uses the above variable to specify cxx standard in `target_compile_features(... PRIVATE cxx_std_${TRITON_MIN_CXX_STANDARD})`, to avoid hardcoded values
This way to recompile Triton in higher standard, one can simply specify ` -DTRITON_MIN_CXX_STANDARD=20` option for cmake command, as shown above.
Related PRs:
- core: …
> Bump min cxx standard to 17

- qa/L0_lifecycle/lifecycle_test.py
- qa/L0_lifecycle/test.sh
This validates the change This validates the change made to `../core` wrt how model configuration mtime is handled.
[MR to ../core](https://github.com/triton-inference-server/core/pull/304)
> Use current time when overwriting model configuration.

- qa/L0_lifecycle/lifecycle_test.py
- qa/L0_lifecycle/test.sh
This validates the change made to ../core wrt how model configuration mtime is handled.
> [cherry-pick] Use current time when overwriting model configuration. (#6727)

- Dockerfile.win10.min
- build.py
Server: https://github.com/triton-inference-server/server/pull/6810
Core: https://github.com/triton-inference-server/core/pull/319
Fixes: https://github.com/triton-inference-server/server/issues/6745
> Remove boost::filesystem from builds

- qa/common/util.sh
See the ticket for more details.
> Add gsutil upload retry helper function

- qa/L0_lifecycle/lifecycle_test.py
- qa/L0_lifecycle/test.sh
Related PR: https://github.com/triton-inference-server/core/pull/323
Add a new test that loads a model that will unload for 10 seconds. The model is then placed into the background and unloaded, by model config overwrite. Before the model can finish unloading in the background, the server is stopped. The server must wait until the background model has finish unloading before shutting down.
The new test verifies the wait is properly commenced by checking the number of models successfully unloaded after the server stops and shuts down. If the server shuts down without waiting for the background model, there will only be one successful model unload logged. If the server shuts down after waiting for the background model, there will be two successful model unload logged.
> Add test for shutdown while unloading model in background

- qa/L0_http/generate_endpoint_test.py
- qa/L0_http/generate_models/mock_llm/1/model.py
- qa/L0_http/test.sh
- src/http_server.cc
For the TRT-LLM backend, it is possible that the output tensor has the 0 dim shape if the end token is predicted at the first step. This PR fixed the handle for 0 dim output, and added test case for it.
Before the fix, when using generate/generate_stream endpoint for zero dim tensors:
**generate**
```
root@a2826b5-lcedt:/opt/tritonserver/tensorrtllm_backend# curl -X POST localhost:8000/v2/models/ensemble/generate --data-binary @sample.txt
{"error":"attempt to access non-existing array index '0'"}
```
**generate_stream**
```
root@a2826b5-lcedt:/opt/tritonserver/tensorrtllm_backend# curl -X POST localhost:8000/v2/models/ensemble/generate_stream --data-binary @sample
.txt
data: {"error":"attempt to access non-existing array index '0'"}
```
After the fix:
**generate**
``` …
```
> Handle 0 dimension output for generate endpoint

- qa/L0_backend_python/common.sh
- qa/L0_backend_python/test.sh
- qa/common/util.sh
Update the miniconda version to use libmamba solver to speed up the test time. From the output we can see that `conda-libmamba-solver` is used as default solver.
```
(base) root@a2826b5-lcedt:/opt/tritonserver/qa/L0_backend_python/env# conda info
active environment : base
active env location : /opt/tritonserver/qa/L0_backend_python/env/miniconda
shell level : 1
user config file : /root/.condarc
populated config files : 
conda version : 23.11.0
conda-build version : not installed
python version : 3.10.13.final.0
solver : libmamba (default)
virtual packages : __archspec=1=skylake_avx512
__conda=23.11.0=0
__cuda=12.2=0
__glibc=2.35=0
__linux=6.5.0=0
__unix=0=0
base environment : /opt/tritonserver/qa/L0_backend_python/env/miniconda  (writable)
conda av data dir : …
```
> Use libmamba solver for L0_backend_python env test. Fix pytest not found

- qa/L0_lifecycle/lifecycle_test.py
- qa/L0_lifecycle/test.sh
Related PR: https://github.com/triton-inference-server/core/pull/324
Add a new test that starts loading a model, and before the model can finish loading, the server shutdowns. Given a model is still loading while shutting down, the unload must happen after the load is completed. If the test cannot assert there is exactly one load complete and one unload in order, then the test fails.
> Add test for shutdown while loading model

- docs/user_guide/trace.md
- qa/L0_cmdline_trace/test.sh
- qa/L0_trace/opentelemetry_unittest.py
- qa/L0_trace/test.sh
- src/command_line_parser.cc
- src/command_line_parser.h
- src/tracer.cc
- src/tracer.h
Fixes issue: https://github.com/triton-inference-server/server/issues/6693
Picked up work from [this PR](https://github.com/triton-inference-server/server/pull/6733) by @theoclark , he has CLA : https://github.com/triton-inference-server/server/pull/6733#issuecomment-1874349122
Currently, OpenTelemetry Trace API uses SimpleSpanProcessor, which send spans one by one, when they are ready. This impacts Triton's performance, when tracing is on and mode is `opentelemetry`. To mitigate this issue, SimpleSpanProcessor was replaced by a BatchSpanProcessor(https://opentelemetry.io/docs/specs/otel/trace/sdk/#batching-processor), which collects spans in batches of a specified size and sends them out to the endpoint periodically. 
There are 3 customization parameters:
`bsp_max_queue_size` - the …
> Adding OpenTelemetry Batch Span Processor

- build.py
This update resolves a compromised vllm install of v0.2.3, possibly due to some issues with intermediate dependencies.
Relevant import error:
`ImportError: /usr/local/lib/python3.10/dist-packages/vllm/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15to_dtype_layout4callERKNS_6TensorEN3c108optionalINS5_10ScalarTypeEEENS6_INS5_6LayoutEEENS6_INS5_6DeviceEEENS6_IbEEbbNS6_INS5_12MemoryFormatEEE`
Should be merged with https://github.com/triton-inference-server/vllm_backend/pull/30
> Updating vllm version to 0.3.0

- qa/L0_dlpack_multi_gpu/test.sh
- qa/L0_warmup/test.sh
Adding unit test reports to L0_dlpack_multi_gpu and L0_warmup to also fix the test failures as we removed the use of `check_test_results` for `python_unittest.py` and it was used in these tests as well.
> Add unit test reports to L0_dlpack_multi_gpu and L0_warmup

- src/command_line_parser.cc
Fixes build with tracing disabled
> Fixing StringTo uint32_t used only by tracing

- qa/L0_dlpack_multi_gpu/test.sh
- qa/L0_warmup/test.sh
* Add unit test reports to L0_dlpack_multi_gpu
* Add unit test reports to L0_warmup
> Add unit test reports to L0_dlpack_multi_gpu and L0_warmup (#6873)

- qa/L0_memory_growth/busy_op_test.py
- qa/L0_memory_growth/test.sh
- qa/python_models/busy_op/config.pbtxt
- qa/python_models/busy_op/model.py
Expected massif output should be something like:
```
Test Duration: 00:01:39 (HH:MM:SS)
--------------------------------------------------------------------------------
Command:            /opt/tritonserver/bin/tritonserver --model-repository=/opt/tritonserver/qa/L0_memory_growth/test_repo
Massif arguments:   --time-unit=B --massif-out-file=test_busyop.massif
ms_print arguments: test_busyop.massif
--------------------------------------------------------------------------------
GB
6.130^                                                ##                      
|                                               @# :::                   
|                                             @@@# :: :                  
|                                          @@@@ @# :: ::                 
| …
```
> Fix busyop test for L0_memory_growth

- docs/protocol/extension_statistics.md
- qa/L0_response_statistics/response_statistics_test.py
- qa/L0_response_statistics/test.sh
- src/grpc/grpc_server.cc
Related PRs:
- https://github.com/triton-inference-server/core/pull/329
- https://github.com/triton-inference-server/common/pull/113
- https://github.com/triton-inference-server/square_backend/pull/17
Add tests for reporting cancellation statistics to response statistics.
> Add cancellation into response statistics

- qa/L0_decoupled/decoupled_test.py
- qa/L0_decoupled/test.sh
- src/grpc/infer_handler.cc
- src/grpc/infer_handler.h
- src/http_server.cc
- src/http_server.h
- src/sagemaker_server.cc
Follow up on https://github.com/triton-inference-server/core/pull/229
For custom backend, one may call send response in the following style, even for "non-decoupled" model
```
TRITONBACKEND_ResponseSend(response, 0, nullptr /* success */);
TRITONBACKEND_ResponseFactorySendFlags(factory, TRITONSERVER_RESPONSE_COMPLETE_FINAL);
```
This yields single response of the request from the client's perspective and would expect a successful inference through HTTP / non-streaming GRPC as it is "non-decoupled". The previous implementation is restricted that it simply assume decoupled use case when response complete callback is invoked multiple time. The change is to relax the restriction and collapse the above into single response to the client.
> Allow non-decoupled model to send response and FINAL flag separately

- qa/L0_batcher/queue_timeout_test.py
- qa/L0_batcher/test.sh
Related PR: https://github.com/triton-inference-server/core/pull/333
Add a test for the prompt rejection of request upon timeout, without waiting for the availability of a payload slot.
> Add test for max queue delay timeout prompt response

- Dockerfile.sdk
Add flag to enable compile of OpenAI support in PA
> Update Dockerfile.sdk with OpenAI support

- qa/L0_data_compression/test.sh
Verifies the Python AsyncIO HTTP client can handle data compression, plus some refactoring.
Original request and response compression algorithms:
| request | response | request != response | is original test case |
| ----- | ----- | ----- | ----- |
| - | - | ❌ | ❌ |
| - | deflate | ✅ | ✅ |
| deflate | - | ✅ | ✅ |
| deflate  | deflate | ❌ | ❌ |
| - | gzip | ✅ | ✅ |
| gzip | - | ✅ | ✅ |
| gzip | gzip | ❌ | ❌ |
| deflate | gzip | ✅ | ✅ |
| gzip | deflate | ✅ | ✅ |
closes: https://github.com/triton-inference-server/server/issues/6887
> Add AsyncIO HTTP compression test

- CMakeLists.txt
- qa/L0_trace/opentelemetry_unittest.py
- qa/L0_trace/test.sh
- qa/L0_trace/trace_context.py
- src/CMakeLists.txt
- src/tracer.cc
- src/tracer.h
The purpose of this PR:
This PR is a Stage 1 towards adding an ability for users to create custom traces in python backend. 
This set of PRs is heavily focused on OpenTelemetry trace mode. 
Functionality:
- Prepares OpenTelemetry trace context via `PrepareTraceContext` and attaches it to TRITONSERVER_InferenceTrace instance through `TRITONSERVER_InferenceTraceSetContex` at the moment in time, when `REQUEST_START` callback happens. That one is happening from the core side, so when PBE model starts execution, it should have context attached to its trace.
- Context is passed as a string and for OpenTelemetry is essentially 2 headers `traceparent` : "..." and `tracestate`: "...". Some of you may know about them from OpenTelemetry context propagation discussions. It's the same. 
- We do …
> Exposing trace context to python backend

- qa/L0_trace/opentelemetry_unittest.py
- qa/L0_trace/test.sh
- qa/L0_trace/trace_context.py
- src/CMakeLists.txt
- src/tracer.cc
- src/tracer.h
* Added TRITONSERVER_InferenceTraceSetContext logic
> Exposing trace context to python backend (#6985)

- Dockerfile.sdk
Remove hatch version so that the tool can report its own version
> Remove hatch version for GenAI-Perf

- build.py
This PR removes the conda package manager from the Triton system.
Conda has been used to isolate DALI wheel (which needs to be installed apart from being unpacked in the container) from the rest of Triton packages. Since we're moving away from this requirement, DALI can be installed bare-metal inside the Triton container and conda is no longer necessary.
> Remove conda package manager 

- docs/conf.py
- docs/generate_docs.py
Addressing comments from previous [PR](https://github.com/triton-inference-server/server/pull/7084#event-12399356287) here.
> Remove obsolete mention of image tags

- qa/L0_lifecycle/lifecycle_test.py
- qa/L0_lifecycle/test.sh
- src/http_server.cc
- src/http_server.h
- src/main.cc
Related PR: https://github.com/triton-inference-server/core/pull/335
When graceful shutdown begin, 
1. The HTTP endpoints stop accepting new connections (existing connections may continue).
2. The server will poll until all connections on the HTTP endpoints end, or `exit_timeout_secs_` expires, whichever is earlier.
3. The server passes the remaining timeout to the core and initiates core shutdown.
4. The core begins its shutdown routine as it is currently.
Example shutdown:
```
I0315 19:34:17.024361 101974 main.cc:329] Timeout 30: Found 1 HTTP connections
I0315 19:34:18.024569 101974 main.cc:329] Timeout 29: Found 1 HTTP connections
I0315 19:34:19.024747 101974 main.cc:329] Timeout 28: Found 1 HTTP connections
I0315 19:34:20.025022 101974 server.cc:307] Waiting for in-flight requests to …
```
> HTTP live connections on server shutdown

- qa/L0_shared_memory/shared_memory_test.py
- qa/L0_shared_memory/test.sh
- src/shared_memory_manager.cc
This PR:
Deferred to separate PRs:
- need to investigate the right way to query device pointer allocated size from cuIPC handle
- need a test to validate the existing code would fail with bad permissions when container is setup with a non-root user (ex: `shm_open`)
ref: DLIS-6198
> Validate system shared memory region size when registering a region

- qa/L0_backend_python/async_execute/concurrency_test.py
- qa/L0_backend_python/async_execute/test.sh
- qa/L0_backend_python/test.sh
- qa/python_models/async_execute_decouple/config.pbtxt
- qa/python_models/async_execute_decouple/model.py
- qa/python_models/async_execute_decouple_bls/config.pbtxt
- qa/python_models/async_execute_decouple_bls/model.py
Related PR: https://github.com/triton-inference-server/python_backend/pull/350
Tests for Python backend decoupled async execute function. Covered cases:
* A async execute function may start multiple coroutines and those are ran concurrently.
* Multiple async execute coroutines are ran concurrently.
* An async execute coroutine started late but finished early will respond before another async execute coroutine that started early but finished late.
* A coroutine may raise an exception and it will be logged.
> Decoupled Async Execute

- qa/L0_backend_python/async_execute/concurrency_test.py
- qa/L0_backend_python/async_execute/test.sh
- qa/L0_backend_python/test.sh
- qa/python_models/async_execute_decouple/config.pbtxt
- qa/python_models/async_execute_decouple/model.py
- qa/python_models/async_execute_decouple_bls/config.pbtxt
- qa/python_models/async_execute_decouple_bls/model.py
* Add async execute decoupled test
* Add decoupled bls async exec test
* Enhance test with different durations for concurrent executes
> Decoupled Async Execute (#7062)

- qa/L0_logging/logging_endpoint_test.py
- qa/L0_logging/test.sh
- src/grpc/grpc_server.cc
- src/http_server.cc
Disable dynamic log file location, aka --log_file API.
> Disable dynamic log file

- qa/L0_shared_memory/shared_memory_test.py
- qa/L0_shared_memory/test.sh
- src/grpc/infer_handler.cc
- src/grpc/infer_handler.h
- src/http_server.cc
- src/shared_memory_manager.cc
- src/shared_memory_manager.h
Validate that memory offset and byte size requested is not out of bounds  
of registered memory. 
Previously in #6914 we checked out of bounds offset for shared memory requests.
This PR also adds more testing to verify the block of memory  is in fact in bounds.
Client change: triton-inference-server/client#565
Cherry pick of: https://github.com/triton-inference-server/server/pull/7083
> Validate the memory requested for the infer request is not out of bounds

- qa/L0_trace/test.sh
- qa/L0_trace/trace_endpoint_test.py
- src/grpc/grpc_server.cc
- src/http_server.cc
- src/tracer.cc
- src/tracer.h
Commit on main https://github.com/triton-inference-server/server/commit/4491fb7b873d05e83c13fbfad51a20d599538120
> Disable dynamic trace file (#7106)

- qa/L0_grpc/test.sh
Testing for: https://github.com/triton-inference-server/client/pull/387
Client PR: https://github.com/triton-inference-server/client/pull/465
> Add test for reusing cached channels

- qa/L0_grpc_state_cleanup/cleanup_test.py
- qa/L0_grpc_state_cleanup/test.sh
- src/grpc/infer_handler.h
- src/grpc/stream_infer_handler.cc
There is a race condition with the `InferHandlerState::complete_` variable. When `ModelStreamInferHandler::StreamInferResponseComplete()` function is called with `TRITONSERVER_RESPONSE_COMPLETE_FINAL` flag, the `InferHandlerState::complete_` variable is updated to `true` before the function returns. Simultaneously, the executing `ModelStreamInferHandler::Process()` function will see the `InferHandlerState::complete_ == true` and instruct its caller `InferHandler::Start()` function to release the `InferHandlerState` object, which is required by the `ModelStreamInferHandler::StreamInferResponseComplete()` function to finish its execution, for instance, checking for `InferHandlerState::IsGrpcContextCancelled()`.
A possible sequence of actions, 
1. …
> Fix gRPC frontend race condition

- qa/L0_perf_analyzer/test.sh
Trace settings update from client support was discontinued in https://github.com/triton-inference-server/server/pull/7106
This PR removes testing in PA of trace settings updating from client.
> Remove client testing of server trace to match discontinued support from server

- qa/L0_perf_analyzer/test.sh
Re-adds in PA trace testing but just avoids using the discontinued trace-file setting
> Re-enable PA trace testing but remove setting trace file

- qa/L0_grpc/test.sh
- src/shared_memory_manager.cc
Fixes windows build caused by: https://github.com/triton-inference-server/server/pull/7083
> fix windows build for shared memory fix

- qa/L0_memory_growth/test.sh
The test is failing due to onnxruntime throwing CUDA OOM error. Decrease the concurrency and increase the repetition to make sure that CUDA memory isn't exhausted, and we still have enough amount of requests sending from PA to observe if the memory grows or not.
> Use a lower concurrency with more repetition for L0_memory_growth

- qa/python_models/torchvision/resnet50/model.py
This PR fixes the HTTP errors occurring in the L0_model_control_stress test, which were caused by extensive access to torch.hub during model loading
```
E0423 06:25:10.553733 50667 model_lifecycle.cc:638] failed to load 'resnet50_python' version 1: Internal: HTTPError: HTTP Error 403: rate limit exceeded
At:
/usr/lib/python3.10/urllib/request.py(643): http_error_default
/usr/lib/python3.10/urllib/request.py(496): _call_chain
/usr/lib/python3.10/urllib/request.py(563): error
/usr/lib/python3.10/urllib/request.py(634): http_response
/usr/lib/python3.10/urllib/request.py(525): open
/usr/lib/python3.10/urllib/request.py(216): urlopen
/usr/local/lib/python3.10/dist-packages/torch/hub.py(164): _read_url
/usr/local/lib/python3.10/dist-packages/torch/hub.py(181): _validate_not_a_forked_repo …
```
> Avoid the HTTP Error 403: rate limit exceeded error

- qa/L0_metrics/metrics_config_test.py
- qa/L0_metrics/model_namespacing_repos/addsub_repo/addsub_ensemble/config.pbtxt
- qa/L0_metrics/model_namespacing_repos/addsub_repo/composing_model/1/model.py
- qa/L0_metrics/model_namespacing_repos/subadd_repo/composing_model/1/model.py
- qa/L0_metrics/model_namespacing_repos/subadd_repo/subadd_ensemble/config.pbtxt
- qa/L0_metrics/test.sh
Related PR: https://github.com/triton-inference-server/core/pull/343
Add test to ensure "namespace" label exists on metrics when the server is launched with `--model-namespacing=true`.
> Add metrics model namespacing label test

- qa/L0_cuda_shared_memory/cuda_shared_memory_test.py
- qa/L0_cuda_shared_memory/test.sh
- qa/L0_grpc/python_grpc_aio_test.py
- qa/L0_shared_memory/shared_memory_test.py
- qa/common/infer_util.py
- src/CMakeLists.txt
- src/shared_memory_manager.cc
- src/shared_memory_manager.h
> Validate CUDA SHM region registration size

- build.py
triton_tensorrtllm_worker has been renamed to trtllmExecutorWorker. See here https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/inflight_batcher_llm/CMakeLists.txt#L352
> Rename triton_tensorrtllm_worker to trtllmExecutorWorker

- Dockerfile.QA
We need this to install go-grpc which is a dependency in our L0_grpc test.
This is needed to fix the test.
```
+ go install github.com/grpc-ecosystem/grpc-health-probe@latest
go: downloading github.com/grpc-ecosystem/grpc-health-probe v0.4.26
go: downloading google.golang.org/grpc v1.63.2
go: downloading github.com/spiffe/go-spiffe/v2 v2.2.0
go: downloading github.com/zeebo/errs v1.3.0
go: downloading google.golang.org/protobuf v1.33.0
go: downloading github.com/go-jose/go-jose/v4 v4.0.1
go: downloading golang.org/x/crypto v0.22.0
go: downloading golang.org/x/sys v0.19.0
go: downloading golang.org/x/sync v0.7.0
go: downloading google.golang.org/genproto/googleapis/rpc v0.0.0-20240401170217-c3f982113cda
go: downloading golang.org/x/net v0.24.0
go: downloading golang.org/x/text v0.14.0 …
```
> Upgrade the golang version to 1.22.3

- src/CMakeLists.txt
- src/shared_memory_manager.cc
This PR fixed the CUDA driver dependency issue on CPU-only system introduced in the previous PR https://github.com/triton-inference-server/server/pull/7178.
> Remove the dependency on CUDA driver

- docs/user_guide/model_configuration.md
- docs/user_guide/model_repository.md
- qa/L0_custom_model_config/test.sh
- qa/L0_lifecycle/lifecycle_test.py
- qa/L0_lifecycle/test.sh
- src/command_line_parser.cc
- src/command_line_parser.h
Add `--mode-config-name` option when starting Triton server. Allow users to select custom configurations other than default config.pbtxt.
core: https://github.com/triton-inference-server/core/pull/348
> Multiple Model Configurations

- docs/user_guide/model_configuration.md
- docs/user_guide/model_repository.md
- qa/L0_custom_model_config/test.sh
- qa/L0_lifecycle/lifecycle_test.py
- qa/L0_lifecycle/test.sh
- src/command_line_parser.cc
- src/command_line_parser.h
Add `--mode-config-name` option when starting Triton server. Allow users to create multiple configurations and select a custom configuration other than the default `model/config.pbtxt`.
> Multiple Model Configurations (#7185)

- qa/L0_simple_go_client/test.sh
The client should run at the same location as go.mod.
This is needed because go has moved to module only execution system.
Client PR: https://github.com/triton-inference-server/client/pull/663
> Fix the L0_simple_go_client

- src/command_line_parser.cc
- src/main.cc
**Before**: Specifying `--load-model` without explicit model control mode will silently not work as expected, and instead load all models with the default model control mode.
```
root@ced35d0-lcedt:/opt/tritonserver# tritonserver --model-repository models --load-model my_model
...
I0522 18:28:47.526658 448 http_server.cc:4692] Started HTTPService at 0.0.0.0:8000
```
**After**: Specifying `--load-model` without explicit model control mode will fail, and prompt you to also set `--model-control-mode=explicit`. **Parsing errors will also be reported at the bottom for immediate visibility.**
```
root@ced35d0-lcedt:/opt/tritonserver# tritonserver --model-repository models --load-model abc
...
LONG
HELP
OUTPUT
...
Error: Use of '--load-model' requires setting '--model-control-mode=explicit' as …
```
> Return an error if --load-model is specified without explicit model control mode

- qa/L0_backend_python/examples/test.sh
Jax has dropped the support for Python 3.8. See here for more info: https://jax.readthedocs.io/en/latest/changelog.html
> Exclude Jax example from Python 3.8

- qa/L0_backend_python/examples/test.sh
- qa/L0_backend_python/setup_python_enviroment.sh
- Fix the conda issue for Python 3.11
- There are some dependency problems: `UNAVAILABLE: Internal: ModuleNotFoundError: No module named 'six'` even though `six` is installed already. Seems like using conda install for TF for Python 3.11 doesn't not mess up with conda env anymore.
- Place the client log of L0_backend_python/example to the outer directory for CI to capture artifacts
> Minor fix for L0_backend_python

- qa/L0_backend_python/response_sender/response_sender_test.py
- qa/L0_backend_python/response_sender/test.sh
- qa/python_models/response_sender/model.py
- qa/python_models/response_sender/model_async.py
- qa/python_models/response_sender/model_common.py
Previous PR: https://github.com/triton-inference-server/server/pull/7254
Related PR: https://github.com/triton-inference-server/python_backend/pull/360
Add the following new tests:
* Non-decoupled model sending a response before / after returning.
* Decoupled / non-decoupled model handling batched requests each using a different style of returning response(s).
* Assert failure on decoupled model returning a response.
Next PR: https://github.com/triton-inference-server/python_backend/pull/361
> Add response sender test for new behavior

- qa/L0_backend_python/decoupled/decoupled_test.py
- qa/L0_backend_python/lifecycle/lifecycle_test.py
Previous PR: https://github.com/triton-inference-server/python_backend/pull/361
Related PR: https://github.com/triton-inference-server/python_backend/pull/362
Update the error message the test expects, given the decoupled data pipeline reports the same error in a different mechanism, which results in the message to be slightly different.
Next PRs:
* https://github.com/triton-inference-server/server/pull/7292
* https://github.com/triton-inference-server/python_backend/pull/363
> Update expected error message

- qa/L0_backend_python/bls/test.sh
- qa/L0_backend_python/response_sender/response_sender_test.py
- qa/L0_backend_python/test.sh
- qa/python_models/response_sender/model.py
- qa/python_models/response_sender/model_async.py
- qa/python_models/response_sender/model_common.py
- src/grpc/stream_infer_handler.cc
Previous PRs:
* https://github.com/triton-inference-server/server/pull/7258
* https://github.com/triton-inference-server/python_backend/pull/362
Related PR: https://github.com/triton-inference-server/python_backend/pull/363
Add tests for decoupled models using the `response_sender` and returning a response.
Add tests for non-decoupled models sending multiple responses, using the `response_sender` and/or returning a response.
> Add test for improper response sending from model

- build.py
Removes the onnxruntime library from the system path which seemed to have been added as a workaround for openVINO EP running behind onnxruntime backend. 
It has been verified with a glab pipeline with TRITON_NIGHTLY=1 that we no longer need this workaround to use the OV EP.
This might help resolve #7200. 
No additional tests were added. The current tests i.e. L0_onnx_optimization and l_onnx_execution_provider should provide sufficient coverage for whether the changes introduced any regressions.
#15568694
We can explore if we can now use different versions of openVINO between ORT and OpenVINO backend.
By including the …
> fix: Remove onnxruntime libraries from system path

- qa/L0_grpc_state_cleanup/cleanup_test.py
- qa/L0_grpc_state_cleanup/test.sh
- src/grpc/stream_infer_handler.cc
When using gRPC streaming for non-decoupled models, the frontend does not properly handle the case which the response and final flag are sent separately. The gRPC server will release the state as soon as the response is received, resulting in a possible segfault when the final flag is later received.
The fix is to defer sending the response if a final flag is not coupled with the response, and leave the gRPC step in WRITEREADY. Then, when the final flag is received, it continue sending the response and move to step WRITTEN.
This PR should merge before https://github.com/triton-inference-server/server/pull/7311
> Fix gRPC streaming non-decoupled segfault if sending response and final flag separately

- qa/L0_backend_python/bls/test.sh
- qa/L0_backend_python/decoupled/decoupled_test.py
- qa/L0_backend_python/lifecycle/lifecycle_test.py
- qa/L0_backend_python/response_sender/response_sender_test.py
- qa/L0_backend_python/response_sender/test.sh
- qa/L0_backend_python/test.sh
- qa/python_models/response_sender/config.pbtxt
- qa/python_models/response_sender/model.py
- qa/python_models/response_sender/model_async.py
- qa/python_models/response_sender/model_common.py
- src/grpc/stream_infer_handler.cc
Related PR: https://github.com/triton-inference-server/python_backend/pull/364
Add testing for using response sender in non-decoupled model. Add testing for different ways of sending response(s), i.e. sending before, after and/or during `execute()` return, for decoupled/non-decoupled and async/threaded models.
Items to be done on another ticket:
* Enable restart sub-test. [This functionality is never mentioned on documentation, so it is ok to skip it for now]
* Investigate why BLS CUDA shm pool 128 MB is using more memory.
Logistics:
* This PR should merge after https://github.com/triton-inference-server/server/pull/7265
* All commits on this PR came from previously approved PRs (less copyright/documentation updates), the purpose of this PR is to merge the feature into the main branch.
> Add support for response sender in the default mode

- qa/L0_request_cancellation/grpc_cancellation_test.py
- qa/L0_request_cancellation/test.sh
- src/grpc/infer_handler.cc
- src/grpc/infer_handler.h
This PR fixes an issue with a gRPC ModelInferHandler stopping accepting requests after a number of cancellation received.
Main root-cause and pre-conditions before hand:
At some point  cancellation notification is received at step `START`. When this happens, we never skip this [block](https://github.com/triton-inference-server/server/blob/352b88590424e83564f00baf411e1c017c694f8d/src/grpc/infer_handler.cc#L696-L699)
Since, we never went skip it, we don't create new state for future incoming requests, i.e.  [call `StartNewRequest`](https://github.com/triton-inference-server/server/blob/352b88590424e83564f00baf411e1c017c694f8d/src/grpc/infer_handler.cc#L729-L731)
Thus, completion queue becomes exhausted at some point. gRPC requests come, but there is nothing that accepts it on Triton's side. …
> fix: Handling grpc cancellation edge-case:: Cancelling at step START

- qa/L0_http/test.sh
- qa/L0_infer/test.sh
- qa/L0_input_validation/input_validation_test.py
Update error messages to comply with core change in infer_request.cc.
https://github.com/triton-inference-server/core/pull/364
L0_input_validation--base
- CI Pipeline ID: 15596087
Rewriting byte size validation check logic and changing error message.
> test: Update error messages to comply with core change

- qa/L0_model_config/noautofill_platform/missing_datatype/config.pbtxt
- qa/L0_model_config/noautofill_platform/missing_datatype/expected
- qa/L0_model_config/noautofill_platform/missing_datatype/expected_ensemble
- qa/L0_model_config/noautofill_platform/reshape_elementcount0/expected
- qa/L0_model_config/noautofill_platform/reshape_elementcount1/expected
- qa/L0_model_config/noautofill_platform/reshape_elementcount2/expected
- qa/L0_model_config/noautofill_platform/reshape_elementcount3/expected
- qa/L0_model_config/noautofill_platform/reshape_nobatch_empty0/expected
- qa/L0_model_config/noautofill_platform/reshape_nobatch_empty1/expected
- qa/L0_model_config/noautofill_platform/reshape_nobatch_variable0/expected
- qa/L0_model_config/noautofill_platform/reshape_nobatch_variable1/expected
- qa/L0_model_config/noautofill_platform/reshape_nobatch_variable2/expected
- qa/L0_model_config/noautofill_platform/reshape_nobatch_variable3/expected
- qa/L0_model_config/noautofill_platform/reshape_nobatch_variable4/expected
- qa/L0_model_config/noautofill_platform/reshape_nobatch_variable5/expected
- qa/L0_model_config/noautofill_platform/reshape_nobatch_zerodims0/expected
- qa/L0_model_config/noautofill_platform/reshape_nobatch_zerodims1/expected
- qa/L0_model_config/noautofill_platform/reshape_variable0/expected
- qa/L0_model_config/noautofill_platform/reshape_variable1/expected
- qa/L0_model_config/noautofill_platform/reshape_variable2/expected
- qa/L0_model_config/noautofill_platform/reshape_variable3/expected
- qa/L0_model_config/noautofill_platform/reshape_variable4/expected
- qa/L0_model_config/noautofill_platform/reshape_variable5/expected
- qa/L0_model_config/noautofill_platform/reshape_zerodims0/expected
- qa/L0_model_config/noautofill_platform/reshape_zerodims1/expected
- qa/L0_model_config/noautofill_platform/zerodims_input0/expected
- qa/L0_model_config/noautofill_platform/zerodims_input1/expected
- qa/L0_model_config/noautofill_platform/zerodims_output0/expected
- qa/L0_model_config/noautofill_platform/zerodims_output1/expected
- qa/L0_model_config/test.sh
Theses updates are added to test the new behavior of Triton core to include tensor names in the error message.
Changing mv to cp so that the test can be re-run multiple number of times in the devel container.
The related core PR: https://github.com/triton-inference-server/core/pull/353.
Passing L0_model_config run: JOB ID 96906455
For the following model configuration:
```
name: "missing_datatype"
max_batch_size: 4
platform: "tensorflow_savedmodel"
input [
{
name: "input"
dims: [ 2, -1 ]
}
]
output [
{
name: "output"
data_type: TYPE_FP32
dims: [ 1 ]
}
]
```
`E0611 19:35:52.422993 138 model_repository_manager.cc:1371] "Poll failed for model directory 'missing_datatype': model output must specify 'data_type' for missing_datatype"`
`
E0611 19:31:47.991606 9486 …
> test: Fix the test to expect updated error messages

- qa/L0_backend_python/io/io_test.py
- qa/L0_backend_python/io/test.sh
Add tests to establish the behavior of Python backend filtering outputs based on requested outputs from the client.
https://github.com/triton-inference-server/python_backend/pull/366
N/A
N/A
#15726534
#15745686
#15752015
N/A
N/A
N/A
> test: Python models filtering outputs based on requested outputs

- qa/L0_simple_ensemble/ensemble_test.py
- qa/L0_simple_ensemble/test.sh
Add test to ensure sequence flags are maintained correctly in case of streaming ensemble requests
Jira : https://jirasw.nvidia.com/browse/DLIS-6801
Core PR : https://github.com/triton-inference-server/core/pull/369
> test: Add test for sequence flags in ensemble streaming inference

- build.py
Fixed the version for setuptools to avoid breaking changes in the later versions.
L0_backend_trtllm* tests should be passing.
- CI Pipeline ID: 15903582
> fix: Fix version for setuptools and grpcio-tools. Remove cudnn 8 installation

- src/tracer.cc
- src/tracer.h
This PR introduces an improvement to our frontend OpenTelemetry tracing implementation. The main goal of this refactoring is to enhance the reliability and flexibility of the system.
Key Changes:
-  Introduced a Stack-Based Approach
- The previous implementation  relied on specific span names to preserve the trace hierarchy. 
- Current solution uses stacks and doesn't need to know what type of span was started.
- For ensemble and bls models, any number of sub-traces can be spawned. Since we preserve `parent_id` for every trace, I utilize this and introduced an unordered map to keep spans in stacks. Each trace and sub-trace has its own stack. When stack is empty, I use `parent_id` to check the top of the parent's stack to get parent span's information.
- This refactor also helps the …
> [refactor]: Refactor Frontend Trace OpenTelemetry Implementation

- build.py
Reduce intermediate layers in order to reduce TRT-LLM container size.
TRT-LLM backend build + tests should pass.
- CI Pipeline ID: 16294063
> build: Reduce intermediate layers

- qa/L0_trt_compat/test.sh
It seems like the error message from TRT might have changed from
```
Internal Error (Cannot deserialize engine...
```
to
```
API Usage Error (Cannot deserialize engine...
```
This PR fixes the expected error message for L0_trt_compat test so that the expected error message matches to the actual error message.
- CI Pipeline ID: 16446460
> fix: Fix error message for L0_trt_compat

- build.py
One of CI tests is failing with the latest version of vLLM. We will revert to 0.5.0.post1 which is known to be working until we can investigate further.
> [24.07] Revert vllm to 0.5.0.post1

- src/grpc/infer_handler.h
- src/grpc/stream_infer_handler.cc
- src/grpc/stream_infer_handler.h
Improve the response throughput of a single gRPC stream on the server frontend.
When there is a large number of responses, responses will compete with each others for the single write slot - a restriction imposed by gRPC that no concurrent write is allowed within a stream. A response that do not get a chance to write will be placed to the back of the completion queue and try again when it comes out. Unless the number of responses reduces immediately, the response that do not get a chance to write will likely not get a chance to write when it comes out. The same happens to other responses at the same time, resulting in a busy loop on the completion queue that impact performance.
This change introduces a new queue for holding responses that do not get a chance to write. When a new response …
> perf: Improve response throughput of a single gRPC stream

- build.py
- docs/user_guide/metrics.md
- qa/L0_backend_python/lifecycle/lifecycle_test.py
- qa/L0_model_queue/model_queue_test.py
- qa/L0_request_cancellation/scheduler_test.py
Currently We don't have any mechanism to count any failures that happen in triton core before the request gets to the backend.
Enhances existing metrics API to incorporate failure and failure counts in inference requests.
This PR adds new test
https://github.com/triton-inference-server/core/pull/377
RespondIfError function call in core
Test for **REJECTED**
Modified qa/L0_model_queue/model_queue_test.py to capture rejections in Ensemble Model and Non Ensemble Model in dynamic batcher.
custom_zero_1_float32 model expected to have 4 request rejects
Test for **OTHER**
Modified qa/L0_model_queue/model_queue_test.py to capture OTHER errors in …
> test: Tests for Metrics API enhancement to include error counters

- build.py
Downgrade ompi version to avoid ucc issues when running TRT-LLM container on kubernetes.
TRT-LLM backend build and tests should be passing.
- CI Pipeline ID: 16512052
> fix: Downgrade ompi version to v4.1.5rc2

- build.py
Update the openssh-client package in Triton TRTLLM containers. 
> Tprd 287 update openssh client for triton trtllm containers

- build.py
Uninstall setuptools after TRTLLM build as this is not required at runtime. 
* [Internal contribution template](https://raw.githubusercontent.com/triton-inference-server/server/main/.git …
> Uninstall setuptools after TRTLLM build

- build.py
Bumping vllm version to the latest.
vllm_backend : https://github.com/triton-inference-server/vllm_backend/pull/47
- CI Pipeline ID: 16687396
> [build]: Bumping vllm version to v0.5.3.post1

- qa/L0_backend_python/python_test.py
- qa/L0_backend_python/test.sh
- qa/python_models/identity_bf16/config.pbtxt
- qa/python_models/identity_bf16/model.py
Adds testing for the BF16 tensor support in Python Backend added here: https://github.com/triton-inference-server/python_backend/pull/371
- https://github.com/triton-inference-server/python_backend/pull/371
- `L0_backend_python::python_test.py::test_bf16`
- CI Pipeline ID: 17050551
See feature PR.
> test: Add BF16 test for python backend

- qa/L0_logging/log_format_test.py
- qa/L0_logging/test.sh
Adds more graceful handling to server startup given the way it's launched in the L0_logging test.
Current test is failing intermittently with call to `client.is_server_ready()` raising an `Exception` on a failed connection. This can happen if the frontends aren't ready and accepting requests yet while server is still starting up.
This PR:
1. Gives more time for natural server startup
2. Adds better handling for exceptions raised by client on failing to connect 
3. Exits early if `DATADIR` isn't set correctly to smooth local testing
- `L0_logging`
> test: Improve L0_logging stability

- qa/L0_backend_python/argument_validation/test.sh
- qa/L0_backend_python/bls/test.sh
- qa/L0_backend_python/custom_metrics/test.sh
- qa/L0_backend_python/request_rescheduling/test.sh
- qa/L0_backend_python/setup_python_enviroment.sh
- qa/L0_backend_python/test.sh
- qa/L0_backend_python/test_infer_shm_leak.py
- qa/L0_dlpack_multi_gpu/test.sh
- qa/L0_warmup/test.sh
- qa/common/shm_util.py
Return custom exit code `123` to indicate known shm leak failure in L0_backend_python bls test. CI will catch the custom exit code and allow the L0_backend_python test to fail if the known issues occur.
In order to propagate the exit code correctly, Python unittest and Pytest can not be used at the same time. In this PR, the `python_unittest.py` is replaced with `test_infer_shm_leak.py` which uses Pytest directly.
tritonserver MR !236.
L0_backend_python should fail with `allowed to fail` if it's failing due to the known shm leak from bls sub test.
- CI Pipeline ID: 17025308
> ci: Return custom exit code to indicate known shm leak failure in L0_backend_python bls test

- Dockerfile.sdk
- docs/customization_guide/build.md
- docs/customization_guide/test.md
Add default value for argument `TRITON_REPO_ORGANIZATION` from sdk Dockerfile. Otherwise it breaks manual build described from https://github.com/triton-inference-server/server/blob/main/docs/customization_guide/test.md#build-sdk-image. This issue seems introduced by PR https://github.com/triton-inference-server/server/pull/6934
And add instruction about clone perf analyzer repo for SDK image build. It's new added to sdk Dockerfile by https://github.com/triton-inference-server/server/pull/7449. And escape angle brackets surrounded strings properly.
n/a
n/a
Manual build sdk docker image that's described from …
> build: Add default value for argument 'TRITON_REPO_ORGANIZATION' from sdk Dockerfile

- README.md
- deploy/gke-marketplace-app/README.md
- deploy/k8s-onprem/README.md
- docs/README.md
- docs/contents.md
- docs/examples/jetson/README.md
- docs/generate_docs.py
- docs/user_guide/debugging_guide.md
- docs/user_guide/faq.md
- docs/user_guide/jetson.md
- docs/user_guide/model_analyzer.md
- docs/user_guide/model_configuration.md
- docs/user_guide/optimization.md
- docs/user_guide/perf_analyzer.md
- docs/user_guide/performance_tuning.md
- qa/L0_perf_analyzer_doc_links/test.sh
Update the PA README in server to point to the PA  repo.
Client changes: https://github.com/triton-inference-server/client/pull/771
PA changes: https://github.com/triton-inference-server/perf_analyzer/pull/21
DALI changes: https://github.com/triton-inference-server/dali_backend/pull/254
MA changes: https://github.com/triton-inference-server/model_analyzer/pull/925
PyTriton changes: https://github.com/triton-inference-server/pytriton/pull/80
Tutorial changes: https://github.com/triton-inference-server/tutorials/pull/105
> chore:Purge PA from Client Repo

- Dockerfile.sdk
- qa/L0_client_build_variants/test.sh
The objective of `L0_client_build_variants` is to build client libraries/binaries by enabling/disabling various optional features and verify that the build succeeds.
One such set of combinations is to enable/disable optional PA features and verify the build succeeds. This test had been passing (false positive) despite running with a client branch that purged PA from the client repo. Examining the logs closer, it was because CMake was simply ignoring PA-related parameters and repeatedly performing the same standard cc-client/python-client build:
```bash
Manually-specified variables were not used by the project:
TRITON_ENABLE_PERF_ANALYZER
TRITON_ENABLE_PERF_ANALYZER_C_API
TRITON_ENABLE_PERF_ANALYZER_TFS
TRITON_ENABLE_PERF_ANALYZER_TS
```
These changes modify the script to point to PA …
> PA Migration: Update L0_client_build_variants

- qa/L0_backend_python/response_sender/response_sender_complete_final_test.py
- qa/L0_backend_python/response_sender/test.sh
- qa/python_models/response_sender_complete_final/config.pbtxt
- qa/python_models/response_sender_complete_final/model.py
Enhance existing test on response sender when the model would sent additional response(s) after sending the complete final flag. The additional response(s) should cause an exception to be raised.
This test enhancement is due to deleting the response factory after the response sender has sent the complete final flag, to ensure the model cannot accidentally trigger a dereference on the deleted response factory by sending response(s) after sending complete final flag.
https://github.com/triton-inference-server/python_backend/pull/373
https://github.com/triton-inference-server/vllm_backend/pull/55
Start with the related PRs before coming back …
> test: Add test for sending response after sending complete final flag

- build.py
- docs/user_guide/metrics.md
Add vLLM counter metrics access through python_backend custom metrics.
https://github.com/triton-inference-server/vllm_backend/pull/53
n/a
L0_backend_vllm/metrics_test
17372863
n/a
Customers requested.
n/a
> feat: Add vLLM counter metrics access through Triton 

- CMakeLists.txt
- build.py
- qa/L0_infer/install_and_test.sh
- src/CMakeLists.txt
This PR adds the following:
- Support for RHEL 8 compatible builds. 
- Public users will need to setup their RHEL-like systems and then use the `--no-container-build` since Triton Inference Server doesn't publish a base container with which to use
- NVIDIA users may build using a private base container to build
- Updated the `target_platform()` method in `build.py` to distinguish between debian and rhel-like systems. 
- A follow on PR to change the target platform from "linux" to "debian" will be generated after this. 
- Update to L0_infer to be able to execute on either debian-like or rhel-like systems. 
- Update to `CMakeLists.txt` files to correctly point at the `lib64` directories on rhel-like systems.
Check the [conventional commit …
> build: RHEL 8 Compatibility

- qa/python_models/custom_metrics/model.py
Tests histogram metric in custom_metrics.
https://github.com/triton-inference-server/vllm_backend/pull/56
https://github.com/triton-inference-server/python_backend/pull/374
https://github.com/triton-inference-server/core/pull/386
n/a
n/a
17487728
n/a
Customer requested histogram metrics from vLLM.
n/a
> test: Test histogram metric

- build.py
- docs/user_guide/metrics.md
Report vLLM counter metrics through Triton server
* [Internal contribution template](https://raw.githubusercontent.com/triton-inference-server/server/main/.github/PULL_REQUEST_TEMPLATE/p …
> feat: Add vLLM counter metrics access through Triton  (#7493)

- qa/L0_lifecycle/lifecycle_test.py
- qa/L0_lifecycle/test.sh
Add the following tests on model version reload:
1. If a version is loaded and unmodified, then it should not be reloaded on the next load request.
2. If a version is loaded but modified, then it should be reloaded on the next load request.
3. If a version is not loaded and its model file is in the model directory, then it should be loaded on the next load request.
4. If a version is not loaded nor its model file is in the model directory, then it should be loaded on the next load request.
5. If a generic file is modified on the model directory, i.e. `model_directory/common_dependency.py`, then all loaded version(s) should be reloaded on the next load request.
box here and add the …
> test: Load new model version should not reload loaded existing model version(s)

- docs/generate_docs.py
Raise errors in the documentation generation script so that CI doesn't falsely report that the job succeeded
> ci: Raise Documentation Generation Errors

- docs/generate_docs.py
Add tensorrtllm_backend into doc generation.
GitLab MR !1264
- CI Pipeline ID: 17763728
> docs: Add tensorrtllm_backend into doc generation

- docs/getting_started/trtllm_user_guide.md
Enhance the TRT-LLM user experience by adding a comprehensive user guide to bridge the gap between Triton users and TRT-LLM functionalities.
> docs: Triton TRT-LLM user guide

- qa/common/gen_jetson_trt_models
- qa/common/gen_qa_custom_ops
- qa/common/gen_qa_model_repository
Updating the model generation script to allow passing DOCKER_GPU_ARGS directly.
> Build: Updating to allow passing DOCKER_GPU_ARGS at model generation

- src/CMakeLists.txt
**Goal:** Don't build `tritonfrontend` for Windows.
> Don't Build `tritonfrontend` for Windows.

- src/CMakeLists.txt
Cherry pick based on: https://github.com/triton-inference-server/server/pull/7599
> Cherry-pick: Don't Build tritonfrontend for Windows

- build.py
- qa/L0_sequence_batcher/test.sh
Goal: Incorporate SBSA builds/tests and extended the smoke tests for x86 and SBSA to include L0_sequence_batcher. 
- [ X ] PR title reflects the change and is of format `<commit_type>: <Title>`
- [ X ] Changes are described in the pull request.
- [ X ] Verified that the PR passes existing CI.
- [ X ] Verified copyright is correct on all changed files.
- [ X ] build
- [ X ] test
PyTorch Backend changes: https://github.com/triton-inference-server/pytorch_backend/pull/139
TensorRT Backend changes: https://github.com/triton-inference-server/tensorrt_backend/pull/99
TensorFlow Backend changes: …
> build/test: RHEL8 EA3

- src/grpc/infer_handler.h
- src/grpc/stream_infer_handler.cc
This PR aims to fix an occasional error (caused by a race condition) that occurs when making multiple asynchronous requests to the ASR model in decoupled mode:
```
E0829 13:41:44.609857 147 stream_infer_handler.cc:528] "Should not print this! Decoupled should NOT write via WRITEREADY!"
```
- CI Pipeline ID: 18428769
> Fix: Add mutex lock for state completion check in gRPC streaming to prevent race condition

- qa/L0_perf_analyzer_capi/test.sh
Set stability threshold to a higher number (9999) to ensure PA gets stable measurement.s
qa/L0_perf_analyzer_capi/test.sh
PA sometimes cannot get stable measurements due to low stability threshold.
> ci: Set stability factor to a higher value

- python/openai/README.md
- python/openai/openai_frontend/main.py
Adding support to start the `KServeHttp` and `KServeGrpc` frontends from the `server/python/openai/openai_frontend/main.py`
> feat: KServe Bindings to start tritonfrontend

- python/openai/README.md
- python/openai/openai_frontend/main.py
- python/openai/tests/conftest.py
- python/openai/tests/utils.py
- Fix argparse typo with `args.port` instead of `args.openai_port`
- Cleanup argparse groups and documentation
- Make kserve frontends optional for now via `--enable-kserve-frontends` to allow opt-in since it's currently an "openai_frontend" application, and in case we need to allow users to disable kserve portions for some reason
- Add small section to README (can be fleshed out in other docs follow-up)
Cleanup to `--help` output example:
```
usage: main.py [-h] --model-repository MODEL_REPOSITORY [--tokenizer TOKENIZER] [--backend {vllm,tensorrtllm}]
[--tritonserver-log-verbose-level TRITONSERVER_LOG_VERBOSE_LEVEL] [--host HOST]
[--openai-port OPENAI_PORT] [--uvicorn-log-level {debug,info,warning,error,critical,trace}]
[--enable-kserve-frontends] [--kserve-http-port KSERVE_HTTP_PORT] …
```
> chore: Fix argparse typo, cleanup argparse groups, make kserve frontends optional

- qa/L0_python_api/test_kserve.py
Currently, if an inference request is sent with the `tritonclient` and the `gRPC` frontend is shutdown, the `StatusCode` and message returned varies depending on the timing of the operations. Modified `test_grpc_req_during_shutdown` to accept multiple possible `StatusCode` values.
18939299
> ci: Reducing flakiness of `L0_python_api` 

- qa/L0_http/generate_endpoint_test.py
- qa/L0_http/generate_models/mock_llm/config.pbtxt
- qa/L0_http/test.sh
- src/http_server.cc
The `generate` and `generate_stream` endpoints did not seem to work when directly querying TRTLLM backend with input tokens. This is because the `HTTPAPIServer::GenerateRequestClass::ExactMappingInput` does not send the correct size of an array input to `ReadDataFromJson`.
This PR also fixes https://github.com/triton-inference-server/tensorrtllm_backend/issues/369
Agreement](https://github.com/NVIDIA/triton-inference-server/blob/master/Triton-CCLA-v1.pdf)
Added a new test case to `L0_http` job.
Internal CI pipeline id: 18800660
> fix: usage of ReadDataFromJson in array tensors

- qa/L0_python_api/test_kserve.py
- qa/L0_python_api/testing_utils.py
Enhance Python gRPC streaming test to send multiple requests, and asserts the request ordering is preserved.
N/A
N/A
The updated test needs to pass either locally or on the CI.
- CI Pipeline ID: 19114649
N/A
The original test only sends one request and expects one response, which leaves the hole open for incorrect request/response ordering when there are multiple requests.
N/A
> test: Enhance Python gRPC streaming test to send multiple requests

- python/openai/openai_frontend/engine/utils/triton.py
- python/openai/openai_frontend/schemas/openai.py
- python/openai/tests/test_chat_completions.py
- python/openai/tests/test_openai_client.py
Adds support and some smoke testing for parameters of type `List` such as `stop: [".", ","]`. This is done by passing sampling_parameters to vLLM backend as serialized JSON string input rather than the previous `TRITONSERVER_Parameter` approach, which didn't support Lists.
Resolves the error:
```
"Unsupported Value. Can\'t convert <class \'list\'> to Request Parameter"
```
> fix: Support sampling parameters of type List for vLLM backend (stop words)

- docs/customization_guide/tritonfrontend.md
- qa/L0_python_api/test_kserve.py
- qa/L0_python_api/testing_utils.py
- src/python/examples/example.py
- src/python/tritonfrontend/_api/_kservegrpc.py
- src/python/tritonfrontend/_api/_kservehttp.py
Removes the keyword `Server` from the `tritonfrontend` package to avoid confusion with multiple definitions of `Server` in the core and frontend bindings.
Previously, using `tritonfrontend.KServeHttp` would look like this:
```
import tritonserver
from tritonfrontend import KServeHttp, KServeGrpc
server = tritonserver.Server(...).start(wait_until_ready=True)
http_service = KServeHttp.Server(server)
http_service.start()
```
New workflow replaces `KServeHttp.Server` with just `KServeHttp`:
```
import tritonserver
from tritonfrontend import KServeHttp, KServeGrpc
server = tritonserver.Server(...).start(wait_until_ready=True)
http_service = KServeHttp(server)
http_service.start()
```
- CI Pipeline ID: 19109526
> refactor: Removing `Server` subclass from `tritonfrontend`

- python/openai/README.md
Add beta note as OpenAI API design/structure/etc. may be subject to change as we collect early feedback.
> docs: Add beta note to OpenAI compatible API

- python/openai/openai_frontend/engine/triton_engine.py
If a user follows the example code and tries to use the `ensemble` instead of `tensorrt_llm_bls`, they will get this error:
```
curl -s http://localhost:9000/v1/chat/completions -H 'Content-Type: application/json' -d '{"model": "ensemble", "messages": [{"role": "user", "content": "Say this is a test!"}]}' | jq
INFO:     127.0.0.1:40064 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
{
"detail": "Unknown backend"
}
```
After the PR fix, the response will be correct:
```
curl -s http://localhost:9000/v1/chat/completions -H 'Content-Type: application/json' -d '{"model": "ensemble", "messages": [{"role": "user", "content": "Say this is a test!"}]}' | jq
INFO:     127.0.0.1:47946 - "POST /v1/chat/completions HTTP/1.1" 200 OK
{
"id": "cmpl-fefc9e2a-8a74-11ef-8e2a-0242c0a80102", …
```
> fix: Fix bug when targeting the TRT-LLM backend ensemble

- qa/L0_simple_ensemble/ensemble_test.py
- qa/L0_simple_ensemble/models/ensemble_partial_add_sub/config.pbtxt
- qa/L0_simple_ensemble/models/partial_add_sub/1/model.py
- qa/L0_simple_ensemble/models/partial_add_sub/config.pbtxt
- qa/L0_simple_ensemble/test.sh
Add test when the composing models of an ensemble do not provide all outputs on the model configuration. The inference should complete normally and return all outputs that are provided.
https://github.com/triton-inference-server/core/pull/399
N/A
N/A
- CI Pipeline ID: 19348789
N/A
N/A
N/A
> test: Allow ensemble to create the final response even if some of the outputs are not created

- python/openai/README.md
- python/openai/requirements-test.txt
- python/openai/requirements.txt
- python/openai/tests/vllm_models/llama-3.1-8b-instruct/config.pbtxt
Updates genai-perf command with `profile` subcommand for 24.08+
Adds missing copyrights to fix `L0_copyrights--build` - should be automated after merging https://github.com/triton-inference-server/server/pull/7699
> chore: Fix genai-perf command and add missing copyrights

- qa/L0_perf_nomodel/run_test.sh
- qa/L0_perf_nomodel/test.sh
Fix L0_perf_nomodel shared memory test - system and cuda.
* Update flag name `BENCHMARK_TEST_SHARED_MEMORY` to `TEST_SHARED_MEMORY`.
* Correctly set the `--output-shared-memory-size` flag for perf analyzer.
Root cause:
* The CI runners were re-configured to set `TEST_SHARED_MEMORY` instead of `BENCHMARK_TEST_SHARED_MEMORY`, causing the system/CUDA shared memory tests to run as non-shared memory test, resulting in no data reported for both shared memory tests since the re-configuration.
N/A
N/A
N/A
- CI Pipeline ID: 19429907
N/A
N/A
N/A
> fix: Fix L0_perf_nomodel shared memory

- CMakeLists.txt
- qa/L0_java_memory_growth/MemoryGrowthTest.java
- qa/L0_java_resnet/ResnetTest.java
https://github.com/triton-inference-server/onnxruntime_backend/pull/277
https://github.com/triton-inference-server/core/pull/403
> Revert "Change compute capablity min value (#7708)"

- python/openai/README.md
Add support matrix (and known limitations) around multi-gpu models for vLLM/TRTLLM
> docs: Add support matrix for model parallelism in OpenAI Frontend

- qa/L0_lifecycle/lifecycle_test.py
Add a small delay to L0_lifecycle test_load_new_model_version after each model reload, to prevent flaky results due to model version load/unload is not completed by the time it is checked by the test script.
N/A
Start by looking into the L0_lifecycle failure of pipeline 19628457
L0_lifecycle pass after the patch.
- CI Pipeline ID: 19662667
N/A
See https://github.com/triton-inference-server/server/pull/7730 and job 117883843
N/A
> test: Add small delay to L0_lifecycle test_load_new_model_version after each model reload

- build.py
related to: https://github.com/triton-inference-server/onnxruntime_backend/pull/276
> Removing caching on windows.

- build.py
**Goal:** Provide RHEL8 support for the Python backend.
PYBE changes: https://github.com/triton-inference-server/python_backend/pull/385
> build: RHEL8 Python Backend

- build.py
The PR is to address CI jobs that are failing due to tritonfrontend and tritonserver wheel installation PR [[Link](https://github.com/triton-inference-server/server/pull/7759)] with the following error message:
```
+ python3 -m pip install --upgrade pip
Requirement already satisfied: pip in /usr/lib/python3/dist-packages (24.0)
Collecting pip
Downloading pip-24.3.1-py3-none-any.whl.metadata (3.7 kB)
Downloading pip-24.3.1-py3-none-any.whl (1.8 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 45.0 MB/s eta 0:00:00
Installing collected packages: pip
Attempting uninstall: pip
Found existing installation: pip 24.0
ERROR: Cannot uninstall pip 24.0, RECORD file not found. Hint: The package was installed by debian.
```
From my understanding, the CI jobs were previously failing because the …
> fix: Fixing pip installation as a system package

- src/python/tritonfrontend/_api/_metrics.pyi
- tools/add_copyright.py
Added support to `add_copyright.py` for files with extension `*.pyi` (Python stub files). Once this PR is merged, copyright headers will automatically be added to any python stub files that are generated with the standard pre-commit workflow.
Ran pipeline with `L0_copyrights--build`.
- CI Pipeline ID: 20148091
> fix: Adding copyright support for `.pyi` files

- qa/common/check_copyright.py
Skip copyrights check for "expected" files in L0_model_config.
L0_copyrights--build
20150189
> fix: Skip copyrights check for "expected" files in L0_model_config

- pyproject.toml
- python/openai/tests/test_chat_completions.py
Allow test_chat_completions_invalid_chat_tokenizer test to be skipped if there is a network issue when accessing the invalid tokenizer.
N/A
N/A
The affected test should continue to pass on existing pipeline, and skipped when there is a network issue.
- CI Pipeline ID: N/A
N/A
N/A
N/A
> test: OpenAI frontend invalid chat tokenizer network issue WAR

- qa/L0_backend_python/bls/test.sh
- qa/L0_backend_python/common.sh
- qa/L0_backend_python/decoupled/test.sh
- qa/L0_backend_python/env/test.sh
- qa/L0_backend_python/io/test.sh
- qa/L0_backend_python/setup_python_enviroment.sh
- qa/L0_backend_python/test.sh
Fix L0_backend_python for Ubuntu 24.04 base container:
- Upgrade default Python version setting to 3.12
- Upgrade default Python version grep
- Upgrade removed PyTorch version
- ~~Upgrade removed cmake version from Kitware repo~~
- Upgrade outdated Conda version
- Upgrade outdated Conda libstd version
- Upgrade Conda python_3_10_environment to 3.12
- Upgrade outdated numpy and TF version for 3.12
- Add Python 3.10 env test
N/A
N/A
Show L0_backend_python can pass on Ubuntu 24.04 base
- CI Pipeline ID: 20372466 & 20380045
N/A
The base container has been upgraded from Ubuntu 22.04 to 24.04.
N/A
> test: Fix L0_backend_python for Ubuntu 24.04 base

- qa/L0_dlpack_multi_gpu/test.sh
- qa/L0_infer/test.sh
- qa/L0_io/test.sh
- qa/L0_libtorch_instance_group_kind_model/test.sh
- qa/L0_trace/opentelemetry_unittest.py
- qa/L0_warmup/test.sh
Upgrade torch installation to 2.3.1+cu118 for
- L0_infer_*
- L0_dlpack_multi_gpu
- L0_warmup
- L0_io
- L0_libtorch_instance_group_kind_model
Replace `self.assertEquals` with `self.assertEqual` for L0_trace as it's not supported in Python 3.12.
The below tests should be passing
- L0_infer_*
- L0_dlpack_multi_gpu--base
- L0_warmup--base
- L0_io--base
- L0_libtorch_instance_group_kind_model--base
- L0_trace
CI Pipeline ID: 20407536
> test: Fix tests for ubuntu 24.04. upgrade

- build.py
Downgrade ORT version from 1.20.0 to 1.19.2.
https://github.com/triton-inference-server/onnxruntime_backend/pull/284
20419664
> fix: Fix L0_onnx_execution_provider 

- qa/L0_model_update/instance_update_test.py
Update the unittest function for Python 3.12.
- CI Pipeline ID: Reusing 20334885
> test: Fix L0_model_update test

- Dockerfile.QA
Preinstalled maven package in ubuntu 24.04 includes JRE 1.21 which no longer compatible with compiler options 1.7 which we rely on in: 
https://github.com/search?q=repo%3Abytedeco%2Fjavacpp-presets+1.7+language%3A%22Maven+POM%22+&type=code
Related to: https://github.com/triton-inference-server/client/pull/808
> Removing maven installation as it causes side package installation

- build.py
**Goal:** Build adjustments to enable the TensorRT execution provider for the RHEL ORT backend (x86 only).
ORT Backend: https://github.com/triton-inference-server/onnxruntime_backend/pull/285
**20532958 && 20538224**
Only extends the build for RHEL x86.
> build: Support RHEL ORT TensorRT Execution Provider

- qa/L0_cuda_shared_memory/cuda_shared_memory_test.py
- qa/L0_cuda_shared_memory/test.sh
- qa/L0_http/http_test.py
- qa/L0_http/test.sh
- src/common.cc
- src/common.h
- src/http_server.cc
This PR addresses the following issue:
- When large data is sent to `/v2/repository/models/<model_name>/load`, the server converts the `param_len` variable from `size_t` to `const int` to pass it to `base64_decode_block`. This conversion can cause an integer overflow in `base64_decode_block`, leading to a server crash with a segmentation fault.
- A similar issue occurs with `/v2/cudasharedmemory/region/{}/register` when large data is sent for the `raw_handle` parameter.
- CI Pipeline ID: 20358255
> fix: Resolve integer overflow in Load API file decoding

- qa/L0_cuda_shared_memory/cuda_shared_memory_test.py
Resolves the following error:
`AttributeError: module 'tritonclient.utils.cuda_shared_memory' has no attribute 'SharedMemoryException'`
- CI Pipeline ID: 20772068
> ci: Fix L0_cuda_shared_memory

- python/openai/openai_frontend/main.py
Following updates to tritonfrontend package here that removed the `.Server` subclass from KServeHTTP and KServeGRPC classes: https://github.com/triton-inference-server/server/pull/7683
This should be observable when running the OpenAI frontend application with the `--enable-kserve-frontends` flag
> fix: Remove .Server subclass to reflect 24.12 tritonfrontend version

- qa/L0_backend_python/io/io_test.py
- qa/L0_backend_python/io/requested_output_model/config.pbtxt
- qa/L0_backend_python/io/requested_output_model/model.py
- qa/L0_backend_python/io/test.sh
Enhance Python backend requested outputs testing when extra outputs from the model are deleted.
https://github.com/triton-inference-server/python_backend/pull/390
Start with the change on the related PR, and then look at the new test case on this PR.
N/A
- CI Pipeline ID: See related PR.
N/A
N/A
N/A
> test: Fix requested output deleting extra outputs

- build.py
This change is a motivation to cover issue in usage of `build.py` for scenario where is no appropriate backend is given.
https://github.com/triton-inference-server/server/pull/7843
Branch `main`: 
1. Without "python_backend"
```
$ python3 build.py --target-platform linux --enable-logging --enable-stats --enable-metrics --enable-cpu-metrics --endpoint grpc --endpoint http --filesystem s3 --dryrun
...
...
$ grep -R 'PIP_BREAK_SYSTEM_PACKAGES' build/
build/Dockerfile.buildbase:ENV PIP_BREAK_SYSTEM_PACKAGES=1
```
2. With "python_bakcend" 
```
$ python3 build.py --target-platform linux --enable-logging --enable-stats --enable-metrics --enable-cpu-metrics --endpoint grpc --endpoint http --filesystem s3 --dryrun  --backend=python
...
...
$ grep -R 'PIP_BREAK_SYSTEM_PACKAGES' build/ …
```
> Update generated Dockerfile

- src/CMakeLists.txt
- src/python/tritonfrontend/CMakeLists.txt
After #7787, L0_build_variants started failing with the following error message:
```
...
=== Building wheel
=== Output wheel file is in: /workspace/build/tritonserver/build/triton-server/python/generic
[ 98%] Built target frontend-server-wheel
[100%] Linking CXX executable tritonserver
/usr/bin/ld: CMakeFiles/main.dir/common.cc.o: in function `triton::server::DecodeBase64(char const*, unsigned long, std::vector<char, std::allocator<char> >&, unsigned long&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
common.cc:(.text+0x76a): undefined reference to `base64_init_decodestate'
/usr/bin/ld: common.cc:(.text+0x77b): undefined reference to `base64_decode_block'
collect2: error: ld returned 1 exit status
gmake[5]: *** …
```
> build: Adding b64 dependency to relevant targets (fix L0_build_variants)

- src/CMakeLists.txt
- src/python/tritonfrontend/CMakeLists.txt
Cherry-pick https://github.com/triton-inference-server/server/pull/7855 into r24.12
Pipeline ID: 21450412
> build: Adding b64 dependency to relevant targets (fix L0_build_variants) (#7855)

- python/openai/openai_frontend/main.py
- python/openai/requirements.txt
Cherry-pick https://github.com/triton-inference-server/server/pull/7881 into r24.12
Pipeline ID: 21458354
> fix: Lock httpx version to fix L0_openai--trtllm test failures (#7870)

- python/openai/openai_frontend/engine/triton_engine.py
- python/openai/openai_frontend/schemas/openai.py
- python/openai/tests/test_chat_completions.py
I found an issue with the OpenAI message format where user messages that are not strings are automatically converted to strings by the code, resulting in a `[ChatCompletionResponseMessageContentPart(text="~~~")]` string conversion problem. I have fixed this issue.
Agreement](https://github.com/NVIDIA/triton-inference-server/blob/master/Triton-CCLA-v1.pdf)
#7561
@rmccorm4 
To fix the issue of ChatCompletionResponseMessageContentPart being mixed with the output
> fix: openai chat message dump logic

- qa/L0_backend_python/lifecycle/lifecycle_test.py
- qa/L0_backend_python/response_sender/response_sender_complete_final_test.py
- qa/L0_backend_python/response_sender/response_sender_test.py
- qa/L0_backend_python/response_sender/test.sh
- qa/L0_batcher/queue_timeout_test.py
- qa/L0_batcher/test.sh
- qa/L0_trt_plugin/test.sh
- qa/common/infer_util.py
Fixes accumulated errors in Windows CI.
CI Pipeline ID:
20833929
> ci: Fix Windows CI Errors

- qa/L0_backend_python/lifecycle/lifecycle_test.py
- qa/L0_backend_python/response_sender/response_sender_complete_final_test.py
- qa/L0_backend_python/response_sender/response_sender_test.py
- qa/L0_backend_python/response_sender/test.sh
- qa/L0_batcher/queue_timeout_test.py
- qa/L0_batcher/test.sh
- qa/L0_trt_compat/test.sh
- qa/L0_trt_plugin/test.sh
- qa/common/infer_util.py
Cherry pick for these fixes: https://github.com/triton-inference-server/server/pull/7837
> [Cherry Pick] ci: Fix Windows CI Errors

- build.py
- qa/L0_openai/test.sh
Changes:
- Installs OpenAI-Compatible Frontend source code and dependencies into the containers
- Updates Triton CLI to support newer TRTLLM container versions
Related PRs:
- tritonserver !1382
Pipeline:
- 21678754
> feat: Add OpenAI-Compatible Server to NGC Container

- build.py
https://github.com/triton-inference-server/core/pull/414 proposes some improvements and automation to our core python binding wheel build, but requires the python `build` package to be installed. 
This PR adds this package to the build image.
Pipeline: 21672308
> build: Add python build package for building core python bindings

- python/openai/README.md
- 24.12 vllm image
- Reduced setup instructions for vllm with pre-installed dependencies
- Update to 24.11 for trtllm image for now, can be bumped to 24.12 and have similar reduction in setup steps after verification
> docs: Update OpenAI README for 24.12 release

- qa/L0_sequence_corrid_batcher/sequence_corrid_batcher_test.py
- qa/L0_sequence_corrid_batcher/test.sh
1. Add unit tests to validate input correlation ID data type.
https://github.com/triton-inference-server/core/pull/425
https://github.com/triton-inference-server/core/pull/425
- L0_sequence_corrid_batcher
22217066
> test: Validate request correlation ID data type 

- qa/common/gen_qa_trt_plugin_models.py
I believe this script is based on the TRT script [here](https://github.com/NVIDIA/TensorRT/blob/main/samples/python/onnx_custom_plugin/load_plugin_lib.py). These changes extend the script to support loading Windows plugin .dlls as well.
> build: Extend TRT Plugin Handling to Support Windows

- python/openai/openai_frontend/frontend/fastapi/__init__.py
Renames `__init__py` typo -> `__init__.py` and adds copyright header.
> fix: Fix package placeholder file name

- qa/L0_trace/test.sh
Changes:
- Remove invalid check for trace_mode after expected error that always produced `RET=1` because the `curl.out` only contained `{"error": ...}` but we checked for `trace_mode` count to be non-zero
- Remove RET=0 reset in middle of script - this was masking the error above
- Add 'cat curl.out' to various places that check the contents and may fail for easier visibility to error in logs. I had to repro the first 2 bullets locally to understand what was happening, so adding this to dump out the `curl` responses so we can better determine what
> ci: Fix error-masking bug and improve debugability in L0_trace

- qa/L0_pinned_memory/test.sh
L0_pinned_memory fails intermittently due to PA unstable measurements that are not critical to the test functionality - this is not a performance test.
This PR adds the use of `--request-count` in PA to remove PA stability criteria and make L0_pinned_memory test more consistent
---
In reality, we probably don't need to be using PA for this test, and can swap it out with a simpler client that doesn't measure performance.
For simplicity, we can just relax the stability requirements on PA to avoid this error with minimal changes for now.
> ci: Stabilize L0_pinned_memory flakiness

- qa/L0_lifecycle/test.sh
There are four tests in L0_lifecycle that the server shutdown is triggered by the py test, which may not return by the time the server completes its shutdown, causing the failure that the test script is trying to shutdown a stopped server.
N/A
N/A
L0_lifecycle should pass.
- CI Pipeline ID: 22497034
N/A
N/A
N/A
> ci: Fix L0_lifecycle server shutdown

- qa/L0_implicit_state/models/growable_memory/config.pbtxt
Update the config file with `max_sequence_idle_microseconds` to avoid sequence timeouts in server
- [] Related issues are referenced.
- [] Populated [github labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels) field
- [] Optional: Additional screenshots for behavior/output changes with before/after.
NA
Config file
NA
https://gitlab-master.nvidia.com/dl/dgx/tritonserver/-/pipelines/22507783
Server waits for `max_sequence_idle_microseconds` before closing the request sequence and expects the client to start a NEW sequence for ANY subsequent request.
Test was failing because …
> fix: Fix L0_implicit_state and it's variants

- qa/L0_perf_analyzer_capi/test.sh
1. Add `STABILITY_THRESHOLD` consistently to all test cases - this isn't a performance test and shouldn't be failing on stability measurements. 
2. Remove negative test for using async mode with triton_c_api. It looks like async support for triton_c_api was added [here](https://github.com/triton-inference-server/perf_analyzer/pull/35) with the addition of TRT-LLM engine in-process support. See screenshot below.
> test: Stabilize L0_perf_analyzer_capi test consistency

- qa/L0_io/gen_libtorch_model.py
- qa/L0_io/test.sh
By reducing the hardware requirement to 2 GPUs, we can get this test running again in CI. 
It didn't appear from the test logic that 4 GPUs were actually needed - that requirement was just inherited from the model generation script previuosly copied from:
```
cp ../L0_libtorch_instance_group_kind_model/gen_models.py ./gen_libtorch_model.py
```
By adding a modified copy of this script for 2 GPUs to the test directory itself, it is unblocked from the 4 GPU requirement.
> test: Update L0_io to work with only 2 GPUs instead of requiring 4 GPUs

- qa/L0_lifecycle/test.sh
Pick https://github.com/triton-inference-server/server/pull/7933 into 25.01 release
Continuing from previously [corrupted PR](https://github.com/triton-inference-server/server/pull/7936)...
> ci: Fix L0_lifecycle server shutdown (#7933)

- qa/L0_openai/test.sh
Replaced Triton CLI usage in the test with TRTLLM tooling for less maintenance effort.
MR 413
- CI Pipeline ID: 22617636
> ci: Fix/Improve L0_openai_trtllm test

- build.py
- docs/user_guide/jetson.md
Downgrade patchelf version from 0.18.0 to 0.17.2 due to patchelf regression
Patchelf shipped a regression in 0.18.0 and has since yanked the pypi release pointing to
0.17.2 as the most recent version. However, 0.18.0 is still the version shipped in both the apt and yum
repositories, thus we must use pip to install the version we want.
See https://github.com/mayeut/patchelf-pypi/issues/87
- https://github.com/triton-inference-server/pytorch_backend/pull/145
- https://github.com/triton-inference-server/openvino_backend/pull/94
- https://github.com/triton-inference-server/onnxruntime_backend/pull/295
- …
> build: Downgrade patchelf version from 0.18.0 to 0.17.2 

- docs/customization_guide/build.md
Remove unused build documentation section. It has been under construction for a long time.
- [ X] docs
We have received questions about this section, but there is not a clear path for this documentation. It has existed for a long time in this state, so removing it makes sense to avoid confusion.
> docs: Remove unused build documentation

- qa/L0_backend_python/parameters/response_parameters_test.py
- qa/L0_backend_python/parameters/test.sh
- qa/L0_backend_python/test.sh
- qa/python_models/response_parameters/config.pbtxt
- qa/python_models/response_parameters/model.py
- qa/python_models/response_parameters_decoupled/config.pbtxt
- qa/python_models/response_parameters_decoupled/model.py
Add tests for Python backend response parameters.
https://github.com/triton-inference-server/python_backend/pull/394
Start with `test_setting_three_element_response_parameters` test case first to get a sense on the feature, and then move on to other test cases, and finish with `test_setting_response_parameters_decoupled` test case.
N/A
- CI Pipeline ID: (See the related Python backend PR for the pipeline Id)
N/A
N/A
N/A
> test: Add Python backend response parameters test

- Dockerfile.QA
Fix `L0_storage_swiftstack` due to [botocore 1.36 incompatibility](https://github.com/boto/boto3/issues/4392). The solution is to pin `awscli<=1.36.40` to make sure we use `botocore<1.36` or else we'd run into the following error when uploading to 3rd party s3 clone:
```
An error occurred (InvalidArgument) when calling the PutObject operation: x-amz-content-sha256 must be UNSIGNED-PAYLOAD, or a valid sha256 value
```
> ci: Pin awscli version due to botocore incompatibility to fix L0_storage_swiftstack

- qa/L0_infer/infer_test.py
minor improvement on L0_infer infer_test.py skip pytorch test output msg to make it clearer 
> test: minor improvement on L0_infer infer_test.py skip pytorch test output msg

- qa/L0_onnx_optimization/test.sh
Tests corresponding to this PR https://github.com/triton-inference-server/onnxruntime_backend/pull/294
https://github.com/triton-inference-server/onnxruntime_backend/pull/294
- CI Pipeline ID: 22894431
- closes GitHub issue: [#166](https://github.com/triton-inference-server/onnxruntime_backend/issues/166)
> test: Add a test for session config in onnxruntime backend

- build.py
Images built for RHEL which did not specify a base image defaulted to Ubuntu 24.04 which caused error during the docker build stage as the `yum` package manager was unavailable. This change causes `build.py` to error out with a message should the RHEL target be specified without a base image also being specified.
Specification of a RHEL base image does _not_ guarantee that the container will build as there are internal dependencies that may be missing.
> build: Dockerfiles generated by build.py for RHEL require base image specification

- src/python/tritonfrontend/CMakeLists.txt
This change is subject to provide resolution for the issue: https://github.com/triton-inference-server/server/issues/7939
It was verified locally and I need to wait on CI.
> build: Fix '--no-container-build' option for 'build.py'

- build.py
- python/openai/requirements.txt
Moving our base vllm version to the latest.
Related PR on vllm backend: https://github.com/triton-inference-server/vllm_backend/pull/81
- CI Pipeline ID: 23116416
> [build] Bumping vllm version to 0.7.0

- build.py
- python/openai/requirements.txt
Related to these two PRs:
* https://github.com/triton-inference-server/server/pull/7978
* https://github.com/triton-inference-server/vllm_backend/pull/81
* 
* https://github.com/triton-inference-server/server/pull/7978
* https://github.com/triton-inference-server/vllm_backend/pull/81
> [build] Bumping vllm version to 0.7.0 (#7978)

- deploy/k8s-onprem/README.md
- deploy/k8s-onprem/templates/deployment.yaml
- deploy/k8s-onprem/templates/rbac.yaml
- deploy/k8s-onprem/templates/serviceaccount.yaml
- deploy/k8s-onprem/values.yaml
Enables deployment, out of the box, on OpenShift by adding the `openshift` toggle to the `tags` top-level values key in the `k8s-onprem` Chart. If this option is enabled, a custom SecurityContextConstraint and bindings to support it are made to a ServiceAccount that is now used for all deployments - instead of using the namespace's `default` account.
With this change:
```
$ helm upgrade --install --namespace triton triton deploy/k8s-onprem --set-json 'tags={"autoscaling":false,"loadBalancing":false,"openshift":true}'
Release "triton" has been upgraded. Happy Helming!
NAME: triton
LAST DEPLOYED: Tue Feb 11 11:44:10 2025
NAMESPACE: triton
STATUS: deployed
REVISION: 2
TEST SUITE: None
$ oc get pod -n triton
NAME                                              READY   STATUS    RESTARTS   AGE …
```
> fix: enable deployment on OpenShift

- Dockerfile.sdk
* SDK container is supposed to contain the version of PA and GAP that was built during its job
* `pip`-installing the GAP wheel built in the SDK job causes [tritonclient](https://pypi.org/project/tritonclient/) from PyPI to be installed
* [tritonclient](https://pypi.org/project/tritonclient/) from PyPI contains its own `perf_analyzer` binary that it installs to `/usr/local/bin`
* [tritonclient](https://pypi.org/project/tritonclient/) from PyPI is going to contain last month's `perf_analyzer` binary (older than the `perf_analyzer` binary built in the SDK job)
* This SDK Dockerfile was inadvertently installing its manually-built `perf_analyzer` binary into `/usr/local/bin` and _then_ `pip`-installing the manually-built GenAI-Perf wheel, causing the previously installed `perf_analyzer` to …
> Reverse order of GAP and PA installation to avoid installing outdated PA

- qa/L0_batch_custom/test.sh
Fix L0_batch_custom - missing [CMake variables](https://github.com/triton-inference-server/backend/blob/main/examples/batching_strategies/volume_batching/CMakeLists.txt#L34) that could result in defaulting to the wrong main branch instead of the branch picked by $TRITON_BACKEND_REPO_TAG
qa/L0_batch_custom/test.sh
25186266
This args require to be passed in to avoid using the default main branch for cases where previous release branches are used. 
> [test]: Fix L0_batch_custom - missing CMake variables that could result in defaulting to the wrong main branch

- docs/contents.rst
- docs/llm_features/speculative_decoding.rst
- docs/llm_features/speculative_decoding_by_backend_type.rst
Renaming `AI Agents` to `Features` since `Constrained Decoding` and `Function Calling` are more like features. 
Also, vLLM side is using Features as well for `Tool Calling` and `Speculative Decoding`
> docs: rename userguide AI Agents section to Features | add spec decoding to Features

- docs/contents.rst
- docs/llm_features/speculative_decoding.rst
- docs/llm_features/speculative_decoding_by_backend_type.rst
> docs: rename userguide AI Agents section to Features | add spec decoding to Features (#8099)

- README.md
- docs/examples/fetch_models.sh
This PR is needed for 25.03, since in 25.03, all TF models would not be loaded. So in the guide, we have to use extra flags to load the onnx model only.
Tested manually and the new cmd works in 25.02.
> docs: change server README to only load densenet_onnx since tf model cannot load after 25.03

- qa/L0_response_cache/ensemble_cache_test.py
TF model would dump its response data on the CPU even if the model was GPU. However, ORT dumps data in GPU memory for the next step to consume it. It only copies the data to CPU if the response data is required. As response cache only supports data from CPU memory we were not populating the cache. Hence seeing no cache hit.
> Fix L0_response_cache test

- src/python/setup.py
The new pydantic release 2.11.1 introduced a some incompatibility to the openai frontend
The list model api will break due to this upgrade
```
root@1ef6a0acb532:/opt/tritonserver# python3 client.py
INFO:     127.0.0.1:43300 - "GET /v1/models HTTP/1.1" 200 OK
Traceback (most recent call last):
File "/opt/tritonserver/client.py", line 11, in <module>
models = client.models.list()
^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/openai/resources/models.py", line 91, in list
return self._get_api_list(
^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/openai/_base_client.py", line 1332, in get_api_list
return self._request_api_list(model, page, opts)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/openai/_base_client.py", …
```
> fix: pin pydantic version for openai compatibility

- qa/L0_backend_python/decoupled/decoupled_test.py
- qa/L0_backend_python/decoupled/models/decoupled_bls_async_cancel/1/model.py
- qa/L0_backend_python/decoupled/models/decoupled_bls_async_cancel/config.pbtxt
- qa/L0_backend_python/decoupled/models/decoupled_bls_cancel/1/model.py
- qa/L0_backend_python/decoupled/models/decoupled_bls_cancel/config.pbtxt
- qa/L0_backend_python/decoupled/models/decoupled_bls_cancel_after_complete/1/model.py
- qa/L0_backend_python/decoupled/models/decoupled_bls_cancel_after_complete/config.pbtxt
- qa/L0_backend_python/decoupled/test.sh
- qa/python_models/response_sender_until_cancelled/config.pbtxt
- qa/python_models/response_sender_until_cancelled/model.py
Add tests cancelling BLS decoupled request in Python backend.
https://github.com/triton-inference-server/python_backend/pull/398
Check the response_sender_until_cancelled python decoupled model added and then check the two added testing models.
The tests are based on the two added testing models sending BLS requests to the response_sender_until_cancelled python decoupled model.
- CI Pipeline ID: 25879687
NA
NA
https://jirasw.nvidia.com/browse/DLIS-7831
> test: Add tests cancelling BLS decoupled request in Python backend

- build.py
> ci: Removed obsolete lib: libnvToolsExt.so

- Dockerfile.QA
- qa/L0_input_validation/test.sh
- src/test/CMakeLists.txt
- src/test/backend_api_test.cc
- src/test/backend_tensor_size_test.cc
Tests modified and new `GetElementCount` and `GetByteSize` functions.
https://github.com/triton-inference-server/backend/pull/112
https://github.com/triton-inference-server/onnxruntime_backend/pull/304
https://github.com/triton-inference-server/tensorrt_backend/pull/111
https://github.com/triton-inference-server/pytorch_backend/pull/149
https://github.com/triton-inference-server/python_backend/pull/400
https://github.com/triton-inference-server/openvino_backend/pull/103
https://github.com/triton-inference-server/identity_backend/pull/31
Review the changes in backend_common.h and backend_common.cc to prevent overflow. …
> test: Add backend_api_test to test backend APIs

- build.py
This PR converts the build arguments used for internal vLLM into secrets.
- build.py
#28811183
- Better practice for dealing with repo URL variables.
> build: Convert vLLM index url ARGS into docker secrets

- qa/L0_decoupled/decoupled_test.py
- qa/L0_decoupled/test.sh
- src/grpc/infer_handler.cc
This PR is intended to fix the following issue:
- In gRPC inference for a non-decoupled model, where the response and final flag are sent separately, if the client cancels the request before the final flag is sent (while sending the response), the related `response_release_payload` will be deleted during the cancellation handling. This causes a problem because the next call to `InferResponseComplete` (sending the final flag) will attempt to use a state that no longer exists.
Made changes to the existing test cases to cover more test data. Also added new test cases, `test_grpc_async_cancel` and `test_grpc_async`, to test the code changes.
- …
> fix: Improve cancellation handling for gRPC non-decoupled inference

- qa/L0_trace/test.sh
Occasionally only 10 traces are written to `collected_traces.json` at [the check](https://github.com/triton-inference-server/server/blob/cea9d69e281100cebc788e3dcea8a037231c2b18/qa/L0_trace/test.sh#L1093) (expect 11). Give more time for the final trace to be collected. 
https://github.com/triton-inference-server/common/pull/133
https://github.com/triton-inference-server/core/pull/438
Previous PR: https://github.com/triton-inference-server/core/pull/429
L0_trace
L0_simple_ensemble
L0_sequence_batcher
L0_backend_python
29344284
- closes GitHub issue: #7650
> test: Ensemble async callback execution (rework)

- qa/python_models/bls_memory/model.py
- qa/python_models/bls_memory_async/model.py
Remove shared memory key id from client error response when out-of-memory. The shared memory key can used for malicious exploitation. Update corresponding tests.
Before:
`[500] Failed to increase the shared memory pool size for key 'triton_python_backend_shm_region_fb03b647-0083-4d79-826b-894768e8f782' to 1048576 bytes. If you are running Triton inside docker, use '--shm-size' flag to control the shared memory region size. Error: No space left on device`
After:
`[500] Failed to increase the shared memory pool size to 1048576 bytes. If you are running Triton inside docker, use '--shm-size' flag to control the shared memory region size. Error: No space left on device`
box here and add …
> test: Remove shared memory key from the error response

- qa/L0_http/http_request_many_chunks.py
- qa/L0_http/test.sh
- qa/L0_sagemaker/sagemaker_request_many_chunks.py
- qa/L0_sagemaker/test.sh
- src/common.h
- src/http_server.cc
- src/http_server.h
- src/sagemaker_server.cc
In the HTTP request handling code where `alloca()` is used to allocate memory on the stack. By sending an HTTP request with chunked transfer encoding containing a large number of chunks, an attacker can trigger a stack overflow. Use `std::vector` for a safer dynamic memory allocation.
1. Update `EVRequestToJsonImpl` to replace `alloca` with `std::vector`.
2. Refactor repeated code in API handlers to `EVRequestToJson` and `EVRequestToJsonAllowsEmpty`.
3. Remove `EVBufferToJson` duplicate implementation in `sagemaker_server.cc`.
4. Add unit tests to L0_http and L0_sagemaker
L0_http
L0_sagemaker
32259137
- closes GitHub …
> refactor: Enhance memory allocation security in HTTP and Sagemaker request handler

- qa/L0_shared_memory/shared_memory_test.py
- qa/L0_shared_memory/test.sh
- qa/common/infer_util.py
- src/shared_memory_manager.cc
When calling `mmap` system call, the returned starting address is starting at the shm register offset (must be multiples of page size) already. Later the register offset is added to the starting address again and raises out-of-bound write issue.
L0_shared_memory
L0_cuda_shared_memory
32791300
https://man7.org/linux/man-pages/man2/mmap.2.html
> fix: Proper handling of system shm register offset

- qa/L0_shared_memory/shared_memory_test.py
- src/shared_memory_manager.cc
Followup from the original request. Similar bug in shared memory boundary checks.
Modify test cases to include `register_offset` in boundary checks.
https://github.com/triton-inference-server/server/pull/8334
L0_shared_memory
32964778
> fix: System shared memory boundary check

- qa/L0_shared_memory/shared_memory_test.py
- qa/L0_shared_memory/test.sh
- src/common.cc
- src/common.h
- src/shared_memory_manager.cc
This PR is an enhancement for #8273.
Previously, users could bypass validation by using a leading slash in shm_key, such as `"/triton_python_backend_shm_region_my_test_shm_key"`, `"///triton_python_backend_shm_region_my_test_shm_key"`
- CI Pipeline ID: 33011596
> fix: Improve validation for system shared memory register

- qa/L0_shared_memory/shared_memory_test.py
- qa/L0_shared_memory/test.sh
- src/common.cc
- src/common.h
- src/shared_memory_manager.cc
Cherry-pick #8336 
- CI Pipeline ID: 33087153
> fix: Improve validation for system shared memory register (#8336)

- python/openai/README.md
- qa/L0_python_api/test.sh
Fix for CuPy CUDA 13 library link.
This PR targets the r25.08 branch directly. Pipeline: 33318849
> test: Fix CuPy CUDA library link

- CONTRIBUTING.md
- README.md
- deploy/gke-marketplace-app/server-deployer/data-test/schema.yaml
- deploy/gke-marketplace-app/server-deployer/schema.yaml
- docs/README.md
- docs/client_guide/python_readme.rst
- docs/contents.rst
- docs/customization_guide/build.md
- docs/customization_guide/compose.md
- docs/getting_started/quick_deployment_by_backend.rst
- docs/index.md
- docs/introduction/index.md
- docs/perf_benchmark/perf-analyzer-README.rst
- docs/repositories.txt
- docs/user_guide/custom_operations.md
- docs/user_guide/faq.md
- docs/user_guide/jetson.md
- docs/user_guide/model_configuration.md
- docs/user_guide/model_repository.md
- docs/user_guide/optimization.md
- docs/user_guide/performance_tuning.md
- qa/python_models/identity_bf16/model.py
- qa/python_models/python_version/model.py
This change fix the removal of obsolete documentation left after 25.04
> Remove TensorFlow references

- python/openai/README.md
- qa/L0_dlpack_multi_gpu/test.sh
- qa/L0_python_api/test.sh
- src/python/setup.py
`cuda-cupy` package has been released with support of CUDA 13. 
Updating configuration in order to confirm that the package can be used.
related to: https://github.com/triton-inference-server/core/pull/450
> Update "cuda-cupy" package

- docs/user_guide/performance_tuning.md
> fix: Replace dead link for Densenet

- src/data_compressor.h
- src/test/data_compressor_test.cc
This change replaces the use of `alloca` which performs stack allocation with `std::unique_ptr<T[]> holder{new T[count]}` because it is safer to perform unknown size allocation in the heap vs stack.
[TRI-69](https://linear.app/nvidia/issue/TRI-69/psirt-buffer-overflow-v2modelsmodel-nameinfer) 
[DLIS-8500](https://jirasw.nvidia.com/browse/DLIS-8500)
CI-Pipeline: [35590031](https://gitlab-master.nvidia.com/dl/dgx/tritonserver/-/pipelines/35590031)
> fix: Replace Use of `alloca`

- src/simple.cc
Fix race condition. The `barrier` object is destructed before access in request release callbacks, leading to segfault.
https://github.com/triton-inference-server/core/pull/452
35850970
> test: Fix L0_simple_lib--base

- qa/L0_openai/generate_engine.py
This change moves the import of `LLM` from `tensorrt_llm` to `tensorrt_llm._tensorrt_engine` to adapt the API changes in TRT-LLM v1.0.
[TRI-71](https://linear.app/nvidia/issue/TRI-71/2509-ci-failure-l0-openai-trtllm-base)
> fix: Update L0_openai to adapt TRT-LLM v1.0
